### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by DenisBolbeko** [netology-code/git-homeworks-neuro-issues#10]
# Описание проблемы

#### Шаги по воспроизведению

1. Перейти к разделу обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи". 

#### Ожидаемый результат

Форма для обратной связи адаптирована для просмотра на мобильных устройствах. 

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

@ikrieg обратите на это внимание

**Comment by solarrust** [comment]
Great! I'll fix it someday =)
