### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by BRLinIT** [netology-code/git-homeworks-neuro-issues#1004]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма вписана в экран по ширине

#### Фактический результат

Ширина формы меньше ширины экрана (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![Screenshot (1)](https://user-images.githubusercontent.com/64595879/81503100-d4e8f800-92f2-11ea-821b-938c23cfbe60.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
