### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Alekseiianko** [netology-code/git-homeworks-neuro-issues#1005]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![текст](https://user-images.githubusercontent.com/63406744/81511431-2a88c900-9322-11ea-81c6-f1d57dd3feae.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
