### ISSUE TITLE
Узкая форма обратной связи

### ISSUE THREAD

**Issue by Alekseiianko** [netology-code/git-homeworks-neuro-issues#1006]
Главная страница. Форма обратной связи слишком узкая
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат
Форма вписана в экран по ширине

Фактический результат
Ширина формы меньше ширины экрана (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![форма](https://user-images.githubusercontent.com/63406744/81511460-5906a400-9322-11ea-87ec-b22df7f583bc.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
