### ISSUE TITLE
Узкая форма обратной связи

### ISSUE THREAD

**Issue by hek777** [netology-code/git-homeworks-neuro-issues#1009]
Главная страница. Форма обратной связи слишком узкая
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат
Форма вписана в экран по ширине

Фактический результат
Ширина формы меньше ширины экрана (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60575903/81590051-e39ee000-93c2-11ea-9705-42e29feeedaa.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
