### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by lokkjo** [netology-code/git-homeworks-neuro-issues#101]
@solarrust , добрый день!

## Суть ошибки

Форма обратной связи слишком сжата (см. скриншот)
![text error 02](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы "Оставайтесь на связи..."

## Ожидаемый результат

Форма свободно вписывается в ширину экрана пользователя

## Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
