### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Flash-g-h** [netology-code/git-homeworks-neuro-issues#1014]
### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: Pixel 2 XL (Android 10)
Браузер: Chrome (81.0.4044.138)

### Скриншот

![scr](https://user-images.githubusercontent.com/63458115/81802192-4c4e9f80-951e-11ea-9ae9-284faa90320c.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
