### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Flash-g-h** [netology-code/git-homeworks-neuro-issues#1015]
### Шаги по воспроизведению

Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
Открыть форму обратной связи веб-сайта NeuroStartUp в десктопном браузере Chrome
### Ожидаемый результат
Форма расширена

### Фактический результат
Форма сжата

### Программное окружение

Устройство: Pixel 2 XL (Android 10)
Браузер: Chrome (81.0.4044.138)

### 
Скриншот
![scr1](https://user-images.githubusercontent.com/63458115/81804029-2c6cab00-9521-11ea-97ba-9e391a2ae1b0.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
