### ISSUE TITLE
Проблема с формой обратной связи в мобильном браузере 

### ISSUE THREAD

**Issue by AntonLogy** [netology-code/git-homeworks-neuro-issues#1017]
# Проблема с формой обратной связи в мобильном браузере 

#### Адресовано
@solarrust

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи.

#### Ожидаемый результат

Форма обратной связи соответствует тз.

#### Фактический результат

Форма обратной связи сжата.(см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![](https://i.imgur.com/HcSpYkT.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
