### ISSUE TITLE
Текст на лендинге наезжает на картинку

### ISSUE THREAD

**Issue by anka-ss** [netology-code/git-homeworks-neuro-issues#1018]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями...".

#### Ожидаемый результат

Текст не наезжает на изображение. 

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: Redmi Note 6 Pro (MIUI Global 11.0.3)
* Браузер: Chrome (81.0.4044.138)

#### Скриншоты

![1](https://user-images.githubusercontent.com/50797880/82244771-6b986300-994a-11ea-8a77-03e44b66e258.JPG)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
