### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by anka-ss** [netology-code/git-homeworks-neuro-issues#1019]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до формы "Оставайтесь на связи".

#### Ожидаемый результат

Форма не сжата.

#### Фактический результат

Форма слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: Redmi Note 6 Pro (MIUI Global 11.0.3).
* Браузер: Chrome (81.0.4044.138).

#### Скриншоты

![2](https://user-images.githubusercontent.com/50797880/82245324-6a1b6a80-994b-11ea-9ffc-7fef4cdda994.JPG)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
