### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by Evgeniy-Varlamov** [netology-code/git-homeworks-neuro-issues#102]
@solarrust

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/51528852/59623306-e9555c80-9144-11e9-9cfc-87a4da318560.png)

![image](https://user-images.githubusercontent.com/51528852/59623574-857f6380-9145-11e9-812f-fa96e2d302db.png)

**Comment by solarrust** [comment]
Нужно было содать два разных issue.
