### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by AlexSMGr54** [netology-code/git-homeworks-neuro-issues#1024]
### **Summary**
В мобильном браузере текст наезжает на изображение.

### **Steps**
1. Открыть страницу проекта NeuroStartUp;
2. Пролистать до блока "Воспользуйтесь современными возможностями...".

### **Expected**
Текст расположен над изображением

### **Actuals**
Текст наезжает на изображение (см. скриншот)

### **Environment**
Устройство: Xiaomi Mi5
ОС: LineageOS 16.0
Браузер: Mozilla Fenec 68.8

### **Additionally**
**Скриншот:*
![](https://raw.githubusercontent.com/AlexSMGr54/netology-git-homework-3.2/master/1.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
