### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AlexSMGr54** [netology-code/git-homeworks-neuro-issues#1025]
### **Summary**
В мобильном браузере форма обратной связи слишком сжата.

### **Steps**
1. Открыть страницу проекта NeuroStartUp;
2. Пролистать до формы обратной связи.

### **Expected**
Форма обратной связи занимает всю ширину страницы

### **Actuals**
Форма обратной связи слишком сжата (см. скриншот)

### **Environment**
Устройство: Xiaomi Mi5
ОС: LineageOS 16.0
Браузер: Mozilla Fenec 68.8

### **Additionally**
**Скриншот:*
![](https://raw.githubusercontent.com/AlexSMGr54/netology-git-homework-3.2/master/2.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
