### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by nelakov** [netology-code/git-homeworks-neuro-issues#1027]
@solarrust 

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Проскроллить страницу в самый низ

#### Ожидаемый результат

Форма обратной связи заполняет весь экран, как на макете 

#### Фактический результат

Форма обратной связи "похудела" и расположена по середине экрана (см. скриншот)

#### Программное окружение

* Устройство: iPhone Xr (iOS 13.2.1)
* Браузер: Chrome (85.0.3538.75)

#### Скриншоты

![image](https://user-images.githubusercontent.com/57618846/82615336-d0fe8500-9bd2-11ea-9da6-0631271685a1.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
