### ISSUE TITLE
Текст наезжает на изображение на главной странице в мобильном браузере

### ISSUE THREAD

**Issue by Boldyrev-M** [netology-code/git-homeworks-neuro-issues#1028]
@solarrust 

# Описание проблемы
При просмотре сайта в мобильном браузере текст "Воспользуйтесь современными возможностями..." наезжает на изображение.

## **Шаги для воспроизведения**

1. Открыть главную страницу сайта NeuroStartUp в мобильном браузере Safari
2. Наблюдать расположение текста на странице
    
## **Ожидаемый результат**

Текст не наезжает на изображение

## **Фактический результат**

Текст наезжает на изображение (см. скриншот)

## **Программное окружение**

- Устройство: iPhone 8 (iOS 11)
- Браузер: Safari 11

## **Скриншот:**
![скриншот главной страницы](https://user-images.githubusercontent.com/8050961/82740304-40e64a00-9d50-11ea-8817-13e2836a7142.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
