### ISSUE TITLE
Некорректная ширина формы обратной связи в мобильном браузере

### ISSUE THREAD

**Issue by Boldyrev-M** [netology-code/git-homeworks-neuro-issues#1029]
@solarrust 

# Описание проблемы
При просмотре сайта в мобильном браузере форма обратной связи слишком сжата

## **Шаги для воспроизведения**

1. Открыть главную страницу сайта NeuroStartUp в мобильном браузере Safari
2. Прокрутить страницу вниз до появления формы обратной связи
2. Наблюдать расположение текстов и полей формы
    
## **Ожидаемый результат**
Ширина формы соответствует ширине экрана мобильного устройства

## **Фактический результат**
Форма занимает узкую полосу на экране, оставлены широкие поля слева и справа.

## **Программное окружение**

- Устройство: iPhone 8 (iOS 11)
- Браузер: Safari 11

## **Скриншот:**
![скриншот формы обратной связи](https://user-images.githubusercontent.com/8050961/82740557-8b68c600-9d52-11ea-9aac-8959f19a4dcc.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
