### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by ButuzovaIrina** [netology-code/git-homeworks-neuro-issues#103]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![Screenshot_321](https://user-images.githubusercontent.com/51653047/59752474-f8debd80-928a-11e9-8d33-1999a4cb652d.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
