### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by liana108** [netology-code/git-homeworks-neuro-issues#1030]
@solarrust
Шаги для решения проблемы :
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Прокрутить страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат :
Текст не наезжает на изображение.
Фактический результат:
Текст наезжает на изображение (см. скриншот)
Программное окружение:
Устройство: Samsung Galaxy J5 (Android 7.0)
Браузер: Chrome (81.0.4044.138)
![neuro](https://user-images.githubusercontent.com/64640915/82741015-522e5700-9d4e-11ea-9bc2-e93e8abe1be7.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
