### ISSUE TITLE
Главная страница. Текстовый блок "Оставайтесь на связи..." слишком сжат.

### ISSUE THREAD

**Issue by liana108** [netology-code/git-homeworks-neuro-issues#1031]
@solarrust 
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Прокрутить  страницу до блока "Оставайтесь на связи..."
Ожидаемый результат:
Блок " оставайтесь на связи" имеет достаточную ширину для корректного (удобного для пользователя ) отображения (прочтения) текста
Фактический результат:
Блок "Оставайтесь на связи..." имеет некорректную ширину, вследствие чего текст отображается неюзабельным (неудобным ) для пользователя
Программное окружение:
Устройство: Samsung Galaxy J5 (Android 7.0)
Браузер: Chrome (81.0.4044.138)
![connection1](https://user-images.githubusercontent.com/64640915/82741147-7e96a300-9d4f-11ea-9085-7d71dfd60f92.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
