### ISSUE TITLE
Текст наезжает на картинку в мобильной версии сайта компании

### ISSUE THREAD

**Issue by rakipov** [netology-code/git-homeworks-neuro-issues#1032]
Привет @solarrust !
Возникли проблемы в мобильной версии сайта NeuroStartUp.
Прошу взять в работу)

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Актуальный результат

Текст наезжает на изображение (см. скриншот во вложении)

#### Программное окружение

* Устройство: iPhone 11 Pro (iOS 13.4.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HJ1VbMj.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
