### ISSUE TITLE
Форма обратной связи слишком сжата в мобильной версии сайта

### ISSUE THREAD

**Issue by rakipov** [netology-code/git-homeworks-neuro-issues#1033]
@solarrust есть еще одна небольшая проблемка
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

#### Ожидаемый результат

Блок имеет корректный размер, чтобы текст имел как минимум перенос строго по словам.

#### Актуальный результат

Блок сжат. Слова имеют перенос по буквам на форме. (см. скриншот во вложении)

#### Программное окружение

* Устройство: iPhone 11 Pro (iOS 13.4.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
