### ISSUE TITLE
Форма обратной связи не масштабируется под размер экрана телефона.

### ISSUE THREAD

**Issue by podnebessssni** [netology-code/git-homeworks-neuro-issues#1035]
@solarrust

# Описание проблемы

#### Главная страница. 
Форма обратной связи слишком сжата и не  масштабируется под размер  экрана.

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Opera
2. Пролистать страницу до формы "Оставайтесь на связи"

#### Ожидаемый результат

Форма подгоняется под размеры мобильного устройства

#### Фактический результат

Форма слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: Samsung s10 (Android 10)
* Браузер: Opera Mobile (12)

#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/65781091/82761229-e3aad100-9e01-11ea-83e1-b1c5708b6d30.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)

**Comment by podnebessssni** [comment]
))))) I`ll wait it)))
