### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by DenGreen** [netology-code/git-homeworks-neuro-issues#1045]
# Описание проблемы

#### Шаги по воспроизведению

Перейти на форму обратной связи

#### Ожидаемый результат

Более широкая форма, с читабельным текстом

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/62832806/82909049-d153a300-9f79-11ea-859f-2773000f199d.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
