### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by lucky-999** [netology-code/git-homeworks-neuro-issues#1047]
@solarrust 

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Перейти на страницу обратной связи

**Ожидаемый результат**
Форма обратной связи растянута на весь экран

**Фактический результат**
Форма обратной связи сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/62803727/82932571-50a0a100-9f91-11ea-8efb-baeed315a5c9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
