### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Shushax** [netology-code/git-homeworks-neuro-issues#1051]
### Описание проблемы
Форма обратной связи слишком сжата
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
Форма не сжата

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншоты

![image](https://user-images.githubusercontent.com/62726056/82966180-e3adfb00-9fd2-11ea-9b0f-a4ee2e98ec52.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
