### ISSUE TITLE
При просмотре лендинга в мобильном браузере присутствуют две проблемы. Вторая

### ISSUE THREAD

**Issue by anastasapro** [netology-code/git-homeworks-neuro-issues#1055]
### Форма обратной связи слишком сжата

**Шаги по воспроизведению:**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Перейти к блоку обратной связи.

**Ожидаемый результат:**

Форма обратной связи отображается корректно.

**Фактический результат:**

![каринка](https://user-images.githubusercontent.com/56173584/77413748-e4f35980-6dd0-11ea-895b-e05ad1b8b3ff.png)

Пользователь @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
