### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Griray** [netology-code/git-homeworks-neuro-issues#1057]
@solarrust 
# Описание проблемы
## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Обратная связь"

## Ожидаемый результат
* Удобный формат обратной связи

## Фактический результат
* Неудобное расположение форм заполнения и текст сильно смещен

## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

## Cкриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/65855579/83048973-20b9d200-a053-11ea-80c0-876d53cd2309.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
