### ISSUE TITLE
Форма обратной связи слишком сжимается на мобильной версии 

### ISSUE THREAD

**Issue by DABronskikh** [netology-code/git-homeworks-neuro-issues#1059]
@solarrust 
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы "Оставайтесь на связи"

#### Ожидаемый результат

Форма на всю ширину экрана

#### Фактический результат

Форма сильно сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![image](https://user-images.githubusercontent.com/31243887/83054665-37205780-a06c-11ea-8629-e4065b3ec2d8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
