### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Nikolai-vyalkov** [netology-code/git-homeworks-neuro-issues#1060]
Шаги по воспроизведению
1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### **Ожидаемый результат**
**Текст не наезжает на изображение**
![image](https://user-images.githubusercontent.com/63542674/83053599-66ce6000-a06a-11ea-901f-07e29532e29f.png)

### **Фактический результат**
**Текст наезжает на изображение**
![image](https://user-images.githubusercontent.com/63542674/83053902-eceaa680-a06a-11ea-98bf-b6f428edce93.png)
  
### **Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
