### ISSUE TITLE
Главная страница. Текстовый блок "Оставайтесь на связи...", слишком узкие рамки  

### ISSUE THREAD

**Issue by Nikolai-vyalkov** [netology-code/git-homeworks-neuro-issues#1061]
Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Прокрутите страницу в низ до блока " Оставайтесь на связи..."
### **Ожидаемый результат**
b775baed3d4acb1f42d19bc9bedf6526cc6c07d8

**### Фактический результат**
![image](https://user-images.githubusercontent.com/63542674/83057356-40132800-a070-11ea-9d6f-81dca0119ce5.png)
Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
