### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by nickupx** [netology-code/git-homeworks-neuro-issues#1062]
Скрин для @solarrust 
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/28119202/83067547-87e57f80-a06f-11ea-8cc3-b43e19ccccf9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
