### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by nickupx** [netology-code/git-homeworks-neuro-issues#1063]
Скрин для @solarrust 

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/28119202/83067652-b9f6e180-a06f-11ea-898c-0ea2398935b0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
