### ISSUE TITLE
В мобильном браузере текст пересекает изображение

### ISSUE THREAD

**Issue by PeterKonovodov** [netology-code/git-homeworks-neuro-issues#1066]
@solarrust 
# Описание

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: PC
* Браузер: Chrome с плагином **Mobile browser emulator**

#### Скриншоты

![1](https://user-images.githubusercontent.com/65940719/83145754-bebea280-a10e-11ea-83ef-091f2ed3d77c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
