### ISSUE TITLE
Нарушено форматирование текста  в портретном режиме просмотра.

### ISSUE THREAD

**Issue by PeterKonovodov** [netology-code/git-homeworks-neuro-issues#1068]
@solarrust 
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи.

#### Ожидаемый результат

Текст воспринимается адекватно

#### Фактический результат

Текст сжат по-горизонтали и вызывает неадекватную реакцию закрыть вкладку.

#### Программное окружение

* Устройство: PC
* Браузер: Chrome с плагином **Mobile browser emulator**

#### Скриншоты

![2](https://user-images.githubusercontent.com/65940719/83146226-6c31b600-a10f-11ea-9f78-fe3c9d151aa5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
