### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by NataliaOleinik** [netology-code/git-homeworks-neuro-issues#1069]
# Описание проблемы
### Шаги по воспроизведению
Открыть форму обратной связи

### Ожидаемый результат

Форма обратной связи выглядит пропорционально, в два раза шире минимум

### Фактический результат

Слишком узкая(см.скриншот)

### Сриншоты
![Изображение](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
