### ISSUE TITLE
Поправить отображение текста на главной странице

### ISSUE THREAD

**Issue by nirastor** [netology-code/git-homeworks-neuro-issues#1072]
# Описание проблемы

#### Участники
@solarrust, посмотри, пожалуйста.

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

Браузер: Chrome (83.0.4103.61), режим разработки, эмулятор iPhone 6/7/8

#### Скриншот

![](https://i.imgur.com/HJ1VbMj.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
