### ISSUE TITLE
Поправить отображение формы обратной связи на главной

### ISSUE THREAD

**Issue by nirastor** [netology-code/git-homeworks-neuro-issues#1073]
# Описание проблемы

#### Участники
@solarrust, посмотри, пожалуйста.

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи."

#### Ожидаемый результат

Форма занимает всю ширину экрана

#### Фактический результат

Форма сжата

#### Программное окружение

Браузер: Chrome (83.0.4103.61), режим разработки, эмулятор iPhone 6/7/8

#### Скриншоты

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
