### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by ButuzovaIrina** [netology-code/git-homeworks-neuro-issues#108]
**Главная страница. Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи
**Ожидаемый результат**

Форма лучше читается

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![Screenshot_322](https://user-images.githubusercontent.com/51653047/59752475-f8debd80-928a-11e9-841a-21941dc9de89.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
