### ISSUE TITLE
Требуется доработка мобильной версии сайта

### ISSUE THREAD

**Issue by romauov** [netology-code/git-homeworks-neuro-issues#1081]
# Отображение сайте в браузере на мобильном устройстве
## Проблема
Текстовый блок "Воспользуйтесь современными возможностями искусственного интеллекта..." наезжает на изображение с логотипом NeuroStartUp.

![пример проблемы](https://camo.githubusercontent.com/d90a6e5e9269c1926cc5e5ea6d624a3a06b53f9a/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)

## Необходимые действия
Доработать мобильную версию сайта
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
