### ISSUE TITLE
Требуется доработка формы обратной связи мобильной версии сайта

### ISSUE THREAD

**Issue by romauov** [netology-code/git-homeworks-neuro-issues#1082]
# Отображение сайте в браузере на мобильном устройстве
## Проблема 
Форма обратной связи в мобильной версии сайта слишком мала и неудобна для заполнения.  
![пример проблемы](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)  
## Необходимые действия 
Увеличить форму обратной связи в мобильной версии сайта и сделать её более удобной для пользователя.
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
