### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by albonigrum** [netology-code/git-homeworks-neuro-issues#1083]
@solarrust 

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

#### Ожидаемый результат

Форма подстраивается под размер экрана

#### Фактический результат

Форма сжата слишком сильно (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HcSpYkT.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
