### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Oleg-Stukalov** [netology-code/git-homeworks-neuro-issues#1084]
### Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**
    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![screenshot-1](https://user-images.githubusercontent.com/65926723/83277908-6a352900-a1db-11ea-8bdb-c4b7c1a89c38.png)

Вниманию @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
