### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Oleg-Stukalov** [netology-code/git-homeworks-neuro-issues#1085]
### Описание проблемы

Главная страница. Форма обратной связи слишком сжата

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока формы обратной связи

**Ожидаемый результат**
Форма обратной связи имеет достаточный размер

**Фактический результат**
Форма обратной связи слишком сжата

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![screenshot-2](https://user-images.githubusercontent.com/65926723/83278041-a23c6c00-a1db-11ea-8e5d-4e68d46f9aab.png)

Вниманию @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
