### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by ruslanraindrop** [netology-code/git-homeworks-neuro-issues#1089]
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Форма обладает теми же пропорциями, что и в десктопной версии

**Фактический результат**
Форма слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![01](https://user-images.githubusercontent.com/62899639/83286306-58a64e00-a1e8-11ea-8db3-9d3feb3447c1.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
