### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

### ISSUE THREAD

**Issue by Lebedeva-Kris** [netology-code/git-homeworks-neuro-issues#1092]
**Шаги по воспроизведению:**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншот**
![Screenshot_1](https://user-images.githubusercontent.com/62759125/83302756-8bf6d600-a204-11ea-8258-cda900d31549.png)

@solarrust посмотри.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
