### ISSUE TITLE
Форма обратной связи на главной странице сжата.

### ISSUE THREAD

**Issue by Lebedeva-Kris** [netology-code/git-homeworks-neuro-issues#1093]
**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат:**
Слова не обрезаны.

**Фактический результат:**
Слово "Оставайтесь" обрезано (см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
Скриншот
![Screenshot_2](https://user-images.githubusercontent.com/62759125/83303536-dd539500-a205-11ea-91f7-fc8a5d477d2d.png)
 @solarrust исправь пожалуйста.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
