### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by EvgeniaTru** [netology-code/git-homeworks-neuro-issues#1094]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншоты
![1](https://user-images.githubusercontent.com/65918749/83303489-2c9dc380-a20e-11ea-91ed-af5e70df57cd.png)

@solarrust, нужно пофиксить этот баг как можно скорее

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
