### ISSUE TITLE
Главная страница. Форма обратной связи отображается в  сжатом виде

### ISSUE THREAD

**Issue by EvgeniaTru** [netology-code/git-homeworks-neuro-issues#1095]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"

Ожидаемый результат
Отображаемый текст отображается без переносов, на каждой строчке умещается больше 1 слова, окна для ввода текста не менее 15 символов в длину

Фактический результат
Форма обратной связи отображается в слишком сжатом виде: по 1-2 слова на строке, перенос частей слова на другую строчку, в окне для ввода текста сам текст отображается не полностью (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншот
![2](https://user-images.githubusercontent.com/65918749/83304075-3d026e00-a20f-11ea-8ac1-ba19d01575ab.png)

@solarrust, необходимо пофиксить этот баг

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
