### ISSUE TITLE
Текст наезжает на картинку;

### ISSUE THREAD

**Issue by IkonnikovaAE** [netology-code/git-homeworks-neuro-issues#11]
@ikrieg 
# Текст наезжает на картинку в мобильном браузере.
## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)

## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

## Скриншот: 
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/47339997/52624098-ad418f00-2ef9-11e9-9a5f-f28607b6ba8a.png)

**Comment by solarrust** [comment]
Great! I'll fix it someday =)
