### ISSUE TITLE
Корректировка ширины формы обратной связи

### ISSUE THREAD

**Issue by serviktor050** [netology-code/git-homeworks-neuro-issues#110]
@solarrust

# Описание проблемы
На данный момент при просмотре страницы с мобильного устройства форма обратной связи очень узкая относительно размеров экрана (см. скриншот). 
## Шаги по воспроизведению
Зайти на сайт с мобильного устройства. Открыть форму обратной связи. 
## Ожидаемый результат
Форма должна быть выровнена по центру страницы.  Отступы справа и слева составляют по 10% от ширины экрана.
## Фактический результат
Отступы больше указанных значений. Форма сжалась.
## Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
## Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/47155712/59965199-98ae7c80-9513-11e9-8e39-ad0af764ed14.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
