### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by UlianaBakhmat** [netology-code/git-homeworks-neuro-issues#1108]
@solarrust 

**Описание проблемы**
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![1](https://user-images.githubusercontent.com/60362431/83330062-84cbd880-a295-11ea-9761-5f57ab37da3a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
