### ISSUE TITLE
Текстовый блок "Оставайтесь на связи." имеет большой шрифт и не умещается в заданном поле.

### ISSUE THREAD

**Issue by UlianaBakhmat** [netology-code/git-homeworks-neuro-issues#1109]
@solarrust 

**Описание проблемы**
Главная страница. Текстовый блок "Оставайтесь на связи." имеет большой шрифт и не умещается в заданном поле.

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи."
Необходимо согласовать размер окна и размер шрифта, чтобы текст умещался в заданном поле.

**Ожидаемый результат**
Текст умещается в заданном поле

**Фактический результат**
Текст умещается в заданном поле

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![2](https://user-images.githubusercontent.com/60362431/83330349-ee98b200-a296-11ea-9bc3-fe308069e2f3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
