### ISSUE TITLE
Текст "Воспользуйтесь..." наезжает на изображение

### ISSUE THREAD

**Issue by Baburjonok** [netology-code/git-homeworks-neuro-issues#111]
# **Описание проблемы**
### **На главной странице текст "Воспользуйтесь современными возможностями..." наезжает на изображение.**

**Шаги по воспроизведению**
-
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
-
Текст не наезжает на изображение

**Фактический результат**
-
Текст наезжает на изображение (см. скриншот)
@solarrust

**Программное окружение**
-
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/51777657/59975722-8b0cfb80-95d4-11e9-900d-7f5769234dc4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
