### ISSUE TITLE
Описание проблемы 1 часть

### ISSUE THREAD

**Issue by evzvereva** [netology-code/git-homeworks-neuro-issues#1110]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

@solarrust 

![image](https://user-images.githubusercontent.com/65786308/83337141-7a7bff80-a2d2-11ea-9579-ac0fa4a27620.png)

![image](https://user-images.githubusercontent.com/65786308/83337330-c67b7400-a2d3-11ea-8ffb-c12ad3b02747.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
