### ISSUE TITLE
Наезд текстового блока на изображение на главной странице в моб.версии.

### ISSUE THREAD

**Issue by orlov11** [netology-code/git-homeworks-neuro-issues#1112]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение @solarrust 

Шаги по воспроизведению:
- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат:
- Текст не наезжает на изображение

Фактический результат
- Текст наезжает на изображение (см. скриншот)

Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты:
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/64555707/83337721-64684200-a2c6-11ea-848c-d4b292ef60f3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
