### ISSUE TITLE
Форма обратной связи на главной странице в моб.версии слишком сжата. 

### ISSUE THREAD

**Issue by orlov11** [netology-code/git-homeworks-neuro-issues#1113]
Главная страница. Форма обратной связи слишком сжата в моб.версии сайта @solarrust 

Шаги по воспроизведению:
- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Оставайтесь на связи."

Ожидаемый результат:
- Форма обратной связи отображается корректно.

Фактический результат
- Форма обратной связи слишком сжата (см. скриншот)

Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты:
![tempsnip](https://user-images.githubusercontent.com/64555707/83337804-f1ab9680-a2c6-11ea-9207-c44f287aa159.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
