### ISSUE TITLE
Главная страница. Текстовый блок наезжает на картинку

### ISSUE THREAD

**Issue by AlexOmetov** [netology-code/git-homeworks-neuro-issues#1114]
@solarrust
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/65901032/83337925-089eb880-a2c8-11ea-8c9c-a6ebc8fd3877.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
