### ISSUE TITLE
Белый текст наезжает на мобильную версию сайта.

### ISSUE THREAD

**Issue by AlexOmetov** [netology-code/git-homeworks-neuro-issues#1115]
@solarrust
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты
![image](https://user-images.githubusercontent.com/65901032/83338214-a4c9bf00-a2ca-11ea-896e-168a9ce60cc3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
