### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by veronicabay** [netology-code/git-homeworks-neuro-issues#1118]
@solarrust 
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

#### Ожидаемый результат

Форма обратной связи занимает всю ширину экрана устройства.

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://user-images.githubusercontent.com/55463491/83339627-810d7580-a2d8-11ea-9cd9-887b4f5de7a1.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
