### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Baburjonok** [netology-code/git-homeworks-neuro-issues#112]
# **Описание проблемы**
### **Форма обратной связи слишком сжата**

**Шаги по воспроизведению**
-

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
-
Ширина формы обратной связи соответствует ширине экрана устройства и расположенному в форме тексту

**Фактический результат**
-
Ширина формы обратной связи слишком маленькая (см. скриншот)
@solarrust

**Программное окружение**
-
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/51777657/59976174-20f75500-95da-11e9-9594-5f78a9c7bc82.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
