### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by VladislavSukhov** [netology-code/git-homeworks-neuro-issues#1120]
@solarrust

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу сайта NeuroStartUp в мобильном браузере Opera Mobile
2. Открыть "Форма обратной связи"

#### Ожидаемый результат

Форма обратной связи не сжата

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: Samsung s10 (Android 9)
* Браузер: Opera Mobile (12)

#### Скриншоты

![](https://user-images.githubusercontent.com/49847824/83349641-23f8da80-a33f-11ea-9561-f99635f607c0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
