### ISSUE TITLE
Главная страница. Текстовый блок наезжает на картинку

### ISSUE THREAD

**Issue by VladislavSukhov** [netology-code/git-homeworks-neuro-issues#1121]
@solarrust

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://user-images.githubusercontent.com/49847824/83349584-a03eee00-a33e-11ea-98c2-ed560de2211d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
