### ISSUE TITLE
Главная страница. Текстовый блок наезжает на картинку

### ISSUE THREAD

**Issue by AlexKarepin** [netology-code/git-homeworks-neuro-issues#1124]
@solarrust
# Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

<img width="229" alt="Screenshot_6" src="https://user-images.githubusercontent.com/63051632/83351072-a7b7c480-a349-11ea-8aa5-b6b0e0e058e7.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
