### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AlexKarepin** [netology-code/git-homeworks-neuro-issues#1125]
@solarrust
# Описание проблемы

**Шаги по воспроизведени**

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.  Пролистать страницу до блока "Форма обратной связи"

**Ожидаемый результат**

Форма обратной связи занимает всю ширину экрана устройства.

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

<img width="98" alt="Screenshot_7" src="https://user-images.githubusercontent.com/63051632/83351376-e9496f00-a34b-11ea-965e-235154fda22a.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
