### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by maxtv1982** [netology-code/git-homeworks-neuro-issues#1128]
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/63042896/83354369-ec9b2580-a360-11ea-8e2a-aaca4609a63d.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
