### ISSUE TITLE
Главная страница. Форма обратной связи

### ISSUE THREAD

**Issue by maxtv1982** [netology-code/git-homeworks-neuro-issues#1129]
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Форма обратной связи"

**Ожидаемый результат**

Форма обратной связи нормального размера

**Фактический результат**

Форма обратной связи слишком сжата. (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/63042896/83354592-4f40f100-a362-11ea-85a9-bcdab410caa3.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
