### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by DmitryKuznetsoff** [netology-code/git-homeworks-neuro-issues#1135]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма обратной связи корректно отображается по ширине устройства

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.ibb.co/LgLbBpk/ZiKgjlK.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
