### ISSUE TITLE
Проблема с отображением текста

### ISSUE THREAD

**Issue by NataliaGrishanova** [netology-code/git-homeworks-neuro-issues#1139]
**На главной странице текстовый блок наезжает на изображение.**

**_Шаги по устранению:_**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

_**Ожидаемый результат:**_
Текст не наезжает на изображение.
@solarrust 

**_Фактический результат:_**
Текст наезжает на изображение (см. скрин.)

**_Программное окружение:_**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

 **Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/65921907/83363862-7c62c300-a3a5-11ea-829a-98a345966d6b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
