### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Hostling** [netology-code/git-homeworks-neuro-issues#114]
На экранах с маленькой шириной форма обратной связи выглядит слишком сжатой:
![image](https://user-images.githubusercontent.com/52398197/60824317-6f9c1600-a1ba-11e9-86e0-7240d40dd39d.png)

@solarrust поправьте, пожалуйста.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
