### ISSUE TITLE
Проблема с формой обратной связи

### ISSUE THREAD

**Issue by NataliaGrishanova** [netology-code/git-homeworks-neuro-issues#1140]
**Форма обратной связи в мобильном браузере слишком сжата.**

**_Шаги по воспроизведению:_**
1. Открыть страницу с формой обратной связи.

**_Ожидаемый результат:_**
Форма обратной связи имеет нормальное отображение.
@solarrust 

**_Фактический результат:_**
Форма обратной связи слишком сжата (см. скрин)

**_Программное окружение_**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/65921907/83363969-407c2d80-a3a6-11ea-8af3-b4c3e07e4ca7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
