### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Gfncid** [netology-code/git-homeworks-neuro-issues#1142]
**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот:**

![PQjrsR1](https://user-images.githubusercontent.com/65940900/83380745-6118a780-a3e7-11ea-84fc-1d632678474c.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
