### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Gfncid** [netology-code/git-homeworks-neuro-issues#1143]
**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Форма обратной связи."

**Ожидаемый результат**

Форма обратной связи нормального размера

**Фактический результат**

Форма обратной связи сжата

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот:**

![lk9f1w1](https://user-images.githubusercontent.com/65940900/83380865-c2407b00-a3e7-11ea-8df4-d935bd997114.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
