### ISSUE TITLE
Слишком сжатая форма обратной связи

### ISSUE THREAD

**Issue by SergeyRichkov** [netology-code/git-homeworks-neuro-issues#1145]
# Описание проблемы
**Форма обратной связи слишком сжата**
## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи..."
## Ожидаемый результат
Форма обратной связи удобна для чтения и заполнения

## Фактический результат
Форма обратной связи слишком сжата, неудобна для чтения и заполнения (см. скриншот)

## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
## Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/65851001/83390122-80c9c300-a41b-11ea-995e-d167998347db.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
