### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by TinAngelvall** [netology-code/git-homeworks-neuro-issues#1147]
@solarrust 
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

#### Ожидаемый результат

Форма обратной связи имеет оптимальный размер

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![изображение](https://user-images.githubusercontent.com/63049757/83403856-e1103300-a422-11ea-8f4e-8faae0345007.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
