### ISSUE TITLE
Слишком сжатая форма обратной связи на мобильных устройствах

### ISSUE THREAD

**Issue by DemalexS** [netology-code/git-homeworks-neuro-issues#1149]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

форма адаптируется к размеру экрана МУ

#### Фактический результат

Форма сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![83390122-80c9c300-a41b-11ea-995e-d167998347db](https://user-images.githubusercontent.com/65888750/83404172-d188ee00-a412-11ea-8e50-56414d593da0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
