### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by safonovatanya** [netology-code/git-homeworks-neuro-issues#115]
@solarrust при заходе на сайт текст наезжает на изображение (прилагаю скриншот):
![60824078-087e6180-a1ba-11e9-9803-abe1410fc7e5](https://user-images.githubusercontent.com/52385575/62637074-71850080-b943-11e9-8457-4381e368fa68.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
