### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by pavel-maiseichyk** [netology-code/git-homeworks-neuro-issues#1151]
# Описание проблемы
**Форма обратной связи слишком сжата**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Открыть форму обратной связи

**Ожидаемый результат**

Форма выглядит нормально

**Фактический результат**

Форма является сжатой (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/62174854/83408191-e8334300-a41a-11ea-86bd-2c871370ec02.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
