### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by Kryazheva** [netology-code/git-homeworks-neuro-issues#1152]
Описание проблемы
### Текст не наезжает на изображение

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму обратной связи

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/41772939/83410455-20d51b80-a41f-11ea-97e1-d882f2cb09d0.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
