### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Kryazheva** [netology-code/git-homeworks-neuro-issues#1153]
Описание проблемы
**### Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму обратной связи

**Ожидаемый результат**

Выглядет нормально 

**Фактический результат**

 Не нормально (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/41772939/83411196-6ba36300-a420-11ea-9f70-e0086bcac7f2.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
