### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by InnaSmir** [netology-code/git-homeworks-neuro-issues#1155]
@solarrust

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма обратной связи отображается корректно

#### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![image](https://user-images.githubusercontent.com/65781957/83417718-29cbea00-a42b-11ea-9ef2-c5e23d5f7c2b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
