### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

### ISSUE THREAD

**Issue by NatalyBolgova** [netology-code/git-homeworks-neuro-issues#1156]
**Шаги для воспроизведения:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![текст на картинке](https://user-images.githubusercontent.com/66001644/83426454-70bbde80-a42f-11ea-848c-dd91609e4d5f.jpg)

@solarrust исправь, пожалуйста :)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
