### ISSUE TITLE
Форма обратной связи на главной странице сжата.

### ISSUE THREAD

**Issue by NatalyBolgova** [netology-code/git-homeworks-neuro-issues#1157]
**Шаги для воспроизведения:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат:**
Заголовок "Оставайтесь на связи" масштабируется при изменении размера формы. Слова не обрезаны.

**Фактический результат:**
Слово "Оставайтесь" обрезано, масштабирования нет
 (см. скриншот)

**Программное окружение:**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![форма ос](https://user-images.githubusercontent.com/66001644/83426819-0b1c2200-a430-11ea-87ff-14556b6df6c4.jpg)

@solarrust исправь, пожалуйста :)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
