### ISSUE TITLE
1st issue - Image REsize

### ISSUE THREAD

**Issue by shumbi** [netology-code/git-homeworks-neuro-issues#1158]
### Need Resize Image

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/65901634/83440281-585abc80-a44d-11ea-9a66-fac9c26535f3.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
