### ISSUE TITLE
2nd issue

### ISSUE THREAD

**Issue by shumbi** [netology-code/git-homeworks-neuro-issues#1159]
### Move Text from Image

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/65901634/83440429-9ce65800-a44d-11ea-8b04-0121740d5eae.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
