### ISSUE TITLE
Форма обратной связи

### ISSUE THREAD

**Issue by safonovatanya** [netology-code/git-homeworks-neuro-issues#116]
@solarrust при заходе на сайт с мобильного устройства вижу, что форма обратной связи выглядит слишком сжато (скриншот прилагаю):
![60824317-6f9c1600-a1ba-11e9-86e0-7240d40dd39d](https://user-images.githubusercontent.com/52385575/62637264-c759a880-b943-11e9-82fa-2471f91935ed.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
