### ISSUE TITLE
Проблемы2

### ISSUE THREAD

**Issue by Gintamen** [netology-code/git-homeworks-neuro-issues#1163]
### Описание проблемы

**Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Открыть форму обратной связи

**Ожидаемый результат**

Текст не разбит на разные строчки

**Фактический результат**

Текст разбит по строчкам на изображение (см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/65783706/83447718-8a721b80-a459-11ea-95da-1be5a2f449e7.png)

**Comment by Gintamen** [comment]
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
