### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by teejay74** [netology-code/git-homeworks-neuro-issues#1168]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Отображение формы обратной связи на полную ширину экрана.

#### Фактический результат

Форма обратной связи сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://user-images.githubusercontent.com/66001644/83426819-0b1c2200-a430-11ea-87ff-14556b6df6c4.jpg)

@teejay74

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
