### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by farkhad** [netology-code/git-homeworks-neuro-issues#117]
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта в мобильном браузере хром
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: айфон 8+, ОС 12.1
* Браузер: хром (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HJ1VbMj.png)

Специально для @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
