### ISSUE TITLE
Текст наезжает на синюю картинку 

### ISSUE THREAD

**Issue by IsmagilovRF** [netology-code/git-homeworks-neuro-issues#1170]
@solarrust

**Описание проблемы**
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/56322000/83516689-365e4a00-a4e0-11ea-887c-1a99b98288ab.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
