### ISSUE TITLE
Еще одна Issues 

### ISSUE THREAD

**Issue by IsmagilovRF** [netology-code/git-homeworks-neuro-issues#1173]
@solarrust

**Описание проблемы**

Cтраница обратной связи. Не помещается на изображение.

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome,
Открыть страницу обратной связи.
Ожидаемый результат

Текст помещается на изображение

**Фактический результат**

Текст не помещается на изображение. (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/56322000/83517944-70c8e680-a4e2-11ea-8feb-dd8f37753904.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
