### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by lizylina** [netology-code/git-homeworks-neuro-issues#1176]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..."
наезжает на изображение**

@solarrust

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/66078533/83547409-fa4cd880-a523-11ea-85c6-495a9354c84a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
