### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by lizylina** [netology-code/git-homeworks-neuro-issues#1177]
**Главная страница. Форма обратной связи слишком сжата.**

@solarrust

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма обратной связи отображается на всю ширину экрана

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/66078533/83547864-a7bfec00-a524-11ea-9bab-60a7eb341f28.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
