### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Oksanteel** [netology-code/git-homeworks-neuro-issues#1178]
@solarrust 

# Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/66247437/83547696-48a1ad80-a50b-11ea-8533-7258affdea82.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
