### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Oksanteel** [netology-code/git-homeworks-neuro-issues#1179]
@solarrust 

# Описание проблемы

**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма обратной связи отображается корректно

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/66247437/83548512-8fdc6e00-a50c-11ea-912a-ac15848bce78.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
