### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by farkhad** [netology-code/git-homeworks-neuro-issues#118]
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта в мобильном браузере хром
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма обратной связи выглядит нормально, не сжатой.

#### Фактический результат

Форма обратной связи выглядит слишком сжатой (см. скриншот)

#### Программное окружение

* Устройство: айфон 8+, ОС 12.1
* Браузер: хром (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HcSpYkT.png)

Специально для @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
