### ISSUE TITLE
Текст наезжает на изображение в мобильной версии 

### ISSUE THREAD

**Issue by IlyaChuharev** [netology-code/git-homeworks-neuro-issues#1187]
* При открытии сайта с мобильного устройства "iPhone 8+ (iOS 12.1)" через мобильный браузер Chrome (70.0.3538.75), текст наезжает на изображение.
@solarrust

**Comment by solarrust** [comment]
Куда же делся скриншот проблемы? =)

**Comment by IlyaChuharev** [comment]
Не оговаривалось про скрин воскресенье, 07 июня 2020г., 01:52 +03:00 от Alena Batitskaya  notifications@github.com :
