### ISSUE TITLE
Размер текста увеличен, для мобильной версии

### ISSUE THREAD

**Issue by IlyaChuharev** [netology-code/git-homeworks-neuro-issues#1188]
![2020-06-03 (2)](https://user-images.githubusercontent.com/65675769/83613315-4469a480-a58c-11ea-9986-4de174571a32.png)
## Два варианта исхода событий:
* Размер текста не соответствует формату
* Границы мобильной версии заужены 
## @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
