### ISSUE TITLE
Ошибка отображения на мобильной версии сайта

### ISSUE THREAD

**Issue by EvgeniyRoschin** [netology-code/git-homeworks-neuro-issues#119]
# Описание проблемы
@solarrust
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
#### Скриншоты
![image](https://user-images.githubusercontent.com/52856208/63427276-d4879480-c425-11e9-87b4-9ba4ab5aa7db.png)
![image](https://user-images.githubusercontent.com/52856208/63427478-3f38d000-c426-11e9-8fb5-ccbb4ef5ecda.png)

**Comment by solarrust** [comment]
Нужно было создать два разных issue, по одному на каждую проблему! =)
