### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by valerie-sidman** [netology-code/git-homeworks-neuro-issues#1190]
# Описание проблемы
@solarrust **Главная страница. Форма обратной связи слишком сжата**
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи
### Ожидаемый результат
Исправлены стили формы обратной связи
### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/62873844/83615684-8f38eb80-a58f-11ea-9e8f-e6d3bf1e212a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
