### ISSUE TITLE
На главной странице текст наезжает на изображение.

### ISSUE THREAD

**Issue by LenoreCldg** [netology-code/git-homeworks-neuro-issues#1192]
**Главная страница. 
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями...

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/66063771/83629674-3a06d500-a5a3-11ea-8a4d-36a096c4181a.png)

@solarrust, прошу взять в работу.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
