### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by LenoreCldg** [netology-code/git-homeworks-neuro-issues#1193]
**Описание проблемы:**
Главная страница. Форма обратной связи слишком сжата

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи
3. Ожидаемый результат
4. Исправлены стили формы обратной связи

**Ожидаемый результат**
Форма обратной связи в читаемом виде.

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![83615684-8f38eb80-a58f-11ea-9e8f-e6d3bf1e212a](https://user-images.githubusercontent.com/66063771/83630029-cd400a80-a5a3-11ea-9685-f41a71235292.png)

@solarrust, прошу взять в работу.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
