### ISSUE TITLE
На главной странице текстовый блок наезжает на изображение.

### ISSUE THREAD

**Issue by Sergey-Zubov** [netology-code/git-homeworks-neuro-issues#1194]
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
#### Ожидаемый результат
Текст не наезжает на изображение
#### Фактический результат
Текст наезжает на изображение (см. скриншот)
#### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
#### Скриншоты
![Текст наезжает на изображение](https://user-images.githubusercontent.com/61541685/83633224-42620e80-a5a9-11ea-944e-7cf2338a83be.png)

_@solarrust, прошу взять в работу_

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
