### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Sergey-Zubov** [netology-code/git-homeworks-neuro-issues#1195]
#### Шаги по воспроизведению
1. Открыть веб-сайт NeuroStartUp в мобильном браузере Chrome
2. С помощью меню в правом верхнем углу, перейти на страницу обратной связи
#### Ожидаемый результат
Форма обратной связи адаптивна к текущему разрешению и положению экрана
#### Фактический результат
Форма обратной связи слишком сжата
#### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
#### Скриншоты
![Форма обратной связи слишком сжата](https://user-images.githubusercontent.com/61541685/83637637-991f1680-a5b0-11ea-93b7-d3ac027ec92f.png)

_@solarrust, прошу взять в работу_

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
