### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by vadimarsh** [netology-code/git-homeworks-neuro-issues#1196]
# Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
### Проблема для 
@solarrust
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты
![problem1](https://user-images.githubusercontent.com/59313785/83637908-e7e1a600-a5da-11ea-855b-4073c193e829.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
