### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by vadimarsh** [netology-code/git-homeworks-neuro-issues#1197]
# Описание проблемы
Главная страница. Форма "Оставайтесь на связи" слишком сжимается при просмотре с мобильного.

## Проблема для
@solarrust

### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до формы "Оставайтесь на связи"
### Ожидаемый результат
Форма занимает 80% пространство

### Фактический результат
Форма слшиком сжимается, при этом с боков остается примерно 50% не использованного пространства

### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты
![problem2](https://user-images.githubusercontent.com/59313785/83639061-b79b0700-a5dc-11ea-9bdb-04988db36147.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
