### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by VitaliGrecciani** [netology-code/git-homeworks-neuro-issues#1199]
# Описание проблемы

@solarrust

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Форма обратной связи нормального размера

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншот
![image](https://user-images.githubusercontent.com/65866647/83657560-ac8aab80-a5c9-11ea-8bba-b337e2aca650.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
