### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by IkonnikovaAE** [netology-code/git-homeworks-neuro-issues#12]
@ikrieg 
# Форма обратной связи слишком сжата
## Ожидаемый результат
Форма читабельного размера

## Фактический результат
Форма сжата

## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

## Скриншот: 
![22268747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/47339997/52624312-322ca880-2efa-11e9-8165-96242425cdc6.png)

**Comment by solarrust** [comment]
Great! I'll fix it someday =)
