### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by egorlichenkoam** [netology-code/git-homeworks-neuro-issues#1200]
@solarrust текст наезжает на картинку. Пример ниже:
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/12269885/83665789-59beed00-a5e5-11ea-84f7-4ea5b998948c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
