### ISSUE TITLE
Форма обратной связи сильно сжата.

### ISSUE THREAD

**Issue by egorlichenkoam** [netology-code/git-homeworks-neuro-issues#1201]
@solarrust форма обратной связи сильно сжата. Некрасиво. Пример ниже:
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/12269885/83665904-8c68e580-a5e5-11ea-8083-207b37748a25.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
