### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by SergeyBabaev31** [netology-code/git-homeworks-neuro-issues#1202]
Главная страница. Форма обратной связи слишком сжата.

@solarrust

Шаги по просмотведению

NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"

Ожидаемый результат

Форма обратной связи отображается на всю ширину экрана

Фактический результат

Форма обратной связи слишком сжата (см. Скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншот

![форма](https://user-images.githubusercontent.com/65763931/83682835-21231180-a5ed-11ea-85a0-417090b250f3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
