### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by SergeyBabaev31** [netology-code/git-homeworks-neuro-issues#1203]
Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

Проблема для
@solarrust

Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
problem1

![картинка](https://user-images.githubusercontent.com/65763931/83683300-d786f680-a5ed-11ea-8315-6053db3183d7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
