### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by NAndrianov** [netology-code/git-homeworks-neuro-issues#1204]
**Описание проблемы**
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Проблема для**
@solarrust

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![Ошибка наезд текста](https://user-images.githubusercontent.com/64007846/83719729-64f33680-a640-11ea-8eca-3dfa68a59ce6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
