### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by NAndrianov** [netology-code/git-homeworks-neuro-issues#1205]
**@solarrust**

**Главная страница. Форма обратной связи сжата.**

**Шаги по воспроизведению**
1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2.  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Форма обратной связи нормального размера

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![Форма обратной связи сжата](https://user-images.githubusercontent.com/64007846/83720716-4d1cb200-a642-11ea-9ea5-dd8d922399e4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
