### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by lizaMosiyash** [netology-code/git-homeworks-neuro-issues#1209]
@solarrust

# Описание проблемы

### Шаги по воспроизведению
* Открыть форму обратной связи на веб-сайте NeuroStartUp в мобильном браузере Chrome

### Ожидаемый результат
Форма обратной связи расположена по всей ширине экрана

### Фактический результат
Форма обратной связи сжата

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот:

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/65972182/83769328-62b4ca80-a688-11ea-8a50-86c602432c43.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
