### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by nugmanov87** [netology-code/git-homeworks-neuro-issues#121]
# Описание проблемы
**Страница с обратной формой связи. Весь блок слишком сжат**
### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
### Ожидаемый результат
Блок занимает всю доступную ширину окна браузера

### Фактический результат
Блок не занимает всю ширину окна браузера (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![Скриншот](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
