### ISSUE TITLE
В мобильном браузере Chrome на главной странице текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

### ISSUE THREAD

**Issue by larinasof** [netology-code/git-homeworks-neuro-issues#1212]
@solarrust 

**Описание проблемы**
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

**Шаги по воспроизведению:**
1) Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2) Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение.

**Фактический результат:**
Текст наезжает на изображение (см. скриншот).

**Программное окружение:**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот:**
![image](https://user-images.githubusercontent.com/65974918/83787335-4fabf580-a69c-11ea-89ef-15fb0174a3bf.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
