### ISSUE TITLE
В мобильном браузере Chrome на главной странице форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by larinasof** [netology-code/git-homeworks-neuro-issues#1213]
@solarrust

**Описание проблемы:**
Главная страница. Форма обратной связи слишком сжата.

**Шаги по воспроизведению:**
1) Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2) Пролистать страницу до блока обратной связи.

**Ожидаемый результат:**
Форма обратной связи располагается на всю ширину экрана.

**Фактический результат:**
Форма обратной связи слишком сжата.

**Программное окружение:**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот:**
![image](https://user-images.githubusercontent.com/65974918/83787863-1b850480-a69d-11ea-8bf7-5203b6bcd1f3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
