### ISSUE TITLE
На главной странице блок с обратной связью слишком сжат

### ISSUE THREAD

**Issue by dmitry-izjurov** [netology-code/git-homeworks-neuro-issues#1215]
# Описание проблемы

**Главная страница. Форма с обратной связью слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока с обратной связью

**Ожидаемый результат**

Блок имеет оптимальную ширину

**Фактический результат**

Блок слишком сжат (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
