### ISSUE TITLE
Белый текст наезжает на картинку

### ISSUE THREAD

**Issue by polecika** [netology-code/git-homeworks-neuro-issues#1216]
#### Описание проблемы для @solarrust
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение наезжает на изображение
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
#### Ожидаемый результат
Текст не наезжает на изображение
#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
#### Скриншот
![](https://user-images.githubusercontent.com/64007846/83719729-64f33680-a640-11ea-8eca-3dfa68a59ce6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
