### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by OlgaZo** [netology-code/git-homeworks-neuro-issues#122]
# Текст наезжает на изображение
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на результат
### Фактический результат
Текст наезжает на изображение (см. скриншот)
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![Screenshot_text](https://user-images.githubusercontent.com/52864045/63689644-2c9e0c80-c813-11e9-8fe1-70286f1f2029.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
