### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by somnambulistic-art** [netology-code/git-homeworks-neuro-issues#1221]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Формы обратной связи"

#### Ожидаемый результат

Форма обратной связи не сжата и имеет нормальный внешний вид.

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![83657560-ac8aab80-a5c9-11ea-8bba-b337e2aca650](https://user-images.githubusercontent.com/65789533/83875949-b551bd80-a740-11ea-8973-84bf4bc2c820.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
