### ISSUE TITLE
Главная страница. Форма обратной связи  "Оставайтесь на связи..." слишком сжата 

### ISSUE THREAD

**Issue by danielyan-emma** [netology-code/git-homeworks-neuro-issues#1226]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2. Пролистать страницу до блока "Оставайтесь на связи..."
### Ожидаемый результат
Форма обратной связи имеет нормальный вид

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты

https://prnt.sc/sumvrg

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
