### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Geniuskaa** [netology-code/git-homeworks-neuro-issues#1229]
# Форма обратной связи слишком сжата при открытии сайта с мобильных устройств

 @solarrust

**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

   1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
   1. Перейти на кнопку "Меню" в левом-верхнем углу страницы
   1. Выбрать пункт "обратная связь"

**Ожидаемый результат**

Блок имеет оптимальную ширину

**Фактический результат**

Блок слишком сжат (см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/65945599/83938874-01ecd580-a7e1-11ea-8372-30371254b2ef.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
