### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by OlgaZo** [netology-code/git-homeworks-neuro-issues#123]
# Форма обратной связи слишком сжата
**Главная страница. Форма обратной связи**
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока Форма обратной связи
### Ожидаемый результат
Форма обратной связи занимает всю ширину страницы
### Фактический результат
Форма обратной связи слишком сжата
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![Screenshot_form](https://user-images.githubusercontent.com/52864045/63690104-7b987180-c814-11e9-91fb-6431e8debbf5.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
