### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by MariiaKulbaka** [netology-code/git-homeworks-neuro-issues#1232]
@solarrust 

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![issue](https://user-images.githubusercontent.com/62563856/83947822-143b3380-a822-11ea-83e5-3f939434a446.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
