### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by la-chispa** [netology-code/git-homeworks-neuro-issues#1235]
@solarrust

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![text](https://user-images.githubusercontent.com/62785709/83950372-292cbc80-a84c-11ea-8467-bfc6d1c3e501.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
