### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by la-chispa** [netology-code/git-homeworks-neuro-issues#1237]
@solarrust

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

#### Ожидаемый результат

Форма обратной связи занимает всю ширину экрана (см. скриншот 2)

#### Фактический результат

Блок с формой занимает половину ширины родительского блока и, соответственно, половину экрана (см. скриншот 1)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

1.
![form](https://user-images.githubusercontent.com/62785709/83950995-7f036380-a850-11ea-8769-e631424ca594.png)

2.
![Снимок экрана 2020-06-06 в 23 46 07](https://user-images.githubusercontent.com/62785709/83950989-790d8280-a850-11ea-9b03-a0f65a85c72d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
