### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Aniki25** [netology-code/git-homeworks-neuro-issues#1238]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Форма обратной связи расширена

#### Фактический результат

Сжатая форма обратной связи (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![image](https://user-images.githubusercontent.com/65915286/83951039-89653380-a837-11ea-8718-8e78b6e791bf.png)

Работу передать пользователю @solarrust.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
