### ISSUE TITLE
Главная страница. Текст наезжает на изображение при просмотре на мобильном.

### ISSUE THREAD

**Issue by denis-luttcev** [netology-code/git-homeworks-neuro-issues#124]
# Описание проблемы
При просмотре главной страницы с мобильного устройства параграф текста
```html
<p class="promo-description mt-5">Воспользуйтесь современными возможностями ... </p>
```
наезжает на центральный элемент фоновой картинки блока
```html
    <div class="promo-container"> ... </div>
````
### Вниманию
@solarrust

## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат
Текст и центральный элемент фонового изображения не совмещаются

## Фактический результат
Текст совмещен с изображением (см. скриншот)

## Программное окружение
Устройство: Sony G3312 (Android 7.0)
Браузер: Chrome (76.0.3809.111)

## Скриншот
![screenshot1](https://user-images.githubusercontent.com/54030569/63694431-1e55ed80-c81f-11e9-81c0-5f830ce70aab.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
