### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by LiquidAssContainer** [netology-code/git-homeworks-neuro-issues#1246]
@solarrust, на главной странице, если пролистать страницу до блока "Воспользуйтесь современными возможностями...", видна ошибка: текст наезжает на картинку.

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/47602463/84116559-82157400-aa49-11ea-821a-07cf4c90b4b5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
