### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by LiquidAssContainer** [netology-code/git-homeworks-neuro-issues#1247]
@solarrust, форма обратной связи слишком сжата (по крайней мере на мобильных устройствах), прилагаю скриншот.

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/47602463/84116781-e7696500-aa49-11ea-83a2-f06c426a2aab.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
