### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата при просмотре на мобильном.

### ISSUE THREAD

**Issue by denis-luttcev** [netology-code/git-homeworks-neuro-issues#125]
# Описание проблемы
При просмотре главной страницы с мобильного устройства форма обратной связи
```html
<div class="contacts-card col-6 mx-auto card pt-4 pb-4"> ... </div>
```
становится слишком узкой.

### Вниманию
@solarrust

## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

## Ожидаемый результат
Форма обратной связи занимает большую часть ширины экрана

## Фактический результат
Отступы слева и справа у формы слишком велики

## Вероятная причина
```css
.col-6 {flex: 0 0 50%; max-width: 50%;}
```
не адаптировано.

## Программное окружение
Устройство: Sony G3312 (Android 7.0)
Браузер: Chrome (76.0.3809.111)

## Скриншот
![screenshot2](https://user-images.githubusercontent.com/54030569/63696555-aa6a1400-c823-11e9-857f-671b905b3634.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
