### ISSUE TITLE
При просмотре лендинга в мобильном браузере текст наезжает на картинку

### ISSUE THREAD

**Issue by VeraVar** [netology-code/git-homeworks-neuro-issues#1252]
@solarrust

### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями...".

**Ожидаемый результат**
Текст расположен выше изображения.

**Фактический результат**
Текст наезжает на изображение (см. скриншот).

**Программное окружение**
•	Устройство: iPhone 8+ (iOS 12.1)
•	Браузер: Chrome (70.0.3538.75)

![Текст поверх картинки](https://user-images.githubusercontent.com/65856530/84288384-c7b96600-ab49-11ea-9139-e22e2069ce4c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
