### ISSUE TITLE
При просмотре лендинга в мобильном браузере форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by VeraVar** [netology-code/git-homeworks-neuro-issues#1253]
@solarrust

### Главная страница. Блок "Оставайтесь на связи" не удобен для восприятия

**Шаги по воспроизведению**

1.	Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2.	Пролистать страницу до блока "Оставайтесь на связи".

**Ожидаемый результат**
Форма обратной связи имеет удобный для восприятия и заполнения вид.

**Фактический результат**
Слово "Оставайтесь" не помещается в строку. Поля для заполнения данных слишком сжаты по ширине (см. скриншот).

**Программное окружение**
•	Устройство: iPhone 8+ (iOS 12.1)
•	Браузер: Chrome (70.0.3538.75)

![Форма обратной связи](https://user-images.githubusercontent.com/65856530/84288781-4dd5ac80-ab4a-11ea-8a98-272748e6909a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
