### ISSUE TITLE
На главной странице текст "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Volkva** [netology-code/git-homeworks-neuro-issues#1254]
@solarrust

**Шаги по воспроизведению**
1. Перейти в телефонном браузере по ссылке сайта.
2. Пролистать страницу до текста "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на картинку

**Фактический результат**
Текст наезжает на картинку (см.скриншот)

**Программное окружение**
Устройство: Redmi Note 7 (Android 9)
Браузер: Chrome (83.0.4103.96)

**Скриншоты**

![изображение](https://user-images.githubusercontent.com/65161513/84295873-9ac67c80-ab64-11ea-8ba1-9bc77a77978c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
