### ISSUE TITLE
Форма обратной связи на главной странице заужена и неудобна для восприятия

### ISSUE THREAD

**Issue by Volkva** [netology-code/git-homeworks-neuro-issues#1255]
@solarrust

**Шаги по воспроизведению**
1. Перейти в телефонном браузере по ссылке сайта.
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма обратной связи при загрузке страницы оптимизируется под размер экрана мобильного устройства

**Фактический результат**
Форма обратной связи при загрузке страницы не оптимизируется под размер экрана мобильного устройства и слишком заужена(см.скриншот)

**Программное окружение**
Устройство: Redmi Note 7 (Android 9)
Браузер: Chrome (83.0.4103.96)

**Скриншоты**

![изображение](https://user-images.githubusercontent.com/65161513/84295746-6b177480-ab64-11ea-894d-78a1d68efa00.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
