### ISSUE TITLE
Основной текст наезжает на картинку при просмотре на мобильных устройствах

### ISSUE THREAD

**Issue by AplusIv** [netology-code/git-homeworks-neuro-issues#1256]
@solarrust 
# Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![issue1](https://user-images.githubusercontent.com/63258578/84442751-e4879380-ac46-11ea-8c96-f926c43a2496.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
