### ISSUE TITLE
Форма обратной связи "Оставайтесь на связи" заужена и неудобна для заполнения и восприятия на мобильных устройствах

### ISSUE THREAD

**Issue by AplusIv** [netology-code/git-homeworks-neuro-issues#1257]
@solarrust 
# Описание проблемы
**Главная страница. Форма обратной связи "Оставайтесь на связи" заужена и неудобна для заполнения и восприятия**
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы "Оставайтесь на связи"
### Ожидаемый результат
Текст формы приятен и удобен для чтения

### Фактический результат
Форма заужена и неудобна восприятия (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![issue2](https://user-images.githubusercontent.com/63258578/84444087-97f18780-ac49-11ea-8077-fb45f184fce8.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
