### ISSUE TITLE
В мобильном браузере на главной странице текст наезжает на изображение

### ISSUE THREAD

**Issue by YurtaevaSofia** [netology-code/git-homeworks-neuro-issues#1258]
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

@solarrust

**Шаги по воспроизведению**
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/63258004/84562553-e2642880-ad5d-11ea-8afe-6c3ab64cb330.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
