### ISSUE TITLE
В мобильном браузере на главной странице форма обратной связи слишком заужена

### ISSUE THREAD

**Issue by YurtaevaSofia** [netology-code/git-homeworks-neuro-issues#1259]
### На главной странице форма обратной связи "Оставайтесь на связи" слишком узкая и неудобна для заполнения пользователем

@solarrust

 **Шаги по воспроизведению**

* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до формы "Оставайтесь на связи"

**Ожидаемый результат**

Форма более широкая, текст читаем, поля удобны для заполнения.

**Фактический результат**

Форма слишком узкая и неудобна для восприятия (см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63258004/84562669-e8a6d480-ad5e-11ea-8f7c-5b5103487397.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
