### ISSUE TITLE
Проблема - при просмотре лендинга в мобильном браузере текст наезжает на картинку

### ISSUE THREAD

**Issue by vl-mobitutor** [netology-code/git-homeworks-neuro-issues#1260]
@solarrust 
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![InkedBug1_screen_1](https://user-images.githubusercontent.com/61451262/84577636-c34db100-adc6-11ea-8065-db62994a18d1.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
