### ISSUE TITLE
Проблема - при просмотре лендинга в мобильном браузере Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by vl-mobitutor** [netology-code/git-homeworks-neuro-issues#1261]
@solarrust 

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

#### Ожидаемый результат

Форма занимает доступное пространство по ширине,
текст корректно переносится 

#### Фактический результат

Форма сжата, текст сжат и некорректно переносится

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![InkedBug2_screen_1](https://user-images.githubusercontent.com/61451262/84577751-c5643f80-adc7-11ea-8dcc-752c2a3d7797.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
