### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата, текст трудно читается, некорректно переносится

### ISSUE THREAD

**Issue by trusenevdaniil** [netology-code/git-homeworks-neuro-issues#1263]
@solarrust 

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

### Ожидаемый результат
Форма занимает доступное пространство по ширине,
текст корректно переносится

### Фактический результат
Форма сжата, текст сжат и некорректно переносится

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60145550/84587949-e31fbc00-ae3c-11ea-9e71-514e7a41c518.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
