### ISSUE TITLE
текст наезжает на изображение

### ISSUE THREAD

**Issue by yana-resha** [netology-code/git-homeworks-neuro-issues#1268]
@solarrust
### Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..."** **наезжает на изображение** 

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. Скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![скриншот](https://user-images.githubusercontent.com/65972460/84805416-e669a200-b00c-11ea-9486-8e21c3ddec63.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
