### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by yana-resha** [netology-code/git-homeworks-neuro-issues#1269]
### Описание проблемы

**блок обратной связи слишком сжат**

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Хром (70.0.3538.75)

**Скриншоты**
![скриншот 2](https://user-images.githubusercontent.com/65972460/84806608-a1466f80-b00e-11ea-9a99-ea826c3f9edf.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
