### ISSUE TITLE
Проблема с текстом на картинке

### ISSUE THREAD

**Issue by AsotikovAnton** [netology-code/git-homeworks-neuro-issues#127]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+
Браузер: Chrome (76.0.3809.100)

**Скриншот**
![Screenshot_1](https://user-images.githubusercontent.com/52882101/63881401-73892f00-c9d8-11e9-9001-a3c0308359cf.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
