### ISSUE TITLE
Текст наезжает на основную картинку

### ISSUE THREAD

**Issue by Goodstasya** [netology-code/git-homeworks-neuro-issues#1270]
@solarrust 
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство:  Samsung A6+  (Android 10)
- Браузер: Chrome (70.0.3538.75)
![neuro1](https://user-images.githubusercontent.com/65770128/84903510-7dd30180-b0ae-11ea-84e5-f87d5d313327.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
