### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by Goodstasya** [netology-code/git-homeworks-neuro-issues#1271]
@solarrust

**Описание проблемы**

Текст сильно сжат (см. скриншот), в связи с этим поехал текст

**Программное окружение**

- Устройство: Samsung A6+ (Android 10)
- Браузер: Chrome (70.0.3538.75)

![neuro2](https://user-images.githubusercontent.com/65770128/84905516-0d79af80-b0b1-11ea-99a2-eb7862022659.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
