### ISSUE TITLE
Текст наезжает на основную картинку

### ISSUE THREAD

**Issue by Dimkuss** [netology-code/git-homeworks-neuro-issues#1273]
@solarrust
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение

Устройство: Redmi Note 5 (Android 10)
Браузер: Chrome (70.0.3538.75)
![84903510-7dd30180-b0ae-11ea-84e5-f87d5d313327](https://user-images.githubusercontent.com/66683657/85027831-0a4ef400-b183-11ea-8bc3-4273e0b39632.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
