### ISSUE TITLE
Текст не наезжает на изображение

### ISSUE THREAD

**Issue by OlesyaU** [netology-code/git-homeworks-neuro-issues#1277]
Шаги по воспроизведению
@solarrust 

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
**Ожидаемый результат**
Текст не наезжает на **изображение**

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Устройство: Samsung A6+ (Android 10)
Браузер: Chrome (70.0.3538.75)
![84903510-7dd30180-b0ae-11ea-84e5-f87d5d313327](https://user-images.githubusercontent.com/53311515/85037293-d5946a00-b18d-11ea-89b8-e8df1a16de4f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
