### ISSUE TITLE
Текст сильно сжат (см. скриншот)

### ISSUE THREAD

**Issue by OlesyaU** [netology-code/git-homeworks-neuro-issues#1278]
@solarrust

**Описание проблемы**

Текст сильно сжат (см. скриншот), в связи с этим поехал текст

**Программное окружение**

Устройство: Samsung A6+ (Android 10)
Браузер: Chrome (70.0.3538.75)
![84905516-0d79af80-b0b1-11ea-99a2-eb7862022659](https://user-images.githubusercontent.com/53311515/85037789-7aaf4280-b18e-11ea-99e8-4cdba3a6b282.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
