### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by etaaaaaaa** [netology-code/git-homeworks-neuro-issues#1279]
@solarrust 

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению:**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение

**Фактический результат:**
Текст наезжает на изображение (см. скриншот):

![Screenshot_13](https://user-images.githubusercontent.com/60183190/85052126-b51ddd00-b198-11ea-8da1-321dbccde506.png)

**Програмное окружение:**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
