### ISSUE TITLE
Проблема с отображением формы 

### ISSUE THREAD

**Issue by AsotikovAnton** [netology-code/git-homeworks-neuro-issues#128]
**Главная страница. Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
Форма имеет ширину экрана

**Фактический результат**
Форма слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+
Браузер: Chrome (76.0.3809.100)

**Скриншот**
![Screenshot_2](https://user-images.githubusercontent.com/52882101/63881881-70db0980-c9d9-11e9-9d1d-9d55cd9e0f52.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
