### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by etaaaaaaa** [netology-code/git-homeworks-neuro-issues#1280]
@solarrust 

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению:**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение

**Фактический результат:**
Текст наезжает на изображение (см. скриншот)

**Программное окружение:**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты:**
![Screenshot_1](https://user-images.githubusercontent.com/60183190/85052476-48efa900-b199-11ea-9545-bbe8ea52e579.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
