### ISSUE TITLE
Текст наезжает на картинку;

### ISSUE THREAD

**Issue by RinaMaximova** [netology-code/git-homeworks-neuro-issues#1285]
### Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

@solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67 (1)](https://user-images.githubusercontent.com/63468617/85136752-c45c6380-b248-11ea-92f4-c8158c5d830f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
