### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by RinaMaximova** [netology-code/git-homeworks-neuro-issues#1286]
### Описание проблемы

**Форма обратной связи слишком сжата**

@solarrust

**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Перейти к блоку обратной связи.

**Ожидаемый результат:**

Форма обратной связи отображается корректно.

**Фактический результат**

Форма обратной связи слишком сжата (см. Скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Хром (70.0.3538.75)

**Скриншот:**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63468617/85138067-d7703300-b24a-11ea-8605-0d024239a579.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
