### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by belolga55** [netology-code/git-homeworks-neuro-issues#1287]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

@solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/66379290/85151897-0099bf00-b25d-11ea-8184-fafb66ce9e05.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
