### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by belolga55** [netology-code/git-homeworks-neuro-issues#1290]
**Описание проблемы**

Форма обратной связи слишком сжата

Текст сильно сжат (см. Скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Хром (70.0.3538.75)

@solarrust

**Скриншот**

![image](https://user-images.githubusercontent.com/66379290/85152898-35f2dc80-b25e-11ea-9119-094f94f70c21.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
