### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by NAleshina** [netology-code/git-homeworks-neuro-issues#1291]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Safari
2. Скроллить до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст читается, не наслаивается на изображение.

#### Фактический результат

Текст невозможно прочесть, располагается поверх изображения

#### Программное окружение

* Устройство: iPhone 7 (iOS 13.5.1)
* Браузер: Safari 13.5.1

#### Скриншот

![](https://i.imgur.com/HJ1VbMj.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
