### ISSUE TITLE
Неправильные переносы текста

### ISSUE THREAD

**Issue by NAleshina** [netology-code/git-homeworks-neuro-issues#1292]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Safari
2. Скроллить до формы обратной связи

#### Ожидаемый результат

Текст написан правильно, правила переноса соблюдены.

#### Фактический результат

Правила переноса текста нарушены.

#### Программное окружение

* Устройство: iPhone 7 (iOS 13.5.1)
* Браузер: Safari 13.5.1

#### Скриншот

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/66998323/85173012-92f88d80-b272-11ea-9e72-1add287d8bfe.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
