### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by PavelZ990** [netology-code/git-homeworks-neuro-issues#1297]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![Лого](https://user-images.githubusercontent.com/63540743/85229458-74210500-b3f2-11ea-847d-1548f8841bd1.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
