### ISSUE TITLE
Форма "Оставайтесь на связи" слишком сжата

### ISSUE THREAD

**Issue by PavelZ990** [netology-code/git-homeworks-neuro-issues#1298]
Главная страница. 
Шаги по воспроизведению
1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.Пролистать страницу до формы "Оставайтесь на связи"

*Ожидаемый результат*
Форма полноценно расположена странице

*Фактический результат*
Форма сжата
![лого2](https://user-images.githubusercontent.com/63540743/85229727-3a50fe00-b3f4-11ea-9d83-95cd3ec58b52.png) (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
