### ISSUE TITLE
Текст наезжает на картинку.

### ISSUE THREAD

**Issue by Antyfeev96** [netology-code/git-homeworks-neuro-issues#1299]
For @solarrust 

**Главная страница. Текстовый блок "Воспользуетесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![image](https://user-images.githubusercontent.com/60137521/85277898-d75f7580-b48c-11ea-841e-26239667a56c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
