### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by juliapolyakova** [netology-code/git-homeworks-neuro-issues#130]
@solarrust
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/52862694/64066834-7a59b100-cc27-11e9-90b2-0d915fd4862e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
