### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Antyfeev96** [netology-code/git-homeworks-neuro-issues#1300]
For @solarrust 

**Форма обратной связи. Форма слишком сжата.**

**Воспроизведение**

- Открыть форму обратной связи в мобильной версии Chrome

**Ожидаемый результат**

Форма растягивается по ширине экрана

**Фактический результат**

Форма слишком узкая (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![image](https://user-images.githubusercontent.com/60137521/85279893-d67c1300-b48f-11ea-8b64-025c4466d25f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
