### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by Artyushin** [netology-code/git-homeworks-neuro-issues#1301]
@solarrust 
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. картинку)

#### Устройство и программное обеспечение

* Устройство: Nokia 3310 (Series 30++)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HJ1VbMj.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
