### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Artyushin** [netology-code/git-homeworks-neuro-issues#1302]
@solarrust 
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока обратной связи

#### Ожидаемый результат

Нормальный вид формы обратной связи

#### Фактический результат

Форма слишком сжата (см. скриншот)

#### Устройство и программное обеспечение

* Устройство: Nokia 3310 (Series 30++)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HcSpYkT.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
