### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by Stasia-Ku** [netology-code/git-homeworks-neuro-issues#1303]
#  Описание проблемы #
## Шаги по воспроизведению ##

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
## Ожидаемый результат ##

Текст не наезжает на изображение

## Фактический результат ##

Текст наезжает на изображение (см. скриншот)
<img width="526" alt="Снимок экрана 2020-06-24 в 12 36 20" src="https://user-images.githubusercontent.com/67242445/85532274-3b627500-b618-11ea-8453-aba46017b084.png">

## Программное окружение ##

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
