### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Stasia-Ku** [netology-code/git-homeworks-neuro-issues#1304]
# Описание проблемы #

## Шаги по воспроизведению ##

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Форма обратной связи"
## Ожидаемый результат ##

Форма обратной связи не сжата, слова и предложения не имеют переносов на другую строку

## Фактический результат ##

Форма сжата. Слово "Оставайтесь" имеет перенос на другую строку, "Email и телефон" отображаются на разных строках

## Программное окружение ##

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
<img width="526" alt="Снимок экрана 2020-06-24 в 13 11 27" src="https://user-images.githubusercontent.com/67242445/85537171-68188b80-b61c-11ea-8512-a6e2ffa0dff3.png">
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
