### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by daryamorozova** [netology-code/git-homeworks-neuro-issues#1305]
@solarrust 
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст находится выше изображения, не
 наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/67016228/85545224-6d79d400-b624-11ea-985b-5c30883f4cda.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
