### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by daryamorozova** [netology-code/git-homeworks-neuro-issues#1306]
@solarrust 

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока  "Оставайтесь на связи"

#### Ожидаемый результат

Все записи формы отображаются в одну строку (см. скриншот)
![Screenshot_1](https://user-images.githubusercontent.com/67016228/85546363-7cad5180-b625-11ea-9c0b-add1d39441cd.jpg)

#### Фактический результат

Форма обратной связи сжата, есть перенос строк  (см. скриншот)
#### Скриншоты
![22222222222](https://user-images.githubusercontent.com/67016228/85545887-0d376200-b625-11ea-9500-665fa092bb9d.png)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
