### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by NikitaRasskazkin** [netology-code/git-homeworks-neuro-issues#1307]
# Описание проблемы
## Шаги по восстановлению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
## Ожидаемый результат
Текст не наезжает на страницу и хорошо читаем
## Фактический результат
Текс наезжает на страницу и плохо читаем
## Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
## Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/65906727/85682915-ca859080-b6dd-11ea-8967-670ec156d2d8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
