### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by NikitaRasskazkin** [netology-code/git-homeworks-neuro-issues#1308]
# Описание проблемы
Форма обратной связи сжата в к центру экрана при просмотре с телефона
## Шаги по восстановлению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome-
1. Пролистать страницу до блока обратной связи
## Ожидаемый результат
Форма занимает большую часть ширины экрана смартфона
## Фактический результат
Форма обратной связи сжата в центре
## Программное окружение
-Устройство: iPhone 8+ (iOS 12.1)
-Браузер: Chrome (70.0.3538.75)
## Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/65906727/85684786-7b405f80-b6df-11ea-9cf0-73dbfc977fd5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
