### ISSUE TITLE
Проблема с формой обратной связи

### ISSUE THREAD

**Issue by juliapolyakova** [netology-code/git-homeworks-neuro-issues#131]
@solarrust
**Форма обратной связи слишком сжата**

**Шаги по воспроизведению**
1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2.  Пролистать страницу до блока обратной связи.

**Ожидаемый результат**

Форма обратной связи соразмерна ширине блока.

**Фактический результат**

Форма обратной связи сжата.

**Программное окружение**
-   Устройство: iPhone 8+ (iOS 12.1)
-   Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/52862694/64066893-27ccc480-cc28-11e9-9229-ced8e0996cc6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
