### ISSUE TITLE
Форма связи слишком сжата

### ISSUE THREAD

**Issue by KateProger** [netology-code/git-homeworks-neuro-issues#1310]
@solarrust 

**Главная страница. Блок "Оставайтесь на связи" меньшего размера, чем необходимо и слишком сжат**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Текст внутри блока (и сам блок) не сжаты, слова читаются целиком, не разделяясь на отдельные слоги

**Фактический результат**

Текст внутри блока (и сам блок) сжаты, слова не читаются целиком, разделяясь на отдельные слоги
 (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60820003/85711419-eeea6880-b6ef-11ea-8c3a-2ddab1ff2e1a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
