### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Vasilina0** [netology-code/git-homeworks-neuro-issues#1311]
@solarrust 

**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение

**Фактический результат:**
Текст наезжает на изображение (см. скриншот)

**Программное окружение:**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![111](https://user-images.githubusercontent.com/62928897/85828876-a9e83400-b7cc-11ea-98be-1a5260f82901.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
