### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Vasilina0** [netology-code/git-homeworks-neuro-issues#1312]
@solarrust

**Шаги по воспроизведению:** 

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму обратной связи

**Ожидаемый результат**
Форма обратной связи по ширине экрана

**Фактический результат**
Текст сжат (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты
![22](https://user-images.githubusercontent.com/62928897/85829280-98ebf280-b7cd-11ea-81e3-439719e7b71d.png)
**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
