### ISSUE TITLE
Текст «наезжает» на картинку при просмотре лендинга в мобильном браузере

### ISSUE THREAD

**Issue by Yuditskiy-o** [netology-code/git-homeworks-neuro-issues#1315]
# Описание проблемы
На главной странице лендинга текстовый блок «Воспользуйтесь современными возможностями...» «наезжает» на изображение.
@solarrust, посмотрите, пожалуйста.

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome;
2. Пролистать страницу до блока «Воспользуйтесь современными возможностями...».

### Ожидаемый результат
Текстовый блок расположен корректно и не «наезжает» на изображение

### Фактический результат 
Текст «наезжает» на изображение (см. скриншот)

### Программное окружение
**Устройство:** iPhone 8+ (iOS 12.1)
**Браузер:** Chrome (70.0.3538.75)

### Скриншот
![1](https://user-images.githubusercontent.com/64474359/85881929-a377ad80-b808-11ea-801b-bcb98c8b2e17.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
