### ISSUE TITLE
Форма обратной связи выглядит очень сжато при просмотре лендинга в мобильном браузере 

### ISSUE THREAD

**Issue by Yuditskiy-o** [netology-code/git-homeworks-neuro-issues#1316]
# Описание проблемы
На главной странице лендинга форма обратной связи выглядит сжато и неудобна для восприятия.
@solarrust, посмотрите, пожалуйста.

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome;
2. Пролистать страницу до формы обратной связи.

### Ожидаемый результат
Текст корректно переносится внутри формы, не выглядит сжатым

### Фактический результат
Форма обратной связи сжата 

### Программное окружение
**Устройство:** iPhone 8+ (iOS 12.1)
**Браузер:** Chrome (70.0.3538.75)

### Скриншот
![image](https://user-images.githubusercontent.com/64474359/85883359-0d915200-b80b-11ea-8108-25d426853a61.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
