### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Volgogradec** [netology-code/git-homeworks-neuro-issues#1319]
# Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.**

#### Шаги по воспроизведению ####
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат ####
Текст не наезжает на изображение

#### Фактический результат ####
Текст наезжает на изображение (см. скриншот)

#### Программное окружение ####
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты ####
![Скриншот ошибки](https://downloader.disk.yandex.ru/preview/48d472c65a4f6d85e97e6704712453d14e684c09bb68bca38c76dfad11b49f20/5ef7ace8/HzHeN5VqvabBH3D6XSfZZ28vf3fLPSfkZycBIDExhNEzCRI5j_dUqph7bqF1pDqJe1plaYWuZUCnJnAUqetizA==?uid=0&filename=2020-06-27+19-14-22+%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82+%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=98964145&size=2048x2048)

Ответственный @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
