### ISSUE TITLE
Форма обратной связи "Оставайтесь на связи" слишком сжата.

### ISSUE THREAD

**Issue by Volgogradec** [netology-code/git-homeworks-neuro-issues#1320]
# Описание проблемы
**Главная страница. Форма обратной связи "Оставайтесь на связи" слишком сжата.**
Можно убрать отступы по краям формы или установить параметр min-width. для стиля .contacts-card.

#### Шаги по воспроизведению ####
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы "Оставайтесь на связи"

#### Ожидаемый результат ####
Форма отображается на всю ширину экрана.

#### Фактический результат ####
Форма слишком сжата (см. скриншот). 

#### Программное окружение ####
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты ####
![Скриншот ошибки](https://s183sas.storage.yandex.net/rdisk/de3032649bf7787195fcb0bc0882d3717ffde394d20e60ca7608faef01d3166e/5ef7aeed/feGwobq8kFChWkp64b1blNDQX0t8_l6fgHJnRkNYK-wJi8vR5mjXJiZzUBRg2S-UCtFWRzS5vYJAzfB8bs-2dw==?uid=0&filename=2020-06-27+19-16-32+%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82+%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=98964145&media_type=image&etag=c81c6ef46a646fe1e3dc1f3e8660f6b1&fsize=66849&hid=ce19663894122cd4d9c7a1b33953aae4&rtoken=i0hKR6EK6ula&force_default=no&ycrid=na-6d4d1d5a35304304d922885d393fded8-downloader11h&ts=5a916d8e7d540&s=6f68d21d42cce112bf848c46703469bd4eb4b7c4a60e94bb779bd490c2f1b026&pb=U2FsdGVkX1_dsSHqNntQSrAZoW9YSkiGr-jRUEDmpKhB-2c0_OI2H9_YMIrh1ZR2M641TF6c77vnYT0VEsoBlWav38CHu1XH-p3eiARY81Q)

Ответственный @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
