### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by SanyaRokin** [netology-code/git-homeworks-neuro-issues#1325]
@solarrust

**Главная страница. Форма обратной связи сжата.**

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Форма обратной связи"

**Ожидаемый результат**
Форма обратной связи растянута по всему экрану

**Фактический результат**
Форма обратной связи слишком сжата

**Программное окружение**

-  Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/67265413/85982358-5b19e480-b9ee-11ea-8d9c-94b73f1fd595.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
