### ISSUE TITLE
На главной странице лендинга текстовый блок «Воспользуйтесь современными возможностями...» «наезжает» на изображение.

### ISSUE THREAD

**Issue by SanyaRokin** [netology-code/git-homeworks-neuro-issues#1326]
@solarrust,

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome;

- Пролистать страницу до блока «Воспользуйтесь современными возможностями...».

**Ожидаемый результат**
Текстовый блок расположен корректно и не «наезжает» на изображение

**Фактический результат**
Текст «наезжает» на изображение.

![85881929-a377ad80-b808-11ea-801b-bcb98c8b2e17](https://user-images.githubusercontent.com/67265413/85982654-e2675800-b9ee-11ea-9c39-4e3edb6229b8.png)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
