### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by BethPech** [netology-code/git-homeworks-neuro-issues#1328]
@solarrust

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Форма обратной связи"

**Ожидаемый результат**
Форма обратной связи не слишком сжата

**Фактический результат**
Форма обратной связи слишком сжата, не читабельно (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/64593985/85992345-67f20480-b9fd-11ea-9ae3-1f234d83758b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
