### ISSUE TITLE
Проблема с формой обратной связи

### ISSUE THREAD

**Issue by krlTarasov** [netology-code/git-homeworks-neuro-issues#133]
# Описание проблемы
@solarrust 
**Главная страница. Форма обратной связи слишком сжата.**
### Шаги по воспроизведению

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до формы обратной связи

### Ожидаемый результат
Форма имеет ширину экрана

### Фактический результат
Форма слишком сжата (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (76.0.3809.100)

### Скриншот

![form screenshot](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
