### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Syan91** [netology-code/git-homeworks-neuro-issues#1333]
@solarrust

Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншоты
![85991397-0aa98380-b9fc-11ea-91c6-518fc3897c91](https://user-images.githubusercontent.com/66880451/86094437-32aaec80-bab9-11ea-880e-e90d7dd9ee77.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
