### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Syan91** [netology-code/git-homeworks-neuro-issues#1334]
@solarrust

Шаги по воспроизведению

1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.Пролистать страницу до блока "Форма обратной связи"

Ожидаемый результат
Форма обратной связи не слишком сжата

Фактический результат
Форма обратной связи слишком сжата, не читабельно (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/66880451/86094882-c5e42200-bab9-11ea-9c12-79e223ec4fee.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
