### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by geralt-of-siberia** [netology-code/git-homeworks-neuro-issues#1335]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 11 (iOS 13.5.1)
* Браузер: Safari

#### Скриншоты

![](https://i.imgur.com/HJ1VbMj.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
