### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by geralt-of-siberia** [netology-code/git-homeworks-neuro-issues#1336]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока Обратной Связи

#### Ожидаемый результат

Форма обратной связи в размер экрана

#### Фактический результат

Форма обратной связи сжата

#### Программное окружение

* Устройство: iPhone 11 (iOS 13.5.1)
* Браузер: Safari

#### Скриншоты

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
