### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Rina043** [netology-code/git-homeworks-neuro-issues#1337]
### **Описание** проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Назначен отвественным** @solarrust

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67 (1)](https://user-images.githubusercontent.com/67234113/86137477-5fcdbe00-bafe-11ea-9916-a7dd225a9a26.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
