### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Rina043** [netology-code/git-homeworks-neuro-issues#1338]
### **Описание проблемы**

**Главная страница. Форма для обратной связи слишком сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи "Оставайтесь на связи..."

**Ожидаемый результат**

Форма обратной связи не слишком сжата

**Фактический результат**

Форма обратной связи слишком сжата, плохо виден текст (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Ответственным назначен** @solarrust

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/67234113/86140360-d4562c00-bb01-11ea-8746-233a1348ce11.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
