### ISSUE TITLE
Текст наезжает на картинку 

### ISSUE THREAD

**Issue by uglymarrow** [netology-code/git-homeworks-neuro-issues#1341]
## Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**@solarrust**

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншоты

![image](https://user-images.githubusercontent.com/52126014/86231161-c7d1e200-bb9a-11ea-9b1f-360571f1fd7d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
