### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by uglymarrow** [netology-code/git-homeworks-neuro-issues#1344]
**@solarrust**
### Шаги по воспроизведению
Открыть  страницу обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
### Ожидаемый результат
Форма обратной связи растянута на весь экран
### Фактический результат
Форма обратной связи слишком сжата
### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншот
![image](https://user-images.githubusercontent.com/52126014/86232409-94905280-bb9c-11ea-8155-b5776232f552.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
