### ISSUE TITLE
Главная страница. Текст наезжает на изображение

### ISSUE THREAD

**Issue by Zeinab182** [netology-code/git-homeworks-neuro-issues#1349]
#  **Описание проблемы**

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1.  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**
![Скрин](https://user-images.githubusercontent.com/67228749/86265020-8efa3300-bbc3-11ea-9e9f-b35bbc209868.png)

**Пользователь**
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
