### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Zeinab182** [netology-code/git-homeworks-neuro-issues#1350]
# **Описание проблемы**

**Главная страница. Блок "Оставайтесь на связи" слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма обратной связи корректно отображается по ширине экрана

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Пользователь**
@solarrust

**Скриншот**
![Скриншот](https://user-images.githubusercontent.com/67228749/86266947-442dea80-bbc6-11ea-8aa7-cb2a89bb8fbc.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
