### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by MaratKrahin** [netology-code/git-homeworks-neuro-issues#1354]
@solarrust 
Главная страница. Текстовый блок "Оставайтесь на связи" слишком сжат

Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат

Форма обратной связи занимает 1/5 экрана.

Фактический результат

Форма обратной связи слишком сжата.

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Пользователь @solarrust

Скриншоты
![2](https://user-images.githubusercontent.com/67018375/86281567-6df70980-bbe6-11ea-8547-a48bebf12e60.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
