### ISSUE TITLE
home worke issues 1

### ISSUE THREAD

**Issue by VasiliyMerzlykov** [netology-code/git-homeworks-neuro-issues#1356]
@solarrust
# Описание проблемы
Текст наезжает на картинку:

![](https://camo.githubusercontent.com/d90a6e5e9269c1926cc5e5ea6d624a3a06b53f9a/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)

### Ожидаемый результат
Текст наезжает на картинку

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
