### ISSUE TITLE
home worke issues 2

### ISSUE THREAD

**Issue by VasiliyMerzlykov** [netology-code/git-homeworks-neuro-issues#1357]
@solarrust
# Описание проблемы:
Форма обратной связи слишком сжата.
![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)
## Ожидаемый результат
Форма обратной связи удобная для использования по размеру

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
