### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by MaxEroshenko** [netology-code/git-homeworks-neuro-issues#1358]
Форма обратно связи слишком сжата.
Ожидаемый результат
Форма сделана комфортно для глаз

Фактический результат
Форма слишком сжата

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![1](https://user-images.githubusercontent.com/67067665/86494186-f0b1cd00-bd7c-11ea-867e-ddfb857697d8.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
