### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by MaxEroshenko** [netology-code/git-homeworks-neuro-issues#1359]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
    
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/67067665/86493868-d4f9f700-bd7b-11ea-90c5-9deb459d420d.png)

@solarrust

**Comment by MaxEroshenko** [comment]
> Шаги по воспроизведению
> Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
> Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
> Ожидаемый результат
> Текст не наезжает на изображение
> 
> Фактический результат
> Текст наезжает на изображение (см. скриншот)
> 
> Программное окружение
> Устройство: iPhone 8+ (iOS 12.1)
> Браузер: Chrome (70.0.3538.75)
> 
> ![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/67067665/86493868-d4f9f700-bd7b-11ea-90c5-9deb459d420d.png)

**Comment by MaxEroshenko** [comment]
> Шаги по воспроизведению
> Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
> Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
> Ожидаемый результат
> Текст не наезжает на изображение
> 
> Фактический результат
> Текст наезжает на изображение (см. скриншот)
> 
> Программное окружение
> Устройство: iPhone 8+ (iOS 12.1)
> Браузер: Chrome (70.0.3538.75)
> 
> ![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/67067665/86493868-d4f9f700-bd7b-11ea-90c5-9deb459d420d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
