### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by alicenetologia** [netology-code/git-homeworks-neuro-issues#1360]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![Captura de pantalla 2020-07-04 a las 14 15 08](https://user-images.githubusercontent.com/67114443/86512275-eafdcb00-be00-11ea-87ca-9660919d5eb5.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
