### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by alicenetologia** [netology-code/git-homeworks-neuro-issues#1361]
**Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока " Форма обратной связи"

**Ожидаемый результат**

Форма обратной связи в удобном для юзера формате и нормальном размере.

**Фактический результат**

Форма слишком сжата 

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)

Браузер: Chrome (70.0.3538.75)

**Скриншот**
![Captura de pantalla 2020-07-04 a las 14 29 51](https://user-images.githubusercontent.com/67114443/86512466-dcb0ae80-be02-11ea-9ccd-5aafc1c61eec.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
