### ISSUE TITLE
Форма обратной связи сжата.

### ISSUE THREAD

**Issue by Kristuut** [netology-code/git-homeworks-neuro-issues#1363]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма обратной связи выглядит корректно.

**Фактический результат**

Форма сжата, перенос по словам некорректен.

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/67163997/86519597-65146b00-be66-11ea-98c1-1e39d676cf9a.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
