### ISSUE TITLE
Проблема с отображением формы

### ISSUE THREAD

**Issue by Gruant** [netology-code/git-homeworks-neuro-issues#137]
**@solarrust**
# Описание проблемы

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)###Скриншоты

### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/47811642/64080690-b82a0880-ccff-11e9-9e9f-758c4a437855.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
