### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by tegslava** [netology-code/git-homeworks-neuro-issues#1371]
@solarrust

# Описание проблемы

**Главная страница. Форма обратной связи отображается в сжатом виде**

### Шаги по воспроизведению

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Форма обратной связи растягивается в зависимости от ширины страницы, сохраняя порядок расположения строк и элементов ввода. 

### Фактический результат
Форма обратной связи отображается в сжатом виде (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### **Скриншоты:**
![image](https://user-images.githubusercontent.com/43936174/86541731-e5df6f80-bf17-11ea-80d5-737a32f6a809.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
