### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Irina-Bebenina** [netology-code/git-homeworks-neuro-issues#1374]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![11](https://user-images.githubusercontent.com/67203147/86600100-40281100-bfa8-11ea-9aba-1ddcd2ec15ba.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
