### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Irina-Bebenina** [netology-code/git-homeworks-neuro-issues#1375]
@solarrust

**Описание проблемы**

Форма обратной связи слишком сжата

Текст сильно сжат (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![22](https://user-images.githubusercontent.com/67203147/86601708-546d0d80-bfaa-11ea-8271-fca8f98ef82c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
