### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by KristinaPelevina** [netology-code/git-homeworks-neuro-issues#1377]
**Описание проблемы**

**Главная страница. Форма обратной связи. Форма очень сжата,слова режутся, буквы едут и переносятся не по правилам русского языка**

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Форма обратной связи."

**Ожидаемый результат**

Форма нормальной формы

**Фактический результат**

Форма слишком сжата (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![2020-07-03_17-15-49](https://user-images.githubusercontent.com/67319943/86727889-0b729300-c056-11ea-8486-b9fdfc977a58.jpg)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
