### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by OlegSkrill** [netology-code/git-homeworks-neuro-issues#1378]
Описание проблемы

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат

Текст не наезжает на изображение

Фактический результат

Текст наезжает на изображение (см. скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншоты:
@dfitiskin 
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/67225903/86785596-4edff800-c07c-11ea-8f0c-a6f6ac066ed0.png)

#
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
