### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by OlegSkrill** [netology-code/git-homeworks-neuro-issues#1379]
### **Описание проблемы**
Форма обратной связи слишком сжата
Текст сильно сжат (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот:

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/67225903/86786133-155bbc80-c07d-11ea-8fbc-e08d2c59b82e.png)

  @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
