### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by teodorro** [netology-code/git-homeworks-neuro-issues#1385]
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат
Текстовый блок в ширину экрана

### Фактический результат
Ширина текстового блока заметно меньше ширины экрана

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/14045231/86917808-64adf580-c12e-11ea-8ed8-4f7ab9e792a9.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
