### ISSUE TITLE
Текст "Воспользуйтесь современными возможностями..." наезжает на картинку

### ISSUE THREAD

**Issue by Tatiana-Brener** [netology-code/git-homeworks-neuro-issues#1386]

**Comment by Tatiana-Brener** [comment]
# Описание проблемы #

### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение ###

### Шаги по воспроизведению: ###

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
1. Наблюдать результат

### Ожидаемый результат ###

Текст не наезжает на изображение

### Фактический результат ###

Текст наезжает на изображение (см. скриншот)

### Программное окружение ###

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust 

### Скриншот ###
![Скриншот_3 2](https://user-images.githubusercontent.com/63563203/87191565-5bbf4e80-c2fd-11ea-9888-fe0ebfbf164a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
