### ISSUE TITLE
Форма обратной связи на сайте NeuroStartUp слишком сжата

### ISSUE THREAD

**Issue by Tatiana-Brener** [netology-code/git-homeworks-neuro-issues#1387]
# Описание проблемы #

### Шаги по воспроизведению: ###

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи
1. Наблюдать результат

### Ожидаемый результат ###

Форма обратной связи не сжата и имеет пропорциональные, корректные размеры

### Фактический результат ###

Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение ###

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

@solarrust

### Скриншот ###

![Скриншот2_3 2](https://user-images.githubusercontent.com/63563203/87192384-03894c00-c2ff-11ea-8751-07639ea4b198.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
