### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by FadeevaDari** [netology-code/git-homeworks-neuro-issues#1389]
## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока обратной связи

## Ожидаемый результат
Форма имеет размер ....

## Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот 
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/67522974/87231553-b9689f00-c3c0-11ea-97d9-b56d2267fcbd.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
