### ISSUE TITLE
Проблемы с отображением в мобильной версии (форма)

### ISSUE THREAD

**Issue by ChumakovaAnna** [netology-code/git-homeworks-neuro-issues#139]
**Главная страница. Форма обратной связи слишком сжата**

*Шаги по воспроизведению*
 1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
 1. Пролистать страницу до форма обратной связи

**Ожидаемый результат**
Форма занимает всю ширину экрана

**Фактический результат**
Форма сжата (см. скриншот)

*Программное окружение*
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/52786216/64082409-f89d7c80-cd27-11e9-8f71-595b149bd050.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
