### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by PiPitOsO** [netology-code/git-homeworks-neuro-issues#1391]
### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока обратной связи
### Ожидаемый результат
&&&

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншот
![87231553-b9689f00-c3c0-11ea-97d9-b56d2267fcbd](https://user-images.githubusercontent.com/67708493/87316413-6b71a980-c52e-11ea-84ef-acaa46431bcb.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
