### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by GSahar** [netology-code/git-homeworks-neuro-issues#1392]
@solarrust
# Описание проблемы
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome ( 83.0.4103.116)

#### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/37238286/87325759-4dff0880-c54b-11ea-8d31-f739257f17c7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
