### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by GSahar** [netology-code/git-homeworks-neuro-issues#1393]
@solarrust
# Описание проблемы
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"
#### Ожидаемый результат

Форма подстраивается под экран

#### Фактический результат

Форма не подстраивается под экран (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome ( 83.0.4103.116)

#### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/37238286/87326546-5146c400-c54c-11ea-80fc-06cef8a13f3a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
