### ISSUE TITLE
Текст заезжает на картинку на главной странице

### ISSUE THREAD

**Issue by Paneka-1** [netology-code/git-homeworks-neuro-issues#1394]
@solarrust 

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/67044124/87702457-1dfd7280-c7a2-11ea-884c-8c3aae7b4343.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
