### ISSUE TITLE
Форма обратной связи слишком узкая

### ISSUE THREAD

**Issue by Paneka-1** [netology-code/git-homeworks-neuro-issues#1395]
@solarrust 

**Главная страница. Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
Форма корректно отображается

**Фактический результат**
Форма отображается слишком узко (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/67044124/87703014-daefcf00-c7a2-11ea-97f8-8037db411a25.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
