### ISSUE TITLE
Сильно сжата форма обратной связи

### ISSUE THREAD

**Issue by landuska** [netology-code/git-homeworks-neuro-issues#14]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Форма обратной связи"

### Ожидаемый результат

Форма имеет ширину, указанную в макете

### Фактический результат

Форма сильно сжата (см. скриншот)

### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот

![изображение сжатой  формы](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

@ikrieg обрати внимание

**Comment by solarrust** [comment]
Someday I'll fix it 🤗
