### ISSUE TITLE
Исправить текст наезжающий на картинку, увеличить форму обратной связи

### ISSUE THREAD

**Issue by hobbitboy** [netology-code/git-homeworks-neuro-issues#140]
###  "Воспользуйтесь современными возможностями..." наезжает на изображение. Форма обратной связи слишком сжата.

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

- Исправить

- Пролистать до "Оставайтесь на связи..."

- Исправить

**Ожидаемый результат**

- Текст не наезжает на изображение

- Форма обратной связи на весь экран

**Фактический результат**

- Текст наезжает на изображение (см. скриншот)

- Форма обратной связи сжата

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/52885799/64184537-445d3c80-ce74-11e9-96c0-287cd3993f79.png)
 ![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/52885799/64184554-4921f080-ce74-11e9-8cb4-cc1dd70aa125.png)

**@solarrust просьба исправить ошибки**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
