### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Kholtobina** [netology-code/git-homeworks-neuro-issues#1401]
# **Описание проблемы**

**Главная страница. Форма обратной связи слишком сжата и текст располагается некорректно**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока обратной связи

**Ожидаемый результат**
Форма обратной связи отображается корректно 

**Фактический результат**
Текст сильно сжат (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![issue 2](https://user-images.githubusercontent.com/67462962/87859962-04932c80-c942-11ea-89d0-9119e09d0f5c.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
