### ISSUE TITLE
Некорректное отображение формы обратной связи

### ISSUE THREAD

**Issue by gudbrant** [netology-code/git-homeworks-neuro-issues#1403]
### Описание проблемы

**Главная страница (_мобильная версия_). Форма обратной связи слишком сжата и текст располагается некорректно**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока обратной связи

**Ожидаемый результат**
Форма обратной связи отображается корректно

**Фактический результат**
Текст сильно сжат (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61345734/87930851-5b704180-cabb-11ea-8f5b-ed1e88b8d8ac.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
