### ISSUE TITLE
Текст наезжает на изображение на главной странице

### ISSUE THREAD

**Issue by pointofnoreturn1** [netology-code/git-homeworks-neuro-issues#1406]
@solarrust 
**Шаги по воспроизведению**
1. Открыть сайт проекта NeuroStartUp через мобильный браузер Google Chrome
2. Прокрутить до текста "Искусственный интеллект решающий ваши бизнес-задачи"
 
**Ожидаемый результат**
Последующий блок текста не наезжает на изображение

**Фактический результат**
Последующий блок текста наезжает на изображение (скриншот во вложении)

**Программное окружение**
Устройство: iPhone 7+ (iOS 13.5.1)
Браузер: Chrome (84.0.4147.71)

![screenshot 1](https://user-images.githubusercontent.com/64410718/88093106-38688f00-cb9a-11ea-88e6-7d9c6d2b6630.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
