### ISSUE TITLE
Некорректное отображение формы обратной связи

### ISSUE THREAD

**Issue by pointofnoreturn1** [netology-code/git-homeworks-neuro-issues#1407]
@solarrust 
**Шаги по воспроизведению**
1. Открыть сайт проекта NeuroStartUp через мобильный браузер Google Chrome
2. Прокрутить до формы обратной связи
 
**Ожидаемый результат**
Элемент формы обратной связи имеет корректную ширину

**Фактический результат**
Элемент формы обратной связи имеет некорректную ширину (слишком сжат). Скриншот во вложении

**Программное окружение**
Устройство: iPhone 7+ (iOS 13.5.1)
Браузер: Chrome (84.0.4147.71)

![screenshot 2](https://user-images.githubusercontent.com/64410718/88093737-220f0300-cb9b-11ea-8bc4-fec785c263fe.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
