### ISSUE TITLE
Главная страница. Верстка формы обратной связи

### ISSUE THREAD

**Issue by Romakin** [netology-code/git-homeworks-neuro-issues#1408]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

#### Ожидаемый результат

Отступы по бокам формы в сумме составляют не более 10% ширины экрана

#### Фактический результат

Отступы по бокам формы занимают более 30% ширины экрана

#### Программное окружение

* Устройство: iPhone 8+ (iOS 13.5.1)
* Браузер: Google Chrome (84.0.4147.71)

#### Скриншоты

![](https://i.imgur.com/HcSpYkT.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
