### ISSUE TITLE
Главная страница. Верстка промо блока

### ISSUE THREAD

**Issue by Romakin** [netology-code/git-homeworks-neuro-issues#1409]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не перекрывает изображение
Текст заголовков центрирован
Отступы по бокам в сумме составляют не более 20% ширины экрана

#### Фактический результат

Текст перекрывает изображение (см. скриншот)
Текст заголовков не центрирован
Отступы занимают более 30% ширины экрана

#### Программное окружение

* Устройство: iPhone 8+ (iOS 13.5.1)
* Браузер: Google Chrome (84.0.4147.71)

#### Скриншоты

![](https://i.imgur.com/HJ1VbMj.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
