### ISSUE TITLE
текстовый блок наезжает на картинку 

### ISSUE THREAD

**Issue by veronazavr** [netology-code/git-homeworks-neuro-issues#1410]

**Comment by veronazavr** [comment]
### Описание проблемы

@solarrust

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**_Ожидаемый результат_**
Текст не наезжает на изображение

**_Фактический результат_**
Текст наезжает на изображение (см. скриншот)

_Программное окружение_
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/67536596/88300512-3b838c80-cd0c-11ea-93a1-641295952606.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
