### ISSUE TITLE
текст наезжает на изображение в мобильной версии сайта.

### ISSUE THREAD

**Issue by veronazavr** [netology-code/git-homeworks-neuro-issues#1411]

**Comment by veronazavr** [comment]
@solarrust
### **Описание проблемы**

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

_Ожидаемый результат_
Текст не наезжает на изображение

_Фактический результат_
Текст наезжает на изображение (см. скриншот)

**_Программное окружение_**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты:**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/67536596/88302026-0415df80-cd0e-11ea-92eb-bd3ba00fa65c.png)
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/67536596/88302032-05470c80-cd0e-11ea-9f80-a38f89fa897e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
