### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by artemkoko13** [netology-code/git-homeworks-neuro-issues#1418]
@solarrust

Шаги по воспроизведению

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат

Текст не наезжает на изображение
Фактический результат

Текст наезжает на изображение (см. скриншот)
Программное окружение

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/67863773/88595124-1a53d080-d06b-11ea-8a19-07c8c2b214bf.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
