### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by artemkoko13** [netology-code/git-homeworks-neuro-issues#1419]
@solarrust

Форма обратной связи слишком сжата

Текст сильно сжат (см. скриншот)
Программное окружение

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

Скриншот

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/67863773/88595369-7cacd100-d06b-11ea-81dd-e0237720b4d9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
