### ISSUE TITLE
Форма обратной связи слишком сжата. Исправить пользователю @sollarrust

### ISSUE THREAD

**Issue by noisydimon** [netology-code/git-homeworks-neuro-issues#1422]
Главная страница. Форма обратной связи не соответствует макету (ширина заужена)
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Обратная связь" и кликнуть на иконку
Ожидаемый результат
Форма обратно связи соответствует макету

Фактический результат
Форма обратной связи не соответствует макету (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/64734161/88754760-36896780-d168-11ea-8a09-d69e7bc27a62.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
