### ISSUE TITLE
Текст наезжает на картинку @solarrust

### ISSUE THREAD

**Issue by iravahnina** [netology-code/git-homeworks-neuro-issues#1423]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение @solarrust 

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/65765500/88791740-dbc13180-d1a2-11ea-8e5e-eb89a981c146.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
