### ISSUE TITLE
Форма обратной связи слишком сжата @solarrust

### ISSUE THREAD

**Issue by iravahnina** [netology-code/git-homeworks-neuro-issues#1424]
Форма обратной связи слишком сжата
@solarrust 
**Проблема:**
 Текст слишком сжат(см.скриншот)

**Ожидаемый результат**
Форма обратной связи отображается корректно.

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/65765500/88792690-4d4daf80-d1a4-11ea-9c20-0165155653ac.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
