### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AlenaKorSpb** [netology-code/git-homeworks-neuro-issues#1426]
@solarrust
# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в  браузере Chrome
2. Пролистать страницу до блока обратной связи "Оставайтесь на связи"
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: DESKTOP-MUBS610
Браузер: Chrome (Windows 10)
### Скриншоты
https://prnt.sc/tqqdsa

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
