### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by german-vorobyev** [netology-code/git-homeworks-neuro-issues#1427]
# Описание проблемы
## Шаги по воспроизведению
 Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
## Ожидаемый результат
 Текст не наезжает на изображение
## Фактический результат
Текст наезжает на изображение (см. скриншот)
## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
## Скриншоты
https://prnt.sc/tqq1ry

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
