### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by german-vorobyev** [netology-code/git-homeworks-neuro-issues#1428]
# Описание проблемы
## Шаги по воспроизведению
Пролистать страницу до блока "Оставайтесь на связи"
## Ожидаемый результат
 Форма обратной связи должна быть удобнее пользователю
## Фактический результат
Форма обратной связи слишком сжата(см.скриншот)
## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
## Скриншоты
https://prnt.sc/tqqdsa

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
