### ISSUE TITLE
Лендинг. Мобильный браузер. Текст наезжает на картинку

### ISSUE THREAD

**Issue by EkaterinaLisovec** [netology-code/git-homeworks-neuro-issues#1429]
@solarrust
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![1](https://user-images.githubusercontent.com/68905137/88953826-237ab280-d2a2-11ea-8952-69338dd1b70b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
