### ISSUE TITLE
Лендинг. Мобильный браузер. Форма обратной связи сжата

### ISSUE THREAD

**Issue by EkaterinaLisovec** [netology-code/git-homeworks-neuro-issues#1430]
@solarrust
### Главная страница. Блок "Оставайтесь на связи" сжат

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Блок отображается стандартно

**Фактический результат**
Блок отображается "сжато"

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![2](https://user-images.githubusercontent.com/68905137/88954119-8c622a80-d2a2-11ea-863d-4f7f33631391.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
