### ISSUE TITLE
На главной странице NeuroStartUp съехал текстовый блок.

### ISSUE THREAD

**Issue by DrobchikDaria** [netology-code/git-homeworks-neuro-issues#1431]
@solarrust 
### Шаги по воспроизведению (Steps to reproduce)

1. Зайти на главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат (Expected result)

Текст не наезжает на изображение

### Фактический результат (Actual result)

Текст наезжает на изображение (см. скриншот)

### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты
![image](https://user-images.githubusercontent.com/61200143/88965915-28e0f880-d2b4-11ea-9d8b-f3fee91efdb5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
