### ISSUE TITLE
Форма обратной связи NeuroStartUp в мобильном браузере Chrome слишком сжата.

### ISSUE THREAD

**Issue by DrobchikDaria** [netology-code/git-homeworks-neuro-issues#1432]
@solarrust 
### Шаги по воспроизведению (Steps to reproduce)

1. Зайти на веб-сайт NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока с формой обратной связи "Оставайтесь на связи"

### Ожидаемый результат (Expected result)

Блок с обратной связью имеет стандартный вид по ширине экрана смартфона.

### Фактический результат (Actual result)

Блок с обратной связью сжат (см. скриншот)

### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты
![image](https://user-images.githubusercontent.com/61200143/88967423-79595580-d2b6-11ea-85c4-d009c1214d7c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
