### ISSUE TITLE
проблема отображения текста на мобильных устройствах 

### ISSUE THREAD

**Issue by kksyai** [netology-code/git-homeworks-neuro-issues#1433]
@solarrust заметила проблему - на мобильном текст наезжает на картинку 
Устройство: iPhone 7+ (iOS 13.6), Браузер: Chrome (84.0.4147.89)

![скриншот](https://i.imgur.com/HJ1VbMj.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
