### ISSUE TITLE
проблема отображения формы обратной связи на мобильных устройствах 

### ISSUE THREAD

**Issue by kksyai** [netology-code/git-homeworks-neuro-issues#1434]
Привет Ален! @solarrust 
Заметила проблему при просмотре на мобильном - форма обратной связи слишком сжата.
Устройство iPhone 7+ 13.6OS, браузер Chrom 84.0.4147.89

![скрин](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
