### ISSUE TITLE
Большие отступы от краев страницы у блока "Оставайтесь с нами"

### ISSUE THREAD

**Issue by Satura** [netology-code/git-homeworks-neuro-issues#1442]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Оставайтесь на связи".

#### Ожидаемый результат

Отступы от краев страницы имеют минимальный размер или не видны. Блок обратной связи размещен на всю (или с минимальным отступом) ширину страницы (для мобильных устройств и на ПК при сжатии окна браузера по ширине).  

#### Фактический результат

Большие отступы от краев страницы, слишком сжат блок обратной связи (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![hw-3-2_issue2](https://user-images.githubusercontent.com/15552095/89434720-523ed000-d75d-11ea-9db3-48ac7263ef7a.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
