### ISSUE TITLE
Форма "Оставайтесь на связи" слишком сжата

### ISSUE THREAD

**Issue by olegkuzmenko** [netology-code/git-homeworks-neuro-issues#1444]
**@solarrust  форма "Оставайтесь на связи" слишком узкая.**

**Ожидаемый результат**
Форма нормальной ширины

**Фактический результат**
форма слишком узкая(см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/49239048/89499502-cebac880-d7c8-11ea-870b-a81b414726ea.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
