### ISSUE TITLE
Описание проблемы

### ISSUE THREAD

**Issue by Anton-CSS** [netology-code/git-homeworks-neuro-issues#1446]
@solarrust

# Описание проблемы
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![222](https://user-images.githubusercontent.com/58559877/89533264-d5166800-d7fb-11ea-9edb-be6f01bf5792.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
