### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by IgorEkimow** [netology-code/git-homeworks-neuro-issues#1452]
@solarrust 

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма обратной связи без искажений

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://user-images.githubusercontent.com/49239048/89499502-cebac880-d7c8-11ea-870b-a81b414726ea.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
