### ISSUE TITLE
В мобильной версии сайта форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Shavonsky** [netology-code/git-homeworks-neuro-issues#1454]
@solarrust 
# Описание проблемы
#### Шаги по воспроизведению:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"
#### Ожидаемый результат
Форма обратной связи отображается по ширине экрана

#### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
#### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/69080021/89706239-715f7c80-d96c-11ea-83db-271ed2389f10.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
