### ISSUE TITLE
Наезжающий на картинку текст на главном баннере стартовой страницы

### ISSUE THREAD

**Issue by 18floor** [netology-code/git-homeworks-neuro-issues#1455]
# Описание проблемы

#### Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

#### Ожидаемый результат

Текст не наползает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: Google Pixel 4a  (Android 10.1)
* Браузер: Chrome (84.0.4147.111)

#### Скриншот

![1](https://user-images.githubusercontent.com/65921171/89708038-5f85d580-d97c-11ea-996b-2b15c54a4250.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
