### ISSUE TITLE
Главная страница. Форма обратной связи. Форма излишне сжата по ширине.

### ISSUE THREAD

**Issue by 18floor** [netology-code/git-homeworks-neuro-issues#1456]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Прокрутить страницу до формы обратной связи.

#### Ожидаемый результат

Форма обратной связи растянута по ширине экрана, с небольшим (10-15px) отступом от краев.

#### Фактический результат

Форма обратной связи слишком сжата по ширине.

#### Программное окружение

* Устройство: Google Pixel 4a  (Android 10.1)
* Браузер: Chrome (84.0.4147.111)

#### Скриншот

![2](https://user-images.githubusercontent.com/65921171/89708606-43386780-d981-11ea-87e6-7cb19cf32b9e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
