### ISSUE TITLE
Текст наезжает на картинку.

### ISSUE THREAD

**Issue by zPlumbum** [netology-code/git-homeworks-neuro-issues#1457]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Скриншот

![](https://i.imgur.com/HJ1VbMj.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
