### ISSUE TITLE
Главная страница. Форма имеет неверную ширину.

### ISSUE THREAD

**Issue by elena-liashkova** [netology-code/git-homeworks-neuro-issues#1462]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока формы обратной связи.

#### Ожидаемый результат

Форма занимает всю ширину экрана, поля имеют достаточную для удобного заполнения длину

#### Фактический результат

Форма слишком узкая, текст смотрится скомканным, поля неудобно заполнять.

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HcSpYkT.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
