### ISSUE TITLE
Главная страница: текстовый блок наезжает на изображение.

### ISSUE THREAD

**Issue by Cliffart44** [netology-code/git-homeworks-neuro-issues#1463]
@solarrust 

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями...".

#### Ожидаемый результат

Текст не наезжает на изображение.

#### Фактический результат

Текст наезжает на изображение (на скриншоте).

#### Программное окружение

* Устройство: Sony Xperia E5633 (Android 6).
* Браузер: Chrome (84.0.4147.111).

#### Скриншот

![](https://i.imgur.com/HJ1VbMj.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
