### ISSUE TITLE
Главная страница: форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Cliffart44** [netology-code/git-homeworks-neuro-issues#1464]
@solarrust 

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до формы обратной связи.

#### Ожидаемый результат

Форма занимает всю полезную площадь экрана.

#### Фактический результат

Форма использует около 35% экрана (на скриншоте).

#### Программное окружение

* Устройство: Sony Xperia E5633 (Android 6).
* Браузер: Chrome (84.0.4147.111).

#### Скриншот

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
