### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by EleonoraPopushoi** [netology-code/git-homeworks-neuro-issues#1466]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.

1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Форма обратной связи слишком сжата.

**Фактический результат**

Форма обратной связи стандартных параметров, соответствует тз, (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/69161628/89784531-704e5c80-dade-11ea-8a60-b3af0cd608e9.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
