### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by MarinaOsborne** [netology-code/git-homeworks-neuro-issues#1467]
# Описание проблемы @solarrust
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/65596875/89788635-238f7380-db28-11ea-91f0-8bdae807de80.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
