### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Holywindmill** [netology-code/git-homeworks-neuro-issues#147]
@solarrust 

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**
![issue](https://user-images.githubusercontent.com/50572981/64490323-ced6df00-d26c-11e9-8b64-b8b0c3d1215d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
