### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Goglbum** [netology-code/git-homeworks-neuro-issues#1470]
#### Шаги по воспроизведению

1. Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

#### Ожидаемый результат

Форма обратной связи соответствует ТЗ.

#### Фактический результат

Форма обратной связи слишком сжата.

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HcSpYkT.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
