### ISSUE TITLE
Форма обратной связи

### ISSUE THREAD

**Issue by MarinaOsborne** [netology-code/git-homeworks-neuro-issues#1471]
# Описание проблемы
Форма обратной связи слишком узкая @solarrust
#### Шаги по воспроизведению
Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
#### Ожидаемый результат
Форма обратной связи соответствует ТЗ.

#### Фактический результат
Форма обратной связи слишком сжата.

#### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/65596875/89794126-4d986400-db2f-11ea-8bd7-f32f968d6ae5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
