### ISSUE TITLE
Узкая формы обратной связи на мобильном

### ISSUE THREAD

**Issue by npeplov** [netology-code/git-homeworks-neuro-issues#1474]
@Vasya

Исправьте ошибку в коммите 6aa1c0b172e285ee42e9a1045f32548414d75ed4 

#### Описание проблемы
На мобильном форма "Оставайтесь на связи" неудобная

#### Получен результат
Текст с широкими отступами

#### Ожидаемый результат
Текст с обычными отступами

#### Программное обеспечение
Устройство: Motorola (Windows 3.11)
Браузер: Lynx 2.0

#### Скриншот
![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
