### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by ilonadobro** [netology-code/git-homeworks-neuro-issues#1475]
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**Скриншоты**
![image](https://user-images.githubusercontent.com/69249966/89800034-e4b4ea00-db36-11ea-8d81-055a402c923a.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
