### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by ilonadobro** [netology-code/git-homeworks-neuro-issues#1476]
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма обратной связи выглядит в соответствии с макетом дизайнера.

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**Скриншоты**
![image](https://user-images.githubusercontent.com/69249966/89800547-9e13bf80-db37-11ea-9e4b-f3ca94f35667.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
