### ISSUE TITLE
Главная страница. Форма обратной связи слишком узкая

### ISSUE THREAD

**Issue by Holywindmill** [netology-code/git-homeworks-neuro-issues#148]
@solarrust 
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма имеет нормальный вид

**Фактический результат**

Форма сильно сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**
<img width="255" alt="issue" src="https://user-images.githubusercontent.com/50572981/64490505-7bfe2700-d26e-11e9-8c3f-52b42c7572d7.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
