### ISSUE TITLE
Наезд изображения в текстовом блоке

### ISSUE THREAD

**Issue by Dmitry099** [netology-code/git-homeworks-neuro-issues#149]
## Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение 

@solarrust

###  Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

###  Ожидаемый результат
Текст не наезжает на изображение

###  Фактический результат
Текст наезжает на изображение (см. скриншот)

###  Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/54704017/64552296-a0760400-d33f-11e9-9c4d-26e16d36b5a2.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
