### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by lenokst** [netology-code/git-homeworks-neuro-issues#1490]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

#### Ожидаемый результат

Форма обратной связи требуемых размеров

#### Фактический результат

Форма обратной связи слишком сжата

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/48587827/89889791-ed5efc00-dbda-11ea-98cc-116c763f11ef.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
