### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by NikolayT35** [netology-code/git-homeworks-neuro-issues#1491]
#  Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

 1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
 2.  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![1,1](https://user-images.githubusercontent.com/63493184/89892035-bbe82f80-dbde-11ea-808f-5461e3ffdcc3.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
