### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by NikolayT35** [netology-code/git-homeworks-neuro-issues#1492]
# Описание проблемы

**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Форма обратной связи правильного размера

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![2](https://user-images.githubusercontent.com/63493184/89892740-cce57080-dbdf-11ea-82cd-f4a51fbe1f94.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
