### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by ZenkiOo** [netology-code/git-homeworks-neuro-issues#1495]
## Шаги по воспроизведению
1 Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1 Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
## Скриншоты: 
![hw](https://user-images.githubusercontent.com/61312231/89931804-63805480-dc15-11ea-9cf0-2a2d09167cf9.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
