### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ZenkiOo** [netology-code/git-homeworks-neuro-issues#1496]
# Страница "Оставайтесь на связи". Форма обратной связи слишком сжата
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"
### Ожидаемый результат
Форма распределена по ширине экрана

### Фактический результат
Форма слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![hw2](https://user-images.githubusercontent.com/61312231/89932333-27012880-dc16-11ea-8a5a-fcff68cb3413.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
