### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Sportgirl55** [netology-code/git-homeworks-neuro-issues#1497]
@solarrust

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот:
![image](https://user-images.githubusercontent.com/60625271/90001282-ae987700-dcaa-11ea-865d-a7de9ccbcda4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
