### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными..." наезжает на изображение

### ISSUE THREAD

**Issue by pullulus** [netology-code/git-homeworks-neuro-issues#1499]
@solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: OPPO A9 2020 (Android 10)
- Браузер: Chrome (84.0.4147.111)

**Скриншот**
![image](https://user-images.githubusercontent.com/69144345/90018205-3e432300-dcb5-11ea-8c65-0b9dc298d78a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
