### ISSUE TITLE
Проблемы с отображением формы обратной связи

### ISSUE THREAD

**Issue by Dmitry099** [netology-code/git-homeworks-neuro-issues#150]
## Главная страница. Отображение элемента "Форма обратной связи" слишком сжато

@solarrust

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Форма обратной связи"

### Ожидаемый результат
Отображение элемента "Форма обратной связи" не сжато в размере

### Фактический результат
Отображение элемента "Форма обратной связи" слишком сжато (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/54704017/64552864-d9fb3f00-d340-11e9-8543-57c38fc5b741.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
