### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by pullulus** [netology-code/git-homeworks-neuro-issues#1500]
@solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
Ширина формы обратной связи совпадает с шириной экрана телефона

**Фактический результат**
Форма  обратной связи значительно уже ширины экрана телефона (см. скриншот)

**Программное окружение**

Устройство: OPPO A9 2020 (Android 10)
Браузер: Chrome (84.0.4147.111)

**Скриншот**
![image](https://user-images.githubusercontent.com/69144345/90018880-4b144680-dcb6-11ea-8737-670bbed380be.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
