### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by kosiginiv83** [netology-code/git-homeworks-neuro-issues#1501]
@solarrust, добрый день!

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![git_3_2a](https://user-images.githubusercontent.com/26786101/90025582-d73f6180-dce8-11ea-9fab-b319ece36d7a.PNG)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
