### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by kosiginiv83** [netology-code/git-homeworks-neuro-issues#1502]
@solarrust, добрый день!

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
Ширина формы примерно равна ширине экрана

**Фактический результат**
Ширина формы в два раза меньше ширины экрана (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![git_3_2b](https://user-images.githubusercontent.com/26786101/90026935-8e88a800-dcea-11ea-8089-6160dbac018b.PNG)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
