### ISSUE TITLE
Текст наезжает на изображение (Главная страница)

### ISSUE THREAD

**Issue by ElviraSi** [netology-code/git-homeworks-neuro-issues#1503]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Исполнитель
 @solarrust 

### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/50614143/90028337-3ccc2780-dcc2-11ea-87e9-d893640f3ad2.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
