### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ElviraSi** [netology-code/git-homeworks-neuro-issues#1504]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат

- Форма обратной связи выровнена по ширине страницы
- Использован шрифт в соответствии с размером страницы

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Исполнитель
@solarrust

### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/50614143/90028936-ef9c8580-dcc2-11ea-852e-d6348e279d41.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
