### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Olga2088** [netology-code/git-homeworks-neuro-issues#1505]
## Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый** **результат**
Текст не наезжает на изображение

**Фактический** **результат** 
Текст наезжает на изображение (см. скриншот)

**К информации для**
@solarrust

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/69146322/90029180-fda6d200-dcd3-11ea-8004-39a406518ba7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
