### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Olga2088** [netology-code/git-homeworks-neuro-issues#1506]
## Описание проблемы
**Страница формы обратной связи. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть страницу формы обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

**Ожидаемый результат**
Форма обратной связи располагается на всю ширину экрана

**Фактический результат**
Форма обратной связи слишком сжата. (см. скриншот)

**К информации для**
@solarrust

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/69146322/90030142-22e81000-dcd5-11ea-9e77-35bba170bd90.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
