### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by kirmakin** [netology-code/git-homeworks-neuro-issues#1507]
### Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**
1 Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2 Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/69255964/90038384-07c5d200-dcce-11ea-8409-2a9e54a947ad.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
