### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by OlegSedov** [netology-code/git-homeworks-neuro-issues#1508]
**Проблема: на главной странице текст наезжает на изображение**
**Шаги по воспроизведению:**
1. Открыть главную страницу сайте NeuroStartUp в мобильном приложении;
2.  Пролистать страницу вниз до блока "Воспользуйтесь современными возможностями..."

### Expected result:

Текст не наезжает на картинку

### Valid result:

Текст наезжает на картинку (см. скриншот)

**Окружение:** 
Устройство: Xiaomi Redmi 5 
ОС: Android 8.1.0
Браузер: Google Chrome 84.0.4147.111

**Скриншот:**
![Скриншот 1](https://user-images.githubusercontent.com/69350166/90038513-2e840880-dcce-11ea-986c-1692f2896b56.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
