### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by kirmakin** [netology-code/git-homeworks-neuro-issues#1509]
### Описание проблемы
**Форма обратной связи слишком сжата**

**Шаги по воспроизведению**
1 Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2 Пролистать страницу до кнопки "Форма обратной связи"
3 Кликнуть по кнопке, открыть форму

**Ожидаемый результат**
Форма занимает всю поверхность экрана

**Фактический результат**
Форма слишком сжатая, занимает 1/2 часть экрана

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/69255964/90039170-f4ffcd00-dcce-11ea-829a-5c52aac65492.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
