### ISSUE TITLE
Форма обратной связи слишком сжата 

### ISSUE THREAD

**Issue by OlegSedov** [netology-code/git-homeworks-neuro-issues#1510]
**Проблема: форма обратной связи слишком сжата** 

**Шаги по воспроизведению:** 
1. Открыть главную страницу сайта NeuroStartUp в мобильном приложении
2. Пролистать страницу вниз до формы обратной связи

### Expected result:
Форма обратной связи выровнена по ширине экрана

### Valid result:
Форма обратной связи меньше ширины экрана

**Окружение:**
Устройство: Xiaomi Redmi 5
ОС: Android 8.1.0
Браузер: Google Chrome 84.0.4147.111

**Скриншот:**
![Скриншот 2](https://user-images.githubusercontent.com/69350166/90039912-f7165b80-dccf-11ea-8fb6-3fae72d543b8.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
