### ISSUE TITLE
Описание № 1

### ISSUE THREAD

**Issue by Andrey-1966** [netology-code/git-homeworks-neuro-issues#1511]
Описание проблемы № 1
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)

## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
![6angle](https://user-images.githubusercontent.com/64395108/90047216-36e24080-dcda-11ea-9bb4-e7a90de8bcab.png)

# А вот ссылка, как того требует задание: @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
