### ISSUE TITLE
Описание № 2

### ISSUE THREAD

**Issue by Andrey-1966** [netology-code/git-homeworks-neuro-issues#1512]
# Какие бывают пирамиды?
Пирамиды бывают:
1. Шестиугольный
1. Четырехугольный
1. Финансовые
1. египетские

Возьмем к примеру, правильную шестиугольную финансовую пирамиду:

![25](https://user-images.githubusercontent.com/64395108/90048358-14e9bd80-dcdc-11ea-9ead-43b034f924f5.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
