### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by Sleypneer** [netology-code/git-homeworks-neuro-issues#1513]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см.     @@@@скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![image](https://user-images.githubusercontent.com/69307393/90123678-e31e3880-dd67-11ea-8cec-a4c3148827d6.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
