### ISSUE TITLE
Искажение формы обратной связи 

### ISSUE THREAD

**Issue by Sleypneer** [netology-code/git-homeworks-neuro-issues#1514]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат
Форма обратной связи выровнена по ширине страницы
Использован шрифт в соответствии с размером страницы
Фактический результат
Размер формы обратной связи не соответствует используемому шрифту, слишком сжата (скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![image](https://user-images.githubusercontent.com/69307393/90123912-3a240d80-dd68-11ea-84c1-c8b7ea558293.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
