### ISSUE TITLE
Проблема с расположением

### ISSUE THREAD

**Issue by Dreamdrom** [netology-code/git-homeworks-neuro-issues#152]
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Что происходит-

Текст наезжает на изображение (см. скриншот)
Форма обратной связи слишком сжата.

### Программное окружение

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

Скриншоты 

![Screen1](https://camo.githubusercontent.com/d90a6e5e9269c1926cc5e5ea6d624a3a06b53f9a/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)

![Screen2](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
