### ISSUE TITLE
 Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Irina-Kovtun** [netology-code/git-homeworks-neuro-issues#1520]
@solarrust 
# Описание проблемы
## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в  браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)

## Программное окружение
Устройство:  Samsung NP-Q210, Win 7 Prof SP1 32 bit, 
Браузер:  Coogle Chrome Версия 83.0.4103.116 (Официальная сборка), (32 бит) Screen size 1280x800 px, Viewport 1280 × 657 px

## 
![Screen shot NeurostartUp text over the image](https://user-images.githubusercontent.com/69343171/90291267-37b8d500-de88-11ea-923e-788a9965aa7f.jpg)
Скриншоты

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
