### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by dobrognev** [netology-code/git-homeworks-neuro-issues#1523]
@solarrust

# Описание проблемы

**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
Форма обратной связи на всю ширину экрана

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
- Устройство: Lenovo x390
- Браузер: Chrome

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/62283602/90314262-0d642780-df1b-11ea-98b3-78fb632edc31.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
