### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by ELENAMIN-eng** [netology-code/git-homeworks-neuro-issues#1524]
# Описание проблемы

## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат

Текст не наезжает на изображение

## Фактический результат

Текст наезжает на изображение (см. скриншот)

## Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

 @solarrust 
![СКРИНШОТ](https://user-images.githubusercontent.com/67221643/90315384-caf31880-df23-11ea-970c-c64eff572af4.PNG)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
