### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by batyss** [netology-code/git-homeworks-neuro-issues#1525]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/66201730/90315846-4c987580-df27-11ea-942b-e293bc4d4535.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
