### ISSUE TITLE
Текст наезжает на экран

### ISSUE THREAD

**Issue by lebedevweb** [netology-code/git-homeworks-neuro-issues#1527]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

1. Текст наезжает на изображение (см. скриншот)
2. Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/34627120/90317488-95096080-df32-11ea-980b-385cafd86551.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
