### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by lebedevweb** [netology-code/git-homeworks-neuro-issues#1528]
**Форма обратной связи. Из-за ширины деформирован заголовок и текст формы.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Перейти к форме подписки.

**Ожидаемый результат**

Содержимое формы отображается корректно, согласно макета.

**Фактический результат**

Форма слишком сжата, деформирован заголовок и текст.

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/34627120/90317632-87080f80-df33-11ea-9730-06fc0fa56f1c.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
