### ISSUE TITLE
Форма обратной связи слишком сжатa

### ISSUE THREAD

**Issue by ELENAMIN-eng** [netology-code/git-homeworks-neuro-issues#1529]
# Описание проблемы

## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до блока "Оставайтесь на связи"

## Ожидаемый результат

Текстовый блок "Оставайтесь на связи" имеет стандартный формат

## Фактический результат

Текстовый блок "Оставайтесь на связи" слишком сжат (см. скриншот)

## Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)

* Браузер: Chrome (70.0.3538.75)

@solarrust 
![Скриншот-1](https://user-images.githubusercontent.com/67221643/90319303-7fe6fe80-df3f-11ea-839d-d12ecd50a33d.PNG)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
