### ISSUE TITLE
Не совсем корректная работа сайта в мобильном приложении

### ISSUE THREAD

**Issue by Poohing88** [netology-code/git-homeworks-neuro-issues#153]
Добрый день @solarrust. Обнаружил не совсем корректную работу сайта в мобильной версии на устройстве iPhone 8+ (iOS 12.1) в браузере Chrome (70.0.3538.75).  Текст наезжает на картинку и форма обратной связи слишком сжата. Прикладываю скриншоты. @solarrust исправьте пожалуйста недоработки. 
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/54687539/64908733-83a94a00-d70c-11e9-9209-1914654f03e6.png)
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/54687539/64908737-89069480-d70c-11e9-86a4-0ce093cc9cd2.png)

**Comment by solarrust** [comment]
Нужно было создать 2 отдельных issue, по одному на каждую из проблем =)
