### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by MVGIC** [netology-code/git-homeworks-neuro-issues#1534]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями...".

#### Ожидаемый результат

Текст не наезжает на изображение.

#### Фактический результат

Текст наезжает на изображение (см. скриншот).

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![1](https://user-images.githubusercontent.com/69240074/90329781-c38a4880-dfd1-11ea-88d5-9d31d870f2dd.png)

@solarrust

**Comment by MVGIC** [comment]
# Описание проблемы

#### Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
#### Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://prnt.sc/u0d5uo)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
