### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by MVGIC** [netology-code/git-homeworks-neuro-issues#1535]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до формы обратной связи.

#### Ожидаемый результат

Форма имеет обычный размер, как и остальные страницы.

#### Фактический результат

Форма сжата, меньше других страниц.

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![2](https://user-images.githubusercontent.com/69240074/90329908-cc2f4e80-dfd2-11ea-9b5d-0aca679f038b.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
