### ISSUE TITLE
Главная страница текст "Искусственный инетелект..." наезжает на картинку.

### ISSUE THREAD

**Issue by vergsparda** [netology-code/git-homeworks-neuro-issues#1536]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

**Ожидаемый результат**

Текст не наезжает на картинку.

**Фактический результат**

Текст наезжает на картинку (см. скриншот)

**Програмное обеспечение**

- Устройство: Iphone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![](https://camo.githubusercontent.com/e648681205a1dfdf6ed69784e1311b18ca924856/68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
