### ISSUE TITLE
Страница формы обратной связи. Форма слишком сжата.

### ISSUE THREAD

**Issue by vergsparda** [netology-code/git-homeworks-neuro-issues#1537]
**Шаги по воспроизведению**

1. Открыть форму страницу формы обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome.
1. Пролистать страницу до формы ввода обратной связи.

**Ожидаемый результат**

Блок формы обратной связи растянут по ширине окна браузера.

**Фактический результат**

Блок формы обратной связи сильно сжат по отношению окна браузера (см. скриншот)

**Програмное обеспечение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
