### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by OSushentsova** [netology-code/git-homeworks-neuro-issues#1538]
Описание:  На главной странице текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению:
1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust
![Screenshot1](https://user-images.githubusercontent.com/69219421/90332103-d0ec0680-dfc2-11ea-961f-bea938891974.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
