### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by OSushentsova** [netology-code/git-homeworks-neuro-issues#1539]
Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

Ожидаемый результат:
Блок формы обратной связи занимает большую часть страницы по ширине, боковые отступы (margin) составляют 10 % от ширины страницы слева и справа.
Фактический результат: 
Блок формы обратной связи слишком сжат по ширине, занимает 50% ширины страницы, боковые отступы по 25% ширины слева и справа.

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust
![Screenshot2](https://user-images.githubusercontent.com/69219421/90332286-41dfee00-dfc4-11ea-92ca-414db3eaf306.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
