### ISSUE TITLE
Текст наезжает на картинку.

### ISSUE THREAD

**Issue by R1Rs** [netology-code/git-homeworks-neuro-issues#154]
### Шаги по воспроизведению:

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат:
Текст не наезжает на изображение

### Фактический результат:
Текст наезжает на изображение (см. скриншот)

Программное окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

###  Скриншоты:
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/53181361/65274835-ea739c80-db2c-11e9-9ede-7d1f612d968a.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
