### ISSUE TITLE
Тест на главной наезжает на картинку

### ISSUE THREAD

**Issue by motoryginad** [netology-code/git-homeworks-neuro-issues#1540]
@solarrust 
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

Шаги по воспроизведению:
Открыть лендинг в мобильном браузере 
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат:
Текст не наезжает на изображение

Фактический результат:
Текст наезжает на изображение (на скриншоте)

Окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Safari

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/69308164/90333933-91c5b180-dfd2-11ea-8028-c7f6a02ae1f0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
