### ISSUE TITLE
Сжата форма обратной связи 

### ISSUE THREAD

**Issue by motoryginad** [netology-code/git-homeworks-neuro-issues#1541]
@solarrust 
Главная страница. Форма обратной связи в мобильном браузере сжимается

Шаги по воспроизведению:
Открыть лендинг в мобильном браузере
Пролистать страницу до блока обратной связи

Ожидаемый результат:
Блок не сжат и отображается по размеру окна 

Фактический результат:
Блок сжат и не отображается корректно

Окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Safari
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/69308164/90334106-c7b76580-dfd3-11ea-9120-7893551b774b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
