### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Anton1353** [netology-code/git-homeworks-neuro-issues#1542]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/69390415/90341672-82feef00-e012-11ea-87fb-4bc894ee3d77.png)

@solarrust.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
