### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Anton1353** [netology-code/git-homeworks-neuro-issues#1543]
Главная страница. Блок "Оставайтесь на связи" слишком сжат
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат
Блок расположен на весь экран 

Фактический результат
Блок "Оставайтесь на связи" сжат (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/69390415/90341963-4680c280-e015-11ea-868a-97b9f8b09557.png)

@solarrust.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
