### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Freedixae** [netology-code/git-homeworks-neuro-issues#1544]
@solarrust 
Главная страница. Форма обратной связи в мобильном браузере сжимается

Шаги по воспроизведению:
Открыть лендинг в мобильном браузере
Пролистать страницу до блока обратной связи

Ожидаемый результат:
Блок не сжат и отображается по размеру окна

Фактический результат:
Блок сжат и не отображается корректно

Окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Safari
![90334106-c7b76580-dfd3-11ea-9120-7893551b774b](https://user-images.githubusercontent.com/66816905/90364481-42998280-e09f-11ea-98ed-7439e773bf7b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
