### ISSUE TITLE
Текст на главной странице наезжает на картинку

### ISSUE THREAD

**Issue by Freedixae** [netology-code/git-homeworks-neuro-issues#1545]
@solarrust 
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

Шаги по воспроизведению:
Открыть лендинг в мобильном браузере
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат:
Текст не наезжает на изображение

Фактический результат:
Текст наезжает на изображение (на скриншоте)

Окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Safari
![90333933-91c5b180-dfd2-11ea-8028-c7f6a02ae1f0](https://user-images.githubusercontent.com/66816905/90364698-796f9880-e09f-11ea-9b1e-af11500897be.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
