### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by vdumchiviy** [netology-code/git-homeworks-neuro-issues#1546]
https://github.com/netology-code/git-homeworks-neuro-issues/blob/857e3d95477bfbd9c93fb04804a64d0007c1c075/index.html#L43

@solarrust

# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот
![Issue_picture_over_text](https://user-images.githubusercontent.com/63311967/90382804-8a101680-e07f-11ea-9a88-8e82af2bf8e2.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
