### ISSUE TITLE
Главная страница. Текстовый блок "Оставайтесь на связи" отображается узко

### ISSUE THREAD

**Issue by vdumchiviy** [netology-code/git-homeworks-neuro-issues#1547]
https://github.com/netology-code/git-homeworks-neuro-issues/blob/857e3d95477bfbd9c93fb04804a64d0007c1c075/index.html#L53

@solarrust  

# Описание проблемы
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат
Форма занимает всю возможную ширину окна отображения

### Фактический результат
Форма сужена (см. скриншот)

### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот
![Issue_slim_form](https://user-images.githubusercontent.com/63311967/90383830-fb03fe00-e080-11ea-898b-92e9732f80db.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
