### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by R1Rs** [netology-code/git-homeworks-neuro-issues#155]
### Шаги по воспроизведению:
- Открыть главную страницу
- Пролистать до формы обратной связи

### Ожидаемый результат
Форма обратной связи по ширине экрана

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/53181361/65275122-a0d78180-db2d-11e9-80dd-3b812b5771ff.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
