### ISSUE TITLE
Главная страница. Сжата Форма обратной связи.

### ISSUE THREAD

**Issue by Rusdos** [netology-code/git-homeworks-neuro-issues#1551]
@solarrust 
# Описание проблемы
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока обратной связи "Оставайтесь на связи"
#### Ожидаемый результат
Фома обратной связи корректно отображается, отсутствуют ошибочные переносы текста

#### Фактический результат
Форма обратной связи сжата (см. скриншот)

#### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![форма обратной связи](https://i.ibb.co/KDdXQD9/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
