### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by SoleMifabis** [netology-code/git-homeworks-neuro-issues#1553]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать до формы обратной связи

**Ожидаемый результат**
Форма обратной связи не сжата

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/66693903/90390909-a1fa9100-e0a5-11ea-84dc-e27aef331048.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
