### ISSUE TITLE
Текст наложился на картинку

### ISSUE THREAD

**Issue by MFV72** [netology-code/git-homeworks-neuro-issues#1554]
# Описание проблемы
### Шаги по воспроизведению

1. Открыть страницу веб-сайта NeuroStartUp в браузере Chrome на смартфоне
2. Скролим до текста "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст "...воспользуйтесь современными ..... позади!" наезжает на изображение ноутбука (скрин)
![screen-1](https://user-images.githubusercontent.com/68160089/90414019-b00dd900-e0c8-11ea-950f-75fb01d3fcfd.PNG)

### Программное окружение
Устройство: iPhone 6
Браузер: Chrome (Версия 84.0.4147.125)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
