### ISSUE TITLE
Форма ввода на главной странице сильно заужена

### ISSUE THREAD

**Issue by MFV72** [netology-code/git-homeworks-neuro-issues#1555]
# Описание проблемы
### Шаги по воспроизведению

1. Открыть страницу веб-сайта NeuroStartUp в браузере Chrome на смартфоне
2. Скролим к конец страницы до формы "Оставайтесь на связи"
3. Наблюдаем размер формы

### Ожидаемый результат
Форма ввода "Оставайтесь на связи" на мобильном устройстве во всю ширину экрана

### Фактический результат
Форма ввода "Оставайтесь на связи" очень узкая (скрин)

### Программное окружение
Устройство: iPhone 6
Браузер: Chrome (84.0.4147.125)

### Скрин
![screen-2](https://user-images.githubusercontent.com/68160089/90415142-19421c00-e0ca-11ea-9f3a-6848465dbcc3.PNG)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
