### ISSUE TITLE
В тестовом блоке указано не допустимое сокращение.

### ISSUE THREAD

**Issue by DimaVakarchuk** [netology-code/git-homeworks-neuro-issues#1556]
# Описание.

### Указано:  
Даю согласие на обработку перс.данных.

*Шаги воспроизведения:*
* Открыть главную страницу веб-сайта NeuroStartUp в любом мобильном браузере.
* Пролистать страницу до блока "Оставайтесь на связи".

### Фактический результат: ###
Отображается: Даю согласие на обработку перс.данных.

### Ожидаемый результат: ###
Даю согласие на обработку персональных данных.

### Операционная система: ###
Android ( не ниже 5.0)
IOS ( не ниже 12.0)

Исполнитель: 
@solarrust

![Screenshot_2](https://user-images.githubusercontent.com/69165441/90432380-1d266c00-e0d3-11ea-817e-da2292f4a72d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
