### ISSUE TITLE
Мобильная версия сайта отображается не корректно.

### ISSUE THREAD

**Issue by DimaVakarchuk** [netology-code/git-homeworks-neuro-issues#1557]
## Описание: ##
При открытии старички сайта на любом мобильном устройстве, его мобильная версия отображается неверно, масштаб странички относительно экрана не верный.  Вся информация отображается сильно с суженной.

*Шаги воспроизведения:*

Открыть главную страницу веб-сайта NeuroStartUp в любом мобильном браузере. 

### Фактический результат: ###
При просмотре странички, информация и внешний вид странички становится лишком суженными, что в свою очередь привод к неудобству восприятия указанной на страничке информации. Информативный текст указанный на страничке, отображается в виде столбцов, слова разделяются и переносятся на другие строки с ошибками.

### Ожидаемый результат: ###
Страничка отображается верно, с верным масштабом в зависимости от диагонали экрана мобильного устройства и его разрешения. Все читается удобно, информация отображается без ошибок и лишних переносов текста.

### Операционная система: ###
Android ( не ниже 5.0)
IOS ( не ниже 12.0)

### Браузер; ###
Любой

*Исполнитель:*
@solarrust
![Screenshot_3](https://user-images.githubusercontent.com/69165441/90434268-d0906000-e0d5-11ea-8fee-2b4ae91055e8.png)
![Screenshot_4](https://user-images.githubusercontent.com/69165441/90434270-d1c18d00-e0d5-11ea-82d1-952856d75a2a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
