### ISSUE TITLE
Текст наезжает на каринку.

### ISSUE THREAD

**Issue by VitalySalmin** [netology-code/git-homeworks-neuro-issues#156]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![ФормаОбрСвязи](https://user-images.githubusercontent.com/49647152/65377259-7400a700-dcb2-11e9-8c97-d1d1ff59c351.png)

cc/ @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
