### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by dianest** [netology-code/git-homeworks-neuro-issues#1561]
@solarrust Посмотри, пожалуйста

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

#### Ожидаемый результат

Форма обратной связи не сжата по ширине.

#### Фактический результат

Форма обратной связи сжата по ширине (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/19961014/90441740-c6706080-e0d9-11ea-87d8-a74807a07ebc.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
