### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Rentick** [netology-code/git-homeworks-neuro-issues#1563]
@solarrust  Просмотрите проблему.

### Описание проблемы
**Главная страница. Форма обратной связи сжата по ширине.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до формы обратной связи.

**Ожидаемый результат**
Форма обратной связи не сжата по ширине.

**Фактический результат**
Форма обратной связи сжата по ширине (см. скриншот).

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/69197035/90516422-a0e06700-e16c-11ea-9da7-4470d89089d7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
