### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by GubinaIrina** [netology-code/git-homeworks-neuro-issues#1569]
**Описание проблемы**
Главная страница. Форма обратной связи слишком сжата по ширине относительно ширины макета страницы в мобильном браузере.

**Шаги по воспроизведению**
1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
Форма обратной связи по ширине соответствует ширине макета страницы в мобильном браузере

**Фактический результат**
Форма обратной связи слишком сжата относительно ширины макета (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот:**
![скрин ошибки 2](https://user-images.githubusercontent.com/69470310/90773320-63abde80-e2fe-11ea-8476-d3fd6897db5d.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
