### ISSUE TITLE
Форма обратноц связи слишком сжата.

### ISSUE THREAD

**Issue by VitalySalmin** [netology-code/git-homeworks-neuro-issues#157]
# Описание проблемы

#### Шаги по воспроизведению

1. 

Открыть главную страницу
2. Пролистать до формы обратной связи

#### Ожидаемый результат

Форма обратной связи по ширине экрана
#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 7 (iOS 12.3.1)
* Браузер: Safari 12 (12)

#### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/49647152/65377548-26863900-dcb6-11e9-8b89-78b3a093b125.png)

cc/ @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
