### ISSUE TITLE
Необходимо исправить: Текст наезжает на картинку.

### ISSUE THREAD

**Issue by AlexWEBArt** [netology-code/git-homeworks-neuro-issues#1571]
# Описание проблемы
**Текстовый блок "Воспользуйтесь современными возможностями" наезжает на изображение на главной странице.**

**Шаги по воспроизведению**

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот:**
![](https://user-images.githubusercontent.com/69470310/90774341-03b63780-e300-11ea-8605-15f898ade4ac.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
