### ISSUE TITLE
Форма обратной связи слишком сжата!!!

### ISSUE THREAD

**Issue by Dolgoff62** [netology-code/git-homeworks-neuro-issues#1576]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи.."

#### Ожидаемый результат
Блок соответствует ширине страницы

#### Фактический результат

Блок слишком сильно сжат по ширине (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://user-images.githubusercontent.com/69470310/90773320-63abde80-e2fe-11ea-8476-d3fd6897db5d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
