### ISSUE TITLE
Текст наезжает на картинку. 

### ISSUE THREAD

**Issue by Orkhan2020** [netology-code/git-homeworks-neuro-issues#1579]
@solarrust

# Описание проблемы
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями...".
#### Ожидаемый результат
Текст не наезжает на изображение.

#### Фактический результат
Текст наезжает на изображение (см. скриншот).

#### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
#### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/64945143/90970344-f5e5f980-e52d-11ea-93c2-252b9eececa6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
