### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Orkhan2020** [netology-code/git-homeworks-neuro-issues#1580]
# Описание проблемы
@solarrust
#### Ожидаемый результат
Текстовый блок "Оставайтесь на связи" имеет стандартный формат

#### Фактический результат
Текстовый блок "Оставайтесь на связи" слишком сжат (см. скриншот)

#### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
#### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/64945143/90970616-69d5d100-e531-11ea-94c4-8ceffa894021.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
