### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by DmitriyMigorenko** [netology-code/git-homeworks-neuro-issues#1582]
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока обратной связи

#### Ожидаемый результат

Заголовок блока обратной связи отображается корректно

#### Фактический результат

Заголовок блока обратной связи сжат

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![Screenshot (1)](https://user-images.githubusercontent.com/43185404/90983667-7c272d80-e578-11ea-81b7-75d65a71ce08.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
