### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by borissova-e** [netology-code/git-homeworks-neuro-issues#1583]
@solarrust
# Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение #

## Шаги по воспроизведению ##
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат ##
Текст не наезжает на изображение

## Фактический результат ##
Текст наезжает на изображение (см. скриншот)

## Программное окружение ##
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![1](https://user-images.githubusercontent.com/69413245/90986581-b1d61180-e58c-11ea-9ae8-19a1e84ee934.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
