### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by borissova-e** [netology-code/git-homeworks-neuro-issues#1584]
@solarrust
# Главная страница. Форма обратной связи слишком сжата. #

## Шаги по воспроизведению ##
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи. 

## Ожидаемый результат ##
Форма обратной связи стандартной ширины.

## Фактический результат ##
Форма обратной связи слишком сжата.

## Программное окружение ##
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![2](https://user-images.githubusercontent.com/69413245/90986831-72a8c000-e58e-11ea-8d22-5f9c042afa7c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
