### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Anna-Kolycheva** [netology-code/git-homeworks-neuro-issues#1589]
Добрый вечер, @solarrust !

# Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/66947941/91033993-77bd4c00-e62e-11ea-8be4-124fc14fb7db.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
