### ISSUE TITLE
Главная страница. Блок "Оставайтесь на связи" слишком сжат

### ISSUE THREAD

**Issue by kraver90** [netology-code/git-homeworks-neuro-issues#159]
**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат:**
Форма обратной связи отображается корректно, слова не разбиваются

**Фактический результат:**
Форма обратной связи слишком сжата, слова разбиты и переносятся (см. скриншот)
![баг2](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Программное окружение:**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust Проверьте и поправьте пожалуйста

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
