### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Anna-Kolycheva** [netology-code/git-homeworks-neuro-issues#1590]
Добрый вечер, @solarrust !

# Описание проблемы

**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму обратной связи

**Ожидаемый результат**
Форма обратной связи не сжата

**Фактический результат**
Форма обратной связи сжата

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/66947941/91034518-54df6780-e62f-11ea-9d38-b6248c5561c2.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
