### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by logvinov-Mikhail** [netology-code/git-homeworks-neuro-issues#1593]
**Добрый день.@solarrust**

### Текущее состояние 
Не читабельная форма обратной связи (см. [скриншот)](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

### Ожидаемый результат 
Читабельная аккуратная форма с меньшими отступами по бокам.

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60041596/91048239-08425f00-e624-11ea-9bb7-287b687de06c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
