### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by NagaitsevO** [netology-code/git-homeworks-neuro-issues#1595]
@solarrust  
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

### Ожидаемый результат
"Форма обратной связи" не слишком сжата

### Фактический результат
"Форма обратной связи" слишком сжата

### Программное окружение
> Устройство: iPhone 8+ (iOS 12.1)
> Браузер: Chrome (70.0.3538.75)

### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/38664172/91068836-80694e80-e63d-11ea-81bf-aab22d9a5a3a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
