### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by pfokin92** [netology-code/git-homeworks-neuro-issues#1596]
@solarrust 
# Текст наезжает на картинку

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты

![head_screen](https://user-images.githubusercontent.com/49921254/91072282-ee177980-e641-11ea-87c1-553f7f0efcd7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
