### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by pfokin92** [netology-code/git-homeworks-neuro-issues#1597]
@solarrust 
# Форма обратной связи слишком сжата

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму обратной связи

### Ожидаемый результат
Форма обратной связи располагается на весь экран

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
<img width="208" alt="feedback_form" src="https://user-images.githubusercontent.com/49921254/91074794-bad6e980-e645-11ea-83a9-bebf81d47345.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
