### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by CarolineFell** [netology-code/git-homeworks-neuro-issues#160]
Шаги по воспроизведению

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат

    Текст не наезжает на изображение

Фактический результат

    Текст наезжает на изображение (см. скриншот)

Программное окружение

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

Скриншот : 
    [Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение](https://camo.githubusercontent.com/e648681205a1dfdf6ed69784e1311b18ca924856/68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)

Не забудьте "упоминать" того, кому адресовано issue в тексте. Это делается при помощи @ и имени пользователя.
