### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by MariaPlotnikova03** [netology-code/git-homeworks-neuro-issues#1600]
@solarrust
### **Описание проблемы**
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению**

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)
    
![скрин](https://user-images.githubusercontent.com/69808838/91197604-35fed500-e704-11ea-94f5-3b35ead9419f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
