### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by MariaPlotnikova03** [netology-code/git-homeworks-neuro-issues#1601]
@solarrust 

### **Описание проблемы**

**Главная страница. Текстовый блок "Оставайтесь на связи" слишком сжат**

**Шаги по воспроизведению**

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

    Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Текстовый блок "Оставайтесь на связи" имеет стандартный формат

**Фактический результат**

Текстовый блок "Оставайтесь на связи" слишком сжат (см. скриншот)

**Программное окружение**

    Устройство: iPhone 8+ (iOS 12.1)

    Браузер: Chrome (70.0.3538.75)

![скрин2](https://user-images.githubusercontent.com/69808838/91199284-5b8cde00-e706-11ea-96c5-7c2a5f0d1834.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
