### ISSUE TITLE
Текстовый блок наезжает на картинку

### ISSUE THREAD

**Issue by Aisafa** [netology-code/git-homeworks-neuro-issues#1602]
@solarrust
## **Шаги воспроизведения:**
1. Открыть главную страницу NeuroStartUp;
2. Пролистать страницу вниз.

## **Ожидаемый результат:**
Текст и картинка отображаются отдельно, а не друг на друге. 

## **Фактический результат:**
Текст "_Воспользуйтесь современными возможностями искусственного интеллекта оставив конкурентов позади_" наезжает на картинку.

## **Окружение:** 
ОС: Windows 7, 64-bit;
Браузер: Google chrome Версия 84.0.4147.135.

## **Скриншот**

![git-3 2 2](https://user-images.githubusercontent.com/66121547/91288292-7fe5ca80-e799-11ea-8cdc-89b4939a2ec1.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
