### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Aisafa** [netology-code/git-homeworks-neuro-issues#1603]
@solarrust
## **Шаги воспроизведения:**

1. Открыть главную страницу NeuroStartUp;
2. Пролистать страницу до конца.

## **Ожидаемый результат:**
Форма обратной связи отображается корректно.

## **Фактический результат:**
Форма обратной связи слишком сжата

## **Окружение:** 
ОС: Windows 7, 64-bit;
Браузер: Google chrome Версия 84.0.4147.135.

## **Скриншот**

![git-3 2 1](https://user-images.githubusercontent.com/66121547/91289075-7d37a500-e79a-11ea-9e35-c887f5c43ab9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
