### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by Vladi71** [netology-code/git-homeworks-neuro-issues#1604]
@solarrust    

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

- Текст не наезжает на изображение

**Фактический результат**

- Текст наезжает на изображение (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот:**

![1](https://user-images.githubusercontent.com/69647342/91313446-10ce9d00-e7be-11ea-9bcd-35e0a03c198a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
