### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Vladi71** [netology-code/git-homeworks-neuro-issues#1605]
@solarrust 

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
- Исправлена форма обратной связи

**Скриншот:**

![2](https://user-images.githubusercontent.com/69647342/91314793-9c94f900-e7bf-11ea-89f3-b077d97b774e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
