### ISSUE TITLE
Текстовый блок закрывает нижнюю часть изображения

### ISSUE THREAD

**Issue by vovaanik** [netology-code/git-homeworks-neuro-issues#1606]
Пользователь @solarrust

**Шаги по воспроизведению**
Открываем  главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистываем  страницу до блока "Воспользуйтесь современными возможностями..."

_Ожидаемый результат_
Текст не закрывает изображение

_Фактический результат_
Текст закрывает нижнюю часть  изображения (см. скриншот)
![Git3 2 Kart 2020-08-27 105846](https://user-images.githubusercontent.com/69124723/91468596-d1ed2580-e857-11ea-86fc-406cb804eba4.png)

Программное окружение
Устройство: WINDOWS 10.18362.1016
Браузер: Chrome 7

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
