### ISSUE TITLE
Форма обратной связи слишком сжата по горизонтали 

### ISSUE THREAD

**Issue by vovaanik** [netology-code/git-homeworks-neuro-issues#1607]
Пользователь @solarrust

**Шаги по воспроизведению**
Открываем главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистываем страницу до блока "Форма обратной связи."

_Ожидаемый результат_
Форма блока обратной связи пропорциональна размерам страницы

_Фактический результат_
Форма блока обратной связи слишком сжата по горизонтали ( см. скриншот)
![GIT 3-2-2 2020-08-27 112923](https://user-images.githubusercontent.com/69124723/91469794-7de34080-e859-11ea-995a-4a7a6ec78a91.png)

Программное окружение
Устройство: WINDOWS 10.18362.1016
Браузер: Chrome 7

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
