### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by VG90sp** [netology-code/git-homeworks-neuro-issues#1608]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)
![ошибка](https://user-images.githubusercontent.com/62422656/91563375-66828100-e947-11ea-8042-c03cb0766251.jpg)

**Программное окружение**
Устройство: iPhone SE (iOS 13.6.1)
Браузер: Chrome (85.0.4183.72)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
