### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by VG90sp** [netology-code/git-homeworks-neuro-issues#1609]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Оставайтесь на связи."

**Ожидаемый результат**

Текст распределен по ширине страницы и выровнен по центру страницы.

**Фактический результат**

Текст сжат по центру страницы с переносом части слов на другие строки (см.скриншот)
![ошибка](https://user-images.githubusercontent.com/62422656/91564052-a9912400-e948-11ea-9468-10add58e4a01.jpg)

**Программное окружение**
Устройство: iPhone SE (iOS 13.6.1)
Браузер: Chrome (85.0.4183.72)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
