### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by CarolineFell** [netology-code/git-homeworks-neuro-issues#161]
Шаги по воспроизведению

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до формы обратной связи

Ожидаемый результат

    Корректное отображение формы обратной связи 

Фактический результат

    Форма обратной связи сжата до нечитабельного формата

Программное окружение

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

Скриншот : 
    [Главная страница. Форма обратной связи слишком сжата](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)

Не забудьте "упоминать" того, кому адресовано issue в тексте. Это делается при помощи @ и имени пользователя.
