### ISSUE TITLE
Текст закрывает часть изображения (в мобильном браузере)

### ISSUE THREAD

**Issue by kokokokokomi** [netology-code/git-homeworks-neuro-issues#1610]
Информация для @solarrust 

**Главная страница лендинга. Текстовый блок "Воспользуйтесь современными возможностями..." закрывает часть изображения.**

**Шаги по воспроизведению:**

1. Открыть сайт NeuroStartUp в мобильном браузере Chrome.

1. Пролистать страницу до блока "Воспользуйтесь современными возможностями...".

**Ожидаемый результат:**
Текст не "наезжает" на изображение.

**Фактический результат:**
Текст "наезжает" на изображение.
![issue1](https://user-images.githubusercontent.com/70074580/91630874-e3f8d080-e9dd-11ea-8722-47372f697410.png)

**Программное окружение:**

- Устройство Xiaomi Redmi 5 Plus (Android 8.1.0).

- Браузер: Chrome (70.0.3538.75).

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
