### ISSUE TITLE
Форма обратной связи сжата по горизонтали

### ISSUE THREAD

**Issue by kokokokokomi** [netology-code/git-homeworks-neuro-issues#1611]
Информация для @solarrust 

**Главная страница лендинга. Форма обратной связи непропорционально вытянута.**

**Шаги по воспроизведению:**

1. Открыть сайт NeuroStartUp в мобильном браузере Chrome.

1. Пролистать страницу до формы обратной связи.

**Ожидаемый результат:**
Форма блока обратной связи пропорциональна размерам страницы.

**Фактический результат:**
Форма блока обратной связи сжата по горизонтали.
![issue2](https://user-images.githubusercontent.com/70074580/91631117-e78d5700-e9df-11ea-98d2-129336197063.png)

**Программное окружение:**

- Устройство Xiaomi Redmi 5 Plus (Android 8.1.0).

- Браузер: Chrome (70.0.3538.75).

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
