### ISSUE TITLE
Для @solarrust. Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by AnastasiyaSergeichik** [netology-code/git-homeworks-neuro-issues#1613]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
Форма обратной связи на всю ширину экрана

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/70150528/91636481-a0b45700-ea09-11ea-8650-57b89671bbaa.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
