### ISSUE TITLE
Форма обратной связи слишком сильно сжимается

### ISSUE THREAD

**Issue by DaniilOr** [netology-code/git-homeworks-neuro-issues#1615]
Для @solarrust 

 **Шаги по воспроизведению**

- Открываем главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистываем страницу до блока "Форма обратной связи."

_Ожидаемый результат_

- Все отображается корректно

_Фактический результат_
- Форма сильно сжимается (см скриншот)

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
