### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by leramovie** [netology-code/git-homeworks-neuro-issues#1616]
@solarrust

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

![pic](https://user-images.githubusercontent.com/38477356/91645013-2c4dd800-ea4a-11ea-805b-0fd447c2cf1f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
