### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by leramovie** [netology-code/git-homeworks-neuro-issues#1617]
@solarrust

### Главная страница. Форма обратной связи слишком сжата

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи."

**Ожидаемый результат**
Форма обратной связи нормального размера

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

![pic2](https://user-images.githubusercontent.com/38477356/91645084-d594ce00-ea4a-11ea-9c33-11ac27cc58c7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
