### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by ghost** [netology-code/git-homeworks-neuro-issues#1619]
@solarrust

# Описание проблемы

#### Шаги по воспроизведению:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи."

#### Ожидаемый результат:
Форма обратной связи нормального размера

#### Фактический результат:
Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

#### Скриншоты:
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/70139903/91656827-a3c04d80-eac4-11ea-9f3e-b03b82c25497.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
