### ISSUE TITLE
Белый текст наезжает на белое изображение в мобильной версии сайта.

### ISSUE THREAD

**Issue by DenisAzarenko777** [netology-code/git-homeworks-neuro-issues#1622]
Главная страница.
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

Шаги по воспроизведению

1. Открыть главную страницу сайта NeuroStartUp в мобильном браузере Opera Mobile
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение

- Устройство: Samsung s10 (Android 9)
- Браузер: Opera Mobile (12)

Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/51092376/91660195-6f21b580-eb07-11ea-9628-262a60d3fd71.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
