### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by NikolayBabankov** [netology-code/git-homeworks-neuro-issues#1627]
### Форма обратной связи слишком сжата
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи."

**Ожидаемый результат**
Текст распределен по ширине страницы и выровнен по центру страницы

**Фактический результат**
Текст сжат по центру страницы с переносом части слов на другие строки ([см.скриншот](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67))

**Программное окружение:**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
