### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by falkona** [netology-code/git-homeworks-neuro-issues#163]
@solarrust
#### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![image](https://user-images.githubusercontent.com/35679132/66638671-0a731900-ec1e-11e9-8297-2881fbbf2a3f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
