### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Mikhail141** [netology-code/git-homeworks-neuro-issues#1630]
Для пользователя **@solarrust**

###  Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение

-  Устройство:  iPhone 7+ (iOS 12.1)
-  Браузер: Chrome (84.0.4147.135)

 ### Screenshot

![Screenshot](https://user-images.githubusercontent.com/70147484/91684969-a0c76a80-eb61-11ea-85fb-6afc77f657d0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
