### ISSUE TITLE
Форма обратной связи  сжата.

### ISSUE THREAD

**Issue by Mikhail141** [netology-code/git-homeworks-neuro-issues#1631]
Для пользователя **@solarrust**

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2. Пролистать страницу до формы "Оставайтесь на связи"

### Ожидаемый результат
Форма обратной связи стандартного размера 

### Фактический результат
Форма обратной связи для мобильного браузера слишком сжата (см. скриншот)

### Программное окружение

- Устройство:  iPhone 7+ (iOS 12.1)

- Браузер: Chrome (84.0.4147.135)

### Screenshot
![Screenshot1](https://user-images.githubusercontent.com/70147484/91688884-b5a8fb80-eb6b-11ea-9c51-0cea8c18cd87.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
