### ISSUE TITLE
Текстовый блок наезжает на картинку

### ISSUE THREAD

**Issue by IrinaVasilenko88** [netology-code/git-homeworks-neuro-issues#1632]
Для @solarrust 

# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/70235659/91697132-46d29f00-eb79-11ea-9c5a-30d4c1b6601c.png)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
