### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by IrinaVasilenko88** [netology-code/git-homeworks-neuro-issues#1633]
Для @solarrust 

# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока  с формой"Оставайтесь на связи"

### Ожидаемый результат
Форма по центру страницы и занимает всю ширину экрана

### Фактический результат
Форма слишком сжата и занимает узкую полоску по ширине экрана (см. скриншот)
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/70235659/91698307-2c012a00-eb7b-11ea-96cd-ab1e6102ba71.png)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
