### ISSUE TITLE
Текст наезжает на картинку!

### ISSUE THREAD

**Issue by AndreyShitikoff** [netology-code/git-homeworks-neuro-issues#1634]
Для @solarrust.

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1.  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/70209594/91703922-9fa73500-eb83-11ea-84ab-6c3201adca83.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
