### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by AndreyShitikoff** [netology-code/git-homeworks-neuro-issues#1635]
Для @solarrust

**Главная страница. Блок форма обратной связи "Оставайтесь на связи..." не адаптирована под ширину экрана**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока с формой"Оставайтесь на связи"

**Ожидаемый результат**
Форма по центру страницы и занимает всю ширину экрана

**Фактический результат**
Форма слишком сжата и занимает узкую полоску по ширине экрана 

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/70209594/91704875-d6317f80-eb84-11ea-8be9-aaac8731b00d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
