### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by AnastasiyaShark** [netology-code/git-homeworks-neuro-issues#1637]
Для @solarrust

# Описание проблемы

#### Шаги по воспроизведению

Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

#### Ожидаемый результат

Форма обратной связи отображена на полный экран.

#### Фактический результат

Форма обратной связи  сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншот
![image](https://user-images.githubusercontent.com/69208104/91713126-75f10c80-eb89-11ea-9655-2d34031efeb3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
