### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by falkona** [netology-code/git-homeworks-neuro-issues#164]
@solarrust
#### Шаги по воспроизведению

1. Открыть форму обратной связи

#### Ожидаемый результат

Форма адаптируется по ширине экрана

#### Фактический результат
Форма обратной связи слишком сжата.

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![image](https://user-images.githubusercontent.com/35679132/66639377-668a6d00-ec1f-11e9-90f7-f1491dc5065d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
