### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by OllyHard** [netology-code/git-homeworks-neuro-issues#1642]
**Шаги по воспроизведению:**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение

**Фактический результат:**
Текст наезжает на изображение (см. скриншот)

**Программное окружение:**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![b1](https://user-images.githubusercontent.com/70107360/91853964-2f84d600-ec8d-11ea-8905-bb5feefa9783.PNG)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
