### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by OllyHard** [netology-code/git-homeworks-neuro-issues#1643]
**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат:**
Форма обратной связи адаптируется под размер экрана, текст переносится корректно.

**Фактический результат:**
Форма обратной связи слишком сжата

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![b2](https://user-images.githubusercontent.com/70107360/91854363-d5384500-ec8d-11ea-9a9a-988ed87270c3.PNG)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
