### ISSUE TITLE
На главной странице текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by yoursalex** [netology-code/git-homeworks-neuro-issues#165]
## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)

## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

## Скриншоты

![скрин](https://8e02c086-a-62cb3a1a-s-sites.googlegroups.com/site/yoursalexpage/home/music/Git1.png?attachauth=ANoY7coSLewipNVgFGfZ7Qbz_IpaBBZKCKiaSvBL7WJKaowluYooLK-hPp8R-Nryga_vvV_1k6jGDHZ8XJge6PdwMA-sMLD4p2lf1URBMp5DEg2q5mM6gQrwvbvNyP6ZQfwQdDArZYTynBryqX6kyce_21CC48D1EC7EIrzSo5DKA_AZquKhS7Q6tDHgOiOGGGmz0kcvFS2w4FfLMV1AICWfRuvdCIprXiTI4csVDr7JSXmkBDPljZk%3D&attredirects=0)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
