### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AlexAlekseyenok** [netology-code/git-homeworks-neuro-issues#1651]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока обратной связи

#### Ожидаемый результат

Форма распределяется на весь экран

#### Фактический результат

Форм сжата

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/53343534/92034133-7b12af00-ed75-11ea-91b9-8df2cee905bb.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
