### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Rimmkin** [netology-code/git-homeworks-neuro-issues#1655]
@solarrust
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Перейти в форму обратной связи

**Ожидаемый результат**

Форма обратной связи отображается корректно.

**Фактический результат**

Форма слишком сжата

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/70262551/92115930-d38c8f80-edfb-11ea-8e62-5611f0921870.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
