### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by KhazovaLyubov** [netology-code/git-homeworks-neuro-issues#1656]
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение
![Главная страница](https://user-images.githubusercontent.com/70195327/92122571-a4cae500-ee0c-11ea-971c-5024349f0aba.png)

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
