### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by KhazovaLyubov** [netology-code/git-homeworks-neuro-issues#1657]
### Главная страница. Блок форма обратной связи "Оставайтесь на связи..." не адаптирована под ширину экрана

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока с формой"Оставайтесь на связи"

**Ожидаемый результат**
Форма по центру страницы и занимает всю ширину экрана

**Фактический результат**
Форма слишком сжата и занимает узкую полоску по ширине экрана (см. скриншот)
![Главная страница 2](https://user-images.githubusercontent.com/70195327/92124058-5f0f1c00-ee0e-11ea-96a2-2e304c815570.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
