### ISSUE TITLE
Есть проблема текст наезжает на изображение

### ISSUE THREAD

**Issue by OAnton1978** [netology-code/git-homeworks-neuro-issues#1660]
@solarrust
Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение
Фактический результат
Текст наезжает на изображение (см. скриншот)
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/61348987/92151198-0301c300-ee21-11ea-83c6-ff32924bbbae.png)
Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
