### ISSUE TITLE
Ошибка признаков, надо устранить

### ISSUE THREAD

**Issue by OAnton1978** [netology-code/git-homeworks-neuro-issues#1661]
@solarrust
Описание проблемы.
При формировании документа в системе выходит ошибка (см. скриншот)
![Error](https://user-images.githubusercontent.com/61348987/92152022-57597280-ee22-11ea-8748-8796b29c9d87.png)
Необходимо разобраться и исправить.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
