### ISSUE TITLE
Наезжает текст на картинку при просмотре лендинга NeuroStartUp

### ISSUE THREAD

**Issue by Nemeziz1** [netology-code/git-homeworks-neuro-issues#1664]
@solarrust 
# Описание проблемы
### **Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### **Ожидаемый результат**
Текст не наезжает на изображение
### **Фактический результат**
Текст наезжает на изображение (см. скриншот)
### **Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
### **Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/68555942/92267599-8ab30480-eee9-11ea-9b6b-e530a2ef11ef.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
