### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Nemeziz1** [netology-code/git-homeworks-neuro-issues#1665]
@solarrust 
# Описание проблемы
### **Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"
### **Ожидаемый результат**
Форма обратной связи не сжата
### **Фактический результат**
Форма обратной связи сжата (см. скриншот)
### **Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
### **Скриншоты**
![form](https://user-images.githubusercontent.com/68555942/92268279-c26e7c00-eeea-11ea-9cd5-0fc2b2e47b06.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
