### ISSUE TITLE
Текст наезжает на картинку 

### ISSUE THREAD

**Issue by AigulD** [netology-code/git-homeworks-neuro-issues#1666]
@solarrust  
### Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![bug1](https://user-images.githubusercontent.com/70228729/92302523-71ac6100-ef86-11ea-8d2d-19bf3ed5d6f7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
