### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AigulD** [netology-code/git-homeworks-neuro-issues#1667]
@solarrust 
### Описание проблемы
**Главная страница. Форма обратной связи слишком сжата.** 

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма не сжата, текст отображается полностью на всю ширину блока без переноса по словам

**Фактический результат**

Форма сжата, текст перенесен по словам, поля ввода для электронного адреса слишком короткая

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![bug2](https://user-images.githubusercontent.com/70228729/92302750-02377100-ef88-11ea-9b5e-c8c84a2d124d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
