### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by Kasparidi** [netology-code/git-homeworks-neuro-issues#1670]
# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение
### Фактический результат
Текст наезжает на изображение (см. скриншот)
### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Пользователь
@solarrust

### Скриншот
![скриншот](https://user-images.githubusercontent.com/70142291/91962062-b3ce6c00-ed14-11ea-89a3-da2e17dd4f95.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
