### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Stepan164i** [netology-code/git-homeworks-neuro-issues#1679]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Слово написано без переноса

#### Фактический результат

Часть слова перенеслось на следующею строку (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/69162015/92404478-58e5ac00-f13c-11ea-8f64-4e96d654ee67.png)

@solarrust.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
