### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by jazz-max** [netology-code/git-homeworks-neuro-issues#168]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

#### Ожидаемый результат

Форма не сжата (слишком узкая)

#### Фактический результат

Форма сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HcSpYkT.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
