### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by MiraDave** [netology-code/git-homeworks-neuro-issues#1681]
**Форма обратной связи слишком сжата**

**Главная страница. Текстовый блок "Оставайтесь на связи..." слишком сжат**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Слова в форме обратной связи не переносятся

**Фактический результат**
Слова в текстовом блоке переносятся (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/70156837/92413353-0ec6ef80-f169-11ea-9162-2ae4a10a7441.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
