### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Elizaveta-m** [netology-code/git-homeworks-neuro-issues#1688]
## **_Описание проблемы_**
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.
### **_Шаги по воспроизведению_**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### **_Ожидаемый результат_**
Текст не наезжает на изображение

## **_Фактический результат_**

Текст наезжает на изображение (см. скриншот)

### **Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### **_Скриншоты_**
![image](https://user-images.githubusercontent.com/70105068/92592561-7041a800-f2a8-11ea-8eb9-04b828c84d74.png)
 ### Дополнительная информация
@solarrust, обратите, пожалуйста, внимание на данный Issue. Необходима ваша обратная связь в ближайшее время.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
