### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by TestDiana** [netology-code/git-homeworks-neuro-issues#1690]
**Форма обратной связи слишком сжата**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
Текст на всю ширину страницы, не сжат

**Фактический результат**
Текст сжат (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust 
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/70095500/92595362-e942fe80-f2ac-11ea-98b0-912e922dac07.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
