### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Elizaveta-m** [netology-code/git-homeworks-neuro-issues#1691]
## **_Описание проблемы_**
Главная страница. Форма обратной связи недостаточной ширины, текст читается неудобно.
### **_Шаги по воспроизведению_**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
1. Пролистать страницу до блока формы обратной связи.
### **_Ожидаемый результат_**
Форма обратной связи не сжата

## **_Фактический результат_**

Форма обратной связи слишком сжата (см. скриншот)

### **Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### **_Скриншоты_**
![image](https://user-images.githubusercontent.com/70105068/92594340-4dfd5980-f2ab-11ea-8522-d66c6831a158.png)

 ### Дополнительная информация
@solarrust, обратите, пожалуйста, внимание на данный Issue. Необходима ваша обратная связь в ближайшее время.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
