### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Alen-Elzner** [netology-code/git-homeworks-neuro-issues#1692]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![Screenshot_1](https://user-images.githubusercontent.com/69523168/92644574-41e5bc00-f2ec-11ea-8d89-6cea734ad881.jpg)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
