### ISSUE TITLE
Главная страница. Блок "Оставайтесь на связи..." слишком сжата

### ISSUE THREAD

**Issue by Alen-Elzner** [netology-code/git-homeworks-neuro-issues#1693]
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**

- Форма обратной связи не сжата
- шрифт заголовков 14рх
- шрифт основного контента 12px

**Фактический результат**
- Форма обратной связи сжата
- шрифт заголовков 32рх
- шрифт основного контента 16px

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/69523168/92645920-4ad78d00-f2ee-11ea-9acb-b99a636e288a.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
