### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Fox-x-x** [netology-code/git-homeworks-neuro-issues#1694]
### Описание проблемы

Привет, @solarrust ! Я обнаружил следующую проблему.
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты:**
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/20825142/92655792-37c6bc00-f2f2-11ea-99e7-5d5b1e7330a9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
