### ISSUE TITLE
Блок "Оставайтесь на связи..." слишком узкий

### ISSUE THREAD

**Issue by Fox-x-x** [netology-code/git-homeworks-neuro-issues#1695]
### Описание проблемы

Привет, @solarrust! Обнаружил вот такую проблему:

**Главная страница. Блок "Оставайтесь на связи..." слишком сжат по горизонтали, слова переносятся на новые строки как попало.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Слова в форме обратной связи не переносятся, сама форма занимает все пространство экрана слева направо.

**Фактический результат**
Слова в текстовом блоке переносятся (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты:**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/20825142/92656319-1f0ad600-f2f3-11ea-9f19-14cb3c67de4f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
