### ISSUE TITLE
Ошибка верстки текста в мобильной версии сайта

### ISSUE THREAD

**Issue by konqueror7** [netology-code/git-homeworks-neuro-issues#17]
# Описание проблемы
**При просмотре сайта в мобильном устройстве с маленьким экраном текст одного из абзацев наезжает на изображение и сливается с ним**
## Как воспроизвести ошибку
1. Открыть сайт в мобильном устройстве или включить режим _Chrome DevTools_: 
    1. Нажать клавишу F12;
    1. Нажать комбинацию клавиш Ctrl + Shift + M
    1. Выбрать мобильное устройство из выпадающего списка или задать размеры экрана самостоятельно
1. Пролистать пальцем до абзаца "Воспользуйтесь современными возможностями..." 
## Ожидаемое поведение
Текст абзаца  "Воспользуйтесь современными возможностями..." не должен накладываться на изображение
## Полученный результат
Текст и картинка сливаются и мешают друг-другу.
## Программное и аппаратное обеспечение:
- Мобильное устройство: Galaxy S5 (Android 6.0.1"Marsmallow")
- Мобильный браузер: Google Chrome (74.0.3703)

## Скриншот
![](https://raw.githubusercontent.com/konqueror7/magonline/master/screenshot.png)

**Comment by solarrust** [comment]
Great!
