### ISSUE TITLE
На главной странице текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Ingask** [netology-code/git-homeworks-neuro-issues#1700]
**Описание  проблемы**
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
@solarrust
![Снимок](https://user-images.githubusercontent.com/70337443/92963677-86ec2880-f47b-11ea-8d23-5554a4a801f3.PNG)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
