### ISSUE TITLE
На главной странице форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Ingask** [netology-code/git-homeworks-neuro-issues#1701]
**Описание проблемы**
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Блок "Оставайтесь на связи" распределен по всей ширине страницы

**Фактический результат**
Блок "Оставайтесь на связи" по ширине уменьшен в размере (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
@solarrust 
![Снимок2](https://user-images.githubusercontent.com/70337443/92964836-750b8500-f47d-11ea-9b00-a0182c966c00.PNG)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
