### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Natalya-Ryabaya** [netology-code/git-homeworks-neuro-issues#1704]
> 
### **Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### **Ожидаемый результат**
Текст не наезжает на изображение
### **Фактический результат**
Текст наезжает на изображение (см. скриншот)
### **Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
![image](https://user-images.githubusercontent.com/70447882/93003577-94bbaf80-f548-11ea-85e3-1436c5d9acb0.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
