### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Natalya-Ryabaya** [netology-code/git-homeworks-neuro-issues#1705]
> 
### **Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу вниз  до блока "Оставайтесь на связи"
### **Ожидаемый результат**
Форма обратной связи на всю ширину экрана
### **Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)
### **Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
![image](https://user-images.githubusercontent.com/70447882/93003825-a00fda80-f54a-11ea-8e7e-e20ba8cebc86.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
