### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by fulcrum888** [netology-code/git-homeworks-neuro-issues#1708]
# Описание проблемы
@solarrust
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![image](https://user-images.githubusercontent.com/70887852/93025011-8387a700-f60b-11ea-8d7c-fbf4997b42a1.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
