### ISSUE TITLE
 Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by fulcrum888** [netology-code/git-homeworks-neuro-issues#1709]
# Описание проблемы
@solarrust
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат
Форма обратной связи отображается по всей ширине экрана

#### Фактический результат

Форма обратной связи сжата, справа и слева много пустого пространства

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![image](https://user-images.githubusercontent.com/70887852/93025066-0ad51a80-f60c-11ea-84dc-9154812fa292.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
