### ISSUE TITLE
Проблема: на главной странице веб-сайта NeuroStartUp текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by Murrk** [netology-code/git-homeworks-neuro-issues#171]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://content.screencast.com/users/Murrk/folders/Jing/media/1e5c21db-d8ac-4761-a135-1bb5e51d3227/2019-10-15_1841.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
