### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by IldarGabi** [netology-code/git-homeworks-neuro-issues#1712]
@solarrust

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome;
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями...".

Ожидаемый результат
Текст не наезжает на изображение.

Фактический результат
Текст наезжает на изображение (см. скриншот).

Программное окружение
Браузер: Chrome (Версия 85.0.4183.102)

Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/70235696/93027726-a28c3600-f617-11ea-9163-6ddd85589066.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
