### ISSUE TITLE
Форма обратной связи слишком сжата по центру страницы

### ISSUE THREAD

**Issue by IldarGabi** [netology-code/git-homeworks-neuro-issues#1713]
@solarrust

Описание проблемы
Главная страница. Форма обратной связи слишком сжата

Шаги по воспроизведению:
1. Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome;
2. Пролистать страницу до блока "Оставайтесь на связи.".

Ожидаемый результат
Текст распределен по ширине страницы и выровнен по центру страницы

Фактический результат
Текст сжат по центру страницы с переносом части слов на другие строки (см.скриншот)

Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/70235696/93028018-a7ea8000-f619-11ea-9ba2-0ceaa36cfdad.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
