### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by DamnFilthy** [netology-code/git-homeworks-neuro-issues#1719]
@solarrust
# Описание проблемы
**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению:**

- Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome;
- Пролистать страницу до блока "Оставайтесь на связи.".

**Ожидаемый результат**

Текст распределен по ширине страницы и выровнен по центру страницы

**Фактический результат**

Текст сжат по центру страницы с переносом части слов на другие строки (см.скриншот)

Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/39647394/93326019-e2723980-f820-11ea-8a38-e1a7eab435f8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
