### ISSUE TITLE
Проблема: форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Murrk** [netology-code/git-homeworks-neuro-issues#172]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

#### Ожидаемый результат

Форма обратной связи не сжата

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://content.screencast.com/users/Murrk/folders/Jing/media/b870a64f-003b-4bc3-96d2-08b8743185f0/2019-10-15_1850.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
