### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Yuribtr** [netology-code/git-homeworks-neuro-issues#1723]
Вниманию @solarrust

**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма обратной связи отображается по всей ширине экрана

**Фактический результат**
Форма обратной связи сжата, справа и слева много пустого пространства (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/20052813/93389203-7de0ca00-f874-11ea-8470-925b58c6db00.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
