### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Kernitskaya** [netology-code/git-homeworks-neuro-issues#1726]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты:**

![2 задание](https://user-images.githubusercontent.com/36434625/93495608-f7c98f80-f916-11ea-9aed-fc6fff3bb715.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
