### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Kernitskaya** [netology-code/git-homeworks-neuro-issues#1727]
**Шаги по воспроизведению:**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Открыть форму обратной связи

**Ожидаемый результат**
Форма обратной связи соответствуют формату экрана

**Фактический результат**
Форма обратной связи сжата

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты:**
![задание 2 2](https://user-images.githubusercontent.com/36434625/93496276-aec60b00-f917-11ea-8232-5886fd890b8e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
