### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by NikoDol** [netology-code/git-homeworks-neuro-issues#1733]
@solarrust

**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат**

Форма обратной связи отображается корректно

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты:**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/69104440/93585029-9dd0d480-f9bf-11ea-80da-431e39d4d9d3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
