### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Alex0322** [netology-code/git-homeworks-neuro-issues#1735]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму обратной связи

#### Ожидаемый результат

Пропорциональная форма

#### Фактический результат

Сжатая форма (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://user-images.githubusercontent.com/28208110/93589499-8d1b6100-f9b5-11ea-81f7-af8109380af3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
