### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by nikiforovamaria** [netology-code/git-homeworks-neuro-issues#1741]
### Описание проблемы
**Форма обратной связи "Оставайтесь на связи..." слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Форма занимает всю ширину окна и корректно отображается

**Фактический результат**
Форма очень узкая и некорректно отображается (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![2](https://user-images.githubusercontent.com/67773375/93624935-f2497380-fa02-11ea-9f66-52e22b0005ce.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
