### ISSUE TITLE
Форма обратной связи слишком сжата 

### ISSUE THREAD

**Issue by vnvm5k** [netology-code/git-homeworks-neuro-issues#1745]
@solarrust

# Описание проблемы
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

#### Ожидаемый результат

Форма занимает всю ширину окна и корректно отображается

####  Фактический результат

Форма очень узкая и некорректно отображается (см. скриншот)

####  Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

####  Скриншоты

![93624935-f2497380-fa02-11ea-9f66-52e22b0005ce](https://user-images.githubusercontent.com/68341879/93668284-1739f700-fa94-11ea-8aa0-098c5e498cb5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
