### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by GromakMaxim** [netology-code/git-homeworks-neuro-issues#1748]
# Описание проблемы

#### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/71246005/93706041-d8747180-fb65-11ea-8fe9-523ad6fd1b9b.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
