### ISSUE TITLE
Форма слишком сжата

### ISSUE THREAD

**Issue by GromakMaxim** [netology-code/git-homeworks-neuro-issues#1749]
## Форма обратной связи "Оставайтесь на связи..." слишком сжата

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Форма занимает всю ширину окна и корректно отображается

**Фактический результат**
Форма очень узкая и некорректно отображается (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/71246005/93706213-5e44ec80-fb67-11ea-9530-80c357896153.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
