### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by polusya** [netology-code/git-homeworks-neuro-issues#1751]
**Описание проблемы**
Форма обратной связи "Оставайтесь на связи." слишком сжата.

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

- Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Форма занимает всю ширину окна и корректно отображается

**Фактический результат**
Форма очень узкая и некорректно отображается (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/71550493/93711665-b7f1ea80-fb58-11ea-988a-b49a0cabe737.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
