### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by AlexeySharaburin** [netology-code/git-homeworks-neuro-issues#1756]
Уважаемый @solarrust,

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

<img width="367" alt="Text picture" src="https://user-images.githubusercontent.com/71267483/93713919-4ff2d280-fb5f-11ea-84cd-f60d2f4b552b.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
