### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AlexeySharaburin** [netology-code/git-homeworks-neuro-issues#1757]
Уважаемый @solarrust,

**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи 

**Ожидаемый результат**

Форма обратной связи не сжата, все слова хорошо читаются

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

<img width="227" alt="Text" src="https://user-images.githubusercontent.com/71267483/93714127-f4c1df80-fb60-11ea-9712-44d9f6da3f58.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
