### ISSUE TITLE
На главной странице текст наезжает на изображение

### ISSUE THREAD

**Issue by ANNA-23021975** [netology-code/git-homeworks-neuro-issues#1763]
# Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока :

> "Воспользуйтесь современными возможностями..."

## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)

## Программное окружение

- Ноутбук Aser (Windows 10,0)
* Браузер: Chrome

## Скриншоты
Специально для @solarrust 

![image](https://user-images.githubusercontent.com/69602013/93718921-e9ce7580-fb87-11ea-9011-6e84badb869e.png)
](url)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
