### ISSUE TITLE
Слишком сжатая форма обратной связи

### ISSUE THREAD

**Issue by ANNA-23021975** [netology-code/git-homeworks-neuro-issues#1765]
# Форма обратной связи смотрится не эстетично.
## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до конца.
1. прочитать форму обратной связи
 
## Ожидаемый результат
Текст удобный для чтения

## Фактический результат

* Текст слишком сжатый
* Ограничен рамками
* Не удобно читаемый перенос ( смотрите скриншот )

## Скриншот
@solarrust 
[
![image](https://user-images.githubusercontent.com/69602013/93719910-53518280-fb8e-11ea-8e3c-741e9863259a.png)
](url)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
