### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Inko21** [netology-code/git-homeworks-neuro-issues#177]
# Описание:
@solarrust прошу обратить внимание, при просмотре сайта через мобильное устройство на главной странице текст наезжает на картинку.

## Окружение:

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

## Скрин: 

![Обзор](https://camo.githubusercontent.com/d90a6e5e9269c1926cc5e5ea6d624a3a06b53f9a/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
