### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AlexanderAndreevGIT** [netology-code/git-homeworks-neuro-issues#1774]
Уважаемый **@solarrust**,

**Главная страница. Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**

Текст корректно умещен в строки без лишних переносов

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/67903829/93753188-6d2fab80-fc08-11ea-890e-8f0aef2f88d9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
