### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by SvetlanaLyubimskaya** [netology-code/git-homeworks-neuro-issues#1778]
Вниманию @solarrist

# Описание проблемы

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат

Форма обратной связи по ширине устройства

### Фактический результат

Форма сжата (см. скриншот)

### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты
![оставайтесь на связи](https://user-images.githubusercontent.com/68334362/93765149-12ed1580-fc1d-11ea-8965-40477a4abcf0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
