### ISSUE TITLE
Главная страница. Кнопка разворачивания меню остается подсвеченной после скрытия меню

### ISSUE THREAD

**Issue by pfzw90** [netology-code/git-homeworks-neuro-issues#1779]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Развернуть верхнее меню
3. Свернуть верхнее меню

#### Ожидаемый результат

Иконка меню перестает быть подсвеченной

#### Фактический результат

Иконка меню обведена оранжевым

#### Программное окружение

* Устройство: iPhone 4 
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://puu.sh/GuWp9/49bc518dc0.png)

@solarrust, ЭТО ПРОСТО УЖАСНО!

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
