### ISSUE TITLE
Ошибки в тексте формы обратной связи

### ISSUE THREAD

**Issue by pfzw90** [netology-code/git-homeworks-neuro-issues#1780]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в любом браузере
2. Пролистать до формы обратной связи, прочитать текст

#### Ожидаемый результат

Все написано грамотно

#### Фактический результат

1. Слова "Ваши" и "Вами" написаны с маленькой буквы;
2. Сокращение слова "персональные" до "перс."

#### Программное окружение

* Устройство: любое
* Браузер: любой

#### Скриншоты

![](https://puu.sh/GuWvl/d6d60cc587.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
