### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Zuevgeniy** [netology-code/git-homeworks-neuro-issues#1784]
### Шаги по воспроизведению

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Оставайтесь на связи..."
- Увеличить масштаб (zoom) страницы.

### Ожидаемый результат
Ширина формы достаточна для корректного переноса текста.

### Фактический результат
Форма слишком узка для корректного переноса текста, по бокам много пустого места (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

[Скриншот](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
