### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by evgenkataev** [netology-code/git-homeworks-neuro-issues#1787]
Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению:

-Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
-Пролистать страницу до блока "Воспользуйтесь современными возможностями..." 

Ожидаемый результат:
Текст не наезжает на изображение

Фактический результат:
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: Персональный компьютер 
ОС: Windows 10
Браузер: Chrome Версия 85.0.4183.102
Скриншот:
![image](https://user-images.githubusercontent.com/70521900/93919811-aa3e8f80-fd27-11ea-8e46-a4c4a9e74697.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
