### ISSUE TITLE
Текст находится не по центру

### ISSUE THREAD

**Issue by evgenkataev** [netology-code/git-homeworks-neuro-issues#1788]
Описание проблемы
Всплывающее окно. Текстовый блок  находится не по центру.
Шаги по воспроизведению:

-Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
-Нажать на кнопку добавить контакты

Ожидаемый результат:
В всплывающем окне текст находится строго по центру окна,

Фактический результат:
В всплывающем окне текст не  находится строго по центру окна, (см. скриншот)

Программное окружение
Устройство: Персональный компьютер
ОС: Windows 10
Браузер: Chrome Версия 85.0.4183.102
Скриншот:
![image](https://user-images.githubusercontent.com/70521900/93920673-efaf8c80-fd28-11ea-9b6b-a1ef183b1305.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
