### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Pfliger** [netology-code/git-homeworks-neuro-issues#1789]
@solarrust

#  Описание проблемы

**Главная страница. Текстовый блок "_Воспользуйтесь современными возможностями..._" наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![11](https://user-images.githubusercontent.com/71281161/93922376-7c9f1980-fd1a-11ea-978f-93bffd2853af.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
