### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by smetanova-ys** [netology-code/git-homeworks-neuro-issues#179]
@solarrust 
## Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.**
## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
## Ожидаемый результат
Текст не наезжает на изображение
## Фактический результат
Текст наезжает на изображение (см. скриншот)
## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
## Скриншот
![obrázok](https://user-images.githubusercontent.com/54677409/67080181-f20e7b80-f194-11e9-8cf2-2a33824a46fd.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
