### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by Pfliger** [netology-code/git-homeworks-neuro-issues#1790]
@solarrust

# Описание проблемы
**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат:**
Форма обратной связи отображается по всей ширине экрана

**Фактический результат:**
Форма обратной связи сжата, справа и слева много пустого пространства (см. скриншот)

**Программное окружение:**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![2](https://user-images.githubusercontent.com/71281161/93922740-05b65080-fd1b-11ea-8ddf-108cbe52c607.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
