### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by SShanshina** [netology-code/git-homeworks-neuro-issues#1793]
# Описание проблемы
@solarrust
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
#### Скриншоты
![image](https://user-images.githubusercontent.com/71622719/94038065-3caa6600-fdf0-11ea-95c2-7c1df61df554.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
