### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by SShanshina** [netology-code/git-homeworks-neuro-issues#1794]
# Описание проблемы
@solarrust
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"
#### Ожидаемый результат
Расширение формы обратной связи
#### Фактический результат
Форма обратной связи сжата (см. скриншот)
#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
#### Скриншоты
![image](https://user-images.githubusercontent.com/71622719/94039080-7465dd80-fdf1-11ea-9264-80a403d3cc15.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
