### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by FedorGarbuzov** [netology-code/git-homeworks-neuro-issues#1796]
@solarrust

**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Размер формы обратной связи достаточен для комфортного чтения текста

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/71636417/94063165-61064280-fdf0-11ea-9dd3-a33d1309a327.png)
**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
