### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by wwowann** [netology-code/git-homeworks-neuro-issues#1798]
# Описание проблемы
## Скриншот
![image](https://user-images.githubusercontent.com/71412393/94071059-f3f8aa00-fdfb-11ea-827e-45b2ba9cb65f.png)
@solarrust, 857e3d95477bfbd9c93fb04804a64d0007c1c075

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
