### ISSUE TITLE
Ошибка верстки формы подписки в мобильной версии сайта

### ISSUE THREAD

**Issue by konqueror7** [netology-code/git-homeworks-neuro-issues#18]
# Описание проблемы
**При просмотре сайта в мобильном устройстве с маленьким экраном форма подписки слишком узкие для ввода и просмотра данных**
## Как воспроизвести ошибку
1. Открыть сайт в мобильном устройстве или включить режим _Chrome DevTools_: 
    1. Нажать клавишу F12;
    1. Нажать комбинацию клавиш Ctrl + Shift + M
    1. Выбрать мобильное устройство из выпадающего списка или задать размеры экрана самостоятельно
2. Пролистать пальцем до формы "Оставайтесь на связи"
## Ожидаемое поведение
Форма ввода контактных данных "Оставайтесь на связи" должна занимать всю ширину экрана мобильного устройства и иметь размеры полей достаточные для ввода и проверки контактных данных.
## Полученный результат
Форма имеет большие отступы от краев экрана и занимает не более 40% его ширины.
## Программное и аппаратное обеспечение:
- Мобильное устройство: Galaxy S5 (Android 6.0.1"Marsmallow")
- Мобильный браузер: Google Chrome (74.0.3703)

## Скриншот
![](https://raw.githubusercontent.com/konqueror7/magonline/master/screenshot2.png)

**Comment by solarrust** [comment]
Great!
