### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by smetanova-ys** [netology-code/git-homeworks-neuro-issues#180]
@solarrust 
## Описание проблемы
**Форма обратной связи слишком сжата.**
## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."
## Ожидаемый результат
Верстка формы должна быть адаптирована под размер экрана.
## Фактический результат
Форма слишком сжата (см. скриншот).
## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
## Скриншот
![obrázok](https://user-images.githubusercontent.com/54677409/67081109-d86e3380-f196-11e9-96eb-b179be2130be.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
