### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Ekaterina199422** [netology-code/git-homeworks-neuro-issues#1804]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Ширина формы обратной связи соответствует ширине экрана устройства и расположенному в форме тексту

#### Фактический результат

Форма обратной связи слишком сжата(см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://user-images.githubusercontent.com/68334362/93765149-12ed1580-fc1d-11ea-8965-40477a4abcf0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
