### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by EvgenyMyznikov** [netology-code/git-homeworks-neuro-issues#1806]
Вниманию @solarrust

# Описание проблемы
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат
Форма обратной связи отображается по всей ширине экрана

#### Фактический результат
Форма обратной связи сжата, справа и слева много пустого пространства (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![image](https://user-images.githubusercontent.com/70178914/94149615-cc97f080-fe80-11ea-9aa5-3b0fc8faaf60.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
