### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by mizafront** [netology-code/git-homeworks-neuro-issues#1809]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![94147104-8725f400-fe7d-11ea-844f-a9d81d04ea65](https://user-images.githubusercontent.com/48541690/94165019-30331580-fea3-11ea-9330-dd6bae370cf9.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
