### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by mizafront** [netology-code/git-homeworks-neuro-issues#1810]
**Главная страница. Форма обратной связи слишком сжата**
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма обратной связи отображается по всей ширине экрана

**Фактический результат**
Форма обратной связи сжата, справа и слева много пустого пространства (см. скриншот)

**Программное окружение**

1. Устройство: iPhone 8+ (iOS 12.1)
2. Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![94149615-cc97f080-fe80-11ea-9aa5-3b0fc8faaf60](https://user-images.githubusercontent.com/48541690/94165449-a9326d00-fea3-11ea-978d-3bc97ed2a54c.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
