### ISSUE TITLE
Текстовый блок наезжает на изображение.

### ISSUE THREAD

**Issue by inessashuvalova** [netology-code/git-homeworks-neuro-issues#1811]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![3 2](https://user-images.githubusercontent.com/57993847/94165505-f78b4000-fe92-11ea-8ee6-c2291ce67892.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
