### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by inessashuvalova** [netology-code/git-homeworks-neuro-issues#1812]
**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма обратной связи отображается по всей ширине экрана

**Фактический результат**

Форма обратной связи сжата, справа и слева много пустого пространства (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![3 2 2](https://user-images.githubusercontent.com/57993847/94166854-8056ab80-fe94-11ea-9ef4-57d0e78bda58.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
