### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Suspend85** [netology-code/git-homeworks-neuro-issues#1820]
@solarrust

**Главная страница. Блок "Оставайтесь на связи" слишком узкий.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Блок соответствует размерам экрана мобильного телефона.

**Фактический результат**

Блок сжат относительно размера экрана мобильноо телефона (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/55913287/94275377-152ed700-ff71-11ea-9ebf-c1e1e13db604.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
