### ISSUE TITLE
обратная связь сжата

### ISSUE THREAD

**Issue by ghost** [netology-code/git-homeworks-neuro-issues#1821]
@solarrust 
Главная страница. Блок "Оставайтесь на связи" слишком узкий.

Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат

Блок соответствует размерам экрана мобильного телефона.

Фактический результат

Блок сжат относительно размера экрана мобильноо телефона (см. скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/71279304/94276426-e6086d80-ff50-11ea-9f29-1d382545213e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
