### ISSUE TITLE
текст наезжает на картинку

### ISSUE THREAD

**Issue by ghost** [netology-code/git-homeworks-neuro-issues#1822]
@solarrust 
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат

Текст не наезжает на изображение

Фактический результат

Текст наезжает на изображение (см. скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/71279304/94276833-6dee7780-ff51-11ea-9769-64cc20f65146.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
