### ISSUE TITLE
Текстовый блок наслаивается на изображение

### ISSUE THREAD

**Issue by JKorneva** [netology-code/git-homeworks-neuro-issues#1823]
### Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
результат текущего отображения на скриншоте

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![Скриншот 25-09-2020 184411](https://user-images.githubusercontent.com/70487182/94293817-2d95f600-ff5f-11ea-9cf4-c0012f0cd701.jpg)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
