### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by JKorneva** [netology-code/git-homeworks-neuro-issues#1824]
### **Описание проблемы**
Форма обратной связи слишком сжата

### **Шаги воспроизведения**
Зайти в мобильное приложение 
Перейти на страницу формы обратной связи

Текущий результат виден на скриншоте.
Ожидаемый результат-корректное отображение верстки

### **Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![Скриншот 25-09-2020 185431](https://user-images.githubusercontent.com/70487182/94294768-9a5dc000-ff60-11ea-8b61-45504b455c1f.jpg)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
