### ISSUE TITLE
Проблема - слишком сжатый блок

### ISSUE THREAD

**Issue by cartiss** [netology-code/git-homeworks-neuro-issues#1828]
### Описание проблемы
**Главная страница. Форма обратной связи слишком сжатая.**

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до формы обратной связи.

**Ожидаемый результат**
Форма не сжатая (адаптирована под моб. версию)

**Фактический результат**
Форма сжатая (см. скриншот)

**Программное окружение**
Устройство: iPhone 11 Pro (iOS 14)
Браузер: Microsoft Edge

@solarrust 

![](https://user-images.githubusercontent.com/63413016/80282954-08d1f400-871d-11ea-8391-6f1b45d9b668.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
