### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by yarchike** [netology-code/git-homeworks-neuro-issues#183]
@solarrust

**Описание проблемы**
Форма обратной связи слишком сжата.

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Верстка формы должна быть адаптирована под размер экрана.

**Фактический результат**
Форма слишком сжата (см. скриншот).

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**Скриншот**
![12312](https://user-images.githubusercontent.com/56361599/67147604-e5764a00-f29e-11e9-8786-1e656abbc223.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
