### ISSUE TITLE
Проблема - форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AR2003** [netology-code/git-homeworks-neuro-issues#1830]
@solarrust

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть форму обратной связи в любом мобильном браузере 

#### Ожидаемый результат

Размер формы соответствует возможностям экрана и позволяет комфортно вводить данные.

#### Фактический результат

Ширина формы меньше размеров экрана 
#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HcSpYkT.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
