### ISSUE TITLE
Исправить. Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by RomanenkoSasha** [netology-code/git-homeworks-neuro-issues#1831]
**Выполнить**
_@solarrust_

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrom.
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/59048554/94350801-ba71aa00-005a-11eb-8ba3-24e72225e63a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
