### ISSUE TITLE
Исправить.Форма обратной связи. Сжат блок. увеличить ширину блока.

### ISSUE THREAD

**Issue by RomanenkoSasha** [netology-code/git-homeworks-neuro-issues#1832]
**Исполнитель**

_@solarrust_

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrom.
2. Пролистать страницу до блока "Форма обратной связи..."

**Ожидаемый результат**

- Блок занимает всю ширину экрана

**Фактический результат**
Узкий блок, располагается по центру. Сжатый текст (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/59048554/94351130-53ee8b00-005e-11eb-896f-bd9596fc1471.png)
**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
