### ISSUE TITLE
Исправить. Файл adv-speed.svg

### ISSUE THREAD

**Issue by Zats1954** [netology-code/git-homeworks-neuro-issues#1835]
@solarrust 
Предлагаю исправить файл adv-speed.svg. Уменьшить opacity фона до 0.4, чтобы ярче была картинка.
строка 8 
`    <rect width="330" height="269" fill="##357AFF" fill-opacity="0.4"/>`

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
