### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение #1837

### ISSUE THREAD

**Issue by netwar1994** [netology-code/git-homeworks-neuro-issues#1837]
**Шаги по воспроизведению**

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

- Текст не наезжает на изображение

**Фактический результат**

- Текст наезжает на изображение (см. скриншот)

**Программное окружение**

-  Устройство: iPhone 8+ (iOS 12.1)
-  Браузер: Chrome (70.0.3538.75)

**Скриншот**

![neuro1](https://user-images.githubusercontent.com/71972081/94570716-f1c99c00-0290-11eb-96b0-eb6f71394856.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
