### ISSUE TITLE
Форма обратной связи сжат #1838

### ISSUE THREAD

**Issue by netwar1994** [netology-code/git-homeworks-neuro-issues#1838]
**Шаги по воспроизведению**

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.  Пролистать страницу до блока "Форма обратной связи..."

**Ожидаемый результат**

- Блок занимает всю ширину экрана

**Фактический результат**

- Блок располагается по центру, узкий блок

 (см. скриншот)

**Программное окружение**

-  Устройство: iPhone 8+ (iOS 12.1)
-  Браузер: Chrome (70.0.3538.75)

**Скриншот**

![neuro2](https://user-images.githubusercontent.com/71972081/94571585-f8a4de80-0291-11eb-854f-74f6900487da.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
