### ISSUE TITLE
Описание проблемы

### ISSUE THREAD

**Issue by naslowski1** [netology-code/git-homeworks-neuro-issues#184]
# Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение
### Фактический результат
Текст наезжает на изображение (см. скриншот)
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/52377394/67158846-1493c680-f346-11e9-925c-02f535b0e598.png)
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/52377394/67158870-6d635f00-f346-11e9-891a-0f8171fa32a1.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
