### ISSUE TITLE
Главная страница. Блок "Оставайтесь на связи" слишком сжат

### ISSUE THREAD

**Issue by kirgurkir** [netology-code/git-homeworks-neuro-issues#1848]
# Описание проблемы @solarrust 

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма занимает всё предоставленное ей пространство из исключением отступов

#### Фактический результат

Форма слишком сжата

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
