### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by marosi13** [netology-code/git-homeworks-neuro-issues#1851]
### Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

@solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу сайта NeuroStartUp в мобильном браузере
2. Пролистать до текста "Воспользуйтесь современными возможностями.."

**Ожидаемый результат**
Текст не наезжает на картинку

**Фактический результат**
Текст наезжает на картинку (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
 
![pic 1](https://user-images.githubusercontent.com/67289775/94787625-36614e80-03db-11eb-9f2f-001727fa4a2b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
