### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by marosi13** [netology-code/git-homeworks-neuro-issues#1853]
### Описание проблемы

@solarrust

**При просмотре в мобильном браузере форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть сайт NeuroStartUp в мобильном браузере Chrome
2. Пролистать до формы обратной связи

**Ожидаемый результат**

- Форма обратной связи не сжата
- Слово "Оставайтесь" отображается без переноса
- "Email" или "Телефон" отображаются на одной строке
- "Персональных данных" - без сокращения

**Фактический результат**  (см скриншот)

- Форма обратной связи слишком сжата
- Слово "Оставайтесь" отображается с переносом
- "Email" или "Телефон" отображаются на разных строках
- "Перс. данных"

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![pic 2](https://user-images.githubusercontent.com/67289775/94790377-db315b00-03de-11eb-9de2-f58985b3a89c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
