### ISSUE TITLE
Описание проблемы

### ISSUE THREAD

**Issue by volkovakaterin** [netology-code/git-homeworks-neuro-issues#1856]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

  1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
  2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

Скриншоты

![image](https://user-images.githubusercontent.com/63072346/94862537-2e8cc300-044a-11eb-9110-c267178028b7.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
