### ISSUE TITLE
Описание проблемы

### ISSUE THREAD

**Issue by volkovakaterin** [netology-code/git-homeworks-neuro-issues#1857]
**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2.  Пролистать страницу до формы обратной связи

**Ожидаемый результат**

Форма обратной связи - горизонтальный прямоугольник 

**Фактический результат**

Форма обратной связи слишком вытянута по вертикали (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншоты

![image](https://user-images.githubusercontent.com/63072346/94864775-90026100-044d-11eb-9546-5d6a15d30d09.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
