### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by EvYuzhalin** [netology-code/git-homeworks-neuro-issues#1858]
### Описание проблемы
**Главная страница. 
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
@solarrust 

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![123](https://user-images.githubusercontent.com/40770411/94995666-30c15f80-05b9-11eb-8320-f414acd82b3a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
