### ISSUE TITLE
Форма обратной связи 

### ISSUE THREAD

**Issue by EvYuzhalin** [netology-code/git-homeworks-neuro-issues#1859]
### Описание проблемы
**Блок обратной связи слишком сжимается**
@solarrust 

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "обратной связи."

**Ожидаемый результат**

Форма обратной связи отображается корректно.

**Фактический результат**

Форма обратной связи сильно сжата(см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![321](https://user-images.githubusercontent.com/40770411/94995950-12f4fa00-05bb-11eb-8685-129a41640a86.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
