### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by PavlovAK** [netology-code/git-homeworks-neuro-issues#1864]
@solarrust

# Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

- Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**

- Размер блока соответствует пропорциям

**Фактический результат**

- Форма слишком сжата (см.скриншот)

**Программное окружение**

Устройство: iPhone XR (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот
![1](https://user-images.githubusercontent.com/72101542/95020884-7b54e180-0676-11eb-9a8b-f83a0a184af8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
