### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by PavlovAK** [netology-code/git-homeworks-neuro-issues#1865]
@solarrust

# Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

- Текст не наезжает на изображение

**Фактический результат**

- Текст наезжает на изображение

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
- Скриншот

![2](https://user-images.githubusercontent.com/72101542/95021019-32515d00-0677-11eb-9340-4a5967af61a8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
