### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by KateYachmeneva** [netology-code/git-homeworks-neuro-issues#1867]
###  Описание проблемы

@solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**

Размер блока выглядит привычно. Текст читается удобно.

**Фактический результат**
Ширина блока по горизонтали недостаточна. (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![image](https://user-images.githubusercontent.com/67925538/95021987-fb7e4580-067c-11eb-89bb-d5667a2b295c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
