### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by jonneg12** [netology-code/git-homeworks-neuro-issues#1868]
### **Описание проблемы**

@solarrust

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![iss1](https://user-images.githubusercontent.com/71975727/95046256-06cd8180-070e-11eb-9fa3-cce1c99fca38.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
