### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by jonneg12** [netology-code/git-homeworks-neuro-issues#1869]
### Форма обратной связи слишком сжата, текст имеет неправильные переносы

@solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**

Размер блока имеет нормальные пропорции. Текст удобно читать.

**Фактический результат**

Ширина блока по горизонтали недостаточна относительно экрана, текст неудобно читать. (см. скриншот)

**Программное окружение**

-  Устройство: iPhone 8+ (iOS 12.1)
-  Браузер: Chrome (70.0.3538.75)

**Скриншот**

![iss2](https://user-images.githubusercontent.com/71975727/95046946-67a98980-070f-11eb-89be-801a96177a58.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
