### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by 222Alexa** [netology-code/git-homeworks-neuro-issues#1874]
Главная страница. Форма обратной связи слишком сжата
===

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат**

Форма обратной связи на всю ширину экрана

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: HP Pavillion
- Браузер: Chrome

**Скриншоты**
![form](https://user-images.githubusercontent.com/60097815/95082064-2e7b1480-0723-11eb-9ca2-6b6248ffecb6.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
