### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by MaximeNefedov** [netology-code/git-homeworks-neuro-issues#1875]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

#### Ожидаемый результат

Форма обратной связи не сжата

#### Фактический результат

Форма обратной связи сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![](https://i.imgur.com/HcSpYkT.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
