### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Daniilzadorozhniy** [netology-code/git-homeworks-neuro-issues#1876]
## **Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## **Ожидаемый результат**
**Текст не наезжает на изображение**

**_Фактический результат_**
Текст наезжает на изображение (см. скриншот)
![1](https://user-images.githubusercontent.com/69350318/95089975-f689c680-074e-11eb-92c7-071a4577e7aa.png)

**_Программное окружение_**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75) 
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
