### ISSUE TITLE
Текст наезжает на картинку.

### ISSUE THREAD

**Issue by ervand7** [netology-code/git-homeworks-neuro-issues#1879]
# Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению:**
> 1) Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
> 2) Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Отмечаемые пользователи:**
@solarrust

**Программное окружение:**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот:**
![image](https://user-images.githubusercontent.com/71432101/95219424-06acaf00-07fe-11eb-8dd4-efe84bc154ca.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
