### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ervand7** [netology-code/git-homeworks-neuro-issues#1880]
# Описание проблемы
**Шаги по воспроизведению:**

> 1) Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
> 2) Пролистать страницу до формы обратной связи

**Ожидаемый результат:**
Пропорциональная форма обратной связи

**Фактический результат:**
Форма обратной связи слишком сжата (см. скриншот)

**Отмечаемые пользователи:**
@solarrust

**Программное окружение:**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот:**
![image](https://user-images.githubusercontent.com/71432101/95220782-7ec7a480-07ff-11eb-8097-42e1eda72e74.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
