### ISSUE TITLE
Сжата форма обратной связи

### ISSUE THREAD

**Issue by lakuleshova** [netology-code/git-homeworks-neuro-issues#1888]
# Описание проблемы

**Главная страница. Форма обратной связи слишком сжата по ширине**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма обратной связи адаптирована по ширине. Слова вмещаются на строку целиком

**Фактический результат**

Форма слишком узкая, слова переносятся на другую строку (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61543358/95451231-29f76b80-0970-11eb-88fd-cb28c552183d.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
