### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by devitos** [netology-code/git-homeworks-neuro-issues#1890]
**Описание проблемы**
**Главная страница. Форма обратной связи слишком сжата**
**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
- Пролистать страницу до блока "Оставайтесь на связи."

**Ожидаемый результат**
Текст распределен по ширине страницы и выровнен по центру страницы

**Фактический результат**
Текст сжат по центру страницы с переносом части слов на другие строки 

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

@solarrust 

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/71663225/95658125-da0bd680-0b20-11eb-9007-2494d2060d53.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
