### ISSUE TITLE
Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Tatachel74** [netology-code/git-homeworks-neuro-issues#1892]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: windows 8_OC
Браузер: Chrome Версия 85.0.4183.102 (Официальная сборка), (64 бит)

@solarrust 
![Задание 3 2](https://user-images.githubusercontent.com/70442392/95673950-6cb28100-0bc6-11eb-806c-512f3e11ddcb.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
