### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Tatachel74** [netology-code/git-homeworks-neuro-issues#1893]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи."
Ожидаемый результат
Текст распределен по ширине страницы и выровнен по центру страницы

Фактический результат
Текст сжат по центру страницы с переносом части слов на другие строки (см.скриншот)
Программное окружение
Устройство: windows 8_OC
Браузер: Chrome Версия 85.0.4183.102 (Официальная сборка), (64 бит)
![Задание3 2](https://user-images.githubusercontent.com/70442392/95674104-7c7e9500-0bc7-11eb-8a5a-2c340bbbc435.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
