### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by IraRogova** [netology-code/git-homeworks-neuro-issues#1895]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока формы обратной связи.
Ожидаемый результат
Форма на всю ширину страницы мобильного устройства

Фактический результат
Форма обратной связи слишком сжата. (см. скриншот https://prnt.sc/ux4rxe)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
