### ISSUE TITLE
Текстовый блок наезжает на изображение.

### ISSUE THREAD

**Issue by RoniHell** [netology-code/git-homeworks-neuro-issues#1896]
#### **Шаги** по воспроизведению
Для @solarrust 

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### **Ожидаемый результат**
Текст не наезжает на изображение

#### **Фактический результат**
Текст наезжает на изображение

![для гита](https://user-images.githubusercontent.com/67387370/95684392-17906280-0bfa-11eb-92e8-fa7d6c45e48c.png)

#### **Программное окружение**

Устройство: ASUS G74S(Windows 10)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
