### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by RoniHell** [netology-code/git-homeworks-neuro-issues#1897]
#### **Шаги** по воспроизведению
Для @solarrust 

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Формы обратной связи."

#### **Ожидаемый результат**
Форма растянута в соответствии с размерами экрана

#### **Фактический результат**
Форма слишком сжата

![форма связи](https://user-images.githubusercontent.com/67387370/95684677-fd578400-0bfb-11eb-9e1f-f2086654d25a.png)

#### **Программное окружение**

Устройство: ASUS G74S(Windows 10)
Браузер: Chrome

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
