### ISSUE TITLE
На главной странице форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by alfiiasharipova** [netology-code/git-homeworks-neuro-issues#1899]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

#### Ожидаемый результат

Форма растянута по ширине экрана

#### Фактический результат

Форма слишком сжата

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/gQrMEIG.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
