### ISSUE TITLE
Некорректное отображение блока

### ISSUE THREAD

**Issue by StivenOBairen** [netology-code/git-homeworks-neuro-issues#19]
@solarrust
# class="promo-description mt-5"
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Firefox
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат

Текст не наезжает на изображение
### Фактический результат

Текст наезжает на изображение (см. скриншот)
### Программное окружение

* Устройство: Galaxy Note 9 (414x846)
* Браузер: Firefox 65.0.1 (64-бит)

#### Скриншоты
![15-02-2019 214236](https://user-images.githubusercontent.com/24472191/52871699-732bf380-316c-11e9-958e-c6600a3b82c8.jpg)

**Comment by solarrust** [comment]
Great!
