### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by EgorNikitin94** [netology-code/git-homeworks-neuro-issues#1901]
# Описание проблемы
Блок "оставайтесь на связи" слишком сжат

**Шаги по воспроизведению**
1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Safari
2. Пролистать страницу до блока "оставайтесь на связи"

**Ожидаемый результат**
Нормальный размер блока
Просьба исправить @solarrust

**Фактический результат**
см. скиншот

**Программное окружение**
* Устройство: iPhone 11 (iOS 14.0)
* Браузер: Safari

**Скриншоты**
![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
