### ISSUE TITLE
Текст наезжает на картинку в мобильном браузере.

### ISSUE THREAD

**Issue by Blodden** [netology-code/git-homeworks-neuro-issues#1908]
### Описание проблемы
**Главная страница. Текст "Воспользуйтесь современными возможностями..." наезжает на картинку ноутбука**

**Воспроизведение проблемы.**

1. Открыть главную страницу в браузере на мобильном телефоне.
2. Пролистать до текста "Воспользуйтесь современными возможностями...".
3. Увидеть налезающий текст (см. скриншот)

**Скриншоты**

![Безымянный](https://user-images.githubusercontent.com/68012267/95870207-87265f00-0d6c-11eb-8eb0-284ef37815bf.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
