### ISSUE TITLE
Форма обратной связи слишком сжата в мобильном браузере

### ISSUE THREAD

**Issue by Blodden** [netology-code/git-homeworks-neuro-issues#1909]
### Описание проблемы
**Форма обратной связи слишком сжата в мобильном браузере. Неудобно читать.**

**Скриншоты**

![Безымянн2ый](https://user-images.githubusercontent.com/68012267/95871011-76c2b400-0d6d-11eb-9aae-3e129de16400.png)

**Желаемый результат**
1. Сделать адаптивную верстку под различные устройства, чтобы форма читалась удобно и понятно

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
