### ISSUE TITLE
Текст наезжает на изображение на экранах с шириной меньше 1200 пикс.

### ISSUE THREAD

**Issue by egor-badaev** [netology-code/git-homeworks-neuro-issues#1912]
@solarrust

### Описание проблемы

На экранах с шириной меньше 1200 пикс. текст наезжает на изображение и из-за этого не читается (см. скриншот)

### Воспроизведение

1. Открыть главную страницу
2. Обратить внимание на текст "Воспользуйтесь современными возможностями искусственного интеллекта, оставив конкурентов позади!"

### Ожидаемое поведение

Текст читается при любой ширине экрана от 320 пикс.

### Фактическое поведение

Текст некрасиво наезжает на изображение на экранах с шириной меньше 1200 пикс.
При ширине меньше 900 пикс. текст перестаёт быть читаемым

### Скриншот

<img width="343" alt="Screen Shot 2020-10-13 at 23 29 29" src="https://user-images.githubusercontent.com/37137463/95913534-0f2c5900-0dad-11eb-93aa-039f93da7c47.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
