### ISSUE TITLE
Форма обратной связи слишком сжата на мобильных устройствах

### ISSUE THREAD

**Issue by egor-badaev** [netology-code/git-homeworks-neuro-issues#1913]
@solarrust 

### Краткое описание проблемы

На экранах шириной менее 570 пикс. форма обратной связи слишком сжата

### Воспроизведение

1. Открыть главную страницу
2. Пролистать до формы обратной связи
3. Обратить внимание на расположение элементов

### Ожидаемый результат

Форма обратной связи отображается корректно на любой ширине от 320 пикс.

### Фактический результат

Форма отображается некорректно при ширине вьюпорта менее 570 пикс.

### Скриншот

<img width="303" alt="Screen Shot 2020-10-13 at 23 30 28" src="https://user-images.githubusercontent.com/37137463/95914632-b1007580-0dae-11eb-9905-7d3f29908561.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
