### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Montren** [netology-code/git-homeworks-neuro-issues#192]
### **Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта [NeuroStartUp](url) в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
**_Устройство:_** Asus zenfone 4 ze554kl (Android 8.1.0)
_**Браузер:**_ Chrome (70.0.3865.92)

### Скриншот
![Заезжающий_текст](https://user-images.githubusercontent.com/39235179/67395494-c33a4000-f5ae-11e9-9cf9-933a35a4d35d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
