### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Bemax2109** [netology-code/git-homeworks-neuro-issues#1921]
# **При открытии формы обратной связи в мобильном браузере текст съезжает, так как форма слишком сжата.**

## **Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Перейти на страницу формы обратной связи. 

## **Ожидаемый результат**
Текст читаемый и не съезжает

## **Фактический результат**
Текст плохо читаемый и съезжает (см. скриншот)

## **Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
## **Скриншот:**
![2](https://user-images.githubusercontent.com/71455523/96079148-40587680-0ede-11eb-9523-68a81fdbec08.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
