### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by ADeoZ** [netology-code/git-homeworks-neuro-issues#1922]
@solarrust
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 6/7/8+ (эмуляция)
- Браузер: Chrome (86.0.4240.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/68968053/96115950-6555e500-0ef0-11eb-9187-99b29bc2bf14.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
