### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ADeoZ** [netology-code/git-homeworks-neuro-issues#1923]
@solarrust
**Главная страница. Форма обратной связи "Оставайтесь на связи" слишком сжата относительно ширины страницы.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы "Оставайтесь на связи"

**Ожидаемый результат**

Форма занимает 90% от ширины экрана

**Фактический результат**

Форма занимает 50% от ширины экрана (см. скриншот)

**Программное окружение**

- Устройство: iPhone 6/7/8+ (эмуляция)
- Браузер: Chrome (86.0.4240.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/68968053/96116558-528fe000-0ef1-11eb-942f-dff6b8c899ef.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
