### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by JuliaGhalini** [netology-code/git-homeworks-neuro-issues#1925]
### **Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 6/7/8+ (эмуляция)
- Браузер: Chrome (86.0.4240.75)

**Скриншот:**

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/72600422/96121919-650e1780-0ef9-11eb-937f-f4875af1b157.png)
 @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
