### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by JuliaGhalini** [netology-code/git-homeworks-neuro-issues#1926]
### **Главная страница. Форма обратной связи "Оставайтесь на связи" слишком сжата относительно ширины страницы.**

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до формы "Оставайтесь на связи"

**Ожидаемый результат**

Форма занимает 90% от ширины экрана

**Фактический результат**

Форма занимает 50% от ширины экрана (см. скриншот)

**Программное окружение**

Устройство: iPhone 6/7/8+ (эмуляция)
Браузер: Chrome (86.0.4240.75)

**Скриншот:**

![96116558-528fe000-0ef1-11eb-942f-dff6b8c899ef](https://user-images.githubusercontent.com/72600422/96122583-5bd17a80-0efa-11eb-898d-a183b882a329.png)

 @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
