### ISSUE TITLE
Текст наезжает на картинку 

### ISSUE THREAD

**Issue by AnastasiaIQA12** [netology-code/git-homeworks-neuro-issues#1929]
### **БАГ**
Текстовый блок "Воспользуйтесь современными возможностями..." на главной странице наезжает на изображение

### **Шаги по воспроизведению**
1 Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2 Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### **Ожидаемый результат**
Текст не наезжает на изображение

### **Фактический результат**
Текст наезжает на изображение (см. скриншот)

### **Программное окружение**
Устройство: Honor 8X
Браузер: Chrome (70.0.3538.75)

### **Скриншоты**
![1](https://user-images.githubusercontent.com/72652840/96129302-23806b00-0eff-11eb-80a7-072be9e57b69.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
