### ISSUE TITLE
Суженная форма для регистрации, некорректный перенос слов

### ISSUE THREAD

**Issue by Montren** [netology-code/git-homeworks-neuro-issues#193]
# **Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Нажать на кнопку  "Зарегистрироваться"

## Ожидаемый результат
Открывается корректная форма для регистрации. Текст в форме не переносится по слогам.

## Фактический результат
Текст в окне регистрации местами переносится на следующую строчку разделяя слово на части

### Программное окружение
**_Устройство:_** Asus zenfone 4 ze554kl (Android 8.1.0)
**_Браузер:_** Chrome (70.0.3865.92)

Скриншот
![Суженная_форма_для_регистрации](https://user-images.githubusercontent.com/39235179/67396072-a3574c00-f5af-11e9-807d-da85e3870798.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
