### ISSUE TITLE
Сжатая форма обратной связи

### ISSUE THREAD

**Issue by AnastasiaIQA12** [netology-code/git-homeworks-neuro-issues#1930]
### **БАГ**
Форма обратной связи слишком сжата на главной странице сайта 

### **Шаги по воспроизведению**
1 Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2 Пролистать страницу до блока "Оставайтесь на связи"

### **Ожидаемый результат**
Форма распределена по ширине страницы

### **Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

### **Программное окружение**
Устройство: Honor 8X
Браузер: Chrome (70.0.3538.75)

### **Скриншоты**
![2](https://user-images.githubusercontent.com/72652840/96130456-a1914180-0f00-11eb-9f6f-2a9006bdce7d.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
