### ISSUE TITLE
Сжатая форма обратной связи в мобильной версии

### ISSUE THREAD

**Issue by Alex-nikiforova** [netology-code/git-homeworks-neuro-issues#1932]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат

Форма обратной связи соответствует ширине страницы

### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншот

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/72600303/96255811-34dd7c00-0fc0-11eb-9670-975489e758c9.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
