### ISSUE TITLE
При открытии лендинга в мобильном браузере текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by ViktoriaMasl** [netology-code/git-homeworks-neuro-issues#1935]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**@solarrust**

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67 (417×736) 2020-10-16 19-15-55 (1)](https://user-images.githubusercontent.com/72658225/96270279-dd9dd280-0fe4-11eb-9c10-4adcd47894df.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
