### ISSUE TITLE
При открытии лендинга в мобильном браузере сжатая форма обратной связи 

### ISSUE THREAD

**Issue by ViktoriaMasl** [netology-code/git-homeworks-neuro-issues#1936]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2. Пролистать страницу до блока обратной связи

**Ожидаемый результат**
Блок широкий, текст читабельный, слова не переносятся

**Фактический результат**
Блок узкий, слова переносятся некорректно

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**@solarrust**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67 (416×740) 2020-10-16 19-24-13](https://user-images.githubusercontent.com/72658225/96271332-2e61fb00-0fe6-11eb-9f65-e7eeefefc808.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
