### ISSUE TITLE
Текстовый блок "Воспользуйтесь..." наезжает на изображение

### ISSUE THREAD

**Issue by vozmissoboi** [netology-code/git-homeworks-neuro-issues#1937]
@solarrust
**В мобильном браузере на Главной странице текстовый блок "Воспользуйтесь..." наезжает на изображение.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: Samsung A8 (Android 9)
Браузер: Chrome (86.0.4240.75)

**Скриншоты**
[Текстовый блок на Главной](https://prnt.sc/v0n0vn)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
