### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by vozmissoboi** [netology-code/git-homeworks-neuro-issues#1938]
@solarrust
**В мобильном браузере на Главной странице форма "Оставайтесь на связи" слишком сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы "Оставайтесь на связи"

**Ожидаемый результат**
Форма обратной связи занимает всю ширину экрана

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
Устройство: Samsung A8 (Android 9)
Браузер: Chrome (86.0.4240.75)

**Скриншоты**
[Форма обратной связи](https://prnt.sc/v0n954)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
