### ISSUE TITLE
В мобильном браузере текст наезжает на изображение

### ISSUE THREAD

**Issue by ghost** [netology-code/git-homeworks-neuro-issues#1939]
### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Внимание для @solarrust
### Скриншот
![1](https://user-images.githubusercontent.com/72693386/96295183-25792580-0ff6-11eb-80bc-571cfe48c3d4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
