### ISSUE TITLE
1. Текст наезжает на картинку; 2. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by AlexDeko** [netology-code/git-homeworks-neuro-issues#194]
@solarrust

# Описание

#### Шаги по воспроизведению

1.1 Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1.2 Нажать на кнопку "Зарегистрироваться"
2.1 Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.2 Пролистать страницу до блока "Оставайтесь на связи"

#### Фактический результат

Текст не наезжает на изображение
Форма обратной связи сжимается пропорционально размеру страницы

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

# Скриншоты

![image](https://user-images.githubusercontent.com/41375747/67409867-d60b3f80-f5c3-11e9-8952-f8fbb3506664.png)
![image](https://user-images.githubusercontent.com/41375747/67410033-2387ac80-f5c4-11e9-8830-edf12a0e5303.png)

**Comment by solarrust** [comment]
Нужно было создать две разных задачи. По одной на каждую из проблем.
