### ISSUE TITLE
В мобильном браузере форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ghost** [netology-code/git-homeworks-neuro-issues#1940]
### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Форма обратной связи..."
### Ожидаемый результат
Форма пригодны для заполнения

### Фактический результат
Форма заполнения обратной связи слишком сжата (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Вниманию @solarrust

![2](https://user-images.githubusercontent.com/72693386/96295697-c071ff80-0ff6-11eb-9096-226a771e5859.png)
### Скриншоты

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
