### ISSUE TITLE
Форма "Оставайтесь на связи" слишком сжата при использовании в мобильном браузере

### ISSUE THREAD

**Issue by VadimOlkhov** [netology-code/git-homeworks-neuro-issues#1944]
Шаги по воспроизведению:
1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.Пролистать страницу до формы "Оставайтесь на связи"

Ожидаемый результат:
Форма обратной связи занимает всю ширину экрана

Фактический результат:
Форма обратной связи слишком сжата (см. скриншот)

Программное окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншот:
![2020-10-17_17h10_38](https://user-images.githubusercontent.com/65563436/96339192-bb1ac080-109b-11eb-8175-0f6b2aaa4526.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
