### ISSUE TITLE
Блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by VadimOlkhov** [netology-code/git-homeworks-neuro-issues#1945]
Шаги по воспроизведению:

1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат:
Текст не наезжает на изображение

Фактический результат:
Текст наезжает на изображение (см. скриншот)

Программное окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншот:
![2020-10-17_17h00_39](https://user-images.githubusercontent.com/65563436/96339252-341a1800-109c-11eb-8247-0e8afbe1d6a8.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
