### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by rinatfe** [netology-code/git-homeworks-neuro-issues#1946]
Описание проблемы

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат

Текст не наезжает на изображение

Фактический результат

Текст наезжает на изображение (см. скриншот)
Программное окружение

    Устройство: Xiaomi MI A2LITE (Android 10)
    Браузер: Chrome (70.0.3538.75)

Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/69366252/96351510-d3570380-10cc-11eb-8c41-422f0d9881df.png)
 @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
