### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by rinatfe** [netology-code/git-homeworks-neuro-issues#1947]
Описание проблемы
В мобильном браузере на Главной странице форма "Оставайтесь на связи" слишком сжата.

Шаги по воспроизведению

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до формы "Оставайтесь на связи"

Ожидаемый результат
Форма обратной связи занимает всю ширину экрана

Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

Программное окружение
Устройство: Xiaomi MI A2LITE (Android 10)
Браузер: Chrome (70.0.3538.75)

Скриншоты
![123](https://user-images.githubusercontent.com/69366252/96351719-5f1d5f80-10ce-11eb-9b73-457c018e35bb.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
