### ISSUE TITLE
Исправить текстовый блок на главной странице

### ISSUE THREAD

**Issue by Aikanush** [netology-code/git-homeworks-neuro-issues#195]
@solarrust 
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты 
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/54668932/67483255-76ba3780-f676-11e9-8a1c-faae78fc6a91.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
