### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by KlokovAleksey** [netology-code/git-homeworks-neuro-issues#1956]
Шаги по воспроизведению:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат:
Текст не наезжает на изображение

Фактический результат:
Текст наезжает на изображение (см. скриншот)

Программное окружение:
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
![1](https://user-images.githubusercontent.com/68289203/96377151-365b9f80-118c-11eb-8b86-1080cbe6ccc3.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
