### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by KlokovAleksey** [netology-code/git-homeworks-neuro-issues#1957]
Шаги по воспроизведению:

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу обратной связи

Ожидаемый результат:
Страница обратной связи во весь экран

Фактический результат:
Страница обратной связи сжата

Программное окружение:

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![2](https://user-images.githubusercontent.com/68289203/96377565-15487e00-118f-11eb-83ae-542c5296b8a2.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
