### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by saika1968** [netology-code/git-homeworks-neuro-issues#1959]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
@solarrust
![image](https://user-images.githubusercontent.com/69457725/96457094-082b9d80-1228-11eb-849e-6e816ee0991a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
