### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Antonina77** [netology-code/git-homeworks-neuro-issues#1963]
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Нажать на кнопку "Обратная связь"

**Ожидаемый результат**
Форма обратной связи не сжата

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

@solarrust

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/72868329/96482807-957ceb00-1244-11eb-9b37-ab8ae19117e5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
