### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by kit4kit** [netology-code/git-homeworks-neuro-issues#1964]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
@solarrust
#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/42236496/96500830-1ee9e880-1258-11eb-8db3-8eaa0b5f109c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
