### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by kit4kit** [netology-code/git-homeworks-neuro-issues#1965]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока с формой обратной связи

#### Ожидаемый результат

Ширина формы обратной связи равна ширине экрана

#### Фактический результат

Ширина формы не равна ширине экрана (см. скрин)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
@solarrust
#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/42236496/96501215-bd764980-1258-11eb-9aee-0bbd81404fc6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
