### ISSUE TITLE
Форма обратной связи слишком сжата в мобильном браузере

### ISSUE THREAD

**Issue by Aikanush** [netology-code/git-homeworks-neuro-issues#197]
@solarrust 

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи..."

#### Ожидаемый результат

Форма обратной связи занимает всю площадь экрана

#### Фактический результат

Форма сжата по центру (см. скриншот)

#### Программное окружение

* _Устройство:_ iPhone 8+ (iOS 12.1)
* _Браузер:_ Chrome (70.0.3538.75)

#### Скриншоты
![Screenshot at окт  24 16-12-22](https://user-images.githubusercontent.com/54668932/67484394-1bd60f80-f679-11e9-9ed6-f178684c35ea.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
