### ISSUE TITLE
Текст наезжает на картинку в мобильной версии

### ISSUE THREAD

**Issue by Elen-Ismaylova** [netology-code/git-homeworks-neuro-issues#1970]
В мобильной версии сайта текст заходит на картинку.
@solarrust
![текст на картинке](https://user-images.githubusercontent.com/72653699/96633103-51abe380-1321-11eb-9c78-a7efc4ffa26d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
