### ISSUE TITLE
форма обратной связи сжата в мобильной версии

### ISSUE THREAD

**Issue by Elen-Ismaylova** [netology-code/git-homeworks-neuro-issues#1971]
В мобильной версии сайта форма обратной связи сжатая.
@solarrust 
![почта](https://user-images.githubusercontent.com/72653699/96633548-edd5ea80-1321-11eb-9799-cc9ec6d9cdd6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
