### ISSUE TITLE
Текст наезжает на картинку в мобильном браузере

### ISSUE THREAD

**Issue by ZSemen47** [netology-code/git-homeworks-neuro-issues#1972]
### Шаги воспроизведения

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..." 

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншот
![Текст наезжает на изображение](https://user-images.githubusercontent.com/65822156/96714949-954b2f80-13ab-11eb-93fa-e0d6a47565a8.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
