### ISSUE TITLE
Форма обратной связи слишком сжата в мобильном браузере Chrome

### ISSUE THREAD

**Issue by ZSemen47** [netology-code/git-homeworks-neuro-issues#1973]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи "Оставайтесь на связи"

### Ожидаемый результат
Текст не сжат и удобно читаем

### Фактический результат
Текст сжат

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншот
![Текст сжат](https://user-images.githubusercontent.com/65822156/96716323-91201180-13ad-11eb-8022-7fcf2b78543f.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)

**Comment by ZSemen47** [comment]
xDDD

ср, 21 окт. 2020 г. в 18:57, Alena Batitskaya <notifications@github.com>:
