### ISSUE TITLE
Текст наехал на картинку на главной странице в приложении  NeuroStartUp 

### ISSUE THREAD

**Issue by Andrew2380** [netology-code/git-homeworks-neuro-issues#1974]
# Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/37656205/96735855-aa808800-13c4-11eb-9ade-3ea954686ec9.png)

@solarrust

**Comment by Andrew2380** [comment]
> # Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
> 
> **Шаги по воспроизведению**
> 
> 1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
> 2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
> 
> **Ожидаемый результат**
> 
> Текст не наезжает на изображение
> 
> **Фактический результат**
> 
> Текст наезжает на изображение (см. скриншот)
> 
> **Программное окружение**
> 
> * Устройство: iPhone 8+ (iOS 12.1)
> * Браузер: Chrome (70.0.3538.75)
> 
> **Скриншоты**
> 
> ![image](https://user-images.githubusercontent.com/37656205/96735855-aa808800-13c4-11eb-9ade-3ea954686ec9.png)
> 
> @solarrust

**Comment by Andrew2380** [comment]
Подправил

**Comment by Andrew2380** [comment]
Уже лучше

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)

**Comment by Andrew2380** [comment]
> # Описание проблемы
> **Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
> 
> **Шаги по воспроизведению**
> 
> 1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
> 2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
> 
> **Ожидаемый результат**
> 
> Текст не наезжает на изображение
> 
> **Фактический результат**
> 
> Текст наезжает на изображение (см. скриншот)
> 
> **Программное окружение**
> 
> * Устройство: iPhone 8+ (iOS 12.1)
> * Браузер: Chrome (70.0.3538.75)
> 
> **Скриншоты**
> 
> ![image](https://user-images.githubusercontent.com/37656205/96735855-aa808800-13c4-11eb-9ade-3ea954686ec9.png)
> 
> @solarrust

**Comment by Andrew2380** [comment]
ОК

**Comment by Andrew2380** [comment]
ок

**Comment by Andrew2380** [comment]
1
