### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by And8Alex** [netology-code/git-homeworks-neuro-issues#1975]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению:**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение

**Фактический результат:**
Текст наезжает на изображение (см. скриншот)

**Программное окружение:**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты:**
![Снимок экрана 2020-10-21 в 5 56 17 ПП](https://user-images.githubusercontent.com/68242373/96738205-28de2980-13c7-11eb-9868-b35a1b8254be.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
