### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by And8Alex** [netology-code/git-homeworks-neuro-issues#1976]
**Форма обратной связи сжата**

**Шаги по воспроизведению:**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу обратной связи

**Ожидаемый результат:**
Страница обратной связи во весь экран

**Фактический результат:**
Страница обратной связи сжата

**Программное окружение:**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты:**
![Снимок экрана 2020-10-21 в 6 05 18 ПП](https://user-images.githubusercontent.com/68242373/96739065-0f89ad00-13c8-11eb-825f-936c7441ef21.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
