### ISSUE TITLE
Форма обратной связи сжата в мобильной версии

### ISSUE THREAD

**Issue by Andrew2380** [netology-code/git-homeworks-neuro-issues#1977]
# Главная страница. Текстовый блок "Оставайтесь на связи" сжат

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи "Оставайтесь на связи"

**Ожидаемый результат**

- Текст не сжат и удобно читаем

**Фактический результат**

- Текст сжат

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![image](https://user-images.githubusercontent.com/37656205/96739320-57a8cf80-13c8-11eb-8c6a-daeec5597a86.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
