### ISSUE TITLE
Текстовый блок наезжает на изображение в мобильном браузере Chrome

### ISSUE THREAD

**Issue by AlekO1967** [netology-code/git-homeworks-neuro-issues#1979]
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению****
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот Главной страницы.**

![Текст на изображении](https://user-images.githubusercontent.com/72633270/96766923-7c12a500-13e4-11eb-8773-b2d9ca87f348.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
