### ISSUE TITLE
Сбой верстки на мобильных: текст пересекается с картинкой и слишком сжата форма обратной связи

### ISSUE THREAD

**Issue by romansuvorkov** [netology-code/git-homeworks-neuro-issues#198]
@solarrust

# Сбой мобильной верстки

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/54857334/67510690-d8969380-f6ae-11e9-928f-c8d6b9034470.png)

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

форма занимает 100% ширины экрана

#### Фактический результат

Форма занимает 1/3 и значительно сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/54857334/67510691-d8969380-f6ae-11e9-929d-4543a3f05f3c.png)

**Comment by solarrust** [comment]
Нужно было создать два issue, по одному на каждую из проблем
