### ISSUE TITLE
В мобильной версии форма обратной связи сильно сжата

### ISSUE THREAD

**Issue by AlekO1967** [netology-code/git-homeworks-neuro-issues#1980]
### Главная страница. Текстовый блок "Оставайтесь на связи" сильно сжат

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи "Оставайтесь на связи"

**Ожидаемый результат**
Текст не сжат и удобно читаем

**Фактический результат**
На экране текст сильно сжат

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![Сжата форма обратной связи](https://user-images.githubusercontent.com/72633270/96768201-3fe04400-13e6-11eb-9ffe-bb610a2865f7.png)

**@solarrust**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
