### ISSUE TITLE
Текст на главной странице наезжает на картинку

### ISSUE THREAD

**Issue by Kisnik** [netology-code/git-homeworks-neuro-issues#1981]
**Тестовое окружение**

Устройство: Sony Xperia xz1, android 9
Браузер Chrome. Версия 86.0.4240.99

**Сценарий**

1. Открыть главную страницу
2. Внимание на блок с текстом "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:** текст расположен по центру страницы и не наезжает на изображение
**Фактический результат:** текст наезжает на изображение

Скриншот

![image](https://user-images.githubusercontent.com/35270226/96768135-250dcf80-13e6-11eb-85a0-8b984299e357.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
