### ISSUE TITLE
Форма обратной связи сильно сжата

### ISSUE THREAD

**Issue by Kisnik** [netology-code/git-homeworks-neuro-issues#1982]
**Тестовое окружение**

Устройство: Sony Xperia xz1, android 9
Браузер Chrome. Версия 86.0.4240.99

**Сценарий**

1. Открыть главную страницу
2. Нажать в правом верхнем углу кнопку с тремя полосками
3. Перейти на вкладку Обратная связь

**Ожидаемый результат:** текст и формы для заполнения обратной связи расположены по по всей рабочей площади страницы
**Фактический результат:** текст и формы для заполнения обратной связи сильно сжаты и не занимают место по краям рабочей площади страницы

Скриншот

![image](https://user-images.githubusercontent.com/35270226/96769935-82a31b80-13e8-11eb-8d68-939f84832c3f.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
