### ISSUE TITLE
На странице лендинга текстовый блок "Воспользуйтесь современными.." накладывается на изображение логотипа 

### ISSUE THREAD

**Issue by LexinFrom02** [netology-code/git-homeworks-neuro-issues#1983]
# Описание проблемы
### Шаги воспроизведения:
1. Открыть лендинг
1. Проскроллить страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат:
1. Текст и область фона с изображением лого не накладываются друг на друга
1. Текст читаем и понятен

###  Фактический результат:
Текстовый блок наезжает на часть фонового изображения с логотипом компании, элементы сливаются, текст нечитаемый

### Программное окружение:
* Устройство: Redmi Note 5 (Версия Android 9 PKQ1.180904.001)
* Браузер: Chrome (86.0.4240.99)

### Вложения
![screenshot](https://camo.githubusercontent.com/e648681205a1dfdf6ed69784e1311b18ca924856/68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
