### ISSUE TITLE
На странице лендинга форма обратной связи сжата по горизонтали

### ISSUE THREAD

**Issue by LexinFrom02** [netology-code/git-homeworks-neuro-issues#1984]
# Описание проблемы
### Шаги воспроизведения:
1. Открыть лендинг
1. Проскроллить страницу до формы обратной связи

### Ожидаемый результат:
1. Форма пропорциональна размеру экрана
1. Текст читаем, презентабелен

###  Фактический результат:
1. Форма обратной связи сжата по горизонтали
1. Текст с переносами, текстовые блоки вытянуты в столбец

### Программное окружение:
* Устройство: Redmi Note 5 (Версия Android 9 PKQ1.180904.001)
* Браузер: Chrome (86.0.4240.99)

### Вложения
![screenshot](https://cdn1.radikalno.ru/uploads/2020/10/21/677d67d9365b8641c8d752dc6ada9fdc-full.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
