### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by IvanBurk** [netology-code/git-homeworks-neuro-issues#1985]
# Описание проблемы 
### Шаги по воспроизведению
  1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
  2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
  Текст не наезжает на изображение

### Фактический результат
  Текст наезжает на изображение (см. скриншот)

### Программное окружение
  * Устройство: iPhone 8+ (iOS 12.1)
  * Браузер: Chrome (70.0.3538.75)
### Скриншоты

![image](https://user-images.githubusercontent.com/64144110/96791896-fa317480-1401-11eb-94fa-cea324f6773d.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
