### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by IvanBurk** [netology-code/git-homeworks-neuro-issues#1986]
# Описание проблемы
### Шаги воспроизведения:
 1. Открыть лендинг
 2. Пролистать страницу до формы обратной связи
### Ожидаемый результат:
 * Форма пропорциональна размеру экрана
 * Текст читается
### Фактический результат:
 Форма обратной связи сжата по горизонтали
### Программное окружение:
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншот

![image](https://user-images.githubusercontent.com/64144110/96792790-c8211200-1403-11eb-9986-cd8d13908e2c.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
