### ISSUE TITLE
[Mobile] Лендинг. Текст наезжает на картинку

### ISSUE THREAD

**Issue by j-rebel** [netology-code/git-homeworks-neuro-issues#199]
#### Что?

На странице лендинга выявлены следующие проблемы:

Текст наезжает на картинку;

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/32876690/67513687-075b3c80-f6a4-11e9-85c4-297f2be530e7.png)

#### Кто?
Проверяющий: @j-rebel
Исполнитель: @solarrust 

#### Почему?
Проблемы негативно сказываются на пользовательском опыте взаимодействия с лендингом.

#### Где? 
Лендинг компании - Шапка

#### Когда?
24.10.2019

## Ожидаемый результат
Текст не наезжает на изображение.

## Шаги для воспроизведения проблемы 
Текст наезжает на картинку;
- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
