### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ElenaDom** [netology-code/git-homeworks-neuro-issues#1990]
### Шаги

1. Отрыть главную страницу веб-сайта NeuroStartAp
2. Скролить экран до формы "Обратная связь"

### Ожидаемый результат
Форма открылась на всю страницу
### Фактический результат
Форма сжата к середине страницы
### Окружение
Устройство: IPhone X версия 14.0.1
Браузер: Safari
![Снимок экрана 2020-10-22 в 16 39 32](https://user-images.githubusercontent.com/72658756/96872850-335ef880-1485-11eb-8d45-8cf5569c6c23.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
