### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by ElenaDom** [netology-code/git-homeworks-neuro-issues#1991]
### Шаги
1. Открываем главную страницу веб-сайта NeuroStartUp
### Ожидаемый результат
Страница разделена на блоки с картинками и блоки с текстом
### Фактический результат
Блок секстам накладывается на блок с картинкой
### Окружение
Устройство:  iPhone X версия 14.0.1
Браузер: Safari
![Снимок экрана 2020-10-22 в 15 56 20](https://user-images.githubusercontent.com/72658756/96873422-f5ae9f80-1485-11eb-9740-5efd146dd081.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
