### ISSUE TITLE
Текст лендинга в мобильном браузере наезжает на картинку

### ISSUE THREAD

**Issue by horungeelena** [netology-code/git-homeworks-neuro-issues#1993]
**Шаги по воспроизведению:**

1. Открыть главную страницу сайта NeuroStartUp в браузере Chrome на мобильном устройстве;
2. Пролистать страницу сайта до блока "Воспользуйтесь современными возможностями ИИ.."

**Ожидаемый результат:**
Текст не наезжает на картинку, надписи читабельны.

**Фактический результат**:
Частично текст не читается из-за наплывания на изображение ( см. скриншот)

**Программное окружение**:

- Устройство:  iPhone SE (iOS 12.1)
- Браузер: Chrome (86.0.4240.110)

**Скриншот**

![11](https://user-images.githubusercontent.com/72626263/96882602-c6952f80-147f-11eb-8483-efa56d8dd31a.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
