### ISSUE TITLE
Форма обратной связи на лендинге при просмотре с мобильного устройства сжата

### ISSUE THREAD

**Issue by horungeelena** [netology-code/git-homeworks-neuro-issues#1994]
**Шаги по воспроизведению:**
1. Открыть главную страницу сайта NeuroStartUp в браузере Chrome на мобильном устройстве;
2. Пролистать страницу сайта до блока "Оставайтесь на связи..."

**Ожидаемый результат**:
Форма обратной связи развернута по всей ширине окна браузера

**Фактический результат**:
Блок формы обратной связи слишком сжат и растянут по вертикали

**Программное окружение**:

- Устройство: iPhone SE (iOS 12.1)
- Браузер: Chrome (86.0.4240.110)

**Скриншот**

![12](https://user-images.githubusercontent.com/72626263/96885039-7cfa1400-1482-11eb-8ab6-90aac27c613a.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
