### ISSUE TITLE
Текстовый блок перекрывает изображение

### ISSUE THREAD

**Issue by Sabbotage-cmd** [netology-code/git-homeworks-neuro-issues#1995]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/70913727/96896777-973ded00-1496-11eb-8ab2-2ba29d3d5e4d.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
