### ISSUE TITLE
Форма обратной связи на странице слишком сжата

### ISSUE THREAD

**Issue by Sabbotage-cmd** [netology-code/git-homeworks-neuro-issues#1996]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма отображается не сжато

#### Фактический результат

Форма обратной связи сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![96716323-91201180-13ad-11eb-8022-7fcf2b78543f](https://user-images.githubusercontent.com/70913727/96897185-04ea1900-1497-11eb-9d2c-aed35a7b478e.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
