### ISSUE TITLE
Мобильная версия, текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by MariyaGrishkova** [netology-code/git-homeworks-neuro-issues#1997]
Сообщение для @solarrust
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![Снимок экрана 2020-10-22 202659](https://user-images.githubusercontent.com/72941053/96908254-07ec0600-14a5-11eb-92ad-91228b7b0918.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
