### ISSUE TITLE
Мобильная версия. Форма обратной связи сжата

### ISSUE THREAD

**Issue by MariyaGrishkova** [netology-code/git-homeworks-neuro-issues#1998]
Сообщение для @solarrust
**Главная страница. Форма обратной связи**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Текст равномерно распределен по строкам

**Фактический результат**
Текст скомкан по строчкам
см. скриншот

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![Снимок экрана 2020-10-22 204024](https://user-images.githubusercontent.com/72941053/96909654-fad01680-14a6-11eb-8683-b7370e141c40.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
