### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by StivenOBairen** [netology-code/git-homeworks-neuro-issues#20]
@solarrust
# class="contacts-card col-6 mx-auto card pt-4 pb-4"
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Firefox
2. Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат

Ограничение по минимальной ширине блока.
Предлагаю изменить min-width до 300px;
### Фактический результат

Ширина блока чрезмерно сжата
### Программное окружение

* Устройство: Galaxy Note 9 (414x846)
* Браузер: Firefox 65.0.1 (64-бит)

#### Скриншоты
![15-02-2019 220343](https://user-images.githubusercontent.com/24472191/52872502-7a540100-316e-11e9-92e4-10b3e415ff60.jpg)

**Comment by solarrust** [comment]
Great!
