### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by OlesyaZubkova** [netology-code/git-homeworks-neuro-issues#2001]
### Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/69164989/96917017-fe689b00-14b0-11eb-97d4-82e1710f71b0.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
