### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by OlesyaZubkova** [netology-code/git-homeworks-neuro-issues#2002]
### Описание проблемы

**Главная страница. Блок "Оставайтесь на связи" слишком сжат**

**Шаги по воспроизведению**

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат

Текст удобно читаем;
Форма обратной связи во весь экран.

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

Скриншоты

![Screenshot_1](https://user-images.githubusercontent.com/69164989/96917801-ff4dfc80-14b1-11eb-8b4b-bd8f35df53fe.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
