### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by YesPechenko** [netology-code/git-homeworks-neuro-issues#2006]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст удобно читаем;
Форма обратной связи во весь экран.

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![image](https://user-images.githubusercontent.com/22775215/96997699-ec333f00-153a-11eb-9785-6e1cae3ef978.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
