### ISSUE TITLE
Форма обратной связи сжимается при просмотре со смартфона

### ISSUE THREAD

**Issue by SorokaVV** [netology-code/git-homeworks-neuro-issues#2008]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Текст удобно читаем, форма обратной связи во весь экран.

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HcSpYkT.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
