### ISSUE TITLE
Блок текста на главной странице наезжает на изображение

### ISSUE THREAD

**Issue by Tatiana43** [netology-code/git-homeworks-neuro-issues#2009]
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/72838522/97052875-7951b480-158a-11eb-8e18-9ce8c10a74fa.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
