### ISSUE TITLE
Проблемы мобильной верстки

### ISSUE THREAD

**Issue by AlxLebedev** [netology-code/git-homeworks-neuro-issues#201]
# Описание проблем

@solarrust 
### На главной странице текст "Воспользуйтесь современными возможностями..." наезжает на картинку

**Шаги по воспроизведению:**
1. Открыть главную страницу сайта на мобильном устройстве
1. Пролистать страницу до текста "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**

Текст не наезжает на картинку

**Фактический результат:**

Текст наезжает на картинку

**Программное окружение:**
* iPhone SE
* Safari

**Скриншот**

![issue_text](https://user-images.githubusercontent.com/54743468/67566926-982c2980-f731-11e9-91c5-603fd0820469.png)

### Форма обратной связи слишком сжата

**Шаги по воспроизведению:**
1. Открыть форму обратной связи
1. Пролистать форму обратной связи сверху вниз

**Ожидаемый результат:**

Форма обратной связи должна занимать ширину мобильного экрана

**Фактический результат:**

Форма обратной связи меньше ширины мобильного экрана (сжата)

**Программное окружение:**
* iPhone SE
* Safari

**Скриншот**

![issue_form](https://user-images.githubusercontent.com/54743468/67566946-a2e6be80-f731-11e9-821d-df853a1da7a9.png)

**Comment by solarrust** [comment]
Нужно было создать два issue, по одному на каждую из проблем.
