### ISSUE TITLE
Форма обратной связи на главной странице сжата

### ISSUE THREAD

**Issue by Tatiana43** [netology-code/git-homeworks-neuro-issues#2010]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма обратной связи отображается во весь экран

**Фактический результат**
Форма обратной связи сжата к центру (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/72838522/97053055-d8172e00-158a-11eb-954d-39548dc8c6fa.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
