### ISSUE TITLE
Текст заголовка "Искусственный интеллект решающий ваши бизнес-задачи" выровнен по разному

### ISSUE THREAD

**Issue by Nika081187** [netology-code/git-homeworks-neuro-issues#2011]
**Описание проблемы**
=======

**Текст заголовка "Искусственный интеллект решающий ваши бизнес-задачи" выровнен по разному**
-----------
Первая часть текста выровнена по левому краю, а вторая часть - по середине

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Искусственный интеллект решающий ваши бизнес-задачи"

**Ожидаемый результат**
Текст выровнен одинаково (по середине или по левому краю)

**Фактический результат**
Первая часть текста выровнена по левому краю, а вторая часть - по середине

**Программное окружение**
Устройство: MacBook Pro 218
Браузер: Chrome (86.0.4240.111)

**Скриншоты**
<img width="418" alt="Снимок экрана 2020-10-24 в 14 24 27" src="https://user-images.githubusercontent.com/26058208/97080551-e6a22b80-1604-11eb-8089-c3bbb316eda0.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
