### ISSUE TITLE
Изображение располагается не по центру экрана

### ISSUE THREAD

**Issue by Nika081187** [netology-code/git-homeworks-neuro-issues#2012]
**Описание проблемы**
=======
**Изображание располагается не по центру экрана**
-----------
Изображение обрезано справа

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу вниз по изображения ноутбука

**Ожидаемый результат**
Изображение расположено по центру экрана

**Фактический результат**
Изображение обрезано с правой стороны

**Программное окружение**
Устройство: MacBook Pro 218
Браузер: Chrome (86.0.4240.111)

**Скриншоты**
<img width="418" alt="Снимок экрана 2020-10-24 в 14 33 33" src="https://user-images.githubusercontent.com/26058208/97080700-06861f00-1606-11eb-920b-7e2aac2f82b9.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
