### ISSUE TITLE
текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by asatoroff** [netology-code/git-homeworks-neuro-issues#2013]
Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![12345678o](https://user-images.githubusercontent.com/71065934/97083356-0ee75580-1618-11eb-88bb-8524320f2e85.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
