### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by asatoroff** [netology-code/git-homeworks-neuro-issues#2014]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат
Форма обратной связи не сжата

Фактический результат
форма обратной связи сжата (см. скриншот)
![12345676543](https://user-images.githubusercontent.com/71065934/97083576-9aadb180-1619-11eb-85a9-922849c9a3ec.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
