### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by Anichirina** [netology-code/git-homeworks-neuro-issues#2015]
### Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

 Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

@solarrust

**Скриншоты**
![image](https://user-images.githubusercontent.com/72977774/97094968-8b9f2180-1662-11eb-9707-d3e5d2f7f1a4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
