### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Anichirina** [netology-code/git-homeworks-neuro-issues#2016]
### Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до формы регистрации "Оставайтесь на связи."

**Ожидаемый результат**

Форма регистрации равномерно располагается по ширине страницы

**Фактический результат**

Форма подписки стала слишком узкая и вытянутая (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

@solarrust

**Скриншоты**

![image](https://user-images.githubusercontent.com/72977774/97095221-64961f00-1665-11eb-9f5e-02ef9ef5a6fc.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
