### ISSUE TITLE
Текст наезжает на изображение на главной странице сайта NeuroStartUp в мобильном браузере.

### ISSUE THREAD

**Issue by DinaOrlova** [netology-code/git-homeworks-neuro-issues#2020]
**Шаги:**

1. Открыть главную страницу веб-сайта NeuroStartUp через мобильный браузер.
1.  Проскролить страницу до изображения.

**Ожидаемый результат:**
Текст расположен ниже изображения.

**Фактический результат:**
Текст наезжает на изображение (см. скриншот)

**Программное окружение:**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты:**
![1](https://user-images.githubusercontent.com/73099171/97110845-6fe05d80-16ec-11eb-8bb9-a9af2c9bd8a8.jpg)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
