### ISSUE TITLE
Форма обратной связи на главной странице сайта NeuroStartUp слишком сжата.

### ISSUE THREAD

**Issue by DinaOrlova** [netology-code/git-homeworks-neuro-issues#2021]
**Шаги:**

1. Открыть главную страницу веб-сайта NeuroStartUp через мобильный браузер.
1. Проскролить страницу до формы обратной связи.

**Ожидаемый результат:**
Форма расположена на всю ширину экрана.

**Фактический результат:**
Форма слишком сжата, гораздо уже ширины экрана (см. скриншот).

**Программное окружение:**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты:**
![2](https://user-images.githubusercontent.com/73099171/97111112-07927b80-16ee-11eb-8bbe-d3f51b089f9e.jpg)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
