### ISSUE TITLE
В мобильном браузере Текстовый блок на главной странице наезжает на изображение

### ISSUE THREAD

**Issue by YuliaKulini4** [netology-code/git-homeworks-neuro-issues#2022]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### 
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
![skreenshot1](https://user-images.githubusercontent.com/72828013/97112312-a3bf8100-16f4-11eb-8302-a9ac65497bef.png)

Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: Redmi Note 8 Pro (MIUI 12.0.3)
Браузер: Chrome (86.0.4240.99)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
