### ISSUE TITLE
В мобильном браузере форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by YuliaKulini4** [netology-code/git-homeworks-neuro-issues#2023]
## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать до формы "Оставайтесь на связи"

### Ожидаемый результат
Ширина формы соответствует ширине экрана, поля 2 мм

### Фактический результат
Форма значительно уже экрана, поля занимает 2/3 экрана

### Программное окружение
Устройство: Redmi 8 Pro (MIUI 12.0.3)
Браузер: Chrome (86.0.4240.99)
![Skreenshot2](https://user-images.githubusercontent.com/72828013/97112837-a374b500-16f7-11eb-8539-c9efa3696765.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
