### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AntoNeo54** [netology-code/git-homeworks-neuro-issues#2025]
# Описание проблемы

#### Главная страница. Форма обратной связи "Оставайтесь на связи" слишком сжата
https://github.com/netology-code/git-homeworks-neuro-issues/blob/857e3d95477bfbd9c93fb04804a64d0007c1c075/index.html#L53

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи "Оставайтесь на связи"

#### Ожидаемый результат

Слово "Оставайтесь"  на одной строке

#### Фактический результат

Слово "Оставайтесь" разрывается и переноситься на следующею строку (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HcSpYkT.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
