### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Nikgr15** [netology-code/git-homeworks-neuro-issues#2026]
[Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение](url)

[Шаги по воспроизведению](url)

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

[Ожидаемый результат](url)

Текст не наезжает на изображение

[Фактический результат](url)

Текст наезжает на изображение (см. скриншот)

[Программное окружение](url)

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

 [Скриншоты](url)
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/71330145/97181725-a8477080-17ac-11eb-8921-539aa4d98972.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
