### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Nikgr15** [netology-code/git-homeworks-neuro-issues#2027]
[Описание проблемы](url)

Форма обратной связи сжата

[Шаги по воспроизведению](url)

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до формы регистрации "Оставайтесь на связи."

[Ожидаемый результат](url)

Форма регистрации располагается равномерно на странице

[Фактический результат](url)

Форма подписки слишком узкая (см.скриншоты)

[Программное окружение](url)

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты[](url)
![888](https://user-images.githubusercontent.com/71330145/97182812-0f195980-17ae-11eb-93a6-3efeb082d7b6.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
