### ISSUE TITLE
Форма обратной связи. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by vladimir-diakonov** [netology-code/git-homeworks-neuro-issues#2029]
To: @solarrust

**Шаги по воспроизведению**

Открыть страницу обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

**Ожидаемый результат**

Форма обратной связи на всю страницу

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/69050443/97190552-e6e22880-17b6-11eb-941e-b385b3d5abc8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
