### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by vinokurovsergey2020-s** [netology-code/git-homeworks-neuro-issues#2030]
**Шаги по воспроизведению**
  1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
  2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

  - Устройство: iPhone 8+ (iOS 12.1)
  - Браузер: Chrome (70.0.3538.75)

 **Скриншот**

 
![image](https://user-images.githubusercontent.com/73140831/97228503-15c4c280-17e8-11eb-8fce-8fc722d5181b.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
