### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by vinokurovsergey2020-s** [netology-code/git-homeworks-neuro-issues#2031]
**Шаги по воспроизведению**
  1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
  2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст удобно читаем;
Форма обратной связи во весь экран.

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
-   Браузер: Chrome (70.0.3538.75)

**Скриншот**
  
![image](https://user-images.githubusercontent.com/73140831/97230778-9afda680-17eb-11eb-8023-c052ed8348ee.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
