### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by urop9xa** [netology-code/git-homeworks-neuro-issues#2032]
Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![97228503-15c4c280-17e8-11eb-8fce-8fc722d5181b](https://user-images.githubusercontent.com/71930372/97292558-71309800-185c-11eb-9cea-b878cd78f93b.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
