### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by urop9xa** [netology-code/git-homeworks-neuro-issues#2033]
Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст удобно читаем;
Форма обратной связи во весь экран.

Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот
![форма](https://user-images.githubusercontent.com/71930372/97293079-3713c600-185d-11eb-9ac3-c504f23e307f.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
