### ISSUE TITLE
Интерфейс пользователя отображается некорректно

### ISSUE THREAD

**Issue by Rostiks52** [netology-code/git-homeworks-neuro-issues#2034]
@solarrust
На главной странице веб-сайта NeuroStartUp текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

**Шаги по воспроизведению:**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/72992818/97399483-50208380-18fe-11eb-94ae-34df806bbd8d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
