### ISSUE TITLE
Визуальное отображение формы обратной связи

### ISSUE THREAD

**Issue by Rostiks52** [netology-code/git-homeworks-neuro-issues#2035]
@solarrust

Главная страница, форма обратной связи слишком сжата

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма отображается во всю ширину экрана

**Фактический результат**

Форма слишком сжата  (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/72992818/97399977-55320280-18ff-11eb-97c5-62add411ed57.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
