### ISSUE TITLE
При просмотре лендинга NeuroStartUp в мобильном браузере Opera текст наезжает на картинку 

### ISSUE THREAD

**Issue by Nazilyash** [netology-code/git-homeworks-neuro-issues#2036]
###  Шаги по воспроизведению

1. Открыть страницу лендинга NeuroStartUp в мобильном браузере Opera.

1. Пролистать страницу до текстового блока "Воспользуйтесь современными возможностями...".

### Ожидаемый результат
Текстовый блок находится выше картинки.

### Фактический результат
Текстовый блок наезжает на картинку (см. скриншот).

### Программное окружение
Устройство:  Sony C4 (Android 6)
Браузер: Chrome (56.1.2780.51589)

_**Assignees**_ @solarrust

### Скриншоты
![image](https://user-images.githubusercontent.com/72624311/97486891-281c3900-196d-11eb-9d0a-edfe8859b024.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
