### ISSUE TITLE
При просмотре в мобильном браузере Opera Форма обратной связи лендинга NeuroStartUp узкая

### ISSUE THREAD

**Issue by Nazilyash** [netology-code/git-homeworks-neuro-issues#2037]
### Шаги по воспроизведению

1. Открыть страницу лендинга NeuroStartUp в мобильном браузере Opera.

1. Нажать на кнопку "Обратная связь".

### Ожидаемый результат
Форма обратной связи пропорциональна окну браузера.

### Фактический результат
Форма обратной связи непропорционально узкая относительно окна браузера (см. скриншот).

Программное окружение
Устройство: Sony C4 (Android 6)
Браузер: Chrome (56.1.2780.51589)

_**Assignees**_ @solarrust

Скриншоты
![image](https://user-images.githubusercontent.com/72624311/97490747-4fc1d000-1972-11eb-89dd-18babbc1a1c7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
