### ISSUE TITLE
Главная страница. Исправить грамматические ошибки и некорректное отображение текста

### ISSUE THREAD

**Issue by Alex-m18** [netology-code/git-homeworks-neuro-issues#204]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Искусственный интеллект..."
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
1. Исправить грамматическую ошибку: после слов "Искусственный интеллект" поставить запятую
1. Текст "Воспользуйтесь современными возможностями искусственного интеллекта оставив конкурентов позади!" не наезжает на изображение 
 
**Фактический результат** @solarrust 
1. Грамматическая ошибка
1. Текст наезжает на изображение (см. скриншот)
![screen-3-2 1](https://user-images.githubusercontent.com/52493820/67601185-6be9ca80-f77c-11e9-80f4-3a9a71bd7b32.png)

Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
