### ISSUE TITLE
Главная страница, моб версия. Текст "Воспользуйтесь современными возможностями..." наезжает на картинку.

### ISSUE THREAD

**Issue by MeriAv** [netology-code/git-homeworks-neuro-issues#2040]
@solarrust 

Шаги воспроизведения:
1. открыть главную страницу лендинга с мобильной версии 
2. проскролить страницу вниз. до блока "воспользуйтесь современными возможностями"

Фактический результат 
Текст "Воспользуйтесь современными возможностями..." наезжает на картинку.

Ожидаемый результат
текст не перекрывает картинку

Окружение:
Браузер: Chrome
Устройство: Samsung s8

Скриншот 
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/72850780/97725797-9e40ad00-1adf-11eb-935e-a106b177d1d3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
