### ISSUE TITLE
Моб версия. Форма обратной связи по ширине слишком сжата

### ISSUE THREAD

**Issue by MeriAv** [netology-code/git-homeworks-neuro-issues#2041]
@solarrust 

Шаги воспроизведения:
1. открыть лендинг в моб версии 
2. нажать кнопку "оставить заявку"

Фактический результат
Форма отображается не корректно, не адаптивна под моб версию, в ширину слишком узкая.

Ожидаемый результат
Форма отображается корректно, подстраиваясь под размер экрана

Окружение 
Браузер : Chrome
Устройство: Samsung s8

Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/72850780/97726592-6f770680-1ae0-11eb-9dd5-f1fbf9966f5d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
