### ISSUE TITLE
# 1 Белый текст наезжает на белое изображение в мобильной версии

### ISSUE THREAD

**Issue by Mogushkov** [netology-code/git-homeworks-neuro-issues#2044]
### ОПИСАНИЕ ПРОБЛЕМЫ
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: Samsung s10 (Android 9)
- Браузер: Opera Mobile (12)

**Скриншот**

![1](https://user-images.githubusercontent.com/69435753/97792284-63c53600-1bed-11eb-900f-7df74ab6a9b3.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
