### ISSUE TITLE
№ 2 Форма обратной связи

### ISSUE THREAD

**Issue by Mogushkov** [netology-code/git-homeworks-neuro-issues#2045]
### Описание проблемы
**Главная страница. Форма обратной связи слишком сжата**
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи.

**Ожидаемый результат**
Форма обратной подстраивается под ширину страницы, текст не выходит за рамки 

**Фактический результат**
форма обратной связи сжата, не подстраивается под ширину страницы

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![2](https://user-images.githubusercontent.com/69435753/97792443-7a6c8c80-1bef-11eb-981a-dc0aa0835b81.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
