### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by fromkerch** [netology-code/git-homeworks-neuro-issues#2048]
**Шаги по воспроизведению**:

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**:

Текст не наезжает на изображение

**Фактический результат**:

Текст наезжает на изображение (см. скриншот)

**Программное окружение**:

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**:
![bug1 текст наезжает на картинку (1)](https://user-images.githubusercontent.com/73745180/97804377-82184980-1c60-11eb-929d-6b39319bcb43.png)

**Исполнитель**: @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
