### ISSUE TITLE
Форма обратной связи. Заужена ширина блока, грамматические ошибки

### ISSUE THREAD

**Issue by Alex-m18** [netology-code/git-homeworks-neuro-issues#205]
**Шаги по воспроизведению**

1. Перейти на страницу формы обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до абзаца "Оставьте ваши контакты ..."

**Ожидаемый результат**
1. Исправить грамматическую ошибку: после слов "Оставьте ваши контакты" поставить запятую
1. В предложении "Даю согласие на обработку перс.данных" между "перс." и "данных" поставить неразрывный пробел
1. Слово "Оставайтесь" должно быть на одной строке без переноса
1. Текст "Email или Телефон" располагается в одну строку без переносов
 
**Фактический результат** @solarrust 
1. Грамматические ошибки
1. Заужена ширина блока формы (см. скриншот)

![screen-3-2 2](https://user-images.githubusercontent.com/52493820/67603546-e6691900-f781-11e9-862b-3fc030d5a33c.png)

Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
