### ISSUE TITLE
Форма обратной связи отображается слишком сжато

### ISSUE THREAD

**Issue by fromkerch** [netology-code/git-homeworks-neuro-issues#2050]
**Шаги по воспроизведению**:

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Оставайтесь на связи".

**Ожидаемый результат**:

Размер формы обратной связи удовлетворяет ширине экрана

**Фактический результат**:

Страница отображается слишком сжато (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**:
![bug2 форма заполнения сжата](https://user-images.githubusercontent.com/73745180/97804581-eb4c8c80-1c61-11eb-95a1-2c2f58373757.png)

**Исполнитель**: @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
