### ISSUE TITLE
Форма обратной связи в мобильной версии слишком сжата по ширине

### ISSUE THREAD

**Issue by OlgaNevezhina** [netology-code/git-homeworks-neuro-issues#2056]
@solarrust 
**Шаги воспроизведения:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма отображается корректно, подстраиваясь под размер экрана

**Фактический результат**

Страница отображается слишком сжато, не подстраивается под размер экрана (см. скриншот)

**Окружение**

Браузер : Chrome (70.0.3538.75)
Устройство: iPhone 8+ (iOS 12.1)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/73498686/97805692-c871a680-1c68-11eb-853e-fc23e58f6e0e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
