### ISSUE TITLE
При просмотре мобильной версии сайта текст наезжает на картинку.

### ISSUE THREAD

**Issue by blackartqa** [netology-code/git-homeworks-neuro-issues#2057]
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст хорошо читается, не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 7 (iOS 14.1)
* Браузер: Chrome (86.0.4240.93)

#### Скриншоты
![bug1](https://user-images.githubusercontent.com/73709065/97806786-6ddb4900-1c6e-11eb-9394-e1a12c2c619d.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
