### ISSUE TITLE
Форма обратной связи слишком сжата по ширине

### ISSUE THREAD

**Issue by blackartqa** [netology-code/git-homeworks-neuro-issues#2058]
### Описание
Форма обратной связи слишком сжата по ширине при просмотре мобильной версии
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере
2. Пролистать страницу до блока "Оставайтесь на связи"
#### Ожидаемый результат
Блок отображается ровно, текст хорошо читается, слова не переносятся по частям
#### Фактический результат
Блок сжат по ширине, слова переносятся по частям (см. скриншот)
#### Программное окружение
* Устройство: iPhone 7 (iOS 14.1)
* Браузер: Chrome (86.0.4240.93) 
#### Скриншот
![bug2](https://user-images.githubusercontent.com/73709065/97807229-b3991100-1c70-11eb-8993-1e1dff71d3ff.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
