### ISSUE TITLE
Ошибка отображения. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

### ISSUE THREAD

**Issue by Netology-Korolchuk** [netology-code/git-homeworks-neuro-issues#206]
@solarrust

### Описание проблемы

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![pic](https://user-images.githubusercontent.com/24487390/67615229-e43fa280-f7f3-11e9-8cdd-a17cfaa895d1.png)
![pic2](https://user-images.githubusercontent.com/24487390/67615249-279a1100-f7f4-11e9-9c65-dc00c8cb2db9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
