### ISSUE TITLE
Исправить форму обратной связи

### ISSUE THREAD

**Issue by MarinaKoshkina** [netology-code/git-homeworks-neuro-issues#2060]
**Страница контактов. Слишком узкая форма обратной связи**

**Шаги по воспроизведению**

1. Открыть страницу контактов веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока сбора координат для обратной связи

**Ожидаемый результат**
Форма размерами ВхШ=190х690px

**Фактический результат**
Форма размерами ВхШ=690х190px (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
@solarrust 

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/67952425/97881752-d8a28800-1d33-11eb-955c-0d93b36051ce.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
