### ISSUE TITLE
Страница лендинга. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by yukurbatova** [netology-code/git-homeworks-neuro-issues#2061]
**Шаги:**

1. Открыть страницу лендинга NeuroStartUp в мобильном браузере.
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение.
**Фактический результат:**
Текст наезжает на изображение (см. скриншот).

**Окружение:**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты:**

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/72889535/97895163-7aca6c00-1d44-11eb-9a0e-10dec063033f.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
