### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by dimka1993kh** [netology-code/git-homeworks-neuro-issues#2062]
@solarrust
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат:

- Текст не наезжает на изображение

Фактический результат:

- Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)

Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/42633736/97902526-cd108a80-1d4e-11eb-9c8e-5ab166ede414.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
