### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by dimka1993kh** [netology-code/git-homeworks-neuro-issues#2063]
@solarrust

**Шаги по воспроизведению**

- Открыть страницу с формой обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

Ожидаемый результат

- Форма обратной связи по ширине страницы

Фактический результат

- Форма обратной связи сжата

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/42633736/97902936-588a1b80-1d4f-11eb-9522-62df21e8cac2.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
