### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by FlyingDog265** [netology-code/git-homeworks-neuro-issues#2064]
@solarrust для инфо

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![46](https://user-images.githubusercontent.com/44607099/97911800-ed474600-1d5c-11eb-91ed-7f62413a8f70.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
