### ISSUE TITLE
Форма обратной связи. В верстке блока "Оставайтесь на связи" поломан перенос текста

### ISSUE THREAD

**Issue by FlyingDog265** [netology-code/git-homeworks-neuro-issues#2065]
@solarrust для инфо

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока ""Оставайтесь на связи""

#### Ожидаемый результат

Текст отображается без переносов слогов

#### Фактический результат

Текст переносит слова на другие строки по слогам (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![47](https://user-images.githubusercontent.com/44607099/97912320-b6256480-1d5d-11eb-840a-f05dc1a6ed2a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
