### ISSUE TITLE
Белый текст наезжает на картинку в мобильном браузере

### ISSUE THREAD

**Issue by Stanislav652** [netology-code/git-homeworks-neuro-issues#2066]
@solarrust

### **Описание проблемы**

Главная страница.
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

_Шаги по воспроизведению_
1. Открыть главную страницу сайта NeuroStartUp в мобильном браузере Opera Mobile
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
![Scr1](https://user-images.githubusercontent.com/67161493/97980151-62f4f580-1de1-11eb-85a6-046999733d20.png)

Текст наезжает на изображение (см. скриншот)

_Программное окружение_
Устройство: Honor 8S (Android 9)
Браузер: Opera Mobile (12)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
