### ISSUE TITLE
Рамка для информации с обратной связью пользователю слишком сжата

### ISSUE THREAD

**Issue by Stanislav652** [netology-code/git-homeworks-neuro-issues#2067]
@solarrust

### Описание проблемы

_Страница с обратной связью пользователю_
Рамка, в которой помещается информация с обратной связью пользователю имеет очень маленькие размеры. 
Текстовый блок "Оставайтесь на связи" помещается в рамке только с переносом слов. 

### Шаги по воспроизведению

1. Открыть главную страницу сайта NeuroStartUp в мобильном браузере Opera Mobile
2. Ввести исходные данные
3. Отправить запрос на исполнение.

### Ожидаемый результат
Текст равномерно распределяется в рамке без переноса слов

### Фактический результат
Текст распределяется в рамке с переносом слов

Программное окружение
Устройство:  Honor 8S (Android 9)
Браузер: Opera Mobile (12)

![Scr2](https://user-images.githubusercontent.com/67161493/97982902-7dc96900-1de5-11eb-8c03-ee3ca050b807.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
