### ISSUE TITLE
Страница лендинга. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by yukurbatova** [netology-code/git-homeworks-neuro-issues#2068]
**Шаги по воспроизведению:**
1. Открыть страницу лендинга NeuroStartUp в мобильном браузере.
2. Пролистать страницу до блока "Оставайтесь на связи".

**Ожидаемый результат:**
Форма обратной связи адаптирована под размеры экрана.  

**Фактический результат:**
Форма обратной связи слишком сжата  (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты:**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/72889535/97984796-51631c00-1de8-11eb-9376-d08e712a581a.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
