### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Vesnushkka** [netology-code/git-homeworks-neuro-issues#2070]
@solarrust 
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи 

**Ожидаемый результат**
Форма обратной связи занимает не менее 70% страницы.

**Фактический результат**
Форма обратной связи слишком сжата для ее корректного заполнения

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/70434801/98111078-e4bc5000-1ec1-11eb-90b0-e8c858b567aa.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
