### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ShirenkovRP** [netology-code/git-homeworks-neuro-issues#2072]
**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Перейти к блоку обратной связи.

**Ожидаемый результат:**
Форма обратной связи отображается корректно.

**Фактический результат:**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

@solarrust

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/73740432/98113350-96ed1b00-1eb4-11eb-9f2e-19625522d6b8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
