### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Otmorozded** [netology-code/git-homeworks-neuro-issues#2074]
**Шаги по воспроизведению:**

1. Открыть страницу лендинга NeuroStartUp в мобильном браузере.
2. Пролистать страницу до блока "Оставайтесь на связи".

**Ожидаемый результат:**
Содержимое формы обратной связи адаптировано под размеры экрана.

**Фактический результат:**
Содержимое формы обратной связи слишком сжато (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

**Скриншот:**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/73711937/98129255-f9044b00-1ec9-11eb-93b5-ee791c2b023e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
