### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by AlenaChimiris** [netology-code/git-homeworks-neuro-issues#2075]
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

**Скриншот**
![скриншот](https://user-images.githubusercontent.com/72695738/98129947-c575f080-1eca-11eb-800a-eaac47f9bc02.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
