### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AlenaChimiris** [netology-code/git-homeworks-neuro-issues#2076]
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Форма обратной связи не сжата.

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

**Скриншоты**
![скриншот2](https://user-images.githubusercontent.com/72695738/98133289-7467fb80-1ece-11eb-8b6b-f2f325192ac9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
