### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by nmarenova** [netology-code/git-homeworks-neuro-issues#2079]
### **Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/38073854/98244007-ca48ac00-1f7f-11eb-8782-5c78152c0a0e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
