### ISSUE TITLE
Страница лендинга. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by nmarenova** [netology-code/git-homeworks-neuro-issues#2080]
### **Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока с обратной связью

**Ожидаемый результат**
Форма обратной связи не сжата

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![image](https://user-images.githubusercontent.com/38073854/98244546-ac2f7b80-1f80-11eb-9dd4-93f8e519599d.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
