### ISSUE TITLE
На главной странице текстовый блок "Воспользуйтесь.." накрывает изображение

### ISSUE THREAD

**Issue by Alymar24** [netology-code/git-homeworks-neuro-issues#2081]
@solarrust обрати внимание

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

- _Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome_

- _Пролистать страницу до блока "Воспользуйтесь современными возможностями..."_

**Ожидаемый результат**
Изображение расположено ниже текста

**Фактический результат**
Текст расположен на изображении (см. скриншот)

**Программное окружение**
Устройство: Asus ZB602KL (Android 9)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/73124717/98247699-09c5c700-1f85-11eb-876d-829d6a8a3ea4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
