### ISSUE TITLE
Текст на форме обратной связи слишком сжат

### ISSUE THREAD

**Issue by Alymar24** [netology-code/git-homeworks-neuro-issues#2082]
@solarrust обрати внимание

**Шаги по воспроизведению**

_- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome_

_- Пролистать страницу до блока с обратной связью_

**Ожидаемый результат**
Форма обратной связи по размеру экрана 

**Фактический результат**
Форма обратной связи слишком сжата, текст сбит в центр

**Программное окружение**
Устройство: Asus ZB602KL (Android 9)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67 2](https://user-images.githubusercontent.com/73124717/98248707-5b228600-1f86-11eb-817e-4bcdcb5dc6b3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
