### ISSUE TITLE
Страница лендинга. Форма обратной связи сильно сжата

### ISSUE THREAD

**Issue by alekskudryashov** [netology-code/git-homeworks-neuro-issues#2086]
@solarrust 

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока с обратной связью

#### Ожидаемый результат

Форма обратной связи имеет нормальную ширину

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/QGiHInk.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
