### ISSUE TITLE
Главная страница. Текст наезжает на картинку.

### ISSUE THREAD

**Issue by mercuriaal** [netology-code/git-homeworks-neuro-issues#2089]
@solarrust 
**Шаги по воспроизведению**
 1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
 1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на сообщение (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншот**

![Наезд текста](https://user-images.githubusercontent.com/73745216/98286286-d0a54b00-1fb4-11eb-8249-9c6aa76821bf.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
