### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by mercuriaal** [netology-code/git-homeworks-neuro-issues#2090]
@solarrust 

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма обратной связи не сжата, слова не разбиваются на несколько строчек.

**Фактический результат**
Форма обратной связи сжата, трудночитаема.

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншот**

![Обратная связь](https://user-images.githubusercontent.com/73745216/98287244-23333700-1fb6-11eb-9e49-848a9368999a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
