### ISSUE TITLE
Текст наезжает на картинку на главной странице

### ISSUE THREAD

**Issue by DariaPap** [netology-code/git-homeworks-neuro-issues#2091]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными ..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение 

#### Программное окружение

* Устройство: Honor 10, Col-L29
* OS: Android 9
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HJ1VbMj.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
