### ISSUE TITLE
Деформирована форма обратной связи

### ISSUE THREAD

**Issue by DariaPap** [netology-code/git-homeworks-neuro-issues#2092]
@solarrust 
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока Обратной связи

#### Ожидаемый результат

Форма  соответствует размерам страницы

#### Фактический результат

Форма сжата относительно размера экрана

#### Программное окружение

* Устройство: Honor 10
* OS: Android 9
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![scrnli_05-11-2020_23-40-16](https://user-images.githubusercontent.com/72595236/98294047-55499680-1fc0-11eb-8ddb-6efc3215727c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
