### ISSUE TITLE
Деформирована форма обратной связи

### ISSUE THREAD

**Issue by cclawss** [netology-code/git-homeworks-neuro-issues#2094]
# Описание проблемы
@solarrust
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до блока Обратной связи

#### Ожидаемый результат

Форма соответствует размерам страницы

#### Фактический результат

Форма сжата относительно размера экрана (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![42e706e67](https://user-images.githubusercontent.com/51705840/98313241-374a5900-1ff5-11eb-89d8-7f70c4890be3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
