### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by mlobina** [netology-code/git-homeworks-neuro-issues#2095]
@solarrust
**Описание проблемы**
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/74069892/98411876-e9cafc00-2087-11eb-939f-eb0b2da53bd8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
