### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by mlobina** [netology-code/git-homeworks-neuro-issues#2096]
@solarrust
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Форма обратной связи..."

**Ожидаемый результат**
Форма соответствует размерам страницы

**Фактический результат**
Форма заполнения обратной связи слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/74069892/98412560-36630700-2089-11eb-9019-e7d25cf0aff3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
