### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by PGVlasov** [netology-code/git-homeworks-neuro-issues#21]
@solarrust

# Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

###  Ожидаемый результат

Текст не наезжает на изображение

### Фактический результат

Текст наезжает на изображение (см. скриншот)

### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![image](https://user-images.githubusercontent.com/47336018/52899823-876d0080-31ff-11e9-952c-f485188cbb3c.png)

**Comment by solarrust** [comment]
Great!
