### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ann-nikolich** [netology-code/git-homeworks-neuro-issues#2102]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Слова в тексте располагаются построчно, без переносов, уменьшить размер текста

#### Фактический результат

Текст выглядит сжатым (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![image](https://user-images.githubusercontent.com/63597918/98462126-c3f64200-21c2-11eb-8be1-9ea15d6a15d4.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
