### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by turaved** [netology-code/git-homeworks-neuro-issues#2104]
@solarrust 

### **Главная страница. Блок "Оставайтесь на связи" слишком сжат**
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Слова в тексте располагаются построчно, без переносов, уменьшить размер текста

**Фактический результат**
Текст выглядит сжатым (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/73443553/98463830-674d5400-21cf-11eb-8153-5bd5d4700d12.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
