### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Lulu0307** [netology-code/git-homeworks-neuro-issues#2105]
Шаги по воспроизведению
1.Открыть главную страницу веб-сайта NeuroStartUp на ПК в браузере Chrome
2.Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат:
Текст не наезжает на изображение

Фактический результат:
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: ноутбук Dell Inspiron 7000series,Windows 10
Браузер:Chrome Версия 86.0.4240.183 (Официальная сборка), (64 бит)
![текст наезжает](https://user-images.githubusercontent.com/65534532/98468512-5d4a4600-220d-11eb-9451-d940704e2719.png)
[](url)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
