### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by denisburnashev** [netology-code/git-homeworks-neuro-issues#2108]
### Главная страница. Блок "Оставайтесь на связи" слишком сжат

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Слова в тексте располагаются построчно, без переносов, уменьшить размер текста

**Фактический результат**
Текст выглядит сжатым (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/72780553/98469021-6a643680-2207-11eb-9730-f4fd28788514.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
