### ISSUE TITLE
Съехала верстка формы обратной связи

### ISSUE THREAD

**Issue by Lulu0307** [netology-code/git-homeworks-neuro-issues#2109]
Шаги по воспроизведению
1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат:
нормальная структурная разметка контента

Фактический результат:
Текст не выровнен, выглядит сжатым,

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![вторая проблема](https://user-images.githubusercontent.com/65534532/98469041-ef534e00-220f-11eb-8ead-2978fe9bf990.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
