### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by debaser276** [netology-code/git-homeworks-neuro-issues#2110]
# Описание проблемы
@solarrust 
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы "Оставайтесь на связи"
### Ожидаемый результат
Размер формы на ширину экрана
### Фактический результат
Форма слишком сжата (см. скриншот)
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![98469041-ef534e00-220f-11eb-8ead-2978fe9bf990](https://user-images.githubusercontent.com/46438629/98469221-4c8ad780-21ef-11eb-9483-139f81a44b6e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
