### ISSUE TITLE
Белый текст наезжает на белое изображение в мобильной версии сайта.

### ISSUE THREAD

**Issue by katerinavp** [netology-code/git-homeworks-neuro-issues#2114]
**@solarrust**

**Главная страница.**

Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

1. Открыть главную страницу сайта NeuroStartUp в мобильном браузере Opera Mobile
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: Samsung s10 (Android 9)
- Браузер: Opera Mobile (12)

**Скриншоты**

![3](https://user-images.githubusercontent.com/62348731/98481363-b82e6e00-220a-11eb-88ef-d86293b7acbc.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
