### ISSUE TITLE
Отступы блока "Оставайтесь на связи" не адаптируются под экран смартфона

### ISSUE THREAD

**Issue by Godexd** [netology-code/git-homeworks-neuro-issues#2116]
@solarrust 

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Блок "Оставайтесь на связи" адаптируется под размер экрана, занимая всю ширину страницы.
Зеленым отмечен ожидаемый размер блока (см. скриншот)

#### Фактический результат

Поля вокруг блока "Оставайтесь на связи" слишком широкие, они не адаптируется под размер экрана.
Красным отмечен фактический размер блока (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 13.4)
* Браузер: Chrome (73.0.3638.71)

#### Скриншоты

![](https://user-images.githubusercontent.com/38652462/98471330-7f879800-21fc-11eb-9a4a-f3080d07f9e7.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
