### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by maksimsar1** [netology-code/git-homeworks-neuro-issues#2119]
**Шаги про воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

[Фактический результат](https://camo.githubusercontent.com/5d3acce2b945789b7c0e6f68dbfd876a54fa134268e0965075afa96852451904/68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67)

Текст наезжает на изображение(см. скриншот)

**Программное обеспечение**

- Устройство android Xiaomi mi 10 pro версия 11.3
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![скрин](https://user-images.githubusercontent.com/71075228/98554753-87a60d00-22ba-11eb-82db-2294b1fd43ec.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
