### ISSUE TITLE
[Mobile] Форма обратной связи сжата.

### ISSUE THREAD

**Issue by z88m** [netology-code/git-homeworks-neuro-issues#212]
Assignees: @solarrust

# Описание проблемы

#### Форма обратной связи слишком узкая.
Проблема в: `<section id="contacts" class="pt-5 pb-5">`
xpatch: `/html/body/div/div/main/section[2]`

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи..."

#### Ожидаемый результат

Форма обратной связи занимает всю площадь экрана

#### Фактический результат

Форма сжата по центру (см. скриншот)

#### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![67484394-1bd60f80-f679-11e9-9ed6-f178684c35ea 1](https://user-images.githubusercontent.com/44113203/67623971-2ab4f180-f834-11e9-83b4-47f785ff5acd.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
