### ISSUE TITLE
Расширить форму обратной связи

### ISSUE THREAD

**Issue by Cooleekova** [netology-code/git-homeworks-neuro-issues#2121]
# Описание проблемы

#### Форма обратной связи. Блок с формой обратной связи слишком узкий

@solarrust

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Нажать на кнопку "Обратная связь"

#### Ожидаемый результат

Появляется форма для заполнения контактных данных,
форма нормальной ширины

#### Фактический результат

Форма появляется, но она слишком узкая

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншот

![](https://camo.githubusercontent.com/8b6aa0acc22de5c12c5a449f639cc7e430299d13757d046bf63f9f010175d210/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
