### ISSUE TITLE
Главная страница. Блок "Оставайтесь на связи" слишком сжат

### ISSUE THREAD

**Issue by maksimsar1** [netology-code/git-homeworks-neuro-issues#2122]
**Шаги по воспроизведению**

1.  Заходим на стартовую страницу
2. Вводим данные в поля заполнения  "формы обратной связи"

**Ожидаемый результат**

Данные вводятся  в одну строку, без переноса

**Фактический результат**

Поля заполнения узкие и данные отображаются в них не полностью [смотреть скриншот](https://user-images.githubusercontent.com/63597918/98462126-c3f64200-21c2-11eb-8be1-9ea15d6a15d4.png)

**Программное окружение**

- Устройство: Android 11.2 версия 12.02.1
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![форма заполнения](https://user-images.githubusercontent.com/71075228/98559228-cc807280-22bf-11eb-896f-4efd252b8212.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
