### ISSUE TITLE
Текстовый блок  на главной странице "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by AnastasiaKuznetzova** [netology-code/git-homeworks-neuro-issues#2127]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

*  Устройство: iPhone 7+ (iOS 13.6)
*  Браузер: Chrome (70.0.3538.75)

**Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/73876881/98666788-90e8b580-235e-11eb-92a0-1420b2d2f4b8.png)
**

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
