### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AnastasiaKuznetzova** [netology-code/git-homeworks-neuro-issues#2128]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу вниз до блока форма обратной связи

**Ожидаемый результат**
Форма развернута по ширине экрана, текст переносится по строкам, легко читается

**Фактический результат**
Форма слишком сжата, вытянута (см. скриншот)

**Программное окружение**
* Устройство: iPhone 7 (iOS 13.6)
* Браузер: Chrome (70.0.3538.75)
**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/73876881/98667628-b3c79980-235f-11eb-804a-a8443bd920d8.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
