### ISSUE TITLE
Главная страница NeuroStartUp, форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by vsvoronin** [netology-code/git-homeworks-neuro-issues#2130]
**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма обратной связи пропорциональна размерам страницы

**Фактический результат**
Форма сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/73753711/98707376-079ea680-2391-11eb-9207-e7ea52b9fa8f.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
