### ISSUE TITLE
Форма обратной связи слишком узкая

### ISSUE THREAD

**Issue by roman-pro18** [netology-code/git-homeworks-neuro-issues#2132]
#### Шаги по воспроизведению

1. Открыть форму обратной связи из главной страницы веб-сайта NeuroStartUp в мобильном браузере Chrome

#### Ожидаемый результат

Корректная форма обратной связи

####  Фактический результат

Форма сжата и тексту не хватает места в строках

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://camo.githubusercontent.com/8b6aa0acc22de5c12c5a449f639cc7e430299d13757d046bf63f9f010175d210/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
