### ISSUE TITLE
Текстовый блок располагается поверх изображения

### ISSUE THREAD

**Issue by fighxy** [netology-code/git-homeworks-neuro-issues#2135]
# Текстовый блок располагается поверх изображения
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
Текст не смещен поверх изображения
#### Фактический результат 
Текст наезжает на изображение (смотреть скриншот)
#### Программное окружение

- Устройство: Xiaomi Redmi Note 5 (Android 10)
- Браузер: Vivaldi (3.14)
### Скриншот
![ScreenshotDefect](https://camo.githubusercontent.com/5d3acce2b945789b7c0e6f68dbfd876a54fa134268e0965075afa96852451904/68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
