### ISSUE TITLE
Блок "Оставайтесь на связи" сильно сжат и вытянут вдоль страницы

### ISSUE THREAD

**Issue by fighxy** [netology-code/git-homeworks-neuro-issues#2136]
# Форма обратной связи чрезмерно сжата
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

#### Ожидаемый результат
Форма обратной связи располагается ровно, не сжата
#### Фактический результат 
Форма обратной связи вытянута вдоль и сильно сжата (смотреть скриншот)
#### Программное окружение

- Устройство: Xiaomi Redmi Note 5 (Android 10)
- Браузер: Vivaldi (3.14)
### Скриншот
![ScreenshotDefect](https://camo.githubusercontent.com/8b6aa0acc22de5c12c5a449f639cc7e430299d13757d046bf63f9f010175d210/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
