### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Rina-gradova** [netology-code/git-homeworks-neuro-issues#2137]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![image](https://user-images.githubusercontent.com/73775853/98853902-e316fd00-246a-11eb-9e5b-19a2546610f2.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
