### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Rina-gradova** [netology-code/git-homeworks-neuro-issues#2138]
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"
**Ожидаемый результат**
Форма обратной связи занимает всю страницу

**Фактический результат**
Форма сжата с боков(см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![image](https://user-images.githubusercontent.com/73775853/98854352-7e0fd700-246b-11eb-996d-c1d7fbb6833e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
