### ISSUE TITLE
Проблемы с формой обратной связи

### ISSUE THREAD

**Issue by LeoSibiryakov** [netology-code/git-homeworks-neuro-issues#214]
# Форма обратной связи

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.  Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат 
Форма растянута по всей длине страницы 

### Фактический результат (см. скриншот)
![Forms](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

#### Программное окружение

1. Устройство: iPhone 8+ (iOS 12.1)
2. Браузер: Chrome (70.0.3538.75)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
