### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Dyubo** [netology-code/git-homeworks-neuro-issues#2141]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![проблема 1](https://user-images.githubusercontent.com/73828936/98931682-27081180-2500-11eb-857d-1afc793dfc2b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
