### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Dyubo** [netology-code/git-homeworks-neuro-issues#2142]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![Проблема 2](https://user-images.githubusercontent.com/73828936/98931765-43a44980-2500-11eb-86bb-db674e9898d6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
