### ISSUE TITLE
Форма обратной связи "Оставайтесь на связи"  слишком сжата.

### ISSUE THREAD

**Issue by ghost** [netology-code/git-homeworks-neuro-issues#2144]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Адаптированный блок под мобильные устройства

**Фактический результат**

Форма обратной связи сжата

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![изображение](https://user-images.githubusercontent.com/73724117/99010379-57cd6280-2563-11eb-8dab-be96c36bd4e5.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
