### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by IbragimovaRoksana** [netology-code/git-homeworks-neuro-issues#2146]
**Главная страница. Блок обратной связи "Оставайтесь на связи" слишком сжат, в результате чего текст отображается некорректно**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Нажать на кнопку "Оставайтесь на связи"

**Ожидаемый результат**
Форма обратной связи растянута по ширине и текст отображается нормально

**Фактический результат**
Форма не на всю ширину экрана, текст переносится некорректно на следующую строку (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/73775733/99067009-bdedd000-25cb-11eb-81e1-7783328fca66.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
