### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by anvartdinovtimurlinux** [netology-code/git-homeworks-neuro-issues#215]
@solarrust
# Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

* Устройство: Xiaomi MI MAX 3 (Android 9 PKQ1.181007.001)
* Браузер: Chrome (77.0.3865.116)

**Скриншоты**

![Ошибка](https://user-images.githubusercontent.com/39489844/67638360-bbeb9d00-f8f4-11e9-8447-7a951dbc829e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
