### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by g00dv1n1** [netology-code/git-homeworks-neuro-issues#2151]
**Шаги по воспроизведению:**

1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение

**Фактический результат:**
Текст наезжает на изображение (см. скриншот)

**Программное окружение:**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/73695656/99082462-3ad17780-25d5-11eb-8b4f-1ade6befe6dd.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
