### ISSUE TITLE
Оставайтесь на связи Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by g00dv1n1** [netology-code/git-homeworks-neuro-issues#2152]
@solarrust

**Описание проблемы**
Главная страница. Форма обратной связи слишком сжата
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи."
**Ожидаемый результат**
Текст распределен по ширине страницы и выровнен по центру страницы

**Фактический результат
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/73695656/99083022-fbeff180-25d5-11eb-980a-603a72732b44.png)
**
Текст сжат по центру страницы с переносом части слов на другие строки (см.скриншот)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
