### ISSUE TITLE
Проблема: Текст наезжает на Изображение

### ISSUE THREAD

**Issue by KirillGu** [netology-code/git-homeworks-neuro-issues#2153]
В браузере Комп. версии все хорошо

Как только мы открываем в мобильном браузере, то текст начинает наезжать на изображение (см.ниже)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![Снимок экрана 2020-11-13 в 18 13 10](https://user-images.githubusercontent.com/74116335/99088044-89cedb00-25dc-11eb-8ee6-cc0cb7ad5c3c.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
