### ISSUE TITLE
Текст обратной связи слишком сжат

### ISSUE THREAD

**Issue by KirillGu** [netology-code/git-homeworks-neuro-issues#2154]
Описание проблемы:
Главная страница. Форма обратной связи слишком сжата

Шаги по воспроизведению:
Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи."

Ожидаемый результат:
Текст распределен по ширине страницы и выровнен по центру страницы

Фактический результат (см.ниже)
![Снимок экрана 2020-11-13 в 18 13 21](https://user-images.githubusercontent.com/74116335/99088764-82f49800-25dd-11eb-8722-fc1e94ac411e.png)
 @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
