### ISSUE TITLE
Текст наезжает на картинку на главной странице

### ISSUE THREAD

**Issue by Vilkelis** [netology-code/git-homeworks-neuro-issues#2155]
# Описание проблемы

#### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Надеюсь, что @solarrust поможет в решении этой задачи

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![image](https://user-images.githubusercontent.com/1661936/99101802-ecd16980-25fe-11eb-9756-7de5f065978e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
