### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Vilkelis** [netology-code/git-homeworks-neuro-issues#2156]
# Описание проблемы

#### Главная страница.  Из-за слишком больших отступов слева и справа на мобильных устройствах форма выглядет слишком сжатой.

Этот баг без проблем вам поможет воспроизвести @solarrust 

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..." (в самом низу страницы)

#### Ожидаемый результат

Форма обратной связи адаптируется при изменении размера экрана и выглядит нормально на экранах мобильных устройств

#### Фактический результат

Форма на мобильных устройствах выглядит слишком сжатой по бокам  (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![image](https://user-images.githubusercontent.com/1661936/99102227-987ab980-25ff-11eb-97cd-9010fd45f563.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
