### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by ILiaBer** [netology-code/git-homeworks-neuro-issues#2157]
**Главаная страница. Текст находится на картинке**

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение 

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/73795748/99110999-59973480-25fc-11eb-86c1-c43e13984c19.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
