### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ILiaBer** [netology-code/git-homeworks-neuro-issues#2158]
****На главной странице форма обратной связи выглядит слишком сжатой****

**Шаги по воспроизведению**

- Открыть главную страницу NeuroStartUp в мобильном браузере Chrome
- Обратить внимание на расположение функции" Оставайтесь с нами"

Ожидаемый результат
Форма обратной связи выглядит в таком же, как и вся остальная информация, но выделяется только за счёт белого фона

Фактический результат
Форма сжата

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот:
![image](https://user-images.githubusercontent.com/73795748/99111734-b34c2e80-25fd-11eb-8f6b-ec3713829f32.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
