### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by anvartdinovtimurlinux** [netology-code/git-homeworks-neuro-issues#216]
@solarrust
# Описание проблемы
**Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**

Верстка формы должна быть адаптирована под размер экрана.

**Фактический результат**

Форма слишком сжата (см. скриншот).

**Программное окружение**

* Устройство: Xiaomi MI MAX 3 (Android 9 PKQ1.181007.001)
* Браузер: Chrome (77.0.3865.116)

**Скриншоты**

![Ошибка](https://user-images.githubusercontent.com/39489844/67638460-9d39d600-f8f5-11e9-8d9b-1a65888b1749.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
