### ISSUE TITLE
текст наезжает на картинку

### ISSUE THREAD

**Issue by San4ez63** [netology-code/git-homeworks-neuro-issues#2161]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
@solarrust

**Шаги по воспроизведению**:
1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.Пролистать страницу до блока "Воспользуйтесь современными возможностями..." 

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![issue](https://user-images.githubusercontent.com/73838348/99147699-7125fa00-269c-11eb-9ff7-fd36c0ee54ba.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
