### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by San4ez63** [netology-code/git-homeworks-neuro-issues#2162]
**На главной странице форма обратной связи выглядит слишком сжата**
@solarrust

**Шаги по воспроизведению**
1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Текст формы обратной связи выровнен по всей ширине ширине страницы 

**Фактический результат**
Текст формы обратной связи слишком сжат (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

скриншот
![issue 2](https://user-images.githubusercontent.com/73838348/99147956-52c0fe00-269e-11eb-96a1-5581cfdc81e2.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
