### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Gennadii8** [netology-code/git-homeworks-neuro-issues#2166]
@solarrust, нужно поправить.
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Нажать на кнопку "Оставайтесь на связи"

### Ожидаемый результат
Форма обратной связи растянута по ширине и текст отображается нормально
### Фактический результат
Форма не на всю ширину экрана, текст переносится некорректно на следующую строку (см. скриншот)
### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![image](https://user-images.githubusercontent.com/71780285/99179657-d3303f00-2730-11eb-84a0-df8a2e928d61.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
