### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

### ISSUE THREAD

**Issue by evgen-911** [netology-code/git-homeworks-neuro-issues#2167]
@solarrust 
**Шаги по воспроизведению**
1) Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2) Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение 

**Программное окружение**
Устройство: Samsung А50, Android 10
Браузер: Chrome (86.0.0.4240.110)

**Скриншот**
![image](https://user-images.githubusercontent.com/74135195/99187396-6edca200-2767-11eb-847c-f1632d93ce55.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
