### ISSUE TITLE
Форма "Оставайтесь на связи" слишком сжата

### ISSUE THREAD

**Issue by evgen-911** [netology-code/git-homeworks-neuro-issues#2168]
@solarrust 

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма расположена по всей ширине экрана, расположение текста по центру.

**Фактический результат**
Форма сжата, текст съехал (см. скриншот)

**Программное окружение**
Устройство: Samsung А50, Android 10
Браузер: Chrome (86.0.0.4240.110)

**Скриншот**
![image](https://user-images.githubusercontent.com/74135195/99188251-08a64e00-276c-11eb-9fbc-f3b906749913.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
