### ISSUE TITLE
Главная страница, проблемы с текстовым блоком

### ISSUE THREAD

**Issue by Kresnov** [netology-code/git-homeworks-neuro-issues#217]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Устройство: Samsung Galaxy S8 (Android 9 PKQ1.181007.001)
Браузер: Chrome (77.0.3865.116)

**Скриншоты**
![67638360-bbeb9d00-f8f4-11e9-8447-7a951dbc829e](https://user-images.githubusercontent.com/54814954/67642238-b30dc200-f91a-11e9-9759-3bcda0fd43a1.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
