### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AnastasiaButova** [netology-code/git-homeworks-neuro-issues#2170]
@solarrust

### Главная страница. Форма "Оставайтесь на связи" слишком сжата

1.     Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.     Пролистать страницу до формы "Оставайтесь на связи"

**Ожидаемый результа**

Форма подгоняется под размер экрана
**Фактический результат**

Форма слишком узкая

 (см. скриншот)
_Программное окружение_

 
-    Устройство: iPhone 8+ (iOS 12.1)
-     Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/74089784/99189428-3393a080-2772-11eb-8692-b53909a00897.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
