### ISSUE TITLE
Главная страница. Текстовый блок наезжает на картинку

### ISSUE THREAD

**Issue by AleksandraArt** [netology-code/git-homeworks-neuro-issues#2171]
Шаги по воспроизведению:

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями...

Ожидаемый результат:
Текст не наезжает на изображение

Фактический результат:
Текст наезжает на изображение (см. скриншот)

Программное окружение:

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
  ![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/73740859/99190898-617ce300-277a-11eb-90dc-166b0b446b01.png)
 @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
