### ISSUE TITLE
Форма обратной связи сжата 

### ISSUE THREAD

**Issue by AleksandraArt** [netology-code/git-homeworks-neuro-issues#2172]
@solarrust 

Шаги по воспроизведению

1. Открыть главную страницу NeuroStartUp через мобильный браузер Chrome
2. Пролистать главную страницу до блока "Оставайтесь на связи"

Ожидаемый результат
Форма расположена по ширине экрана, текст расположен по центру

Фактический результат 
Текст в форме сжат (см. скриншот)

Окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/73740859/99191375-6d1dd900-277d-11eb-8da7-6370119164dd.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
