### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AntonVeldin** [netology-code/git-homeworks-neuro-issues#2174]
@solarrust 

**Шаги по воспроизведению:**
 * Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
 * Пролистать страницу до Формы обратной связи

**Ожидаемый результат:**
Форма обратной связи отображается корректно

**Фактический результат:**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение:**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот:**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/74303169/99253907-41722000-285d-11eb-81e2-3d2b359510b4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
