### ISSUE TITLE
Проблемы с формой обратной связи

### ISSUE THREAD

**Issue by Kishinskiy** [netology-code/git-homeworks-neuro-issues#2176]
# Описание проблемы

### Сжатая форма обратной связи

@solarrust Вторая проблема

#### Шаги по воспроизведению

Открыть главную страницу NeuroStartUp через мобильный браузер Chrome
Пролистать главную страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма расположена по ширине экрана, текст расположен по центру

#### Фактический результат

Текст в форме сжат (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://github.com/Kishinskiy/nitologi-issue/raw/main/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
