### ISSUE TITLE
Проблема - Текст наезжает на картинку

### ISSUE THREAD

**Issue by irlen3** [netology-code/git-homeworks-neuro-issues#2177]
# Описание проблемы
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![image](https://user-images.githubusercontent.com/69305644/99395864-51cbde80-28e1-11eb-9158-26434126044f.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
