### ISSUE TITLE
Проблема - Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by irlen3** [netology-code/git-homeworks-neuro-issues#2178]
# Описание проблемы
#### Шаги по воспроизведению
1. Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до конца для просмотра формы 

#### Ожидаемый результат
Форма обратной связи не сжата

#### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![image](https://user-images.githubusercontent.com/69305644/99397396-4da0c080-28e3-11eb-97ee-c22cdec1521d.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
