### ISSUE TITLE
Проблемы при просмотре лендинга на веб-сайте

### ISSUE THREAD

**Issue by German200597** [netology-code/git-homeworks-neuro-issues#2179]
# Описание проблемы  #

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**

Текст не наезжает на изображение

**Фактический результат:**

Текст наезжает на изображение (см. скриншот)

**Программное окружение:**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

[@solarrust](url)

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/63213547/99559152-83be6d00-29d5-11eb-8cfd-656c98d65564.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
