### ISSUE TITLE
Проблема с формой обратной связи

### ISSUE THREAD

**Issue by Kresnov** [netology-code/git-homeworks-neuro-issues#218]
Форма обратной связи слишком сжата.

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**

Верстка формы должна быть адаптирована под размер экрана.

**Фактический результат**

Форма слишком сжата (см. скриншот).

**Программное окружение**

Устройство: Samsung Galaxy S8 (Android 9 PKQ1.181007.001)
Браузер: Chrome (77.0.3865.116)

**Скриншоты**
![67638460-9d39d600-f8f5-11e9-8d9b-1a65888b1749](https://user-images.githubusercontent.com/54814954/67642286-30d1cd80-f91b-11e9-8234-9cf3a11eb5d3.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
