### ISSUE TITLE
Проблема формы обратной связи

### ISSUE THREAD

**Issue by German200597** [netology-code/git-homeworks-neuro-issues#2180]
## Описание проблемы ##

Форма обратной связи слишком сжата

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока " Обратная связь "

**Ожидаемый результат**

Форма растянута на всю страницу

**Фактический результат**

Форма стянута к центру

**Программное окружение**

Устройство: Mac Book 
Браузер: Safari

Кто должен решить: 
[@solarrust](url)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63213547/99560888-6f7b6f80-29d7-11eb-9e0e-737e9a6efb79.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
