### ISSUE TITLE
Текст наезжает на картинку. Главная страница.

### ISSUE THREAD

**Issue by AndreyE-lance** [netology-code/git-homeworks-neuro-issues#2181]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншоты 
![Issue1](https://user-images.githubusercontent.com/51997645/99661175-46191d00-2a85-11eb-884f-925d8730e1f4.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
