### ISSUE TITLE
Форма обратной связи слишком сжата. Главная страница

### ISSUE THREAD

**Issue by AndreyE-lance** [netology-code/git-homeworks-neuro-issues#2182]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока обратной связи.

### Ожидаемый результат
Сделать блок адаптируемым к ширине экрана.

### Фактический результат
Блок обратной связи слишком сильно сжат (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншоты
![Issue2](https://user-images.githubusercontent.com/51997645/99661817-34844500-2a86-11eb-8df4-9b0a32a4708d.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
