### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Mortiferus** [netology-code/git-homeworks-neuro-issues#2187]
@solarrust

**Описание проблемы**

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

    1)Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    2)Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма обратной связи располагается равномерно по ширине экрана

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60236568/99698284-a5852600-2aa1-11eb-9d60-09c8195cf8f7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
