### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by baturina** [netology-code/git-homeworks-neuro-issues#2188]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/74075776/99709427-39f68500-2ab0-11eb-831f-d7a3ac7914c6.png)

- @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
