### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." на главной странице наезжает на изображение

### ISSUE THREAD

**Issue by AlexPopov487** [netology-code/git-homeworks-neuro-issues#2191]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
@solarrust  Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/74566663/99850865-f418ea00-2b9f-11eb-9376-2f8d7edd6d08.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
