### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by AlexPopov487** [netology-code/git-homeworks-neuro-issues#2192]
### Шаги по воспроизведению
Открыть страницу формы обратной связи

### Ожидаемый результат
@solarrust Исправленное форматирование страницы

### Фактический результат
Страница слижком сжата (см. скриншот)

### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/74566663/99851488-13fcdd80-2ba1-11eb-8a0e-533bd4673973.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
