### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by jmatytsina** [netology-code/git-homeworks-neuro-issues#2193]
## **Описание проблемы**
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

### **Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### **Ожидаемый результат**
Текст не наезжает на изображение

### **Фактический результат**
Текст наезжает на изображение (см. скриншот)
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/22019254/99900625-4dd5fd00-2ce3-11eb-80aa-3be7908b6e01.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
