### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by jmatytsina** [netology-code/git-homeworks-neuro-issues#2194]
## **Описание проблемы**
Главная страница. Форма обратной связи слишком сжата.

### **Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока обратной связи

### **Ожидаемый результат**
Форма обратной связи соответствует корректному отображению в браузере.

### **Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/22019254/99900917-6e06bb80-2ce5-11eb-8b87-443416be3baf.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
