### ISSUE TITLE
Форма обратной связи сжата 

### ISSUE THREAD

**Issue by fedoseevatatyana** [netology-code/git-homeworks-neuro-issues#2196]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть ссылку обратная связь

#### Ожидаемый результат

Форма отображается корректно

#### Фактический результат

Форма отображается не во всю ширину (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![image](https://user-images.githubusercontent.com/74595766/99985702-57cd2e00-2dbf-11eb-9c7a-af5de75f7aa0.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
