### ISSUE TITLE
Проблемы с формой обратной связи!

### ISSUE THREAD

**Issue by NickChirgin** [netology-code/git-homeworks-neuro-issues#220]
@solarrust 
# Форма обратной связи слишком сжата.
### Шаги по воспроизведению
> 1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
> 2. Пролистать страницу до блока Форма обратной связи
### Ожидаемый результат
Форма обратной связи занимает всю ширину страницы.
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![](https://user-images.githubusercontent.com/52864045/63690104-7b987180-c814-11e9-91fb-6431e8debbf5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
