### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by itrm000** [netology-code/git-homeworks-neuro-issues#2200]
# Описание проблемы

Форма обратной связи слишком сжата

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

#### Ожидаемый результат

Форма соответствует размерам страницы

#### Фактический результат

Форма заполнения обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://user-images.githubusercontent.com/69457725/96456883-c995e300-1227-11eb-83ef-21aaceddcee0.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
