### ISSUE TITLE
Описание проблемы

### ISSUE THREAD

**Issue by Sergey55rex** [netology-code/git-homeworks-neuro-issues#2201]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в  браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Кликнуть правой клавишей мышки на странице, в всплывающем меню выбрать "просмотреть код".  Выбрать просмотр в режиме мобильного устройства.
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение

Браузер: Chrome (70.0.3538.75)
Скриншоты
 
![Скрин1](https://user-images.githubusercontent.com/74469795/99998306-881cc880-2dcf-11eb-854b-d57aab3dd8b0.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
