### ISSUE TITLE
Описание проблемы

### ISSUE THREAD

**Issue by Sergey55rex** [netology-code/git-homeworks-neuro-issues#2202]
Главная страница. Форма обратной связи слишком сжата
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
Пролистать страницу до блока "Форма обратной связи"
Кликнуть правой клавишей мышки на странице, в всплывающем меню выбрать "просмотреть код". Выбрать просмотр в режиме мобильного устройства.
Ожидаемый результат
Форма обратной связи удобна в использовании

Фактический результат
Форма обратной связи слишком сжат (см. скриншот)

Программное окружение

Браузер: Chrome (70.0.3538.75)
Скриншоты
![скрин 2](https://user-images.githubusercontent.com/74469795/100000373-902a3780-2dd2-11eb-8cdb-ee890de66d1d.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
