### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

### ISSUE THREAD

**Issue by AlexPahomov** [netology-code/git-homeworks-neuro-issues#2203]
Шаги по воспроизведению

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)
![image](https://user-images.githubusercontent.com/74317221/100008313-5101e380-2dde-11eb-8f50-573a8eb3c920.png)

Программное окружение
Устройство: ПК, Windows 8.1 64-bit
Браузер: Chrome (86.0.4240.198)

Кто должен решить:
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
