### ISSUE TITLE
Форма "Оставайтесь на связи" слишком сжата

### ISSUE THREAD

**Issue by AlexPahomov** [netology-code/git-homeworks-neuro-issues#2204]
Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат
Форма расположена по всей ширине экрана, расположение текста по центру.

Фактический результат
Форма сжата, текст съехал (см. скриншот)
![image](https://user-images.githubusercontent.com/74317221/100009461-01bcb280-2de0-11eb-9d41-bf367f96ea73.png)

Программное окружение
Устройство: ПК, Windows 8.1 64-bit,
Браузер: Chrome (86.0.0.4240.198)

Кто должен решить:
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
