### ISSUE TITLE
Главная страница. Текст "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by KirillovAlexander** [netology-code/git-homeworks-neuro-issues#2205]
**Шаги по воспроизведению:** 
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: Redmi Note 9 Pro (MIUI Global 12.0.1)
* Браузер: Chrome (86.0.4240.110)

**Скриншоты:** 
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/35372327/100088562-5f451380-2e61-11eb-8d27-fad491d71b14.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
