### ISSUE TITLE
Форма "Оставайтесь на связи" слишком сжата

### ISSUE THREAD

**Issue by KirillovAlexander** [netology-code/git-homeworks-neuro-issues#2206]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат:**
Форма расположена по всей ширине экрана, расположение текста по центру.

**Фактический результат:**
Форма сжата, текст съехал (см. скриншот)

**Скриншот:**
![100009461-01bcb280-2de0-11eb-9d41-bf367f96ea73](https://user-images.githubusercontent.com/35372327/100088861-d9759800-2e61-11eb-9a02-40e6a211be98.png)

**Программное окружение:**
Устройство: Redmi Note 9 Pro (MIUI 12.0.1)
Браузер: Chrome (86.0.0.4240.110)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
