### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by DaniilOrlov96** [netology-code/git-homeworks-neuro-issues#2207]
**Шаги по воспроизведению:**

**1.** Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
**2.** Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты:**

![](https://user-images.githubusercontent.com/35372327/100088562-5f451380-2e61-11eb-8d27-fad491d71b14.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
