### ISSUE TITLE
Форма "Оставайтесь на связи" слишком сжата

### ISSUE THREAD

**Issue by DaniilOrlov96** [netology-code/git-homeworks-neuro-issues#2208]
**Шаги** **по** **воспроизведению:**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат:**
Форма расположена по всей ширине экрана, расположение текста по центру.

**Фактический результат:**
Форма сжата, текст съехал (см. скриншот)

![](https://camo.githubusercontent.com/8b6aa0acc22de5c12c5a449f639cc7e430299d13757d046bf63f9f010175d210/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
