### ISSUE TITLE
На главной странице текст наезжает на картинку.

### ISSUE THREAD

**Issue by ZabelinsA** [netology-code/git-homeworks-neuro-issues#221]
@solarrust
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.**

**Шаги по воспроизведению**:

    1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**:
Текст не наезжает на изображение.

**Фактический результат**:
Текст наезжает на изображение (см. скриншот).

**Программное окружение**

    * Устройство: iPhone 8+ (iOS 12.1)
    * Браузер: Chrome (70.0.3538.75)

**Скриншоты**;
![изображение](https://user-images.githubusercontent.com/56668958/67687227-0fb7be00-f9a9-11e9-837c-2a7f74b0c2ef.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
