### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by DmitryZ123** [netology-code/git-homeworks-neuro-issues#2210]
### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
### Ожидаемый результат
Форма обратной связи не сжата

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/72604623/100094720-80f6c880-2e6a-11eb-8768-77e1809bc78d.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
