### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by LadyBag** [netology-code/git-homeworks-neuro-issues#2211]
@solarrust
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![132](https://user-images.githubusercontent.com/73749976/100250817-22efe100-2f4f-11eb-8c3c-5f824adb39a6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
