### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by LadyBag** [netology-code/git-homeworks-neuro-issues#2212]
@solarrust
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма не сжата

**Фактический результат**
Форма обратной связи слишком сжата.

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![124](https://user-images.githubusercontent.com/73749976/100251560-f5576780-2f4f-11eb-8ecf-4d08879351c2.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
