### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Mikhail9030** [netology-code/git-homeworks-neuro-issues#2213]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на картинку

#### Фактический результат

Текст наезжает на картинку (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![image](https://user-images.githubusercontent.com/74503001/100274082-e2a05b00-2f6e-11eb-99ba-7142601e98ad.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
