### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Mikhail9030** [netology-code/git-homeworks-neuro-issues#2214]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Обратная связь"
3. Нажать на "Оставайтесь на связи"

#### Ожидаемый результат

Форма обратной связи нормального размера

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![image](https://user-images.githubusercontent.com/74503001/100274678-e97b9d80-2f6f-11eb-98e0-fd2aca80f5f9.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
