### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by lDarkHawkI** [netology-code/git-homeworks-neuro-issues#2215]
**Описание проблемы** для @solarrust
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

Открыть главную страницу сайта NeuroStartUp в мобильном браузере
Пролистать до текста "Воспользуйтесь современными возможностями.."
Ожидаемый результат
Текст не наезжает на картинку

**Фактический результат**
Текст наезжает на картинку (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**Скрин:**
![1](https://user-images.githubusercontent.com/74211413/100672766-7315db80-3373-11eb-85a5-69d7bad54b6c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
