### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by lDarkHawkI** [netology-code/git-homeworks-neuro-issues#2216]
**Описание проблемы** для @solarrust
Форма обратной связи слишком сжата.

**Шаги по воспроизведению**:

Открыть форму обратной связи  сайта NeuroStartUp в мобильном браузере.

**Ожидаемый результат**
Форма не сжата

**Фактический результат**
Форма сжата (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**Скрин:
![2](https://user-images.githubusercontent.com/74211413/100673731-013e9180-3375-11eb-8287-3b24039df576.png)
**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
