### ISSUE TITLE
Наезжание текста на изображение на главной странице веб-сайта NeuroStartUp

### ISSUE THREAD

**Issue by ghost** [netology-code/git-homeworks-neuro-issues#2217]
**ОПИСАНИЕ ПРОБЛЕМЫ:**
На главной странице веб-сайта NeuroStartUp наблюдается наезжание текстового блока "Воспользуйтесь современными возможностями искуственного интеллекта, оставив конкурентов позади!" на изображение нетбука. Поскольку цвета текста и изображения схожи (оба близки к белому), @solarrust  текст практически нечитаем. Также изображение нетбука отображается не по центру, в результате чего правый край нетбука отображается усеченно.

**ШАГИ ПО ВОСПРОИЗВЕДЕНИЮ ПРОБЛЕМЫ:**
1. Открыть главную страницу в мобильном брайзере Chrome.
2. Прокрутить главную страницу до отображения текста на фоне нетбука (внизу страницы).

**ОЖИДАЕМЫЙ РЕЗУЛЬТАТ:**
Текст не наезжает на изображение или отображается оптимальным для читабельности цветом. Изображение располагается так, чтобы нетбук был виден полностью.

**ФАКТИЧЕСКИЙ РЕЗУЛЬТАТ:**
Текст наезжает на изображение и нечитабелен из-за схожести с изображением по цвету оформления, а правый край нетбука не виден (см. скриншот).

**ОБОРУДОВАНИЕ И ПРОГРАММНОЕ ОКРУЖЕНИЕ:**
- SAMSUNG SM-G398FN; Android 10, One UI 2.0.
- Chrome 87.0.4280.66.

**СКРИНШОТ:**
![текст на фоне изображения](https://user-images.githubusercontent.com/72408634/100384560-805c5e80-3031-11eb-83d3-f4325e15d435.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
