### ISSUE TITLE
Отображение формы обратной связи на веб-сайте NeuroStartUp сжато по вертикали

### ISSUE THREAD

**Issue by ghost** [netology-code/git-homeworks-neuro-issues#2218]
**ОПИСАНИЕ ПРОБЛЕМЫ:**
Форма обратной связи на веб-сайте  NeuroStartUp сжата по вертикали относительно боковых границ страницы, в результате чего некорректно распорлагаются текстовые блоки внутри формы, а также @solarrust  не виден нижний край формы.

**ШАГИ ДЛЯ ВОСПРОИЗВЕДЕНИЯ ПРОБЛЕМЫ:**
1. Открыть веб-сайт NeuroStartUp в мобильном браузере Chrome.
2. Перейти на страницу с формой обратной связи.

**ОЖИДАЕМЫЙ РЕЗУЛЬТАТ:**
Окно формы обратной связи на странице веб-сайта NeuroStartUp имеет оптимальные границы по вертикали, при которых текстовые блоки внутри формы читабельны и корректно отцентрованы. Также видны все границы окна формы.

**ФАКТИЧЕКИЙ РЕЗУЛЬТАТ:**
Окно формы обратной связи на странице веб-сайта NeuroStartUp отображается слишком узким, в результате чего не отцентрованы текстовые блоки внутри формы, а также не виден нижний край окна формы.

**ОБОРУДОВАНИЕ И ПРОГРАММНОЕ ОКРУЖЕНИЕ:**
- SAMSUNG SM-G398FN; Android 10, One UI 2.0.
- Chrome 87.0.4280.66.

**СКРИНШОТ:**
![границы формы уже, чем надо](https://user-images.githubusercontent.com/72408634/100386671-1fd02000-3037-11eb-9993-37270837cb1b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
