### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Draywer** [netology-code/git-homeworks-neuro-issues#2219]
**Описание проблемы**
Текстовый блок "Воспользуйтесь современными возможностями..", расположенный на главной странице, наезжает на изображение. 

**Шаги воспроизведения:**
1. Открыть на смартфоне в браузере Safari  главную страницу сайта http://neurostartup.com    
2. Пролистать Главную страницу до текстового блока  "Воспользуйтесь современными возможностями.."

**Ожидаемое поведение**
Текстовый блок "Воспользуйтесь современными возможностями..." не наезжает на изображение и находится выше изображения.

**Скриншоты**

![image](https://user-images.githubusercontent.com/53969463/100490322-9b12fe00-312b-11eb-93af-c66523760c43.png)

**Мобильное устройство:**
 - Устройство: iPhone6
 - ОС: iOS8.1
 - Браузер stock browser, safari
 - Версия браузера: 22

**Исполнитель:** @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
