### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by ZabelinsA** [netology-code/git-homeworks-neuro-issues#222]
@solarrust

**Форма обратной связи слишком сжата.**

**Шаги по воспроизведению:**

    1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат:**

Верстка формы должна быть адаптирована под размер экрана.

**Фактический результат:**

Форма слишком сжата (см. скриншот).

**Программное окружение:**

   * Устройство: iPhone 8+ (iOS 12.1)
   * Браузер: Chrome (70.0.3538.75)

**Скриншоты:**

![изображение](https://user-images.githubusercontent.com/56668958/67687729-ce73de00-f9a9-11e9-903f-498a26cfa0c5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
