### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Draywer** [netology-code/git-homeworks-neuro-issues#2220]
**Описание проблемы**
Форма обратной связи, расположенная на странице Контакты, слишком сжата. 

**Шаги воспроизведения:**
1. Открыть на смартфоне в браузере Safari  главную страницу сайта http://neurostartup.com
2. Перейти на страницу Контакты.     
3. Пролистать страницу Контакты до формы  обратной связи.

**Ожидаемое поведение**
Форма обратной связи должна располагаться на всю ширину окна браузера.

**Скриншоты**

![image](https://user-images.githubusercontent.com/53969463/100490622-b7179f00-312d-11eb-88c4-1f771b27cef6.png)

**Мобильное устройство:**
 - Устройство: iPhone6
 - ОС: iOS8.1
 - Браузер stock browser, safari
 - Версия браузера: 22

**Исполнитель:** @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
