### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by helenlpraud** [netology-code/git-homeworks-neuro-issues#2223]
# **Описание проблемы**

### **Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### **Ожидаемый результат**
Текст не наезжает на изображение

### **Фактический результат**
Текст наезжает на изображение (см. скриншот)

### **Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### **Скриншоты**

![errorFirst](https://user-images.githubusercontent.com/9416469/100525726-0e704a80-31d4-11eb-8b40-d6d1699effa2.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
