### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by helenlpraud** [netology-code/git-homeworks-neuro-issues#2224]
# Описание проблемы

### Шаги по воспроизведению
1. Перейти на страницу формы обратной связи

### Ожидаемый результат
Масштаб формы соответствует содержимому

### Фактический результат
Форма слишком сжата

### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75

### Скриншоты

![errorTwo](https://user-images.githubusercontent.com/9416469/100526858-0cab8480-31de-11eb-9316-6bf626b5c2e0.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
