### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Zlobiinn** [netology-code/git-homeworks-neuro-issues#2227]
**Описание проблемы:**

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению:**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат

Текст не наезжает на изображение

_Фактический результат:_
Текст наезжает на изображение (см. скриншот)

@solarrust - прошу откликнуться

Программное окружение

Устройство: iPhone XR (iOS 14.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/63444880/100546928-146a3800-3275-11eb-9bcc-201b0e52a985.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
