### ISSUE TITLE
Текст формы обратной связи не умещается в предполагаемое для него поле

### ISSUE THREAD

**Issue by Zlobiinn** [netology-code/git-homeworks-neuro-issues#2228]
**Описание проблемы:**

1. Текст формы обратной связи не умещается в предполагаемое для него поле
2. Форма поля должна быть боле наглядной - стороны прямоугольника должны быть более равными между собой

**Шаги по воспроизведению:**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Кликнуть на раздел "Оставайтесь на связи"

_Ожидаемый результат:_
Наглядная форма отклика

Программное окружение:
Устройство: iPhone XR (iOS 14.1)
Браузер: Chrome (70.0.3538.75)

@solarrust - прошу откликнуться

Скриншот:
![image](https://user-images.githubusercontent.com/63444880/100547112-17195d00-3276-11eb-860d-2ab19ece37cd.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
