### ISSUE TITLE
Текстовый блок на главной странице наезжает на изображение

### ISSUE THREAD

**Issue by MichaelBro** [netology-code/git-homeworks-neuro-issues#2229]
# Описание проблемы
#### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

@solarrust - прошу откликнуться

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

#### Скриншот
![image](https://user-images.githubusercontent.com/20611135/100549388-c01a8480-3283-11eb-807c-064cc3d114d1.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
