### ISSUE TITLE
Блок формы обратной не растягивается в зависимости от контента

### ISSUE THREAD

**Issue by MichaelBro** [netology-code/git-homeworks-neuro-issues#2230]
# Описание проблемы:

#### Шаги по воспроизведению:
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Кликнуть на раздел "Оставайтесь на связи"

#### Ожидаемый результат:
Форма соответствует размерам страницы

#### Фактический результат
Форма заполнения обратной связи слишком сжата (см. скриншот)

Программное окружение:
Устройство: iPhone 12 (iOS 14.1)
Браузер: Chrome (81.0.3538.75)

@solarrust - прошу откликнуться

Скриншот
![image](https://user-images.githubusercontent.com/20611135/100549732-d590ae00-3285-11eb-9c6a-8f9830f08920.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
