### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by davalesha** [netology-code/git-homeworks-neuro-issues#2232]
@solarrust, прошу поправить.

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере

2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Корректная форма обратной связи

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![task2](https://user-images.githubusercontent.com/74869869/100550528-a2e9b400-328b-11eb-8186-7401d76c729e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
