### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by 0xAxPx** [netology-code/git-homeworks-neuro-issues#2235]
<h4>Шаги по воспроизведению</h4>

<ol>
<li>Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome</li>
<li>Пролистать страницу до блока "Воспользуйтесь современными возможностями..."</li>
</ol>

<h4>Ожидаемый результат</h4>
Текст не наезжает на изображение

<h4>Фактический результат</h4>
Текст наезжает на изображение (см. скриншот)

<h4>Программное окружение</h4>
<ul>
<li>Устройство: iPhone 8+ (iOS 12.1)</li>
<li>Браузер: Chrome (70.0.3538.75)</li>
</ul>

<h4>Скриншоты</h4>

![issue](https://user-images.githubusercontent.com/16291332/100647972-510b6180-3351-11eb-9e49-e68f704abdc6.png)

</p>
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
