### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by 0xAxPx** [netology-code/git-homeworks-neuro-issues#2236]
<h4>Шаги по воспроизведению</h4>

<ol>
<li>Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome</li>
<li>В правом верхнем углу нажать на кнопку "Обратная связь" "</li>
<li>В открывшейся форме ввести необходимые данные"</li>
</ol>

<h4>Ожидаемый результат</h4>
Текст формы выровнен на масштабу экрана 

<h4>Фактический результат</h4>
Форма сжата и неудобна для пользователя (см. скриншот)

<h4>Программное окружение</h4>
<ul>
<li>Устройство: iPhone 8+ (iOS 12.1)</li>
<li>Браузер: Chrome (70.0.3538.75)</li>
</ul>

<h4>Скриншоты</h4>

![issue2](https://user-images.githubusercontent.com/16291332/100648763-751b7280-3352-11eb-8199-6a11a1625659.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
