### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Crabgore** [netology-code/git-homeworks-neuro-issues#2237]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![Скриншоты](https://user-images.githubusercontent.com/48756344/100752690-8c5d6d00-33f1-11eb-93b9-6fb40d5fcc7e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
