### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Crabgore** [netology-code/git-homeworks-neuro-issues#2238]
**Страница обратной связи. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**
1. Открыть страницу обратной связи NeuroStartUp в мобильном браузере Chrome

**Ожидаемый результат**
Корректное отображение формы обратной связи

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/48756344/100753068-fd048980-33f1-11eb-92c9-0c9ab0a1aa3c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
