### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by MargaritaPustovalova** [netology-code/git-homeworks-neuro-issues#2239]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

- [ ] ![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/71708472/100764617-968a6600-3407-11eb-8ca4-58d85c35b748.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
