### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Ilyachigin** [netology-code/git-homeworks-neuro-issues#2241]
@solarrust 
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp 
2. Пролистать страницу до блока с обратной связью

#### Ожидаемый результат

Блок на всю длинну страницы

#### Фактический результат

Сильно сжатое изображение

#### Программное окружение

* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://camo.githubusercontent.com/8b6aa0acc22de5c12c5a449f639cc7e430299d13757d046bf63f9f010175d210/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
