### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by alexeyKoshelevJava** [netology-code/git-homeworks-neuro-issues#2245]
## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
## Ожидаемый результат 
- Текст не наезжает на изображение

## Фактический результат

- Текст наезжает на изображение (см. скриншот)

## Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

-Браузер: Chrome (70.0.3538.75)
## Пользователь  @solarrust

![image](https://user-images.githubusercontent.com/74651785/100844800-62f21f00-348d-11eb-95bb-ec286e28919d.png)

**Comment by alexeyKoshelevJava** [comment]
пользователь  @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
