### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by sorokinkir** [netology-code/git-homeworks-neuro-issues#2246]
@solarrust 
# Описание проблемы
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма обратной связи должна расширяться на всю доступную ширину

#### Фактический результат

Форма обратной связи имеет не достаточную ширину (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)

#### Скриншоты
![](https://i.imgur.com/HcSpYkT.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
