### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by alexeyKoshelevJava** [netology-code/git-homeworks-neuro-issues#2247]
## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Обратная связь."
## Ожидаемый результат

- Расширенная форма обратной связи

## Фактический результат

- Форма обратной связи слишком сжата

##Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
## Пользователь
@solarrust 

![image](https://user-images.githubusercontent.com/74651785/100846835-0e9c6e80-3490-11eb-8927-6734f87def29.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
