### ISSUE TITLE
Съехал текст "Оставайтесь на связи"

### ISSUE THREAD

**Issue by Cook1eM** [netology-code/git-homeworks-neuro-issues#2249]
# Описание проблемы
#### Ожидаемый результат
* Текст не съезжет
#### Фактический результат
* Текст съезжает (см. скриншот)
#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
#### Скриншот 
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/73870450/100893022-f6e2db80-34cb-11eb-8aeb-23c6f2c7c5bb.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
