### ISSUE TITLE
Текст наезжает на киртинку

### ISSUE THREAD

**Issue by DarkElectro74** [netology-code/git-homeworks-neuro-issues#225]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/46447048/67834082-3cceb280-fb08-11e9-8c90-43115c332ec9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
