### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by shibzuko** [netology-code/git-homeworks-neuro-issues#2254]
@solarrust
**При открытии диалогового окна веб-сайта NeuroStartUp в мобильном браузере Chrome в верхнем блоке "Оставайтесь на связи..." текст съезжает из-за узкого блока.**

**Ожидаемый результат**
Текст не съезжет

**Фактический результат**
Текст съезжает (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/33262442/101015525-252eec80-359a-11eb-95fc-537ae062d609.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
