### ISSUE TITLE
Форма слишком сжата

### ISSUE THREAD

**Issue by ivankamenev** [netology-code/git-homeworks-neuro-issues#2256]
Описание проблемы для @solarrust
Форма обратной связи слишком сжата.

Шаги по воспроизведению:

Открыть форму обратной связи сайта NeuroStartUp в мобильном браузере.

Ожидаемый результат
Форма не сжата

Фактический результат
Форма сжата (см. скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скрин:
![2](https://user-images.githubusercontent.com/48853442/101022586-a1b5d100-3582-11eb-9d79-838d97f0b1be.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
