### ISSUE TITLE
Форма слишком сжата

### ISSUE THREAD

**Issue by soni-avd** [netology-code/git-homeworks-neuro-issues#2258]
**Форма обратной связи слишком сжата, текст плохо читается** 

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Справа есть форма обратной связи, текст на ней плохо читается, она слишком сжата

### Ожидаемый результат
Сделать форму шире, уменьшить шрифт текста

### Фактический результат
Слова переносятся, из-за чего текст плохо читается (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

Решить проблему @solarrust 

**Скриншот** 
![Скриншот](https://camo.githubusercontent.com/8b6aa0acc22de5c12c5a449f639cc7e430299d13757d046bf63f9f010175d210/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
