### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by DarkElectro74** [netology-code/git-homeworks-neuro-issues#226]
**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "форма обратной связи"

**Ожидаемый результат**
Форма обратной связи в нормальном размере

**Фактический результат**
Форма слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/46447048/67834348-fe85c300-fb08-11e9-8d32-4c0f08ad3645.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
