### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Chikhareva** [netology-code/git-homeworks-neuro-issues#2262]
@solarrust
1.В браузере Google Chrome зайти на сайт neuroStart Up
2. пролистать до первой картинки после описания 

Ожидаемый результат- заканчивается текст, начинается картинка
Фактический результат- Текст наезжает на картинку

Програмное окружение- Windows 7
Браузе  Версия 87.0.4280.88 (Официальная сборка), (32 бит)
![image](https://user-images.githubusercontent.com/75243175/101161303-1b0ffb00-3639-11eb-95cc-f81bc035dce4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
