### ISSUE TITLE
На сайте NeuroStartUp форма обратной связи сжата

### ISSUE THREAD

**Issue by Chikhareva** [netology-code/git-homeworks-neuro-issues#2263]
@solarrust

1. В браузере Google Chrome  зайти на сайт NeuroStartUp

2. Нажать на кнопку обратной связи

Ожидаемый результат- корректное отображение формы обратной связи для заполнения
Фактический результат- Форма обратной связи сжата, по бокам формы пустая страница

![image](https://user-images.githubusercontent.com/75243175/101165732-d3d93880-363f-11eb-93dc-cd3486c636c5.png)
Програмное укружение
Windows 7
Браузер Версия 87.0.4280.88 (Официальная сборка), (32 бит)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
