### ISSUE TITLE
Главная страница: текст наехал на картинку

### ISSUE THREAD

**Issue by ghost** [netology-code/git-homeworks-neuro-issues#2264]
# Описание проблемы

@solarrust 
---

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты

![image](https://user-images.githubusercontent.com/19320667/101179342-aa8acd80-367c-11eb-9353-bab66b25c9b5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
