### ISSUE TITLE
Форму обратной связи плющит

### ISSUE THREAD

**Issue by ghost** [netology-code/git-homeworks-neuro-issues#2265]
# Описание проблемы

@solarrust
---

Главная страница. Форма обратной связи сплющена с обеих сторон и выглядит плохо.

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до самого низа, где форма обратной связи.

**Ожидаемый результат**
Форма обратной связи имеет ширину экрана

**Фактический результат**
Форма занимает не все доступное ей пространство экрана, сплющена с боков (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/19320667/101180104-bc20a500-367d-11eb-8182-1528d27019af.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
