### ISSUE TITLE
Описание проблемы

### ISSUE THREAD

**Issue by Assem7** [netology-code/git-homeworks-neuro-issues#2268]
###  Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

 ### Ожидаемый результат
Текст не наезжает на изображение
 
### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)
![ошибка 1](https://user-images.githubusercontent.com/51492154/101195967-372f8e80-3671-11eb-87de-65524298796d.png)

 @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
