### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by a-vystavkina** [netology-code/git-homeworks-neuro-issues#227]
@solarrust
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..."
наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![scan](https://user-images.githubusercontent.com/54661749/68069711-24af9b00-fd75-11e9-8f8e-955ead625399.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
