### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by Sergey-Zvonarev** [netology-code/git-homeworks-neuro-issues#2272]
# Шаги по воспроизведению

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат
Текст не наезжает на изображение

## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/71452927/101211977-6d7d0600-3691-11eb-9d01-5ddb87c78f22.png)

Пользователь @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
