### ISSUE TITLE
Форма "Оставайтесь на связи" слишком сжата

### ISSUE THREAD

**Issue by Sergey-Zvonarev** [netology-code/git-homeworks-neuro-issues#2273]
@solarrust

# Описание проблемы

**Главная страница. Форма обратной связи - слишком сжата**

###  Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат

Форма обратной связи имеет ширину экрана

### Фактический результат

Форма сплющена с боков (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/71452927/101213064-3c053a00-3693-11eb-9cd6-61a2b0a794bb.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
