### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by boog25** [netology-code/git-homeworks-neuro-issues#2274]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текс наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![Screenshot_7](https://user-images.githubusercontent.com/75333408/101240109-f5edbc00-370e-11eb-99d4-5b18a847cc3e.jpg)

**Ссылка на проект:** [https://github.com/netology-code/git-homeworks-neuro-issues.git](url)
**Пользователь:** @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
