### ISSUE TITLE
Форма "Оставайтесь на связи" слишком сжата

### ISSUE THREAD

**Issue by boog25** [netology-code/git-homeworks-neuro-issues#2275]
**Описание** 
Главная страница. Форма обратной связи - слишком сжата

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Форма обратной связи имеет ширину экрана

**Фактический результат**
Форма сплющена с боков (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот:**
![Screenshot_8](https://user-images.githubusercontent.com/75333408/101240365-b7f19780-3710-11eb-861a-a013e15d4c0e.jpg)

**Ссылка на проект:** [https://github.com/netology-code/git-homeworks-neuro-issues.git](url)

**Пользователь:**  @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
