### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by maslovu** [netology-code/git-homeworks-neuro-issues#2276]
Описание
Главная страница. Форма обратной связи - слишком сжата

Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Форма обратной связи имеет ширину экрана

Фактический результат
Форма сплющена с боков (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншот: 

![101240109-f5edbc00-370e-11eb-99d4-5b18a847cc3e](https://user-images.githubusercontent.com/37995469/101242525-b0d08680-371c-11eb-9695-06e70b918a2a.jpg)

Ссылка на проект: https://github.com/netology-code/git-homeworks-neuro-issues.git

Пользователь: @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
