### ISSUE TITLE
Форма "Оставайтесь на связи" слишком сжата

### ISSUE THREAD

**Issue by maslovu** [netology-code/git-homeworks-neuro-issues#2277]
Описание проблемы
Главная страница. Форма обратной связи - слишком сжата

Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Форма обратной связи имеет ширину экрана

Фактический результат
Форма сплющена с боков (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![101240365-b7f19780-3710-11eb-861a-a013e15d4c0e](https://user-images.githubusercontent.com/37995469/101242714-fc833000-371c-11eb-92b4-afbece2f9273.jpg)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
