### ISSUE TITLE
Форма оставайтесь на связи слишком сжата

### ISSUE THREAD

**Issue by gurueg** [netology-code/git-homeworks-neuro-issues#2279]
# Описание проблемы
### Шаги по воспроизведению 
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Форма обратной связи имеет ширину экрана

### Фактический результат
Форма сплющена с боков (см. скриншот)

### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/57090594/101243000-4284c780-370e-11eb-8b99-6633c4062993.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
