### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by a-vystavkina** [netology-code/git-homeworks-neuro-issues#228]
@solarrust
**Главная страница. Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу  до формы обратной связи.

**Ожидаемый результат**

Форма обратной связи принимает стандартные размеры.

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![form](https://user-images.githubusercontent.com/54661749/68069800-507f5080-fd76-11e9-8cac-5340a027bd90.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
