### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Maximus23X** [netology-code/git-homeworks-neuro-issues#2280]
# Описание проблемы

## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)

## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

## Скриншот
![8E5C6D7C-651E-48EB-9F75-B87580900B1A](https://user-images.githubusercontent.com/75327838/101247951-8804bd00-372d-11eb-825a-7dd9240887a8.png)

### Пользователь: @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
