### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Maximus23X** [netology-code/git-homeworks-neuro-issues#2281]
# Описание
## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат
Форма обратной связи имеет ширину экрана

## Фактический результат
Форма сплющена с боков (см. скриншот)

## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

## Скриншот:
![148E2BDC-81BE-421A-AA8D-A295BB8ACECE](https://user-images.githubusercontent.com/75327838/101249065-327ce000-372e-11eb-9798-9d898cf48896.png)

### Пользователь: @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
