### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by straivi** [netology-code/git-homeworks-neuro-issues#2285]
# Описание проблемы

#### Главная страница. Форма "Оставайтесь на связи слишком узкая." наезжает на изображение
@solarrust 

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Адаптированная под экран форма

#### Фактический результат

Форма слишком узкая, все элементы съехали (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/42292995/101260361-5cd79900-3740-11eb-9d66-468915a6882e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
