### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by AnyaKorosteleva** [netology-code/git-homeworks-neuro-issues#2286]
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншот
![текст наезжает на картинку](https://user-images.githubusercontent.com/74379643/101260585-2ac73680-3742-11eb-9ddb-71a5ab960c43.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
