### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AnyaKorosteleva** [netology-code/git-homeworks-neuro-issues#2287]
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы "Оставайтесь на связи."

#### Ожидаемый результат

Форма отображается на всю ширину странички

#### Фактический результат

Форма слишком узкая (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![форма слишком сжата](https://user-images.githubusercontent.com/74379643/101260755-0cae0600-3743-11eb-9b17-9d59dd5d164e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
