### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by r616on** [netology-code/git-homeworks-neuro-issues#2289]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Форма обратной связи слишком сжата.

#### Фактический результат

Форма обратной связи слишком сжата. (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://user-images.githubusercontent.com/69537715/101262693-9bc21a80-3751-11eb-9eda-fcf5de6409cc.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
