### ISSUE TITLE
Netology issue

### ISSUE THREAD

**Issue by BadmaV** [netology-code/git-homeworks-neuro-issues#229]
# Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

Скриншоты

![Screenshot_3](https://user-images.githubusercontent.com/55066536/68076569-636e4100-fdc7-11e9-8f93-a19b73613c44.png)

@solarrast

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
