### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ops-00000000** [netology-code/git-homeworks-neuro-issues#2295]
@solarrust 
**Описание проблемы**

- Главная страница. Форма обратной связи слишком сжата

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

- Форма обратной связи имеет ширину экрана

**Фактический результат**

- Форма связи слишком сжата(см скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот:**

![](https://user-images.githubusercontent.com/75327838/101249065-327ce000-372e-11eb-9798-9d898cf48896.png)

[Проект]( https://github.com/netology-code/git-homeworks-neuro-issues.git)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
