### ISSUE TITLE
Проблема отображения текстового блока на мобильных устройствах

### ISSUE THREAD

**Issue by yushkevich-a-a** [netology-code/git-homeworks-neuro-issues#2298]
@solarrust

# Описание проблемы

**На главной странице, текстовый блок "Воспользуйтесь современными возможностями..." наезжает на логотип**

**Шаги для воспроизведения проблемы:**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере в Chrome 
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

* Браузер: Chrome (87.0.4280.88) (отображение на мобильных устройствах)

![Неисправность1](https://user-images.githubusercontent.com/64197715/101287987-d1740b80-3804-11eb-945c-4ab242734f49.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
