### ISSUE TITLE
Проблема отображения блока обратной связи на мобильных устройствах

### ISSUE THREAD

**Issue by yushkevich-a-a** [netology-code/git-homeworks-neuro-issues#2299]
@solarrust

# Описание проблемы

**Форма обратной связи на мобильных устройствах слишком сжата, что приводит к переносам слов и нагромождению описания полей ввода**

**Шаги для воспроизведения проблемы:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере в Chrome
1. Пролистать страницу до блока формы обратной связи

**Ожидаемый результат**

форма обратной связи имеет минимальные отступы по краям и, если сужается, то пропорционально ширине экрана устройства, также имея минимальные отступы по краям. Так же не должно создаваться впечатления нагромождения описания, и текст должен равномерно распределяться по области отображения блока обратной связи.

**Фактический результат**

Слишком большие отступы по краям формы обратной связи, текстовые описания не помещаются в поля и появляются лишние переносы слов (см. скриншот)

**Программное окружение**

Браузер: Chrome (87.0.4280.88) (отображение на мобильных устройствах)

![Неисправноесть2](https://user-images.githubusercontent.com/64197715/101288454-b951bb80-3807-11eb-92e5-ef8a03eeb425.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
