### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Anastasia-Krutitskaya** [netology-code/git-homeworks-neuro-issues#2302]
@solarrust

### Описание проблемы

Форма обратной связи слишком сжата

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до формы обратной связи

**Ожидаемый результат**

Форма обратной связи имеет ширину экрана

**Фактический результат**

Форма связи слишком сжата(см скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/71830361/101288993-8e1c9b80-380a-11eb-8373-99812ef1fbaa.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
