### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by nice312-dev** [netology-code/git-homeworks-neuro-issues#2304]
**Описание проблемы**

Форма обратной связи слишком сжата

**Шаги по воспроизведению**

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до формы обратной связи

**Ожидаемый результат**

Форма обратной связи имеет ширину экрана

Фактический результат

Форма связи слишком сжата(см скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/74597002/101338193-78f14c80-389e-11eb-8090-5e4f24c54985.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
