### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Etnogenes** [netology-code/git-homeworks-neuro-issues#2305]
@solarrust

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

![scr1](https://user-images.githubusercontent.com/65664172/101352411-29614f80-38a3-11eb-95f4-8633fbab1204.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
