### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Etnogenes** [netology-code/git-homeworks-neuro-issues#2306]
@solarrust

**Ожидаемый результат**
Форма обратной связи правильно масштабирована

**Фактический результат**
Форма обратной связи съехала (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![scr2](https://user-images.githubusercontent.com/65664172/101352731-a1c81080-38a3-11eb-9d67-80d210880518.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
