### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by EkaterinaAkhmetzyanova** [netology-code/git-homeworks-neuro-issues#2308]
@solarrust форма обратной связи в мобильной версии слишком сжата.

**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи "Оставайтесь на связи"

**Ожидаемый результат**
Форма хорошо и читабельно отображается в мобильной версии

**Программное окружение:**

*Устройство: iPhone 8+ (iOS 12.1)
*Браузер: Chrome (70.0.3538.75)

**Скриншоты:**

![subscription_mobile](https://user-images.githubusercontent.com/71600753/101400072-6cdaae80-38e1-11eb-99f8-b41f3efe1289.PNG)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
