### ISSUE TITLE
Задание №2. Миннуллин

### ISSUE THREAD

**Issue by Arsenko** [netology-code/git-homeworks-neuro-issues#231]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![](https://i.imgur.com/HJ1VbMj.png)

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Блок отбражается корректно

#### Фактический результат

Форма ввода текста сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/20711822/68133899-4c982d80-ff32-11e9-9951-337737407337.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
