### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by shumovdenis** [netology-code/git-homeworks-neuro-issues#2310]
Форма обратной связи слишком сжата
@solarrust

**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Перейти к блоку обратной связи.

**Ожидаемый результат:**

Форма обратной связи отображается корректно.

**Фактический результат:**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/75227278/101427013-23a15380-390f-11eb-9519-49c22d071c0d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
