### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by octopus-dev-d** [netology-code/git-homeworks-neuro-issues#2313]
### Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Ответственные: @solarrust**

**Скриншоты**

![123](https://user-images.githubusercontent.com/69010704/101442625-e73d1a00-3945-11eb-83c6-525c176cf5cd.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
