### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by octopus-dev-d** [netology-code/git-homeworks-neuro-issues#2314]
### Описание проблемы

**Форма обратной связи слишком сжата в мобильной версии сайта**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**

Форма выглядит ровно и красиво с соблюдением всех пропорций

**Фактический результат**

Форма слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Ответственные: @solarrust**

**Скриншоты**

![1234](https://user-images.githubusercontent.com/69010704/101442859-57e43680-3946-11eb-9f63-8e8e20d21a6a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
