### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by rahel81** [netology-code/git-homeworks-neuro-issues#2316]
Шаги по воспроизведению

1. Открыть веб-сайт NeuroStartUp в мобильном браузере Chrome
2. Перейти на страницу с формой обратной связи

Ожидаемый результат
Каждое предложение располагается на одной строке 

Фактический результат
Форма сжата, предложение разбито на несколько строк  (см. скриншот)

Программное окружение

-  Устройство: iPhone 8+ (iOS 12.1)
-  Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/75310641/101484943-790b4e00-396b-11eb-88ac-cd54774e6f20.png)

Исполнитель @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
