### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by BelyakovArkadiy** [netology-code/git-homeworks-neuro-issues#2317]
@solarrust 

Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![Screenshot_1](https://user-images.githubusercontent.com/75253889/101484767-56396380-3984-11eb-83de-9d7864d951ce.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
