### ISSUE TITLE
В форме обратной связи заголовок слишком сжат 

### ISSUE THREAD

**Issue by BelyakovArkadiy** [netology-code/git-homeworks-neuro-issues#2319]
@solarrust 
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат
Слово "Оставайтесь" отображается корректно без переноса на новую строку
![Screenshot_2](https://user-images.githubusercontent.com/75253889/101485876-0196e800-3986-11eb-8128-954def008bbe.png)

Фактический результат
Слово "Оставайтесь" имеет не корректный перенос на новую строку (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
