### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Valerrrrrrrrria** [netology-code/git-homeworks-neuro-issues#2322]
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

**Ожидаемый результат**
Форма обратной связи имеет удобные размеры

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60038555/101504081-ddd2a280-3983-11eb-8beb-11055f8d0118.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
