### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Zippelin** [netology-code/git-homeworks-neuro-issues#2323]
### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншоты
![image](https://user-images.githubusercontent.com/11209504/101507763-f5ac2580-3987-11eb-8eb6-975a858e1a15.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
