### ISSUE TITLE
Форма обратной связи слишком сжатая

### ISSUE THREAD

**Issue by Zippelin** [netology-code/git-homeworks-neuro-issues#2324]
### Шаги по воспроизведению
Открыть страницу обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
### Ожидаемый результат
Форма обратной связи должна иметь адекватный размер

### Фактический результат
Форма обратной связи слишком узкая

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншоты
![image](https://user-images.githubusercontent.com/11209504/101508063-4885dd00-3988-11eb-9d0b-e39fe89ec2b2.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
