### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Marpl7** [netology-code/git-homeworks-neuro-issues#2325]
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот
![image](https://user-images.githubusercontent.com/65710926/101519810-e7f4a100-3983-11eb-9a6f-9cdb8e383a72.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
