### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Marpl7** [netology-code/git-homeworks-neuro-issues#2326]
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат
Форма обратной связи занимает весь экран

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение
*  Устройство: iPhone 8+ (iOS 12.1)
*Браузер: Chrome (70.0.3538.75)

### Скриншоты
![image](https://user-images.githubusercontent.com/65710926/101520372-af08fc00-3984-11eb-8b05-51576d8d9ca9.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
