### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Denis-Zhigun** [netology-code/git-homeworks-neuro-issues#2327]
# Описание проблемы
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат

Текст не наезжает на изображение

### Фактический результат

Текст наезжает на изображение (см. скриншот)

### Программное окружение:

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

### Скриншот: 
![2020-12-08_21-52-55](https://user-images.githubusercontent.com/75408606/101528154-f94ba680-399f-11eb-9463-d25880228bdc.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
