### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Denis-Zhigun** [netology-code/git-homeworks-neuro-issues#2328]
# Описание проблемы 

### Шаги по воспроизведению:

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы оставайтесь на связи

### Ожидаемый результат

Форма не сжата

### Фактический результат

Форма сжата (см. скриншот)

### Программное окружение:

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншот: 
![Скрин 2](https://user-images.githubusercontent.com/75408606/101530048-724bfd80-39a2-11eb-8343-46082e10ecf4.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
