### ISSUE TITLE
Форма обратной связи.

### ISSUE THREAD

**Issue by BadmaV** [netology-code/git-homeworks-neuro-issues#233]
# Форма обратной связи слишком сжата.
**Шаги по воспроизведению:**
1. Открыть сайт в браузере Google Chrome.
2. Перейти на форму обратной связи

**Ожидаемый результат:**
Расположить форму обратной связи на всю ширину страницы.

**Фактический результат:**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение:**
* Устройство: IPhone 8+
* Браузер: Chrome

**Скриншот:**

![Screenshot_4](https://user-images.githubusercontent.com/55066536/68253924-442b1a00-003a-11ea-8f58-9f6a3d429a18.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
