### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by dariy-mvs** [netology-code/git-homeworks-neuro-issues#2330]
# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"
### Ожидаемый результат
Надпись читабельна.

### Фактический результат
Надпись не влезает в строку (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/71699400/101536425-09b54e80-39ab-11eb-870b-deb3cdbb81c9.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
