### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AnnaManketova** [netology-code/git-homeworks-neuro-issues#2334]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат
форма обратной связи не сжата 

Фактический результат
Форма обратной связи слишком сжата 
(см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
скриншот 
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/73355478/101630664-411c0d80-3a34-11eb-91f7-d3e651e9b901.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
