### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Zhekalova** [netology-code/git-homeworks-neuro-issues#2335]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

_Ожидаемый результат:_
Текст не наезжает на изображение

_Фактический результат:_
Текст наезжает на изображение (см. скриншот)

_Программное окружение:_
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![bug1](https://user-images.githubusercontent.com/71697812/101636137-f1d9db00-3a3b-11eb-8808-a7380a0e3b99.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
