### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Zhekalova** [netology-code/git-homeworks-neuro-issues#2336]
**Форма "Оставайтесь на связи". Слишком узкий размер**

**Шаги по воспроизведению**

1. Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

_Ожидаемый результат:_
Форма имеет ширину, равную ширине экрана, все содержимое отображается корректно

_Фактический результат:_
Форма сжата, содержимое отображается некорректно

_Программное окружение:_
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![bug2](https://user-images.githubusercontent.com/71697812/101636638-ae33a100-3a3c-11eb-85c2-6239c48d0950.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
