### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by pavlom10** [netology-code/git-homeworks-neuro-issues#2338]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи..."

#### Ожидаемый результат

Форма не сжата

#### Фактический результат

Форма не сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![image](https://user-images.githubusercontent.com/13799945/101654111-2f952e80-3a51-11eb-93bf-ac8eebbcc4ee.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
