### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by SakharovEugeniy** [netology-code/git-homeworks-neuro-issues#234]
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
#### Ожидаемый результат
Текст не наезжает на изображение
#### Фактический результат
Текст наезжает на изображение (см. скриншот)
#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![UI Bug](https://user-images.githubusercontent.com/56508434/68301563-666c7880-00ca-11ea-82c6-522052331e8c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
