### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by pochtalexa** [netology-code/git-homeworks-neuro-issues#2342]
# Описание проблемы

@solarrust

**Форма обратной связи. Некорректное отображение, форма сильно сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Нажать на кнопку "Обратная связь"

**Ожидаемый результат**
Форма обратной связи отображается корректно в полном формате

**Фактический результат**
Форма сжата

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/63396617/101666585-7558f380-3a5f-11eb-9cbb-886c56dfca26.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
