### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

### ISSUE THREAD

**Issue by Zipozz** [netology-code/git-homeworks-neuro-issues#2343]
**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/75432542/101668388-8a368680-3a61-11eb-9f6a-3cf5aea0a1ed.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
