### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Zipozz** [netology-code/git-homeworks-neuro-issues#2344]
**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Форма обратной связи..."

**Ожидаемый результат**
Форма не сжата

**Фактический результат**

Форма не сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/75432542/101668949-498b3d00-3a62-11eb-8a8e-e0f7dac2279f.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
