### ISSUE TITLE
Главная страница. Форма обратной связи сжата. Некорректный перенос текста 

### ISSUE THREAD

**Issue by mariyaburtseva** [netology-code/git-homeworks-neuro-issues#2346]
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма не сжата. Текст имеет принудительный перенос по словам

**Фактический результат**
Форма сжата, некорректный перенос слов (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншот**
![Скриншот второй проблемы](https://user-images.githubusercontent.com/74449914/101670933-e058f900-3a64-11eb-8627-73ef0df54a5c.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
