### ISSUE TITLE
На главной странице веб-сайта NeuroStartup текст наезжает на картинку

### ISSUE THREAD

**Issue by larlarlar** [netology-code/git-homeworks-neuro-issues#2349]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**
![изображение_2020-12-09_235329](https://user-images.githubusercontent.com/74267660/101686164-bc53e280-3a79-11eb-841f-b8b1c94b12fc.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
