### ISSUE TITLE
Баг верстки страницы Оставайтесь на вязи

### ISSUE THREAD

**Issue by SakharovEugeniy** [netology-code/git-homeworks-neuro-issues#235]
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи..."
#### Ожидаемый результат
* Заголовок "Оставайтесь на связи..." расположен на двух строчках
#### Фактический результат
* Заголовок "Оставайтесь на связи..." расположен на трёх строчках (см.скриншот)
#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/56508434/68393056-52da1400-0195-11ea-8b5b-cb868837456e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
