### ISSUE TITLE
Форма обратной связи веб-сайта NeuroStartUp слишком сжата

### ISSUE THREAD

**Issue by larlarlar** [netology-code/git-homeworks-neuro-issues#2350]
**Страница обратной связи. Текстовый блок "Оставайтесь на связи..." слишком сжат, и слова перенесены не правильно**

**Шаги по воспроизведению**

- Открыть страницу обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

**Ожидаемый результат**
Текст читаем, страница выглядит опрятно, переносы между строк выполнены в соответствии с правилами русского языка, либо отсутствуют

**Фактический результат**
Форма слишком сжата, поля очень большие, слова перенесены некорректно

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![изображение_2020-12-09_235730](https://user-images.githubusercontent.com/74267660/101686572-4bf99100-3a7a-11eb-8613-ae92f62f2d7a.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
