### ISSUE TITLE
Форма "Оставайтесь на связи" в разделе обратной связи сжата

### ISSUE THREAD

**Issue by EvgeniyaSelivanova** [netology-code/git-homeworks-neuro-issues#2352]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. В правом верхнем углу перейти на форму обратной связи

**Ожидаемый результат** - Форма "Оставайтесь на связи" отображается по ширине окна мобильного устройства

**Фактический результат** - Форма "Оставайтесь на связи" сжата, отображение текста и перенос текста - некорректно, поля ввода данных укорочены (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншот
<a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/8b6aa0acc22de5c12c5a449f639cc7e430299d13757d046bf63f9f010175d210/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67"><img src="https://camo.githubusercontent.com/8b6aa0acc22de5c12c5a449f639cc7e430299d13757d046bf63f9f010175d210/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67" alt="" data-canonical-src="https://i.imgur.com/HcSpYkT.png" style="max-width:100%;"></a>

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
