### ISSUE TITLE
Проблема. Текст наезжает на картинку.

### ISSUE THREAD

**Issue by ITAlexMakarov** [netology-code/git-homeworks-neuro-issues#2353]
### **Описание проблемы**:
При открытии сайта с мобильного телефона iPhone 8 (iOS 12.1) через браузер Chrome (v.70.0.3538.75) наблюдается некорректное отображение текста (наезжает на картинку).

> Скриншот

 ![error1](https://user-images.githubusercontent.com/63881068/101813664-11513080-3b2e-11eb-9ad4-a2fc4b1752a7.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
