### ISSUE TITLE
Проблема. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ITAlexMakarov** [netology-code/git-homeworks-neuro-issues#2354]
### **Описание проблемы:**
При открытии сайта с мобильного телефона iPhone 8 (iOS 12.1) через браузер Chrome (v.70.0.3538.75) наблюдается некорректное отображение формы обратной связи (слишком сжата).

> `Скриншот`

![error2](https://user-images.githubusercontent.com/63881068/101814423-35614180-3b2f-11eb-996a-9cd22460113c.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
