### ISSUE TITLE
На главной странице текст наезжает на изображение

### ISSUE THREAD

**Issue by iamlenulya** [netology-code/git-homeworks-neuro-issues#2355]
### **Описание проблемы**

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение

**Фактический результат:**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 7+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты:**

![Screenshot1](https://user-images.githubusercontent.com/75331879/101816642-b4a84280-3b3a-11eb-84ab-499b55e48bec.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
