### ISSUE TITLE
Некорректное отображение формы "Обратная связь"

### ISSUE THREAD

**Issue by iamlenulya** [netology-code/git-homeworks-neuro-issues#2356]
### **Описание проблемы**

**При нажатии кнопки "Обратная связь" на главной странице появляется форма обратной связи, которая отображается некорректно - слишком сжата**

**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до конца.
3. Нажать на кнопку "Обратная связь"

**Ожидаемый результат:**
При переходе на форму, страница отображается корректно, пропорционально. Поля заполнения широкие, тест не переносится.

**Фактический результат:**
Форма отображается сжато, текст съезжает и переносится.

**Программное окружение**

- Устройство: iPhone 7+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты:**

![Screenshot2](https://user-images.githubusercontent.com/75331879/101819396-a3613500-3b3e-11eb-8cc4-e1cd70f7afc3.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
