### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by shmelevvv** [netology-code/git-homeworks-neuro-issues#2357]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/74837867/101827525-78c4ab80-3b41-11eb-80fa-e59304c10452.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
