### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by shmelevvv** [netology-code/git-homeworks-neuro-issues#2358]
Форма обратной связи слишком сжата
Шаги по воспроизведению
Открыть форму обратной связи в мобильном браузере Chrome

Ожидаемый результат
Заголовок формы отображается в одну строку

Фактический результат
Текст заголовка отображается в три строки

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/74837867/101828225-4ebfb900-3b42-11eb-9317-254f4c061a33.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
