### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by alexey-olfert** [netology-code/git-homeworks-neuro-issues#236]
**Главная станица. Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи.

**Ожидаемый результат**

Форма обратной связи пропорционально заполняет страницу, текст не имеет большого колличества переносов.

**Фактический результат**

Форма сжата к середине, из-за этого каждое предложение в тексте заполняет несколько строчек.

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
-  Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/56882078/68544011-8d2ef580-03cf-11ea-9eb2-53e248a6ca53.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
