### ISSUE TITLE
Сжатый текстовый блок "Оставайтесь на связи..."

### ISSUE THREAD

**Issue by kerainka** [netology-code/git-homeworks-neuro-issues#2360]
# Описание проблемы
@solarrust 

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

### Ожидаемый результат
Текст не сжат и слова целиком находятся на одной строке

### Фактический результат
Текстовый блок "Оставайтесь на связи..." сжат  (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60443585/101840922-e0c4c300-3b3c-11eb-8c90-0c56777f586f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
