### ISSUE TITLE
Сжатый текстовый блок "Оставайтесь на свзи"

### ISSUE THREAD

**Issue by SergeyShein** [netology-code/git-homeworks-neuro-issues#2362]
@solarrust 
Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть вкладку "Обратная связь"
Ожидаемый результат
Текст распределен на всю страницу

Фактический результат
Текст слишком сжат (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/75269913/101894144-c8918a00-3bb6-11eb-90fc-847b67847e0b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
