### ISSUE TITLE
Сжатый текстовый блок "Оставайтесь на связи..."

### ISSUE THREAD

**Issue by AnastMast** [netology-code/git-homeworks-neuro-issues#2364]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Текст не сжат и слова целиком находятся на одной строке

**Фактический результат**
Текстовый блок "Оставайтесь на связи..." сжат (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![2git-homeworks_remote at master · netology-code_git](https://user-images.githubusercontent.com/75419963/101896890-bb769a00-3bba-11eb-8730-de7f45002086.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
