### ISSUE TITLE
Iphone. Текстовый блок "Воспользуйтесь.." Наезжает на изображение

### ISSUE THREAD

**Issue by Bogdmoen** [netology-code/git-homeworks-neuro-issues#2367]
# Описание проблемы

#### Шаги:

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

**Окружение:**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

#### Скриншоты 

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/75544437/101931061-fe039b00-3be9-11eb-8130-37a7c31a34b2.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
