### ISSUE TITLE
Мобильный браузер. Некорректный ресайз блока "оставайтесь на связи"

### ISSUE THREAD

**Issue by Bogdmoen** [netology-code/git-homeworks-neuro-issues#2368]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть страницу "Обратная связь"  в портетном режиме

#### Ожидаемый результат

Блок "оставайтесь на связи" подстраивается под размер экрана устройства, верстка блока не ломается.

#### Фактический результат

Блок "оставайтесь на связи" слишком узкий, некорректно подстраивается под размер экрана устройства

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/75544437/101932006-3b1c5d00-3beb-11eb-85a3-135eb62fbb79.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
