### ISSUE TITLE
Ошибка расположения элементов в мобильном браузере

### ISSUE THREAD

**Issue by Arendecat** [netology-code/git-homeworks-neuro-issues#2375]
### Текстовый блок наезжает на изображение

**Описание проблемы:**
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение логотипа.

**Воспроизведение:**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение
Фактический результат:
Текст наезжает на изображение (см. скриншот)

**Программное окружение:**
Устройство: iPhone 6s (iOS 14.1)
Браузер: Safari

**Скриншот проблемы:**
![image](https://user-images.githubusercontent.com/75226637/102009115-5354bf00-3d46-11eb-87ab-6d46395c970b.png)

**Для:** @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
