### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by ZabavinaL** [netology-code/git-homeworks-neuro-issues#2376]
# Описание проблемы #
#### Шаги по воспроизведению ####
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат ####
Текст не наезжает на изображение

#### Фактический результат ####
Текст наезжает на изображение (см. скриншот)

#### Программное окружение ####
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

@solarrust
#### Скриншоты ####
<img width="386" alt="Снимок экрана 2020-12-13 в 13 28 44" src="https://user-images.githubusercontent.com/75333812/102009498-cfe89d00-3d48-11eb-9163-902caa0046cc.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
