### ISSUE TITLE
Некорректный размер текста в мобильном браузере

### ISSUE THREAD

**Issue by Arendecat** [netology-code/git-homeworks-neuro-issues#2377]
### Текст на всей главной странице значительно большего размера, чем необходимо.

**Воспроизведение:**
Открыть главную страницу сайта NeuroStartUp в мобильном браузере 

**Ожидаемый результат:**
Размер текста соответствует настройкам устройства, ИЛИ размер текста и его расположение лаконично выглядят при просмотре с мобильного устройства при сохранении читабельности.
**Фактический результат:**
Текст чрезвычайно большого размера, некоторые слова не помещаются на целую строку. В среднем, одно слово на строку.

**Программное окружение:**
Устройство: iPhone 6s (iOS 14.1)
Браузер: Safari

**Скриншот:**
![image](https://user-images.githubusercontent.com/75226637/102009706-5a7dcc00-3d4a-11eb-8771-dfb3b01344ae.png)

**Для:**
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
