### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ZabavinaL** [netology-code/git-homeworks-neuro-issues#2378]
# Описание проблемы #
#### Шаги по воспроизведению ####
1. Перейти на вкладку "Обратная связь" веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы "Оставайтесь на связи"

#### Ожидаемый результат ####
Форма обратной связи нормального размера, не сжата

#### Фактический результат ####
Форма обратной связи слишком сжата(см. скриншот)

#### Программное окружение ####
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

@solarrust

#### Скриншоты ####
<img width="382" alt="скрин" src="https://user-images.githubusercontent.com/75333812/102009825-2ce55280-3d4b-11eb-86b8-eb3e8d603e21.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
