### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by helenkhim** [netology-code/git-homeworks-neuro-issues#2379]
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: Redmi Note 8T (Версия Android 10 QKQ1.200114.002)
- Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/73491230/102010381-c104e900-3d4e-11eb-9290-a8bc5b518535.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
