### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Anastessha** [netology-code/git-homeworks-neuro-issues#238]
@solarrust

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

### Ожидаемый результат
Форма должна быть адаптирована под мобильную версию 

### Фактический результат
Форма сжата под экран мобильного телефона (см. скриншот)

![image](https://user-images.githubusercontent.com/55062098/68744696-8ce56300-0638-11ea-8cb6-d6a2ac162c21.png)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
