### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by helenkhim** [netology-code/git-homeworks-neuro-issues#2380]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
форма адаптируется под размеры экрана

**Фактический результат**
форма сжата под узкий экран

**Программное окружение**

- Устройство: Redmi Note 8T (версия Android 10 QKQ1.200114.002)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/73491230/102010567-eba37180-3d4f-11eb-8f79-bd17a9d358bf.png)
Для @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
