### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by nansan77** [netology-code/git-homeworks-neuro-issues#2382]
Шаги по воспроизведению
1.	Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Yandex
2.	Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат:
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)
![неро наезд текста](https://user-images.githubusercontent.com/75754208/102019025-ee1ebf00-3d81-11eb-843c-eb004549d2e8.png)

Программное окружение
•	Устройство: Samsung A51 (Android 10)
•	Браузер: Yandex (70.0.3538.75)
#

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
