### ISSUE TITLE
Сжатый текстовый блок "Оставайтесь на связи..."

### ISSUE THREAD

**Issue by GeorgKonst** [netology-code/git-homeworks-neuro-issues#2384]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Текст не сжат и слова целиком находятся на одной строке

**Фактический результат**
Текстовый блок "Оставайтесь на связи..." сжат (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/75683506/102019176-fdead300-3d82-11eb-8ee4-06c484294486.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
