### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Koch007** [netology-code/git-homeworks-neuro-issues#2385]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Текст не сжат и слова целиком находятся на одной строке

**Фактический результат**
Текстовый блок "Оставайтесь на связи..." сжат (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![102019112-81f08b00-3d82-11eb-9355-b6b7bd9bae10](https://user-images.githubusercontent.com/72028856/102019499-c20d3900-3d95-11eb-87e3-338518cccc2b.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
