### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Koch007** [netology-code/git-homeworks-neuro-issues#2386]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Текст не сжат и слова целиком находятся на одной строке

**Фактический результат**
Текстовый блок "Оставайтесь на связи..." сжат (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/72028856/102019603-4eb7f700-3d96-11eb-9cf9-1f0334ae7052.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
