### ISSUE TITLE
Исправить ошибку на главной странице мобильной версии. 

### ISSUE THREAD

**Issue by khizhnyakov** [netology-code/git-homeworks-neuro-issues#2388]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

*Устройство: iPhone 8+ (iOS 12.1)
*Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/71666955/102019010-cd566980-3d81-11eb-8ce4-5898ee16c801.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
