### ISSUE TITLE
Исправить верстку страницы "Оставайтесь на связи".

### ISSUE THREAD

**Issue by khizhnyakov** [netology-code/git-homeworks-neuro-issues#2389]
**Страница "Оставайтесь на связи".  Текстовый блок "Оставайтесь на связи" некорректно переносится в мобильной верстке.** 

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Текст переносится по словам

**Фактический результат**

Текст переносится по буквам (см. скриншот)

**Программное окружение**

*Устройство: iPhone 8+ (iOS 12.1)
*Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/71666955/102020010-971be880-3d87-11eb-899e-6dd5c0e8bec4.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
