### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by nansan77** [netology-code/git-homeworks-neuro-issues#2390]
Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."
Ожидаемый результат:
Текст не сжат и слова целиком находятся на одной строке
Фактический результат
Текстовый блок "Оставайтесь на связи..." сжат (см. скриншот)
![неро обратная связь](https://user-images.githubusercontent.com/75754208/102020056-ed892700-3d87-11eb-96be-e46786ffd613.png)
Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
