### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by SidorinAA** [netology-code/git-homeworks-neuro-issues#2391]
**Шаги по воспроизведению**

 1. Открыть главную страницу в мобильном браузере Chrome
 2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Cкриншот**

![Скриншоты](https://user-images.githubusercontent.com/60000063/102028373-e9c2c800-3dba-11eb-896a-413e5ecd563c.png)

**Ответственный**

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
