### ISSUE TITLE
Неправильного размера форма обратной связи (мобильная версия)

### ISSUE THREAD

**Issue by SidorinAA** [netology-code/git-homeworks-neuro-issues#2392]
**Блок "Оставайтесь на связи" имеет слишком маленькую ширину.**

**Шаги по воспроизведению**

1. Открыть главную страницу NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Оставайтесь на связи".

**Ожидаемый результат**

Удобная форма окна.

**Фактический результат**

Ширина формы обратной связи слишком маленькая.

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60000063/102028732-aa957680-3dbc-11eb-992d-7383140de984.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
