### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by IsaevDmitriy** [netology-code/git-homeworks-neuro-issues#2396]
@solarrust

Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи..."

Ожидаемый результат
Текст развернут по ширине формы. Слова не имеют переносов.

Фактический результат
Текстовый блок "Оставайтесь на связи..." некорректно отображается на экране устройства (см. скриншот)
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/28756912/102074812-27f5d100-3e27-11eb-8914-c5554ef10015.png)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
