### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by maliukota** [netology-code/git-homeworks-neuro-issues#240]
_@solarrust нужно срочно исправить!_

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму обратной связи

**Ожидаемый результат**

Форма обратной связи расположена по ширине окна

**Фактический результат**

Форма обратной связи сужена

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/57589422/69068054-b5b19200-0a56-11ea-96f0-39195099d489.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
