### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by SamojlovaA** [netology-code/git-homeworks-neuro-issues#2401]
@solarrust

# Главная страница. Текстовый блок "Оставайтесь на связи ..." слишком сжат и неприятен глазу
## Шаги по воспроизведению
1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.Пролистать страницу до блока "Оставайтесь на связи..."

## Ожидаемый результат
Текст равномерно расположен

## Фактический результат
Текст неравномерно расположен

## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
