### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by mishacausur** [netology-code/git-homeworks-neuro-issues#2402]
Привет @solarrust, тут небольшой бажок:

### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат

Текст не наезжает на изображение

Фактический результат

Текст наезжает на изображение (см. скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншоты

![556](https://user-images.githubusercontent.com/60923960/102122073-cce3ce80-3e66-11eb-9c46-f8dd057f22df.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
