### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by mishacausur** [netology-code/git-homeworks-neuro-issues#2403]
### Форма обратной связи 
слишком сжаты данные, @solarrust

Фактический результат

Пользователям неудобно оставлять фидбек (см. скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты

![image](https://user-images.githubusercontent.com/60923960/102122495-5c897d00-3e67-11eb-8aaa-c4c5f7696906.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
