### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by friklen** [netology-code/git-homeworks-neuro-issues#2406]
# Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

# Ожидаемый результат
Текст не наезжает на изображение

# Фактический результат
Текст наезжает на изображение (см. скриншот)

# Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
@solarrust

![InkedJO0dX6DO_LI](https://user-images.githubusercontent.com/75694906/102234370-a9725f80-3f0a-11eb-870a-812fa5980bb5.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
