### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by friklen** [netology-code/git-homeworks-neuro-issues#2407]
# Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи..."

# Ожидаемый результат 
Текст целиком помещается в форме

# Фактический результат
Текст не помещается в форму целиком, форма сжата (см. скриншот)

# Программное окружение 
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
@solarrust
![faXqhVbn](https://user-images.githubusercontent.com/75694906/102236439-f7886280-3f0c-11eb-8d48-e8fce6802069.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
