### ISSUE TITLE
Текстовый блок  наезжает на изображение

### ISSUE THREAD

**Issue by kondli** [netology-code/git-homeworks-neuro-issues#2408]
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* 
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/71591246/102338544-09b5df80-3fa5-11eb-9bca-d24f6674712e.png)
Браузер: Chrome (70.0.3538.75)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
