### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by kondli** [netology-code/git-homeworks-neuro-issues#2409]
### Главная страница. Форма обратной связи слишком сжата.
Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"
### Ожидаемый результат
Форма обратной связи на всю страницу

### Фактический результат
 Форма обратной связи слишком сжата(см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
![Screenshot_1](https://user-images.githubusercontent.com/71591246/102339765-b5136400-3fa6-11eb-913f-7fcb41761407.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
