### ISSUE TITLE
Chrome mobile fix

### ISSUE THREAD

**Issue by Tequila2908** [netology-code/git-homeworks-neuro-issues#241]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/54939210/69157370-e1378980-0af5-11ea-86a6-24ab04aa1860.png)

@solarrust

**Comment by Tequila2908** [comment]
test

**Comment by Tequila2908** [comment]
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
