### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by NastiaZe** [netology-code/git-homeworks-neuro-issues#2412]
Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат

Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: lenovo  ПО: Windows 10 pro
Браузер: Chrome Версия 87.0.4280.88
Скриншоты
![скриншот 1 проблемы](https://user-images.githubusercontent.com/75496002/102497505-c5e8d600-4089-11eb-8f94-9a0134104188.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
