### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by NastiaZe** [netology-code/git-homeworks-neuro-issues#2413]
### Шаги по воспроизведению:
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
### Ожидаемый результат
Форма обратной связи не сжата

### Фактический результат
Форма обратной связи сжата 
### Скриншот:
![скриншот проблема 2](https://user-images.githubusercontent.com/75496002/102498139-a2725b00-408a-11eb-9904-5173fc41f444.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
