### ISSUE TITLE
Текстовый блок наезжает на изображение на главной странице

### ISSUE THREAD

**Issue by elenkalee** [netology-code/git-homeworks-neuro-issues#2414]
**Шаги воспроизведения:**
1. Открыть главную страницу веб-сайта NeuroStartUp
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение

**Фактический результат:**
Текст наезжает на изображение (см. скриншот)

**Программное окружение:**
Устройство: Honor 10
Android 10
Мобильный браузер: Chrome (87.0.4280.101)

**Скриншоты:**
![Screenshot 2020-12-17 at 19 43 03](https://user-images.githubusercontent.com/75325456/102516795-5205f800-40a0-11eb-9ce7-3d3bee2c0966.png)
 @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
