### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by elenkalee** [netology-code/git-homeworks-neuro-issues#2415]
**Шаги воспроизведения:**

Перейти на страницу "Обратная связь" веб-сайта NeuroStartUp

**Ожидаемый результат:**
Форма обратной связи растягивается по ширине экрана. Текст не обрывается при переносе.

**Фактический результат:**
Форма обратной связи слишком сжата, теряется форматирования текста (см. скриншот)

**Программное окружение:**
Устройство: Honor 10
Android 10
Мобильный браузер: Chrome (87.0.4280.101)

**Скриншоты:**
![image](https://user-images.githubusercontent.com/75325456/102517565-4109b680-40a1-11eb-921a-8b47cd612fbd.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
