### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение 

### ISSUE THREAD

**Issue by PHILIPPVII** [netology-code/git-homeworks-neuro-issues#2419]
Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат:
- Текст не наезжает на изображение

Фактический результат:
- Текст наезжает на изображение (см. скриншот)

Программное окружение
- Устройство: Honor 10 (Android 10)
- Браузер: Chrome (87.0.4280.101)

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/11511803/102680338-4a566880-41f2-11eb-8c2e-f5966259d802.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
