### ISSUE TITLE
Форма обратной связи "Оставайтесь с нами" некорректное масштабирование

### ISSUE THREAD

**Issue by PHILIPPVII** [netology-code/git-homeworks-neuro-issues#2420]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome. Пролистать страницу до блока "Оставайтесь на связи"

Ожидаемый результат
- Форма обратной связи должна расширяться на всю доступную ширину устройства

Фактический результат
- Форма обратной связи имеет не достаточную ширину (см. скриншот)

Программное окружение
- Устройство: Honor 10 (Android 10)
- Браузер: Chrome (87.0.4280.101)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/11511803/102680648-1b8dc180-41f5-11eb-8f2d-8b233492d5d9.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
