### ISSUE TITLE
Форма обратной связи на главной странице слишком сжата.

### ISSUE THREAD

**Issue by Kraus-Artur** [netology-code/git-homeworks-neuro-issues#2422]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока обратной связи

Ожидаемый результат
Форма обратной связи масштабируется во весь экран

Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

Программное окружение
Устройство: Huawei P30 (Android 10)
Браузер: Chrome (87.0.4280.101)
Скриншоты

![](https://camo.githubusercontent.com/8b6aa0acc22de5c12c5a449f639cc7e430299d13757d046bf63f9f010175d210/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
