### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Texnoer** [netology-code/git-homeworks-neuro-issues#2424]
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome. 
1. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма обратной связи должна расширяться на всю доступную ширину устройства

**Фактический результат**
Форма обратной связи имеет не достаточную ширину (см. скриншот)

**Программное окружение**

* Устройство: Honor 10 (Android 10)
* Браузер: Chrome (87.0.4280.101)
![GitHub Logo](https://camo.githubusercontent.com/8b6aa0acc22de5c12c5a449f639cc7e430299d13757d046bf63f9f010175d210/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
