### ISSUE TITLE
Текст наезжает на изображение в мобильном браузере

### ISSUE THREAD

**Issue by AdamovaM** [netology-code/git-homeworks-neuro-issues#2425]
Для пользователя @solarrust.

Лендинг NeuroStartUp. В мобильном браузере текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение с логотипом NeuroStartUp

**Шаги по воспроизведению**

1. Открыть лендинг NeuroStartUp в мобильном браузере Chrome
2. После загрузки на странице отображается брак верстки: текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение с логотипом NeuroStartUp

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![скриншот](https://user-images.githubusercontent.com/73654197/102692619-8ce56880-4225-11eb-988c-d9d98d65f036.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
