### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by TatianaRudikova** [netology-code/git-homeworks-neuro-issues#2427]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![Скриншот](https://user-images.githubusercontent.com/75572588/102695472-a47a1c80-4238-11eb-93e8-2c4154f25b70.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
