### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by TatianaRudikova** [netology-code/git-homeworks-neuro-issues#2428]
# Описание проблемы

Для @solarrust

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму обратной связи

#### Ожидаемый результат

Форма обратной связи масштабируется во весь экран

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншот

![Скриншот](https://user-images.githubusercontent.com/75572588/102695697-09824200-423a-11eb-814e-453e73198f77.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
