### ISSUE TITLE
Основная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by zzz86zzz** [netology-code/git-homeworks-neuro-issues#2431]
@solarrust

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![96339024-79d5e100-109a-11eb-908e-8550343ac021](https://user-images.githubusercontent.com/75853358/102698159-5f5fe580-424c-11eb-874a-b980ed91a4ef.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
