### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by zzz86zzz** [netology-code/git-homeworks-neuro-issues#2432]
@solarrust

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome;
2. Пролистать страницу до формы обратной связи;

### Ожидаемый результат
Форма обратной связи соответствует размерам.

### Фактический результат
Форма обратной связи слишком сжата.

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![12](https://user-images.githubusercontent.com/75853358/102698398-0002d500-424e-11eb-8876-c968d45279b2.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
