### ISSUE TITLE
Problem with the description text. In front of the picture.

### ISSUE THREAD

**Issue by ReVadim** [netology-code/git-homeworks-neuro-issues#2433]
**Home page. text block "Воспользуйтесь современными возможностями..." In front of the picture.**

**Steps to reproduce**

   1. Open the main page of the Neuro startup website in the Chrome mobile browser.
   2. Scroll through the page to the text block "Воспользуйтесь современными возможностями..."

**Expected result**

The text does not run over the image

**Actual result**

The text in front of the picture (see the screenshot).

**Software environment**

- Device: Nokia 3310
- Browser: Mozilla Gecko x86-64

**Screenshot**

![first trouble](https://user-images.githubusercontent.com/75584682/102698479-b961aa80-424e-11eb-8f9e-23d5dc5d7450.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
