### ISSUE TITLE
The feedback form is too narrow

### ISSUE THREAD

**Issue by ReVadim** [netology-code/git-homeworks-neuro-issues#2434]
### **Steps to reproduce**

1. Open the main page of the Neuro startup website in the Chrome mobile browser
2. Open the feedback form

**Expected result**
The text is not compressed, easy to read, without hyphenation

**Actual result**
The text is too compressed at the edges, the words do not fit completely on the lines (see the screenshot)

**Software environment**

- Device: Nokia 3310
- Broeser: Mozilla Gecko x86-64

@solarrust

**screenshot**
![second trouble](https://user-images.githubusercontent.com/75584682/102698768-ef079300-4250-11eb-8750-41c78897cfcf.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
