### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." узкое изображение 

### ISSUE THREAD

**Issue by Dima-Melnikov** [netology-code/git-homeworks-neuro-issues#2437]
## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
## Ожидаемый результат
Изображение должно быть в полном размере 
## Фактический результат
Изображения на сайте слишком узкое
## Программное окружение
+ Устройство: iPhone 8+ (iOS 12.1)
+ Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/73770384/102770991-20d64200-4396-11eb-88cc-69e2e8764ff4.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
