### ISSUE TITLE
Текст наезжает на картинку;

### ISSUE THREAD

**Issue by AlexanderKott** [netology-code/git-homeworks-neuro-issues#2442]
Здравствуйте, @solarrust

Шаги:
1 Зайдите на главную страницу сайта
2 Прокрутите страницу до  "Воспользуйтесь современными возможностями..."

Фактический результат
Текст наезжает на картинку. Смотрите приложенный  скриншот

Ожидаемый результат
Этот текст должен идти до картинки

Среда 
 Браузер Хром Версия 87.0.4280.88

Исправьте пожалуйста

Скриншот 
![logo](https://camo.githubusercontent.com/e60494acb1cedbd04df029d249b408c91cec9268f2cfe98a6d3f9b5bb3d52cb3/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
