### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AlexanderKott** [netology-code/git-homeworks-neuro-issues#2443]
Здравствуйте, @solarrust

Шаги:
1 Зайдите на главную страницу сайта
2 Прокрутите страницу до самого низа где размещена форма "Оставайтесь на связи"

Фактический результат : 
 Форма выглядит черезмерно сжатой (Смотрите приложенный скриншот)

Ожидаемый результат
 Форма должна адаптироваться под размер экрана

Программное окружение
Браузер: Chrome (70.0.3538.75)

![logo](https://camo.githubusercontent.com/8b6aa0acc22de5c12c5a449f639cc7e430299d13757d046bf63f9f010175d210/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
