### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Cossmoz** [netology-code/git-homeworks-neuro-issues#2446]
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![1-1](https://user-images.githubusercontent.com/76067754/103081806-24fe9b80-45f2-11eb-9fef-08f5f97cbf69.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
