### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Cossmoz** [netology-code/git-homeworks-neuro-issues#2447]
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

**Ожидаемый результат**
Форма имеет нормальную ширину

**Фактический результат**
Форма обратной связи слишком узкая.

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![2](https://user-images.githubusercontent.com/76067754/103081907-68f1a080-45f2-11eb-9b5b-c6b81871bff2.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
