### ISSUE TITLE
Главная страница. Форма обратной связи "Оставайтесь на связи..." слишком сжата.

### ISSUE THREAD

**Issue by AleksandrZhuravel** [netology-code/git-homeworks-neuro-issues#245]
### Главная страница. Форма обратной связи "Оставайтесь на связи..." слишком сжата.
Шаги по воспроизведению:

1.	Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1.	Пролистать страницу до формы обратной связи "Оставайтесь на связи..."

**Ожидаемый результат:**
Ширина формы обратной связи по соответствует ширине страницы.

**Фактический результат:**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение:**
•	Устройство: iPhone 8+ (iOS 12.1)
•	Браузер: Chrome (70.0.3538.75)

**Скриншоты:**
 ![Screen](https://github.com/AleksandrZhuravel/trash/blob/master/Screen2.png?raw=true)
**Комментарий:** @solarrust прошу принять к сведению.

**Comment by AleksandrZhuravel** [comment]
@solarrust прошу принять к сведению.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
