### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Yuliyarubtsova** [netology-code/git-homeworks-neuro-issues#2450]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат** 

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![git-homeworks_issue-example md at master · netolog](https://user-images.githubusercontent.com/75926926/103136592-b2c6ad80-46fc-11eb-86e9-adbeb4fcf541.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
