### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Yuliyarubtsova** [netology-code/git-homeworks-neuro-issues#2451]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи

**Ожидаемый результат**

Форма занимает не менее 90% ширины экрана

**Фактический результат**

Форма занимает 50% ширины экрана

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![изображение_2020-12-25_220445](https://user-images.githubusercontent.com/75926926/103136672-4ef0b480-46fd-11eb-8337-d39015af339b.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
