### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by YuliyaMuraveva** [netology-code/git-homeworks-neuro-issues#2455]
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат:**
Форма развернута на ширину экрана

**Фактический результат:**
Форма слишком сжата

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67 (416×740) 2020-12-26 20-31-20](https://user-images.githubusercontent.com/59201000/103156404-5a091a80-47b9-11eb-9eb3-047ff965b9e0.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
