### ISSUE TITLE
сплющенная форма обратной связи

### ISSUE THREAD

**Issue by Warlokk** [netology-code/git-homeworks-neuro-issues#2456]
@solarrust ошибка в верстке - форма обратной связи веб-сайта NeuroStartUp не растянута на весь экран.
**Программное окружение:**
*Устройство: iPhone 8+ (iOS 12.1)
*Браузер: Chrome (70.0.3538.75)
![форма](https://user-images.githubusercontent.com/50544036/103172344-39e66380-486c-11eb-9b11-56547ec11884.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
