### ISSUE TITLE
текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by Warlokk** [netology-code/git-homeworks-neuro-issues#2457]
@solarrust ошибка в верстке - текст перекрывается картинкой на главной странице веб-сайта NeuroStartUp.
**Программное окружение:**
*Устройство: iPhone 8+ (iOS 12.1)
*Браузер: Chrome (70.0.3538.75)

![скрин](https://user-images.githubusercontent.com/50544036/103172203-3acac580-486b-11eb-9b4c-eb202e1908e7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
