### ISSUE TITLE
Текстовый блок "Воспользуйтесь..." на главной странице наезжает на изображение

### ISSUE THREAD

**Issue by AnastasiaMR** [netology-code/git-homeworks-neuro-issues#2458]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/74010731/103177991-1a613200-4890-11eb-97b4-4b48bf8808d3.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
