### ISSUE TITLE
Форма "Обратная связь" слишком сжата

### ISSUE THREAD

**Issue by AnastasiaMR** [netology-code/git-homeworks-neuro-issues#2459]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Обратная связь"
Ожидаемый результат
Форма открыта на всю ширину страницы

Фактический результат
Форма сильно сжата (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/74010731/103178126-2b5e7300-4891-11eb-9250-c8c501bf1d51.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
