### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." накладывается на изображение

### ISSUE THREAD

**Issue by AleksandrZhuravel** [netology-code/git-homeworks-neuro-issues#246]
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." накладывается на изображение

**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текстовый блок "Воспользуйтесь современными возможностями..." расположен выше изображения

**Фактический результат:**
Текстовый блок "Воспользуйтесь современными возможностями..." накладывается на изображение (см. скриншот)

**Программное окружение:**
•	Устройство: iPhone 8+ (iOS 12.1)
•	Браузер: Chrome (70.0.3538.75)

**Скриншоты:**
 ![Screen](https://github.com/AleksandrZhuravel/trash/blob/master/Screen1.png?raw=true)
**Комментарий:** @solarrust прошу принять к сведению.

**Comment by AleksandrZhuravel** [comment]
@solarrust прошу принять к сведению

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
