### ISSUE TITLE
Форма "Обратная связь" слишком сжата

### ISSUE THREAD

**Issue by DElena90** [netology-code/git-homeworks-neuro-issues#2461]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Обратная связь"

**Ожидаемый результат:**

Форма открыта на всю ширину страницы

**Фактический результат:**

Форма сильно сжата (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/75312846/103204248-d7f03180-4931-11eb-8bbf-c2d3fbc079d5.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
