### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by EliseevG787** [netology-code/git-homeworks-neuro-issues#2462]
### Шаги по воспроизведению 

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
	
### Ожидаемый результат
Текст не наезжает на изображение
### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/54417477/103221462-c0b24380-4933-11eb-824b-897b4fa5ac5d.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
