### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by EliseevG787** [netology-code/git-homeworks-neuro-issues#2463]
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Нажать на кнопку "Обратная связь"
### Ожидаемый результат
Ширина формы обратной связи соответствует ТЗ.
### Фактический результат
Форма обратной связи слишком сжата. (см. скриншот)
### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![image](https://user-images.githubusercontent.com/54417477/103222736-bc872580-4935-11eb-8f2c-577b80cb1f81.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
