### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by stdd0101** [netology-code/git-homeworks-neuro-issues#2467]
@solarrust

## Описание проблемы
Главная страница. Форма обратной связи слишком сжата.

### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат
Форма обратной связи соответствует макету

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншоты
![image](https://user-images.githubusercontent.com/76597782/103235420-94aab880-495b-11eb-8ff1-c4d1719d2af3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
