### ISSUE TITLE
Текст в середине главной страницы наезжает на изображение

### ISSUE THREAD

**Issue by VeraKofeinikova** [netology-code/git-homeworks-neuro-issues#247]
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение монитора

for @solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст находится выше изображения монитора, не налезая на него

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**
![trouble-text-on-pic](https://user-images.githubusercontent.com/47572808/69251131-ff6abb80-0bc1-11ea-8dd7-c38fc8c8237a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
