### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by DmitrievDA97** [netology-code/git-homeworks-neuro-issues#2470]
@solarrust 
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![Screenshot_7](https://user-images.githubusercontent.com/76554635/103279067-0d525900-49de-11eb-9ec8-aac816cbfee5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
