### ISSUE TITLE
Форма обратной связи на главной странице отображается сжатой

### ISSUE THREAD

**Issue by DmitrievDA97** [netology-code/git-homeworks-neuro-issues#2471]
@solarrust 
# Описание проблемы  #
Главная страница. Блок обратной сжат по горизонтали

**Шаги по воспроизведению**
1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1.Пролистать страницу до блока обратной связи

**Ожидаемый результат**
Форма обратной связи отображается корректно 

**Фактический результат**
Форма обратной связи слишком сжата (см. Скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![Screenshot_8](https://user-images.githubusercontent.com/76554635/103279630-3f17ef80-49df-11eb-9ef3-cb2c556ccb31.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
