### ISSUE TITLE
Некорректное расположение текста на стартовой странице мобильного приложения

### ISSUE THREAD

**Issue by palatniks** [netology-code/git-homeworks-neuro-issues#2472]
### Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
### Шаги по воспроизведению

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
@solarrust

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/45352400/103286221-eb160680-49f0-11eb-8e9f-96660a9d463e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
