### ISSUE TITLE
Форма обратной связи меньше, чем экран

### ISSUE THREAD

**Issue by palatniks** [netology-code/git-homeworks-neuro-issues#2473]
### Описание проблемы
**Форма обратной связи. Располагается по центру экрана устройства, оставляя много свободного места.** 

**Шаги по воспроизведению**
Открыть контактную форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

**Ожидаемый результат**
Форма занимает всю страницу

**Фактический результат**
Форма расположена по центру экрана устройства (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
@solarrust

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/45352400/103286759-01709200-49f2-11eb-9982-8fa625ffddbf.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
