### ISSUE TITLE
Слишком узкая форма обратной связи на в мобильной версии страницы NeuroStartUp 

### ISSUE THREAD

**Issue by Filosoff42** [netology-code/git-homeworks-neuro-issues#2475]
@solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи "Оставайтесь на связи"

**Ожидаемый результат**

Ширина блока с формой обратной связи адаптируется к краям страницы на используемом устройстве

**Фактический результат**

Блок с формой обратной связи слишком узкий (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/76683029/103289127-7d210d80-49f7-11eb-8705-a91dd2808cde.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
