### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by plo-vi** [netology-code/git-homeworks-neuro-issues#2476]
## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

## Программное окружение
**Устройство:** iPhone 8+ (iOS 12.1)
**Браузер:** Chrome (70.0.3538.75)

## Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/75584040/103305071-4a890c00-4a1b-11eb-89d3-0c0195c23d59.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
