### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата (менее 1/2 экрана)

### ISSUE THREAD

**Issue by plo-vi** [netology-code/git-homeworks-neuro-issues#2477]
## Шаги по воспроизведению
1. Открыть страницу "Обратная связь" веб-сайта NeuroStartUp в мобильном браузере Chrome

### Ожидаемый результат
Форма обратной связи занимает всю ширину экрана

### Фактический результат
Форма обратной связи расположена в центральной части экрана в пропорциях правый столбец:форма:левый столбец - 100px:190px:100px соответственно (см. скриншот)

## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

## Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/75584040/103305936-6f7e7e80-4a1d-11eb-8036-ec8ba8a10735.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
