### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by mona52** [netology-code/git-homeworks-neuro-issues#2478]
@solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone XS (iOS 14.3)
Браузер: Chrome (87.0.4280.77)

**Скриншоты**
![issue1](https://user-images.githubusercontent.com/60571791/103465546-b5a14e00-4d4d-11eb-9919-15c7c05ec6f4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
