### ISSUE TITLE
Форма обратной связи "Оставайтесь на связи" слишком сжата в мобильной версии сайта

### ISSUE THREAD

**Issue by mona52** [netology-code/git-homeworks-neuro-issues#2479]
@solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма обратной связи "Оставайтесь на связи" не сжата

**Фактический результат**
Форма обратной связи "Оставайтесь на связи слишком сжата"

**Программное окружение**
Устройство: iPhone XS (iOS 14.3)
Браузер: Chrome (87.0.4280.77)

**Скриншоты**
![issue2](https://user-images.githubusercontent.com/60571791/103465680-49274e80-4d4f-11eb-9a7c-a9b1088c6383.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
