### ISSUE TITLE
Проблемы с шириной у формы обратной связи на главной странице

### ISSUE THREAD

**Issue by VeraKofeinikova** [netology-code/git-homeworks-neuro-issues#248]
### Форма обратной связи на главной странице слишком сжата, что выглядит неэстетично и может затруднить введение данных в поля формы

for @solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до самого низа к форме обратной связи

**Ожидаемый результат**

Ширина формы соответствует размерам экрана с соответствующими макету небольшими отступами от краев

**Фактический результат**

Форма ужата по ширине от размеров экрана примерно вдвое, в результате чего она выглядит как длинная отцентрованная колбаса (см. скриншот)

**Программное окружение**

-  Устройство: iPhone 8+ (iOS 12.1)
-  Браузер: Chrome (70.0.3538.75)

**Скриншот**
![trouble-form-for-connection](https://user-images.githubusercontent.com/47572808/69252512-2629f180-0bc4-11ea-858b-8182680f7452.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
