### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by OksanaTarun** [netology-code/git-homeworks-neuro-issues#2481]
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма не сжата, занимает весь экран

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/76516037/103474884-2b8ecf00-4db9-11eb-88ca-52df89f0f687.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
