### ISSUE TITLE
Форма "Оставайтесь на связи" не адаптируется к ширине экрана

### ISSUE THREAD

**Issue by kseniabobkova** [netology-code/git-homeworks-neuro-issues#2488]
FIY @solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
2. Проскролить страницу до формы обратной связи "Оставайтесь на связи"

**Ожидаемый результат**

Ширина блока с формой обратной связи адаптируется к ширине экрана на используемом устройстве

**Фактический результат**

Ширина блока с формой обратной связи  на используемом устройстве

**Окружение**

Device: Samsung Galaxy J2 Core SM-J260F 
OS: Android 8.1.0 
Browser: Google Chrome 
Version: 87.0.4280.101

**Скриншот**

![2](https://user-images.githubusercontent.com/76531306/103663535-42345200-4f82-11eb-9f5c-dc3b944f5bff.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
