### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by kseniabobkova** [netology-code/git-homeworks-neuro-issues#2489]
FIY @solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
2. Пролистать страницу до формы обратной связи "Оставайтесь на связи"

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Device: Samsung Galaxy J2 Core SM-J260F
OS: Android 8.1.0
Browser: Google Chrome
Version: 87.0.4280.101

**Скриншот**

![1](https://user-images.githubusercontent.com/76531306/103664922-da7f0680-4f83-11eb-8613-a8047a3e65b8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
