### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by nicys** [netology-code/git-homeworks-neuro-issues#2490]
@solarrust

## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![1](https://user-images.githubusercontent.com/76640426/103736040-fb963480-5021-11eb-8625-e8b3b35a4d03.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
