### ISSUE TITLE
Форма "Оставайтесь на связи" не адаптируется к ширине экрана

### ISSUE THREAD

**Issue by nicys** [netology-code/git-homeworks-neuro-issues#2491]
@solarrust

## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
1. Проскролить страницу до формы обратной связи "Оставайтесь на связи"

### Ожидаемый результат
Ширина блока с формой обратной связи адаптируется к ширине экрана на используемом устройстве

### Фактический результат
Ширина блока с формой обратной связи на используемом устройстве

**Окружение**

Device: Samsung Galaxy J2 Core SM-J260F
OS: Android 8.1.0
Browser: Google Chrome
Version: 87.0.4280.101

*Прилагаемый скрин*
![2](https://user-images.githubusercontent.com/76640426/103736523-03a2a400-5023-11eb-9cb8-c807c845af66.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
