### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by AlexandroHubZaytsev** [netology-code/git-homeworks-neuro-issues#2492]
@solarrust
Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: Honor 9 Lite LLD-L31
OS: Android 9
Браузер: Chrome (Версия 87.0.4280.101)
Скриншоты
![текстовый блок](https://user-images.githubusercontent.com/75636649/103764718-07d3bf00-502d-11eb-9964-5fa8af825264.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
