### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by rabmail** [netology-code/git-homeworks-neuro-issues#2493]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
- Текст не наезжает на изображение

**Фактический результат**

- Текст наезжает на изображение (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот** 
![nsu1](https://user-images.githubusercontent.com/76004636/103766076-3f436b00-502f-11eb-9ee0-99c42df7a1c5.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
