### ISSUE TITLE
Блок текста в форме "Оставайтесь на связи" не адаптируется к ширине экрана

### ISSUE THREAD

**Issue by AlexandroHubZaytsev** [netology-code/git-homeworks-neuro-issues#2494]
@solarrust
Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
2. Проскролить страницу до формы обратной связи "Оставайтесь на связи"
Ожидаемый результат
Ширина блока с формой обратной связи адаптируется к ширине экрана на используемом устройстве и отображается на всем экране.

Фактический результат
Ширина блока с формой обратной связи на используемом устройстве  слишком сжата (см. скриншот)

Окружение

Device: Honor 9 Lite  LLD-L31
OS: Android 9
Браузер: Chrome (Версия 87.0.4280.101)
Скриншот
![2 issue](https://user-images.githubusercontent.com/75636649/103766588-1d96b380-5030-11eb-98fa-048a9afb8538.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
