### ISSUE TITLE
Не выполнена адаптивная верстка формы под все разрешения экрана.

### ISSUE THREAD

**Issue by rabmail** [netology-code/git-homeworks-neuro-issues#2495]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
2. Проскролить страницу до формы обратной связи "Оставайтесь на связи"

**Ожидаемый результат**

- Ширина блока с формой обратной связи адаптируется к ширине экрана на используемом устройстве.

**Фактический результат**

- Ширина блока с формой обратной связи не  адаптируется к ширине экрана на используемом устройстве.

**Окружение**

- Device: Ulephone Armor W3
- OS: Android 9.0
- Browser: Google Chrome
- Version: 87.0.4280.101

**Скриншот**
![nsu2](https://user-images.githubusercontent.com/76004636/103767429-a7934c00-5031-11eb-8b7b-c65250d8c098.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
