### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Lada34** [netology-code/git-homeworks-neuro-issues#2496]
**Шаги по воспроизведению** 

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

- Текст не наезжает на изображение
**Фактический результат**

- Текст наезжает на изображение (см. скриншот)
**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
**Скриншот**
![Задание3 1](https://user-images.githubusercontent.com/76051368/103794347-ac69f700-5055-11eb-9ad0-c150767d6eaf.png)
**@solarrust**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
