### ISSUE TITLE
Форма обратной связи на сайте слишком сжата.

### ISSUE THREAD

**Issue by Lada34** [netology-code/git-homeworks-neuro-issues#2497]
**Шаги по воспроизведению** 

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Нажать кнопку обратной связи в левом нижнем углу экрана

**Ожидаемый результат**

- Окно формы обратной связи открывается отдельным всплывающим окном шириной в 10 сантиметров.
- Текстовая информация каждого предложения не более двух строк.

**Фактический результат**

- Окно открывается шириной 5 сантиметров (см. скриншот)
- Предложения расположены в четыре и более строки.

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**
![Задание3 1](https://user-images.githubusercontent.com/76051368/103795790-788fd100-5057-11eb-92d0-5c5ff56e5174.png)
**@solarrust**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
