### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by n3xth0p** [netology-code/git-homeworks-neuro-issues#2499]
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи 

#### Ожидаемый результат

Форма обратной связи: текст, блоки ввода
должны занимать всю ширину экрана мобильного устройства.

#### Фактический результат

Форма обратной связи слишком сжата. (см. скриншот)

#### Программное окружение

* Устройство: Huawei P20 Pro  (Android 10)
* Браузер: Chrome (70)

#### Скриншоты

![form](https://user-images.githubusercontent.com/55766610/103832932-a5140f00-5090-11eb-9715-7b7257b0502c.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
