### ISSUE TITLE
Текст наезжает на картинку; Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Anasteisha5** [netology-code/git-homeworks-neuro-issues#25]
1)Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)
https://camo.githubusercontent.com/e648681205a1dfdf6ed69784e1311b18ca924856/68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67 

2)Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат
Форма обратной связи в читабельном варианте, более широкая

Фактический результат
Форма обратной связи слишком сжата.
https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67
@solarrust

**Comment by solarrust** [comment]
Добрый день. 

Нужно было создать два issue. По одному на каждое замечание.
