### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Svetlana0406** [netology-code/git-homeworks-neuro-issues#2504]
@solarrust 
Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот

![Screenshot_1](https://user-images.githubusercontent.com/75991471/103924256-d4755b00-5126-11eb-994c-2da0999de0d9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
