### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Svetlana0406** [netology-code/git-homeworks-neuro-issues#2505]
@solarrust 
Описание проблемы
Главная страница. Текстовый блок "Оставайтесь на связи" слишком сжат
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до формы обратной связи "Оставайтесь на связи"
Ожидаемый результат
Форма обратной связи нормального размера

Фактический результат
Форма обратной связи слишком сжата

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![Screenshot_2](https://user-images.githubusercontent.com/75991471/103924914-d12e9f00-5127-11eb-9821-30bbfc352d71.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
