### ISSUE TITLE
Блок с текстом на главной странице "Воспользуйтесь современными возможностями..." наезжает на изображение.

### ISSUE THREAD

**Issue by DarcenRal** [netology-code/git-homeworks-neuro-issues#2508]
@solarrust 

**Описание проблемы**

Главная страница. Блок с текстом "Воспользуйтесь современными возможностями..." наезжает на изображение.

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: Ноутбук  Acer Aspire E 15
- Браузер: Chrome (Версия 87.0.4280.88)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/75911924/103933794-01306f00-5135-11eb-922e-6d5ae6f88f02.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
