### ISSUE TITLE
Форма "Оставайтесь на связи" не адаптируется к ширине экрана

### ISSUE THREAD

**Issue by DarcenRal** [netology-code/git-homeworks-neuro-issues#2509]
@solarrust

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
- Проскролить страницу до формы обратной связи "Оставайтесь на связи"

**Ожидаемый результат**

Ширина блока с формой обратной связи адаптируется к ширине экрана на используемом устройстве

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: Ноутбук Acer Aspire E 15
- Браузер: Chrome (Версия 87.0.4280.88)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/75911924/103938097-c7fafd80-513a-11eb-8d31-830569b9bbf7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
