### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by rasul230885** [netology-code/git-homeworks-neuro-issues#2512]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![777](https://user-images.githubusercontent.com/76871357/103990244-f3fd9980-51a1-11eb-830a-a7961a513af2.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
