### ISSUE TITLE
При переходе по ссылке форма Обратной связи слишком сжата

### ISSUE THREAD

**Issue by rasul230885** [netology-code/git-homeworks-neuro-issues#2513]
Описание проблемы
Главная страница. Текстовый формат "Оставайтесь на связи" слишком сжат

Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Yandex
Пролистать страницу до формы обратной связи "Оставайтесь на связи"

Ожидаемый результат
Форма обратной связи нормального размера

Фактический результат
Форма обратной связи слишком сжата

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Yandex

![88](https://user-images.githubusercontent.com/76871357/103991860-5a83b700-51a4-11eb-9896-62a2a7cb5068.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
