### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by 2328960** [netology-code/git-homeworks-neuro-issues#252]
@solarrust

### Страница с формой обратной связи. Блок слишком узкий.

**Шаги по воспроизведению**

1. Открыть страницу обратной связи на веб-сайте NeuroStartUp в мобильном браузере Chrome.

**Ожидаемый результат**
Форма обратной связи соответствует ширине экрана.

**Фактический результат**
Форма обратной связи намного уже, чем ширина экрана.

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншот
![2](https://user-images.githubusercontent.com/57352439/69349383-14fae680-0c91-11ea-975e-14bf3b5ad9bd.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
