### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by 6apblra58** [netology-code/git-homeworks-neuro-issues#2520]
# Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![image](https://user-images.githubusercontent.com/76905867/104092113-df4cfe80-5292-11eb-8d73-366467569eb6.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
