### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by 6apblra58** [netology-code/git-homeworks-neuro-issues#2521]
# Главная страница. "Оставайтесь на связи". Форма обратной связи слишком сжата
**Шаги по воспроизведению**
1. Открыть главную страницу "Оставайтесь на связи" в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи".

**Ожидаемый результат**
Расширение блока

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![image](https://user-images.githubusercontent.com/76905867/104092253-c1cc6480-5293-11eb-8799-497d958224bb.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
