### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by verakirillova** [netology-code/git-homeworks-neuro-issues#2522]
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**

Текст не наезжает на изображение

**Фактический результат:**

Текст наезжает на изображение (см. скриншот)

![image](https://user-images.githubusercontent.com/76569893/104105140-4b445c80-52bd-11eb-8154-42b06b5cdd96.png)

**Программное окружение:**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
