### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by l0197d** [netology-code/git-homeworks-neuro-issues#2523]
@solarrust

Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению:
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат:
Текст не наезжает на изображение

Фактический результат:
Текст наезжает на изображение (см. скриншот)

Программное окружение:
Устройство: iPhone 8+ (iOS 12.1)

Браузер: Chrome (70.0.3538.75)

Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/76581010/104105447-28b34300-52bf-11eb-80f9-5a311f542751.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
