### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by l0197d** [netology-code/git-homeworks-neuro-issues#2524]
@solarrust

Описание проблемы
Форма обратной связи слишком сжата
Шаги по воспроизведению:
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до формы обратной связи
Ожидаемый результат:
Размещенный на форме текст не разбит переносом

Фактический результат:
Текст разбит из-за недостаточной ширины формы (см. скриншот)

Программное окружение:
Устройство: iPhone 8+ (iOS 12.1)

Браузер: Chrome (70.0.3538.75)

Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/76581010/104105482-78920a00-52bf-11eb-90b6-cb23fb05150a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
