### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by verakirillova** [netology-code/git-homeworks-neuro-issues#2525]
### Главная страница. "Оставайтесь на связи". Форма обратной связи слишком сжата

**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат:**

Открывается форма обратной связи. Ширина блока с формой обратной связи адаптируется к ширине экрана на используемом устройстве.

**Фактический результат:**

Открывается форма обратной связи. Форма обратной связи слишком сжата (см. скриншот)

![image](https://user-images.githubusercontent.com/76569893/104105533-dd4d6480-52bf-11eb-89ec-16cf74df7554.png)

**Программное окружение:**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
