### ISSUE TITLE
Текст наезжает на картинку.

### ISSUE THREAD

**Issue by vadikpkin** [netology-code/git-homeworks-neuro-issues#253]
# Текст наезжает на картинку.
## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат
Текст не наезжает на изображение
## Фактический результат
Текст наезжает на изображение (см. скриншот)
## Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

## Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/56551614/69482177-f891b200-0e28-11ea-88a8-861def78c3d2.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
