### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Irina04041987** [netology-code/git-homeworks-neuro-issues#2530]
**Описание проблемы**
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**
1.	Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.	Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
•	Устройство: iPhone 8+ (iOS 12.1)
•	Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![11111111111111111](https://user-images.githubusercontent.com/74503846/104118343-59d05980-5339-11eb-838f-52a7817a3829.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
