### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Irina04041987** [netology-code/git-homeworks-neuro-issues#2531]
**Форма обратной связи слишком узкая**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы для заполнения "Оставайтесь на связи"

**Ожидаемый результат**
Форма удобна для использования и читабельна

**Фактический результат**
Форма сжата, текст сложно прочитать (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![22222222222222222222222222](https://user-images.githubusercontent.com/74503846/104118458-65705000-533a-11eb-86e7-3ef4434d2673.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
