### ISSUE TITLE
Главная страница. Текстовый блок наезжает на светлый фон и сливается с ним

### ISSUE THREAD

**Issue by Natalia-Bondarenko** [netology-code/git-homeworks-neuro-issues#2532]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат

Текст "Воспользуйтесь современными возможностями..." должен находиться на синем фоне, выше изображения ноутбука с эмблемой NeuroStartUp.

### Фактический результат

Текст наезжает на светлый фон (см. скриншот)

### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот

![2021 01 10_First problem_1](https://user-images.githubusercontent.com/18085714/104120080-1bd93280-5345-11eb-98af-0ab8e280fad6.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
