### ISSUE TITLE
Главная страница. Форма обратной связи в мобильном браузере слишком сжата

### ISSUE THREAD

**Issue by Natalia-Bondarenko** [netology-code/git-homeworks-neuro-issues#2533]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
1. Пролистать страницу до блока "Оставайтесь на связи".

### Ожидаемый результат

Форма "Оставайтесь на связи" должна быть адаптирована под мобильный браузер, т е слова должны быть написаны целиком, шрифт и боковые поля адаптированы под мобильный браузер.

### Фактический результат

Переносы части слов на новую строку, большой шрифт, текст сильно сгруппирован, широкие поля по бокам (см. скриншот)

### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот

![2021 01 10_Second problem](https://user-images.githubusercontent.com/18085714/104120165-b5a0df80-5345-11eb-8906-213a24a75dbe.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
