### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by alexp995** [netology-code/git-homeworks-neuro-issues#2534]
@solarrust

Описание проблемы

Главная страница. Блок с текстом "Воспользуйтесь современными возможностями..." наезжает на изображение.

Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат

Текст не наезжает на изображение

Фактический результат

Текст наезжает на изображение (см. скриншот)

Программное окружение

Устройство: Iphone 7 (ios 14.1)
Браузер: Chrome (Версия 87.0.4280.88)

Скриншот

![image](https://user-images.githubusercontent.com/73243703/104120997-7b8b0a00-5354-11eb-94ef-6c5ff05fd363.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
