### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by alexp995** [netology-code/git-homeworks-neuro-issues#2535]
### Шаги по воспроизведению:

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до формы обратной связи

### Ожидаемый результат:

Форма обратной связи на всю ширину экрана

### Фактический результат:

Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение:

Устройство: Iphone 7 (ios 14.1)
Браузер: Chrome (70.0.3538.75)

### Скриншот:

![image](https://user-images.githubusercontent.com/73243703/104121162-bb062600-5355-11eb-8fd8-9a6dec35d955.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
