### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

### ISSUE THREAD

**Issue by Orazalina** [netology-code/git-homeworks-neuro-issues#2536]
Шаги:
   1 Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
   2 Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

@solarrust 

![Screenshot_9](https://user-images.githubusercontent.com/76688678/104124770-bf920500-537c-11eb-9e7c-75d7301a58bb.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
