### ISSUE TITLE
Форма "Обратная связь" слишком сжата

### ISSUE THREAD

**Issue by Aleksey-Bur** [netology-code/git-homeworks-neuro-issues#2539]
@solarrust
  **Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Нажать на кнопку "Обратная связь"
  
  **Ожидаемый результат**
Форма открыта на всю ширину страницы

  **Фактический результат**
Форма обратной связи слишком сжата. (см. скриншот)

  **Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/76645207/104126651-d6315f80-536e-11eb-94e5-19c9f134bc84.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
