### ISSUE TITLE
Форма обратной связи "Оставайтесь на связи..." слишком сжата.

### ISSUE THREAD

**Issue by vadikpkin** [netology-code/git-homeworks-neuro-issues#254]
# Форма обратной связи "Оставайтесь на связи..." слишком сжата.
### Шаги по воспроизведению:

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи "Оставайтесь на связи..."

## Ожидаемый результат:
Ширина формы обратной связи по соответствует ширине страницы.

## Фактический результат:
Форма обратной связи слишком сжата (см. скриншот)

Программное окружение:

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
![69349383-14fae680-0c91-11ea-975e-14bf3b5ad9bd](https://user-images.githubusercontent.com/56551614/69482220-75bd2700-0e29-11ea-839a-cbdaa223f655.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
