### ISSUE TITLE
Форма "Обратная связь" слишком сжата

### ISSUE THREAD

**Issue by EkaterinaPeregudova** [netology-code/git-homeworks-neuro-issues#2541]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Нажать на кнопку "Обратная связь"

**Ожидаемый результат**
Форма открыта на всю ширину страницы

**Фактический результат**
Форма обратной связи слишком сжата. (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
 
@solarrust
Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/76491846/104133108-692fc100-5392-11eb-9388-a1dbec3df7fa.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
