### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Darya-Rak** [netology-code/git-homeworks-neuro-issues#2542]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

Скриншоты
![image](https://user-images.githubusercontent.com/77027602/104134009-2a9d0500-5398-11eb-96da-4d7e606d2cd2.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
