### ISSUE TITLE
Форма "Обратная связь" слишком сжата

### ISSUE THREAD

**Issue by Darya-Rak** [netology-code/git-homeworks-neuro-issues#2543]
Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Нажать на кнопку "Обратная связь"
Ожидаемый результат
Форма открыта на всю ширину страницы

Фактический результат
Форма обратной связи слишком сжата. (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust
Скриншот
![image](https://user-images.githubusercontent.com/77027602/104134170-13aae280-5399-11eb-988e-bbc93d93e566.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
