### ISSUE TITLE
На главной странице текст "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by tosolya** [netology-code/git-homeworks-neuro-issues#2544]
**@solarrust**

**Шаги по воспроизведению**
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

![текст на картинке](https://user-images.githubusercontent.com/75759854/104134134-e6f6cb00-5398-11eb-88dd-4b796f0f9027.png)
**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**Скриншоты**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
