### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by tosolya** [netology-code/git-homeworks-neuro-issues#2545]
**@solarrust**

**Шаги по воспроизведению**
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
*  Найти меню "Оставайтесь на связи"

**Ожидаемый результат**
Меню "Оставайтесь на связи" выглядит нормально, раскрывается на ширину всей страницы, удобен для заполнения

**Фактический результат**
Меню "Оставайтесь на связи" сжалось  внизу экрана и все поля для E-mail и Имени очень узкие, что неудобно и не красиво
 (см. скриншот)
![обр связь](https://user-images.githubusercontent.com/75759854/104134569-78ffd300-539b-11eb-9c4d-91d257ca25ed.png)
**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
