### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by aov4in** [netology-code/git-homeworks-neuro-issues#2546]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

![Screen_Zadanie_3 1](https://user-images.githubusercontent.com/73604679/104136142-74d8b300-53a5-11eb-9cea-fc938438698b.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
