### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by aov4in** [netology-code/git-homeworks-neuro-issues#2547]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. В меню открыть "Оставайтесь на связи"

**Ожидаемый результат**
Меню "Оставайтесь на связи" выглядит нормально, раскрывается на ширину всей страницы, удобен для заполнения

**Фактический результат**
Меню "Оставайтесь на связи" сжалось внизу экрана и все поля для E-mail и Имени очень узкие, что неудобно и не красиво. Скрин бага прикрепляю.
![Screen_Zadanie_3 1-2](https://user-images.githubusercontent.com/73604679/104136438-1e6c7400-53a7-11eb-8532-f880e95a6c03.png)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
