### ISSUE TITLE
Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Alexlopotov** [netology-code/git-homeworks-neuro-issues#2548]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
@solarrust
Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/75681881/104163274-3542b300-5407-11eb-870e-61fcde633e45.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
