### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Alexlopotov** [netology-code/git-homeworks-neuro-issues#2549]
Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
В меню открыть "Оставайтесь на связи"
Ожидаемый результат
Меню "Оставайтесь на связи" выглядит нормально, раскрывается на ширину всей страницы, удобен для заполнения

Фактический результат
Меню "Оставайтесь на связи" сжалось внизу экрана и все поля для E-mail и Имени очень узкие, что неудобно и не красиво. Скрин бага прикрепляю. @solarrust
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/75681881/104163415-733fd700-5407-11eb-8cb3-450ce234c3f5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
