### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by lord6498** [netology-code/git-homeworks-neuro-issues#2550]
### Описание проблемы

Главная страница. **Текстовый блок "Воспользуйтесь современными возможностями..."** **наезжает на изображение**

_Шаги по воспроизведению_

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

_Ожидаемый результат_

Текст не наезжает на изображение

_Фактический результат_

Текст наезжает на изображение (см. скриншот)

_ Программное окружение_

Устройство: iPhone 10 (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/17721357/104173657-29f78380-5417-11eb-972a-d8e72f927a17.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
