### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by lord6498** [netology-code/git-homeworks-neuro-issues#2551]
### Шаги по воспроизведению

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Нажать на кнопку "Обратная связь"

_Ожидаемый результат_
Форма открыта на всю ширину страницы

_Фактический результат_
Форма обратной связи слишком сжата. (см. скриншот)

_Программное окружение_
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust 
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/17721357/104175164-c3269a00-5417-11eb-8467-13e38676f9f7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
