### ISSUE TITLE
Текст наезжает на картинку на главной странице

### ISSUE THREAD

**Issue by redzhina** [netology-code/git-homeworks-neuro-issues#2556]
**Шаги:**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение

**Фактический результат:** 
Текст наезжает на изображение (см. скриншот).

**Программное окружение:**
Устройство: iPhone 8+ (iOS 14.3)
Браузер: Chrome (70.0.3538.75)

**Скриншот:**
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/76973287/104243857-4f65ab00-5472-11eb-8177-c262f192a3d8.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
