### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by redzhina** [netology-code/git-homeworks-neuro-issues#2557]
**Шаги:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы "Оставайтесь на связи"

**Ожидаемый результат:**
Форма "развернута" по размеру дисплея смартфона, слова не переносятся на слоги.

**Фактический результат:**
Форма сжата и отображается не по формату дисплея, слова переносятся на слоги и "скомканы". 

**Программное окружение:**
Устройство: iPhone 8+ (iOS 14.3)
Браузер: Chrome (70.0.3538.75)

**Скриншот:**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/76973287/104244593-cb142780-5473-11eb-9bac-deb6909152cd.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
