### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by YuliyaGer** [netology-code/git-homeworks-neuro-issues#256]
@solarrust 
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока с формой обратной связи

**Ожидаемый результат**
Форма обратной связи соответствует ширине экрана 

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/56927385/69496154-1b32d200-0ee0-11ea-9620-23f2c1bcf9c3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
