### ISSUE TITLE
Исправление в мобильном приложении

### ISSUE THREAD

**Issue by roandr1970** [netology-code/git-homeworks-neuro-issues#26]
@solarrust
# **Описание проблемы**
1. **Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
2. **Форма _"Оставайтесь на связи"_ слишком сжата**

### **Шаги по воспроизведению**

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
3.  Пролистать страницу до блока "Оставайтесь на связи"

**_Ожидаемый результат_**

Текст не наезжает на изображение.
Форма "Оставайтесь на связи" принимает нормальный вид.

**_Фактический результат_**

Текст наезжает на изображение (см. скриншот).
Форма "Оставайтесь на связи"  вытянута (см. скриншот).

**_Программное окружение_**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты
![1](https://user-images.githubusercontent.com/48286984/54333662-ca729600-463c-11e9-96ec-c0aaee1a5b04.png)
![2](https://user-images.githubusercontent.com/48286984/54333669-d1010d80-463c-11e9-841d-22e7de0ceaf0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
