### ISSUE TITLE
Текст на главной странице наезжает на изображение

### ISSUE THREAD

**Issue by OlgaTyupina** [netology-code/git-homeworks-neuro-issues#260]
@solarrust 

### Шаги по воспроизведению

1. Открыть у веб-сайт Neuro-StartUp на главной странице в мобильном браузере Chrome.
2. Пролистать вниз страницы до текста "Воспользуйтесь современными возможностями...".

### Ожидаемый результат
Текст не должен наезжать на изображение.

### Фактический результат
Текст "Воспользуйтесь современнными возможностями..." не читается, потому что наезжает на изображение.

### Программное окружение

- Устройство Huawei Honor 9 (Android 9)

- Браузер: Chrome 78.0.3904.108

### Скриншот
![nstup1](https://user-images.githubusercontent.com/57899824/69649868-c24d7000-107e-11ea-937e-cff3db34996f.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
