### ISSUE TITLE
Форма обратной связи в мобильном браузере слишком сжата

### ISSUE THREAD

**Issue by OlgaTyupina** [netology-code/git-homeworks-neuro-issues#261]
@solarrust 

### Шаги по воспроизведению

1. Открыть веб-сайт Neurp-StartUp на главной странице в мобильном браузере Chrome.

1. Пролистать до блока "Обратная связь".

### Ожидаемый результат
Форма обратной связи соответствует размеру экрана мобильного телефона

### Фактический результат
Форма обратной связи сжата и не соответствует размеру экрана мобильного телефона

### Программное окружение

- Устройство Huawei Honor 9 (Android 9)

- Браузер: Chrome 78.0.3904.108

### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/57899824/69650570-da71bf00-107f-11ea-9da5-88e3bed9f739.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
