### ISSUE TITLE
Главная страница. Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by anmak70** [netology-code/git-homeworks-neuro-issues#262]
@solarrust

### Описание
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

#### Шаги по воспроизведению

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

Скриншоты

![изображение](https://user-images.githubusercontent.com/57963372/69670746-a27d7280-10a5-11ea-9761-b7947d8e8b5f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
