### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by anmak70** [netology-code/git-homeworks-neuro-issues#263]
@solarrust

### Описание

Главная страница. Форма обратной связи слишком сжата

#### Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Форма обратной связи"

#### Ожидаемый результат

Блок "Форма обратной связи " соответствует размерам спецификации
 
#### Фактический результат

Блок "Форма обратной связи " слишком сжат (см. скриншот)

#### Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншоты

![изображение](https://user-images.githubusercontent.com/57963372/69671662-92669280-10a7-11ea-9928-941092a6d4e3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
