### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by JunQA** [netology-code/git-homeworks-neuro-issues#264]
#### Описание проблемы
Форма обратной связи слишком сжата.
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2. Пролистать страницу до формы обратной связи

#### Ожидаемый результат
Форма обратной связи выровнена по ширине и высоте в  соответствии с стандартами организации. 

#### Фактический результат
Форма обратной связи слишком сжата.

#### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/55852085/69743489-93eb9580-114f-11ea-9cf0-286f27fac54c.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
