### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на картинку

### ISSUE THREAD

**Issue by Moitomik** [netology-code/git-homeworks-neuro-issues#265]
@solarrust

**Шаги по воспроизведению:**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на картинку

**Фактический результат:**
Текст наезжает на картинку (см. скриншот)

**Программное окружение:**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот:**
![Картинка](https://user-images.githubusercontent.com/57899338/69805488-cd74dd00-11f1-11ea-9f16-a455cbed24eb.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
