### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Moitomik** [netology-code/git-homeworks-neuro-issues#266]
@solarrust

**Шаги по воспроизведению:**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат:**
Текст в форме обратной связи не сжат и отображается в одну строчку по каждому блоку формы

**Фактический результат:**
Форма обратной связи слишком сжата, текст в блоках формы не помещается в одну строчку (см. скриншот)

**Программное окружение:**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот:**
![Форма обратной связи](https://user-images.githubusercontent.com/57899338/69806053-124d4380-11f3-11ea-88cd-c84fbcab384d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
