### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by AlexanderKachalov** [netology-code/git-homeworks-neuro-issues#271]
@solarrust 
---
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение
### Фактический результат
Текст наезжает на изображение (см. скриншот)
### Программное окружение
- Устройство: iMac (early 2009) (OS X El Capitan ver. 10.11.16)
- Браузер: Chrome (Версия 78.0.3904.97)
### Скриншоты
![Снимок экрана 2019-12-05 в 23 21 54](https://user-images.githubusercontent.com/58187585/70270738-190d2500-17b6-11ea-99b3-88060ef1b952.png)
![Снимок экрана 2019-12-05 в 23 22 09](https://user-images.githubusercontent.com/58187585/70270759-1f9b9c80-17b6-11ea-8dc5-a62e9fea5c84.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
