### ISSUE TITLE
Устранить наезд текста на изображение

### ISSUE THREAD

**Issue by s-klimov** [netology-code/git-homeworks-neuro-issues#272]
# Описание проблемы
Главная страница. Текстовый блок "Искусственный интеллект, решающий ваши бизнес-задачи" наезжает на изображение
@solarrust  - прошу принять участие в решение проблемы

## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Искусственный интеллект, решающий ваши бизнес-задачи"
## Ожидаемый результат
Текст "Воспользуйтесь современными возможностями ... " не наезжает на изображение
## Фактический результат
Текст наезжает на изображение (см. скриншот)
## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
## Скриншот
![screenshot](https://user-images.githubusercontent.com/58282452/70297570-3a572b00-1821-11ea-960c-123ecb41ea3c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
