### ISSUE TITLE
Верстка съехала на лендинге

### ISSUE THREAD

**Issue by ovcharenko-a** [netology-code/git-homeworks-neuro-issues#2728]
Коллеги! В мобильной версии лендинга у нас есть проблема толи с марджинами, толи с паддингами:

- Заголовок выстроился в ужасный столбец.
    *(добавить переносы, уменьшить шрифты, прибрать отступы - попробуйте варианты)*

- Текст предложения съехал на изображение ноутбука.
  *(Возможно стоит подстраховаться и сделать более контрастный шрифт?)*

К решению проблем приглашается @solarrust.

![image](https://user-images.githubusercontent.com/75633464/107855139-4130f300-6e53-11eb-8437-ee36d7332cf7.png)

**Comment by KirillKazakoff** [comment]
@ovcharenko-a ситуация идентичная. Судя по количеству issues проблема серьезная
![Screen1](https://user-images.githubusercontent.com/74245663/107887852-116e1200-6f5d-11eb-804e-303b5fdcc646.png)
