### ISSUE TITLE
Переформатировать форму обратной связи

### ISSUE THREAD

**Issue by s-klimov** [netology-code/git-homeworks-neuro-issues#273]
# Описание проблемы
Форма обратной связи "Оставайтесь на связи" слишком зажата.
@solarrust - прошу принять участие в решение проблемы

## Шаги по воспроизведению
Открыть форма обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
## Ожидаемый результат
Окно формы обратной связи имеет пропорциональный вид. Текст в форме не скомкан, легко читается
## Фактический результат
Окно формы обратной связи имеет вытянуто в высоту. В строчках по два слова текста (см. скриншот)
## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
## Скриншот
![screenshot2](https://user-images.githubusercontent.com/58282452/70312978-49e96a80-1847-11ea-8152-9f444e107e4a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
