### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by total-blue** [netology-code/git-homeworks-neuro-issues#274]
# Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### Шаги по воспроизведению:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат:
Текст не наезжает на изображение

### Фактический результат:
Текст наезжает на изображение (см. скриншот)

### Программное окружение:
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты:
![screen1](https://user-images.githubusercontent.com/37304055/70334477-8e303700-1856-11ea-8de5-90a27638040d.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
