### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by total-blue** [netology-code/git-homeworks-neuro-issues#275]
# Описание проблемы:
Главная страница. Форма ввода контактных данных слишком сжата по горизонтали

### Шаги по воспроизведению:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы "Оставайтесь на связи"

### Ожидаемый результат:
Форма не сжата 

### Фактический результат:
Форма сжата (см. скриншот)

### Программное окружение:
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты: 
![screen2](https://user-images.githubusercontent.com/37304055/70334951-7311f700-1857-11ea-856d-05a34746cbf3.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
