### ISSUE TITLE
Сб.07.12 Правки - Мобильная версия сайта - Текст

### ISSUE THREAD

**Issue by hybrydtheory** [netology-code/git-homeworks-neuro-issues#276]
### Проблема 1:

- При открытии мобильной версии сайта текст наезжает на изображение (https://prnt.sc/q78q3c)

**Проверяли на устройстве:** 
iPhone6s, браузер Chrome (версия 3.45)

Необходимо: 
- Поправить текст

- Выполнить проверку через различные браузеры (Opera, Safari, Chrome, Амиго)

Ответственный за выполнение: @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
