### ISSUE TITLE
Сб.07.12 Правки - Мобильная версия сайта - Форма обратной связи

### ISSUE THREAD

**Issue by hybrydtheory** [netology-code/git-homeworks-neuro-issues#277]
### Проблема 2:

- При открытии мобильной версии сайта форма обратной связи сжата и занимает не всё доступное пространство (https://prnt.sc/q78vkh)

**Проверяли на устройстве:** 
iPhone6s, браузер Chrome (версия 3.45)

Необходимо: 
- Адаптировать форму обратной связи чтобы она занимала доступное пространство мобильной версии сайта. 

- Выполнить проверку через различные браузеры (Opera, Safari, Chrome, Амиго)

Ответственный за выполнение: @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
