### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by kric1929** [netology-code/git-homeworks-neuro-issues#279]
# Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![Текст наезжает на картинку](https://user-images.githubusercontent.com/58208029/70371269-fb3cde80-18e1-11ea-8814-c158e5dfd080.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
