### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Stegur** [netology-code/git-homeworks-neuro-issues#28]
@solarrust 
### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

### Ожидаемый результат
Текст должен располагаться по ширине экрана до картинки и не должен мешать её отображению

### Фактический результат
Текст наезжает на картинку (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![пример](https://camo.githubusercontent.com/d90a6e5e9269c1926cc5e5ea6d624a3a06b53f9a/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
