### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by kric1929** [netology-code/git-homeworks-neuro-issues#280]
# Описание проблемы

**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма обратной связи расширена

**Фактический результат**

Форма обратной связи сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![форма обратной связи](https://user-images.githubusercontent.com/58208029/70371404-9e422800-18e3-11ea-8aa0-2b52a3a73cb0.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
