### ISSUE TITLE
 Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Danshin-alexey** [netology-code/git-homeworks-neuro-issues#283]
# Описание проблемы
Главная страница. Форма обратной связи слишком сжата
## Шаги по воспроизведению 
для @solarrust
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до формы "Оставайтесь на связи"
## Ожидаемый результат
Форма легко читаема, выровнена по краям

Фактический результат
Форма слишком сжата (см. скриншот)

Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
Скриншоты: 
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/58550261/70389971-61eff400-19d7-11ea-8150-f143a4a4bd4e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
