### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Danshin-alexey** [netology-code/git-homeworks-neuro-issues#284]
# Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
## Шаги по воспроизведению
для@solarrust
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/58550261/70390203-fd826400-19d9-11ea-9570-49faf40a5a9e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
