### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by drevnik** [netology-code/git-homeworks-neuro-issues#285]
# **Описание проблемы**
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..."** **наезжает на изображение**
### **Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### **Ожидаемый результат**
Текст не наезжает на изображение

### **Фактический результат**
Текст наезжает на изображение (см. скриншот)

### **Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)
### **Скриншоты**
![Clip2net_191208165000](https://user-images.githubusercontent.com/58367397/70390330-12abc280-19db-11ea-8647-344ca676ecac.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
