### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by drevnik** [netology-code/git-homeworks-neuro-issues#286]
# **Описание проблемы**
**Главная страница. Форма обратной связи слишком сжата**
### **Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

- Пролистать страницу до формы "Оставайтесь на связи"

### **Ожидаемый результат**
Форма легко читаема, выровнена по краям

### **Фактический результат**
Форма слишком сжата (см. скриншот)

### **Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

### **Скриншоты**
![Clip2net_191208165034](https://user-images.githubusercontent.com/58367397/70390417-d3ca3c80-19db-11ea-9b61-ac3f8a518303.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
