### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by supremko** [netology-code/git-homeworks-neuro-issues#288]
Шаги по воспроизведению

1. Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

Ожидаемый результат
Ширина обратной связи удобна для чтения и занимает весь экран

Фактический результат
Текст сжат и ширина ~50% (см. скриншот)

Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты
![2](https://user-images.githubusercontent.com/505723/70390545-f9a41100-19dc-11ea-8d02-e8b901d68967.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
