### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by MaxZarn** [netology-code/git-homeworks-neuro-issues#29]
@solarrust 
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат

Текст не наезжает на изображение

### Фактический результат

Текст наезжает на изображение (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты

![](https://camo.githubusercontent.com/e648681205a1dfdf6ed69784e1311b18ca924856/68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
