### ISSUE TITLE
Текст наезжает на изображение на главной странице в мобильном браузере 

### ISSUE THREAD

**Issue by anmaslow** [netology-code/git-homeworks-neuro-issues#291]
# Описание проблемы
Если открыть главную страницу NeuroStartUp в мобильном браузере, текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение. @solarrust 
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями...".
### Ожидаемый результат
Текстовый блок расположен в соответствии с вёрсткой, под изображением, чётко виден и легко читаем.
### Фактический результат
Текстовый блок наезжает на изображение (см. скриншот). 
### Программное окружение
* Устройство: iPhone SE (iOS 13.2.3)
* Браузер: Chrome (70.0.3538.75)
### Скриншот 
![text-overlapping](https://user-images.githubusercontent.com/53662258/70393901-5533c600-1a00-11ea-88b1-ba6fce97b1a8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
