### ISSUE TITLE
Форма обратной связи сжимается на главной странице в мобильном браузере

### ISSUE THREAD

**Issue by anmaslow** [netology-code/git-homeworks-neuro-issues#292]
# Описание проблемы
Если открыть главную страницу NeuroStartUp в мобильном браузере, форма обратной связи некорректно масштабируется и слишком сильно сжимается. @solarrust 
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
1. Пролистать страницу до блока "Оставайтесь на связи".
### Ожидаемый результат
Блок "Оставайтесь на связи" принимает ширину мобильного устройства.
### Фактический результат
Блок "Оставайтесь на связи" сжат, так что по бокам остаются широкие поля. Текст и поля ввода неудобны для взаимодействия. (см. скриншот). 
### Программное окружение
* Устройство: iPhone SE (iOS 13.2.3)
* Браузер: Chrome (70.0.3538.75)
### Скриншот 
![narrow-form](https://user-images.githubusercontent.com/53662258/70394037-ee171100-1a01-11ea-826c-5a560548aafa.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
