### ISSUE TITLE
Форма обратной связи

### ISSUE THREAD

**Issue by camomilla07** [netology-code/git-homeworks-neuro-issues#294]
# Описание проблемы

Форма обратной связи слишком сжата при просмотре на телефоне 

## Шаги по воспроизведению

* Открыть страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Открыть форму обратной связи 

## Ожидаемый результат

Границы формы отступают от границ страницы на 5 мм, текст равномерно распределен по центру

## Фактический результат

Форма слишком сжата (см. скриншот)
![scrin2](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
