### ISSUE TITLE
Форма обратной связи

### ISSUE THREAD

**Issue by ELvovo7** [netology-code/git-homeworks-neuro-issues#295]
### Описание проблемы

Форма обратной связи. Текстовый блок "Оставайтесь на связи" некорректно масштабируется при просмотре на мобильном устройстве.

### Шаги по воспроизведению
1. Открыть страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму обратной связи

### Ожидаемый результат
Форма полностью вмещает текстовую часть без переносов

### Фактический результат
Форма слишком сжата (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/57502747/70627035-885f9a80-1c36-11ea-835e-efb7ace2c93a.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
