### ISSUE TITLE
Главная страница. Текст блока "Воспользуйтесь современными возможностями..." наезжает на картинку

### ISSUE THREAD

**Issue by Evgeniya-EVA** [netology-code/git-homeworks-neuro-issues#296]
Вниманию @solarrust

## Шаги воспроизведения:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере.
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат:
Текст не наезжает на изображение.

## Фактический результат:
Текст наезжает на изображение (см. скриншот).

## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

## Скриншот:
![TextAndPictureConflict](https://user-images.githubusercontent.com/58333040/70697219-2eaead00-1cd6-11ea-9729-9c739217c90f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
