### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Evgeniya-EVA** [netology-code/git-homeworks-neuro-issues#297]
Вниманию @solarrust .

## Шаги по воспроизведению:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Форма обратной связи".

## Ожидаемый результат
Отображение и верстка "Формы обратной связи" соответствует макету для мобильных браузеров с разрешением экрана, соответствующим окружению.

## Фактический результат
"Форма обратной связи" слишком сжата (см. скриншот).

## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

## Скриншоты
![CallBackForm](https://user-images.githubusercontent.com/58333040/70697852-56524500-1cd7-11ea-9222-7f2c9da9040b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
