### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by asenok152** [netology-code/git-homeworks-neuro-issues#300]
@solarrust
Шаги по воспроизведению

* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![ff](https://user-images.githubusercontent.com/58488845/70940618-ceb06180-205b-11ea-93c7-7041b0a0a063.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
