### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by asenok152** [netology-code/git-homeworks-neuro-issues#301]
@solarrust
Шаги по воспроизведению

* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу вниз до блока форма обратной связи

Ожидаемый результат
Форма развернута по ширине экрана, текст легко читается

Фактический результат
Форма слишком сжата, вытянута

![f](https://user-images.githubusercontent.com/58488845/70940812-31a1f880-205c-11ea-9832-8b0331a23da9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
