### ISSUE TITLE
Текст наезжает на картинку в мобильной версии сайта😢

### ISSUE THREAD

**Issue by ppvinogradova** [netology-code/git-homeworks-neuro-issues#304]
**Тескт "Воспользуйтесь современными возможностями..." на главной странице наезжает на изображение**

@solarrust 

 ### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат

Текст не наезжает на изображение

### Фактический результат

Текст наезжает на изображение (см. скриншот)

### Программное окружение

Устройство: Redmi Note 4 (Android 7.0)
Браузер: Chrome (79.0.3945.79)

### Скриншот
![text](https://camo.githubusercontent.com/d90a6e5e9269c1926cc5e5ea6d624a3a06b53f9a/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
