### ISSUE TITLE
Форма обратной связи слишком сжата🤔

### ISSUE THREAD

**Issue by ppvinogradova** [netology-code/git-homeworks-neuro-issues#305]
**При просмотре мобильной версии главной страницы форма обратной связи выглядит некорректно из-за того что слишком сжата**

@solarrust 

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи

### Ожидаемый результат

Форма обратной связи выглядит корректно и красиво для пользователя

### Фактический результат

Форма обратной связи сжата слишком сильно, слова дробятся (см. скриншот)

### Программное окружение

Устройство: Redmi Note 4 (Android 7.0)
Браузер: Chrome (79.0.3945.79)

### Скриншот

![form](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
