### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Kaldinskii** [netology-code/git-homeworks-neuro-issues#306]
@solarrust 
**Тескт** "Воспользуйтесь современными возможностями..." на главной странице наезжает на изображение

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: Redmi 4X (Android 7.0)
Браузер: Chrome (79.0.3945.79)

**Скриншот**
![image](https://user-images.githubusercontent.com/39535760/71354812-82eb4400-2596-11ea-8fc0-ef5119681a5a.png)

**Comment by Kaldinskii** [comment]
> @solarrust
> Тескт "Воспользуйтесь современными возможностями..." на главной странице наезжает на изображение
> 
> Шаги по воспроизведению
> Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
> Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
> Ожидаемый результат
> Текст не наезжает на изображение
> 
> Фактический результат
> Текст наезжает на изображение (см. скриншот)
> 
> Программное окружение
> Устройство: Redmi 4X (Android 7.0)
> Браузер: Chrome (79.0.3945.79)
> 
> Скриншот
> ![image](https://user-images.githubusercontent.com/39535760/71354812-82eb4400-2596-11ea-8fc0-ef5119681a5a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
