### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Kaldinskii** [netology-code/git-homeworks-neuro-issues#307]
При просмотре мобильной версии главной страницы форма обратной связи выглядит некорректно из-за , что слишком сжата

@solarrust

### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до формы обратной связи

### Ожидаемый результат
Форма обратной связи выглядит корректно и красиво для пользователя

### Фактический результат
Форма обратной связи сжата слишком сильно, слова дробятся (см. скриншот)

### Программное окружение
Устройство: Redmi Note 4 (Android 7.0)
Браузер: Chrome (79.0.3945.79)

### Скриншот
![image](https://user-images.githubusercontent.com/39535760/71355124-89c68680-2597-11ea-8853-00c9f0e51a12.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
