### ISSUE TITLE
Это баг или фича?

### ISSUE THREAD

**Issue by lapssh** [netology-code/git-homeworks-neuro-issues#308]
**На странице лендинга, после пафосной фразы и про искусственный интеллект, который якобы решает наши бизнес задачи ничего не разобрать...**
---
**Шаги по воспроизведению:**
1. Перейти на сайт NeuroStartUp поверив назойливой реферальной рекламе
2. Заставить себя попытаться прочитать написанное

**Ожидаемый результат:**
Узнать способ увеличить продажи на 3000%  с помощью искусственного интеллекта (потому что работать сами мы устали)

**Фактический результат**
Если вы нам не поможете сегодня, завтра нам отключат интернет за неуплату

**Программное окружение**
- ZX-Spectrum 48K
- Магнитофон кассетный "Вега"
- Цветной ламповый телевизор Taurus с декодером

**Скриншоты**
![etoproval](https://camo.githubusercontent.com/e648681205a1dfdf6ed69784e1311b18ca924856/68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
