### ISSUE TITLE
Здесь могла бы быть Ваше реклама.

### ISSUE THREAD

**Issue by Kutyrevdma** [netology-code/git-homeworks-neuro-issues#309]
@solarrust 
# Текст наезжает на картинку и Форма обратной связи слишком сжата.

## На главной странице нашего сайта имеются следующие ошибки:
1. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.
1. Форма обратной связи слишком сжата.

## Шаги по воспроизведению:

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат:

Текст не наезжает на изображение

## Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншот с ошибкой

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/59098298/71558582-0fe63f80-2a66-11ea-9822-e279f3b4e436.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
