### ISSUE TITLE
Проблема с сайтом на мобильных устройствах

### ISSUE THREAD

**Issue by rychanya** [netology-code/git-homeworks-neuro-issues#310]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HJ1VbMj.png)

#### Шаги по воспроизведению

1. Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

#### Ожидаемый результат

Форма имет нормальный размер и хорошо читается.

#### Фактический результат

Форма слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

@solarrust сделайте с этим что-нибудь

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
