### ISSUE TITLE
Проблема с отображением текста на сайте.

### ISSUE THREAD

**Issue by Samsonyk** [netology-code/git-homeworks-neuro-issues#314]
# Описание проблемы

### **Главная страница. Текстовый блок "Воспользуйтесь современными возможностями.." наезжает на изображение**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: iphone8+ (iOS 12.1)
* Браузер Chrome (70.0.3538.75)

**Скриншоты**

![ ](https://camo.githubusercontent.com/e648681205a1dfdf6ed69784e1311b18ca924856/68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67)

### **Шаги по воспроизведению**
Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
## Ожидаемый результат

Форма имеет нормальный размер и хорошо читается.

### **Фактический результат**

Форма слишком сжата (см. скриншот)

### **Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)
@solarrust исправить недочет

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
