### ISSUE TITLE
Проблема с отображением на мобильном устройстве

### ISSUE THREAD

**Issue by tetyorkin** [netology-code/git-homeworks-neuro-issues#316]
# Описание проблемы
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![issue](https://user-images.githubusercontent.com/22164906/71774606-5bd04180-2f9c-11ea-9c20-5a17c8bf576b.png)
![issue2](https://user-images.githubusercontent.com/22164906/71774617-7c000080-2f9c-11ea-99f2-98140d2fb69d.png)
@solarrust давай исправим эту проблему

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
