### ISSUE TITLE
Текст наезжает на картинку при просмотре в мобильном браузере

### ISSUE THREAD

**Issue by andrew-pahomov** [netology-code/git-homeworks-neuro-issues#317]
# Описание проблемы
@solarrust 

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат

Текст не наезжает на изображение

### Фактический результат

Текст наезжает на изображение (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты:

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/59327373/71777257-8aefae80-2fae-11ea-9aec-49a158e7cbd0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
