### ISSUE TITLE
Форма обратной связи слишком сжата при просмотре в мобильном браузере

### ISSUE THREAD

**Issue by andrew-pahomov** [netology-code/git-homeworks-neuro-issues#318]
# Описание проблемы
@solarrust 

Главная страница. Форма обратной связи слишком узкая

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы "Обратная связь"

### Ожидаемый результат

Форма обратной связи имеет нормальную ширину

### Фактический результат

Форма обратной связи узкая (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты:

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/59327373/71779067-93071880-2fc5-11ea-8ccf-6b9c7e2e5687.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
