### ISSUE TITLE
Проблема отображения формы обратной связи

### ISSUE THREAD

**Issue by stanislawkostenko** [netology-code/git-homeworks-neuro-issues#32]
# На главной странице блок "Оставайтесь на связи" отображается в некорректных пропорциях #
@solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Блок отображается соответственно пропорциям страницы и экрана устройства

**Фактический результат**
Блок отображается в некорректных пропорциях, более узкий по ширине и более короткий по высоте (см. скриншот)

**Программное окружение**
 * Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![Скриншот](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
