### ISSUE TITLE
Текст наезжает на логотип

### ISSUE THREAD

**Issue by kotnk** [netology-code/git-homeworks-neuro-issues#320]
# Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншот**

![text](https://user-images.githubusercontent.com/36637780/71782850-ceb6d800-2fef-11ea-9aa8-184629b7561f.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
