### ISSUE TITLE
Сжатие формы обратной связи

### ISSUE THREAD

**Issue by kotnk** [netology-code/git-homeworks-neuro-issues#321]
# Описание проблемы
**Главная страница. Форма обратной связи (для введения телефона, почты и имени) слишком сжата и искажена.**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи

**Ожидаемый результат**

Форма обратной связи использует всю ширину страницы на мобильном устройстве, текст отформатирован без разрыва слов.

**Фактический результат**

Форма связи очень узкая, много свободного места по бокам, текст плохо форматируется (см. скриншот).

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншот**

![form](https://user-images.githubusercontent.com/36637780/71782899-7c29eb80-2ff0-11ea-8bf7-f060add913d3.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
