### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by r1zon** [netology-code/git-homeworks-neuro-issues#322]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншот

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67 1](https://user-images.githubusercontent.com/59363080/71785224-1ea49780-300e-11ea-9c52-d1db83e19055.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
