### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by r1zon** [netology-code/git-homeworks-neuro-issues#323]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма обратной связи использует всю ширину экрана, текст записан без переноса

#### Фактический результат

Блок сжат, что также привело к разрыву слов на части (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/59363080/71785364-ba82d300-300f-11ea-802e-94ebd384ecf1.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
