### ISSUE TITLE
Главная страница. Текст наезжает на картинку. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by krus210** [netology-code/git-homeworks-neuro-issues#324]
# Описание  проблемы
### 1. Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение
### Фактический результат
Текст наезжает на изображение (см. скриншот)
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![img1](https://camo.githubusercontent.com/e648681205a1dfdf6ed69784e1311b18ca924856/68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67)
### 2. Форма обратной связи слишком сжата
![img2](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
