### ISSUE TITLE
Текст наезжает на картинку.

### ISSUE THREAD

**Issue by Razmen91** [netology-code/git-homeworks-neuro-issues#325]
# Описание проблемы
### Шаги по воспроизведению
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты
![Imgur](https://i.imgur.com/hicvmgG.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
