### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Razmen91** [netology-code/git-homeworks-neuro-issues#326]
# Описание проблемы
### Шаги по воспроизведению
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до формы обратной связи

### Ожидаемый результат
Форма обратной связи выглядит корректно

### Фактический результат
Форма обратной связи слишком сжата

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты
![Imgur](https://i.imgur.com/yV7Ps7Y.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
