### ISSUE TITLE
Главная страница. Текст наезжает на изображение, форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by NazarovAn** [netology-code/git-homeworks-neuro-issues#327]
## Описание проблемы №1

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями...".

### Ожидаемый результат

Текст не наезжает на изображение.

### Фактический результат

Текст наезжает на изображение (см. скриншот).

### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/54843867/71930356-898bd500-31ac-11ea-95a8-a2daa811184a.png)

## Описание проблемы №2

Форма обратной связи слишком сжата. 

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи

### Ожидаемый результат

Широкая, легко читаемая, форма обратной связи.

### Фактический результат

Форма обратной связи слишком сжата. (см. скриншот)

### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот 

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/54843867/71930700-3c5c3300-31ad-11ea-9a02-6dd769a82bdd.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
