### ISSUE TITLE
В мобильной версии текст наезжает на картинку и поехала форма обратной связи

### ISSUE THREAD

**Issue by abbnv** [netology-code/git-homeworks-neuro-issues#328]
## Описание проблем
* На главной странице текстовый блок «Воспользуйтесь современными возможностями» наезжает на картинку
* Форма обратной связи слишком сжата

## Шаги по воспроизведению
**Баг с текстом и картинкой:**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Баг с формой**
1. Открыть главную страницу в мобильном Chrome
2. Пролистать страницу до формы заявки

**Программное окружение**
1. Устройство: iPhone 8+ (iOS 12.1)
2. Браузер: Chrome (70.0.3538.75)

## Скриншоты
**Баг с текстом**

![Форма](https://camo.githubusercontent.com/e648681205a1dfdf6ed69784e1311b18ca924856/68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
