### ISSUE TITLE
Homework_Onufriev

### ISSUE THREAD

**Issue by Mpa3b3k** [netology-code/git-homeworks-neuro-issues#33]
# Описание проблемы
## Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)
@solarrust 

## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
## Скриншоты
![image](https://user-images.githubusercontent.com/45596135/54539131-a3062b00-49a6-11e9-937d-3eec434c634e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
