### ISSUE TITLE
На главной странице 2 проблемы: текстовый блок наезжает на изображение и форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by shvedcate** [netology-code/git-homeworks-neuro-issues#330]

**Comment by shvedcate** [comment]
# Описание проблемы №1
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/58511155/71969002-4dde2300-321f-11ea-9c33-07a102fa7fc6.png)

# Описание проблемы №2
**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи

**Ожидаемый результат**

Форма обратной связи соответствует ширине окна. Удобна для чтения, предложения не разрываются

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/58511155/71969523-4408ef80-3220-11ea-81e6-dcf80eb4ec35.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
