### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by tihon49** [netology-code/git-homeworks-neuro-issues#334]
# Описание проблемы

### Шаги по воспроизведению:

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат

Текст не наезжает на изображение

### Фактический результат

Текст наезжает на изображение (см. скриншот):

![1](https://user-images.githubusercontent.com/29193437/72046035-956cb980-32c8-11ea-8e31-483122679a53.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
