### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by tihon49** [netology-code/git-homeworks-neuro-issues#335]
@solarrust
# Форма обратной связи слишком сжата.

### Шаги по воспроизведению

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до формы обратной связи

### Ожидаемый результат

Форма обратной связи использует всю ширину страницы на мобильном устройстве, текст отформатирован без разрыва слов.

### Фактический результат

Форма связи очень узкая, много свободного места по бокам, текст плохо форматируется (см. скриншот):

![2](https://user-images.githubusercontent.com/29193437/72046366-5723ca00-32c9-11ea-9cc6-c97ebfb2ad20.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
