### ISSUE TITLE
Главная страница. Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by pabloz777** [netology-code/git-homeworks-neuro-issues#34]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

*Устройство: iPhone 8+ (iOS 12.1)
*Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![screenshot](https://user-images.githubusercontent.com/48356139/54558536-973f5680-49f0-11e9-90a5-6b723696bff3.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
