### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by aulazarev** [netology-code/git-homeworks-neuro-issues#341]
@solarrust 
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

### Ожидаемый результат
Форма обратной связи использует всю ширину страницы на мобильном устройстве,

### Фактический результат
Форма обратной связи слишком сжата. (см. скриншот):
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/42849038/72079389-dfc35a00-330b-11ea-89d4-fede91209de8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
