### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by DimGA** [netology-code/git-homeworks-neuro-issues#342]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не заезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см.скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

<img width="343" alt="Снимок экрана 2020-01-09 в 18 28 06" src="https://user-images.githubusercontent.com/57522974/72080554-0aaead80-330e-11ea-85b6-78b43762cd2d.png">

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
