### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by DimGA** [netology-code/git-homeworks-neuro-issues#343]
**Главная страница. Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи

**Ожидаемый результат**

Форма связи занимает 100% ширины устройства

**Фактический результат**

Слишком сжатая форма связи (см.скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

<img width="350" alt="Снимок экрана 2020-01-09 в 18 34 53" src="https://user-images.githubusercontent.com/57522974/72081069-e69f9c00-330e-11ea-8aae-d698d0bac5ec.png">

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
