### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by MironovaGV** [netology-code/git-homeworks-neuro-issues#345]
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![скриншот-текста](https://user-images.githubusercontent.com/57486655/72105510-b7a11e80-333e-11ea-943c-025de512cf82.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
