### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by MironovaGV** [netology-code/git-homeworks-neuro-issues#346]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи
### Ожидаемый результат
Увелечение ширины формы
### Фактический результат
Форма слишком сжата (см. скриншот)
### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
### Скриншоты
![форма-обратной-связи](https://user-images.githubusercontent.com/57486655/72106507-8f1a2400-3340-11ea-861d-f3174116e227.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
