### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by aledavydkin** [netology-code/git-homeworks-neuro-issues#356]
**Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу нажать на ссылку "Форма обратной связи" в мобильном браузере Chrome
1. Пролистать страницу до блока "Форма обратной связи"

**Ожидаемый результат**

Форма нормального размера

**Фактический результат**

Форма обратной связи слишком сжата(см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![687](https://user-images.githubusercontent.com/36063790/72156017-3b5a1a00-33d6-11ea-9e02-1f47a4890627.png)

@solarrust какие есть идеи для решения данной задачи?

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
