### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by SomeoneDude666** [netology-code/git-homeworks-neuro-issues#360]
### Шаги по воспроизведению

1. Открыть страницу обратной связи

### Ожидаемый результат
Ширина формы соответствует размеру экрана

### Фактический результат
Форма обратной связи слишком сжата.

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/59486510/72192462-e38fd300-3416-11ea-8f8b-dd5ded357217.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
