### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by edge1312** [netology-code/git-homeworks-neuro-issues#362]
# Описание проблемы

### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншот
![screen_1](https://user-images.githubusercontent.com/59048404/72205560-9dc61f80-3495-11ea-8752-5cd6c125dd57.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
