### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by edge1312** [netology-code/git-homeworks-neuro-issues#363]
# Описание проблемы

### Шаги по воспроизведению
Открыть меню "Форма обратной связи" веб-сайта NeuroStartUp в мобильном браузере Chrome
для ввода контактных данных

### Ожидаемый результат
Форма связи открывается по ширине страницы. 
Слова переносятся корректно.

### Фактический результат
Форма обратной связи слишком сжата.
Перенос текста выполняется некорректно (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншот
![screen_2](https://user-images.githubusercontent.com/59048404/72205716-73756180-3497-11ea-86d9-295a50d9194c.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
