### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by lubavin01** [netology-code/git-homeworks-neuro-issues#365]
# Описание проблемы
**Форма "Оставайтесь на связи" слишком узкая**

**Шаги по воспроизведению**
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма "Оставайтесь на связи" читаемая и удобная

**Фактический результат**
Форма "Оставайтесь на связи" слишком узкая

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/57035674/72207799-3c11af80-34ad-11ea-8b46-e95c17dfd450.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
