### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by MaxPirojkov** [netology-code/git-homeworks-neuro-issues#366]
Форма "Оставайтесь на связи" слишком узкая

Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат
Форма "Оставайтесь на связи" читаемая и удобная

Фактический результат
Форма "Оставайтесь на связи" слишком узкая

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/36989427/72208858-18546680-34b9-11ea-9f03-005152072a5e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
