### ISSUE TITLE
Текст наезжает на изоборажение

### ISSUE THREAD

**Issue by FedmanCassad** [netology-code/git-homeworks-neuro-issues#367]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 7 (iOS 13.3)
* Браузер: Safari (70.0.3538.75)

#### Скриншоты

![Screensho1](https://user-images.githubusercontent.com/59616193/72212333-29b66680-34eb-11ea-83e6-c356ead9ad0c.png)
@solarrust Следует внести правки ASAP.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
