### ISSUE TITLE
Форма обратной связи не масштабируется под экраны мобильных устройств.

### ISSUE THREAD

**Issue by FedmanCassad** [netology-code/git-homeworks-neuro-issues#368]
#Описание проблемы

#### Шаги по воспроизведению

1. Открыть страницу обратной связи
####  Ожидаемый результат

Ширина формы соответствует размеру экрана

####  Фактический результат

Форма обратной связи слишком сжата.

Программное окружение

Устройство: iPhone 7 (iOS 13.3)
Браузер: Safari (13)

#### Скриншоты
![Screenshot2](https://user-images.githubusercontent.com/59616193/72212402-4606d300-34ec-11ea-8f82-b62b5f67cce1.png)

@solarrust Take care of this issue please.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
