### ISSUE TITLE
Styling errors on the main page

### ISSUE THREAD

**Issue by Roolen** [netology-code/git-homeworks-neuro-issues#37]
_@solarrust_
#### Описание проблемы

- Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.
- Главная страница. Форма обратной связи слишком сжата.

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
3. Пролистать страницу до формы обратной связи.

#### Ожидаемый результат

- Текст не наезжает на изображение
- Форма обратной связи занимает всю ширину экрана

#### Фактический результат

- Текст наезжает на изображение (см. скриншот 1)
- Форма обратной связи слишком узкая (см. скриншот 2)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

Скриншот 1:
![](https://i.imgur.com/HJ1VbMj.png)

Скриншот 2:
![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
