### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by karina-apolonskaya** [netology-code/git-homeworks-neuro-issues#371]
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

@solarrust

#### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/59331439/72215862-ada03b00-354b-11ea-9f8b-869dd5b8a197.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
