### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by karina-apolonskaya** [netology-code/git-homeworks-neuro-issues#372]
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат
Форма обратной связи не сжата при просмотре в мобильном браузере

#### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

@solarrust

#### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/59331439/72216361-73866780-3552-11ea-8f7e-2cb228a27dbc.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
