### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Risovaniy** [netology-code/git-homeworks-neuro-issues#374]
# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи "
### Ожидаемый результат
Слова не переносятся между строчками

### Фактический результат
Слово "Оставайтесь" переносится между строками

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/43520776/72217568-abd97600-3551-11ea-8a6a-6c3380dc48ad.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
