### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by NataliaGracheva** [netology-code/git-homeworks-neuro-issues#376]
@solarrust 
**Форма обратной связи слишком сжата**

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока Форма обратной связи

**Ожидаемый результат**
Форма обратной связи занимает всю ширину экрана

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![pic2](https://user-images.githubusercontent.com/40542294/72218576-fb25a380-355d-11ea-8b11-9881bc0face4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
