### ISSUE TITLE
Текст наезжает на изображение (с телефона) 

### ISSUE THREAD

**Issue by ahtimir** [netology-code/git-homeworks-neuro-issues#377]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 7+ (iOS 13.3)
* Браузер: Chrome (79.0.3945.116)

Для пользователя @solarrust

#### Скриншоты

![](https://i.imgur.com/HJ1VbMj.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
