### ISSUE TITLE
Форма обратной связи слишком сжата на телефоне 

### ISSUE THREAD

**Issue by ahtimir** [netology-code/git-homeworks-neuro-issues#378]
# Форма обратной связи слишком сжата

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

#### Ожидаемый результат

Форма обратной связи занимает всю ширину экрана

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 7+ (iOS 13.3)
* Браузер: Chrome (79.0.3945.116)

Для пользователя @solarrust

#### Скриншоты

![](https://i.imgur.com/GaT8CAk.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
