### ISSUE TITLE
Проблемы с отображением информации в UI

### ISSUE THREAD

**Issue by ymlct** [netology-code/git-homeworks-neuro-issues#379]
адресовано пользователю
                                                                       @solarrust

### Описание проблемы № 1
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
#### _Шаги по воспроизведению_
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
#### _Ожидаемый результат_
Текст не наезжает на изображение
#### _Фактический результат_
Текст наезжает на изображение (см. скриншот)
#### _Программное окружение_
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

#### _Скриншоты_
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/59499236/72220941-8caa0b00-3588-11ea-83e9-47dcb7607a0d.png)

### Описание проблемы № 2
На странице с формой обратной связи сама форма слишком сжата.
#### _Шаги по воспроизведению_
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
Перейти по ссылке "Оставайтесь на связи".
#### _Ожидаемый результат_
Форма заполняет все пространство страницы по горизонтали.
#### _Фактический результат_
По горизонтали форма занимает ~ 50% от всего пространства (см. скриншот)
#### _Программное окружение_
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

#### _Скриншоты_
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/59499236/72221061-997b2e80-3589-11ea-98a6-0fe2878f7709.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
