### ISSUE TITLE
Главная страница. Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by eapotapova** [netology-code/git-homeworks-neuro-issues#38]
@solarrust 
### Шаги по воспроизведению
1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1.Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншоты
![скрин 1](https://user-images.githubusercontent.com/48554040/54607615-d35dd000-4a5f-11e9-9ca4-492e4d95cc41.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
