### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by ivalynx** [netology-code/git-homeworks-neuro-issues#380]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![screen1](https://user-images.githubusercontent.com/57597588/72224158-11e0f000-3588-11ea-93ca-c3bc95f585e0.png)

@solarrust посмотрите, пожалуйста

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
