### ISSUE TITLE
Узкая форма обратной связи

### ISSUE THREAD

**Issue by ivalynx** [netology-code/git-homeworks-neuro-issues#381]
**Главная страница. Узкая форма обратной связи**

**Шаги по воспроизведению**

* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Ширина формы обратной связи совпадает с шириной окна браузера или незначительно меньше неё, верхний внешний отступ формы пропорционален боковым.

**Фактический результат**
Узкая форма обратной связи (см. скриншот), большой внешний отступ.

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![screen2](https://user-images.githubusercontent.com/57597588/72224232-35586a80-3589-11ea-8d08-611f8efbdac8.png)

@solarrust посмотрите, пожалуйста.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
