### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by root1604** [netology-code/git-homeworks-neuro-issues#387]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Ширина формы обратной связи совпадает с шириной окна браузера или незначительно меньше неё, верхний внешний отступ формы пропорционален боковым.

#### Фактический результат

Узкая форма обратной связи (см. скриншот), большой внешний отступ.

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![72224232-35586a80-3589-11ea-8d08-611f8efbdac8](https://user-images.githubusercontent.com/53382091/72254202-692ca200-3614-11ea-9bb7-0269777cfaa4.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
