### ISSUE TITLE
Форма обратной связи слишком сжата 

### ISSUE THREAD

**Issue by eapotapova** [netology-code/git-homeworks-neuro-issues#39]
@solarrust 
 ### Шаги воспроизведения
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Обратная связь"

### Ожидаемый результат
Форма обратной  связи занимает всю площадь экрана
### Фактический результат 
Форма обратной связи сжата (см. скриншот)
### Системное окружение 
Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншот
![скрин 2](https://user-images.githubusercontent.com/48554040/54608484-d9ed4700-4a61-11e9-8e40-d85a0f405e67.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
