### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by blackseliger** [netology-code/git-homeworks-neuro-issues#395]
**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока ">Оставайтесь на связи"

**Ожидаемый результат**
Адаптированный размер текста под экран устройства

**Фактический результат**
Текст не адаптирован (см. скриншот)

@solarrust https://github.com/netology-code/git-homeworks-neuro-issues/blob/857e3d95477bfbd9c93fb04804a64d0007c1c075/index.html#L53

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![проблема](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
