### ISSUE TITLE
NeuroStartUp. Лэндинг. Текст наезжает на картинку

### ISSUE THREAD

**Issue by Straiff20** [netology-code/git-homeworks-neuro-issues#396]
@solarrust

Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![image](https://user-images.githubusercontent.com/59826755/72411046-0bff3080-377b-11ea-9fed-733a906f7487.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
