### ISSUE TITLE
2. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Mistel-77** [netology-code/git-homeworks-neuro-issues#398]
### Описание проблемы

**Главная страница. Текстовый блок "Оставайтесь на связи" Форма обратной связи слишком сжата.**

#### Шаги по воспроизведению
1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.  Пролистать страницу до блока "Оставайтесь на связи..."

#### Ожидаемый результат
Форма обратной связи располагается по всей ширине окна браузера

#### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение
-  Устройство: iPhone 8+ (iOS 12.1)
-  Браузер: Chrome (70.0.3538.75)

@solarrust
#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/57500921/72429909-0832d480-37a2-11ea-86f8-76d202c4a80f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
