### ISSUE TITLE
Text overflow

### ISSUE THREAD

**Issue by pavelzhdan** [netology-code/git-homeworks-neuro-issues#399]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 4 (iOS 12.1)
* Браузер: Chrome (79.0.3945.117)

@solarrust

#### Скриншоты

![Screenshot_1](https://user-images.githubusercontent.com/54664188/72359467-6490e800-36ff-11ea-9d94-1d96a836c6c1.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
