### ISSUE TITLE
Текст наезжает на картинку, форма обратной связи сжата по ширине

### ISSUE THREAD

**Issue by KirillBakhtin** [netology-code/git-homeworks-neuro-issues#40]
@solarrust 

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

Шаги по воспроизведению
1) Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1) Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/47248819/54611470-32800c80-4a81-11e9-9c70-efb19b7eeecb.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
