### ISSUE TITLE
Form width

### ISSUE THREAD

**Issue by pavelzhdan** [netology-code/git-homeworks-neuro-issues#400]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

#### Ожидаемый результат

Форма по ширине занимает всю ширину экрана

#### Фактический результат

Форма обратной слишком узкая (см. скриншот)

#### Программное окружение

* Устройство: iPhone 4 (iOS 12.1)
* Браузер: Chrome (79.0.3945.117)

@solarrust

#### Скриншоты

![Screenshot_2](https://user-images.githubusercontent.com/54664188/72359465-6490e800-36ff-11ea-9a0a-b74809d9b9bb.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
