### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by MissarvaT** [netology-code/git-homeworks-neuro-issues#402]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Safari
2. Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат
Ширина формы адаптирована для комфортного взаимодействия.

### Фактический результат
Форма слишком узкая – неудобно читать текст и вносить данные.

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншот
![2](https://user-images.githubusercontent.com/54108000/72522626-2e727600-386f-11ea-8563-3d5a7b0fc1e7.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
