### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by dmitry-korotkov** [netology-code/git-homeworks-neuro-issues#403]
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome;
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/57562584/72554242-5384da00-38ab-11ea-85f4-e19d43d05e6b.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
