### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by dmitry-korotkov** [netology-code/git-homeworks-neuro-issues#404]
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока с формой обратной связи "Оставайтесь на связи..."

### Ожидаемый результат
Форма обратной связи растянута по ширине мобильного устройства

### Фактический результат
Форма обратной связи слишком сжата. (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/57562584/72555033-e114f980-38ac-11ea-83a6-66a05773e6a0.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
