### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by r-krasovskiy** [netology-code/git-homeworks-neuro-issues#405]
# Problems with mobile version

## 1. Wrong head margins with width 320px
 1) right and left h1 margins are not equal
 2) the same about h2

![image](https://user-images.githubusercontent.com/54819181/72561674-c184cd80-38ba-11ea-8591-aa6ea166419e.png)

**Action plan:** make margins shorter, centre h1, h2. 

## 2. Incorrect form positioning

![image](https://user-images.githubusercontent.com/54819181/72561947-5ee00180-38bb-11ea-895f-0dddb8a7b95a.png)

**Action plan:**  make form area larger, put text/check boxes, labels and button in correct order.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
