### ISSUE TITLE
Главная страница "NeuroStartUp". Съехала верстка для экранов мобильных устройств

### ISSUE THREAD

**Issue by toptun80** [netology-code/git-homeworks-neuro-issues#406]
### **Шаги воспроизведения:**
- открыть главную страницу сайта NeuroStartUp: [neurostartup.__](url)

### **Ожидаемый результат:** 
- над логотипом отображается текст главной страницы, который не соприкасается с логотипом;
- под логотипом располагается блок с формой обратной связи, текст в блоке отображается с соблюдением правил русского языка и имеет эстетичный формат.

### **Фактический результат:**
- текст главной страницы наезжает на логотип;
- узкая разметка формы обратной связи, неэстетичный формат текста, слова переносятся с нарушением правил грамматики.
   **(см. скриншоты)**

### **Окружение:**
- Устройства: Google Pixel 2 (Android 9), iPhone X (iOS 13)
- Браузер: Chrome (79.0.3945)

###     **Pixel 2 / Screenshot 1**
![2020-01-16_233641](https://user-images.githubusercontent.com/54706630/72563015-cc8d2d00-38bd-11ea-989e-da3e56807889.jpg)

###     **Pixel 2 / Screenshot 2**
![2020-01-16_233712](https://user-images.githubusercontent.com/54706630/72563018-cc8d2d00-38bd-11ea-87ce-76eeb23b4424.jpg)

###     **iPhone X / Screenshot 1**
![2020-01-17_001734](https://user-images.githubusercontent.com/54706630/72563961-d1eb7700-38bf-11ea-92f8-aafe2c5989c6.jpg)

###     **iPhone X / Screenshot 1**
![2020-01-17_001758](https://user-images.githubusercontent.com/54706630/72563980-d879ee80-38bf-11ea-931d-d4e8c7166ec6.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
