### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by PronzhenkoKonstantin** [netology-code/git-homeworks-neuro-issues#407]
#  Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." текст наезжает на картинку
## Шаги по воспроизведению:
  1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome;
  2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат:
Текст не наезжает на изображение

## Фактический результат:
Текст наезжает на изображение (см. скриншот)

## Программное окружение:
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

## Скриншоты:
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/59308700/72584700-2c0a2d80-38fc-11ea-9581-65c59073433f.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
