### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by PronzhenkoKonstantin** [netology-code/git-homeworks-neuro-issues#408]
# Главная страница. Блок с формой "Оставайтесь на связи..." слишком сжата.

### Шаги по воспроизведению:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока с формой обратной связи "Оставайтесь на связи..."

### Ожидаемый результат:
Форма обратной связи растянута по ширине мобильного устройства

### Фактический результат:
Форма обратной связи слишком сжата. (см. скриншот)

### Программное окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/59308700/72585396-fe72b380-38fe-11ea-82bb-18bce384d4d4.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
