### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by BuAleksandr** [netology-code/git-homeworks-neuro-issues#4081]
**Главная страница . Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**
  

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"
   

**Ожидаемый результат**

Форма обратной связи корректна

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

Скриншот
![форма обратной связи](https://user-images.githubusercontent.com/87057144/125375602-0d8fd000-e3d5-11eb-9a08-1ad8b8cc9622.png)

@solarrust

**Comment by AlexandrProkhorenko** [comment]
Санек! Привет! Я тут)))))) Почему корявую верстку сделал????)))))))
