### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Fedaykin1980** [netology-code/git-homeworks-neuro-issues#409]
## Описание проблемы:
# Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." Текст наезжает на картинку

## Шаги по воспроизведению:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Текущая ситуация - при просмотре лендинга в мобильном браузере выявлена проблема:

* Текст наезжает на картинку (см. скриншот)

![1](https://user-images.githubusercontent.com/58568435/72603575-52df5880-392a-11ea-9900-ff0d03fd2e4d.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
