### ISSUE TITLE
Форма обратной связи слишком сжата 

### ISSUE THREAD

**Issue by dunaevaalisa** [netology-code/git-homeworks-neuro-issues#41]
@solarrust
# Описание проблемы
### Шаги по воспроизведению 
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи..."
### Ожидаемый результат
Форма занимает установленное место 
### Фактический результат 
Форма слишком сжата (см. скриншот) 
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/48627604/54614985-6140b780-4a6e-11e9-80a8-37cc96c9b2aa.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
