### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Fedaykin1980** [netology-code/git-homeworks-neuro-issues#410]
## Описание проблемы:
# Форма обратной связи слишком сжата

## Шаги по воспроизведению:

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

- Пролистать страницу до блока с формой обратной связи "Оставайтесь на связи..."

## Ожидаемый результат:
Форма обратной связи растянута по ширине мобильного устройства

## Текущая ситуация:
при просмотре лендинга в мобильном браузере выявлена проблема:
Форма обратной связи слишком сжата (см. скриншот)
![2](https://user-images.githubusercontent.com/58568435/72604303-af8f4300-392b-11ea-9fc1-d587016a0456.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
