### ISSUE TITLE
Текст на главной наезжает на изображение

### ISSUE THREAD

**Issue by sharikova** [netology-code/git-homeworks-neuro-issues#411]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Safari
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone XS Max (iOS 13.1)
* Браузер: Safari

#### Скриншоты

![](https://i.imgur.com/HJ1VbMj.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
