### ISSUE TITLE
Слишком узкая форма обратной связи

### ISSUE THREAD

**Issue by sharikova** [netology-code/git-homeworks-neuro-issues#412]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Safari
2. Пролистать страницу до блока обратной связи

#### Ожидаемый результат

Форма с белым фоном занимает всю ширину видимой области страницы

#### Фактический результат

Форма занимает только центр (см. скриншот)

#### Программное окружение

* Устройство: iPhone XS Max (iOS 13.1)
* Браузер: Safari

#### Скриншоты

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
