### ISSUE TITLE
Проблема с версткой

### ISSUE THREAD

**Issue by sheriff777** [netology-code/git-homeworks-neuro-issues#413]
ИНформация для @solarrust 

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. приложенные два скриншота)

Программное окружение
Устройство: Windows 10
Браузер: Chrome (Версия 79.0.3945.117 (Официальная сборка), (64 бит))

![000](https://user-images.githubusercontent.com/56364272/72680212-7d274680-3ae1-11ea-99b1-2c05d5f7a721.jpg)
![111](https://user-images.githubusercontent.com/56364272/72680218-8e705300-3ae1-11ea-8fe7-0bf507e3b688.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
