### ISSUE TITLE
На главной странице, текстовый блок наезжает на изображение на мобильных устройствах

### ISSUE THREAD

**Issue by zhukovskysv** [netology-code/git-homeworks-neuro-issues#414]
### Описание

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение на мобильных устройствах

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HJ1VbMj.png)

857e3d95477bfbd9c93fb04804a64d0007c1c075

https://github.com/netology-code/git-homeworks-neuro-issues/blob/857e3d95477bfbd9c93fb04804a64d0007c1c075/index.html#L43

ДЗ для проверки Алёной @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
