### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by rinAkhm** [netology-code/git-homeworks-neuro-issues#415]
Для @solarrust 

Шаги по воспроизведению:
1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат:
Текст не наезжает на изображение

Фактический результат:
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншоты:
![image](https://user-images.githubusercontent.com/59740123/72686115-3c8bf500-3b02-11ea-89c0-a8c6b7a7c68f.png)
![image](https://user-images.githubusercontent.com/59740123/72686121-562d3c80-3b02-11ea-9834-c58b81d91757.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
