### ISSUE TITLE
Форма обратной связи очень сжата

### ISSUE THREAD

**Issue by Solomakhin-Anton** [netology-code/git-homeworks-neuro-issues#417]
### Страница с формой обратной связи.

# Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Обратная связь"

## Ожидаемый результат
Форма обратной связи удобна для заполнения, в ней видны все введенные символы.

## Фактический результат
Форма очень сжата, отчего не видны все введенные символы (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/59666885/72688621-2427d480-3b1a-11ea-8fff-132f65650db2.png)

Для @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
