### ISSUE TITLE
Текст "Воспользуйтесь современными ..." наезжает на картинку

### ISSUE THREAD

**Issue by NikkiNoble** [netology-code/git-homeworks-neuro-issues#418]
# Описание проблемы
Текст: "Воспользуйтесь современными возможностями искусственного интеллекта, оставив конкурентов позади!" в мобильном браузере наезжает на изображение NeuroStartUp.
## Программное окружение

- Устройство: iPhone 7 (13.3)

- Браузер: Chrome 79.0.3945.73

## Шаги воспроизведения

1. Открыть сайт NeuroStartUp, используя мобильный браузер типа Chrome.

1. Пролистать главную страницу вниз до изображения.
## Ожидаемый результат
Текст находится над картинкой, легко читается и не пересекается с ней
## Фактический результат
Текст наезжает на картинку

![Скриншот текст на картинке](https://user-images.githubusercontent.com/59572257/72688948-33872d80-3ada-11ea-965e-3ce48ed12e84.jpg) 

Для @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
