### ISSUE TITLE
Форма обратной связи на сайте NeuroStartUp сжата

### ISSUE THREAD

**Issue by NikkiNoble** [netology-code/git-homeworks-neuro-issues#419]
# Описание проблемы
Форма обратной связи на главной странице слишком сжата и вытянута.
## Программное окружение

- Устройство: iPhone 7 (13.3)

- Браузер: Chrome 79.0.3945.73
## Шаги воспроизведения
1. Открыть сайт NeuroStartUp, используя мобильный браузер типа Chrome.

1. Пролистать главную страницу вниз до формы обратной связи.
##  Ожидаемый результат

- Форма обратной связи квадратная

- Фразы "Оставайтесь на связи", "Даю согласие..." и т.д. занимают по одной строке и удобны в прочтении
## Фактический результат
- Форма сильно сжата
- Текст  разорван и трудно читаем

![Скриншот формы](https://user-images.githubusercontent.com/59572257/72689190-e22c6d80-3adc-11ea-828f-537bdd30232d.jpg)

 Для @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
