### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by dunaevaalisa** [netology-code/git-homeworks-neuro-issues#42]
@solarrust
# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение (см. скриншот)
### Программное окружение 
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/48627604/54616258-7880a480-4a70-11e9-9925-4e0280f7599c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
