### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by ReactORcss** [netology-code/git-homeworks-neuro-issues#422]
@solarrust, https://github.com/netology-code/git-homeworks-neuro-issues/issues/new 

**Шаги по решению проблемы:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение:**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/57535924/72738060-cf379d00-3bb1-11ea-89df-261d1ae6ca1b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
