### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ReactORcss** [netology-code/git-homeworks-neuro-issues#423]
@solarrust 

**Описание проблемы**
Форма обратной связи на главной странице слишком сжата

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Шаги воспроизведения**

1. Открыть сайт NeuroStartUp, используя мобильный браузер типа Chrome.
2. Пролистать главную страницу вниз до формы обратной связи.

**Фактический результат**

- Форма сильно сжата
- Текст разорван и трудно читаем

**Ожидаемый результат**

- Форма обратной связи не сжата
- Фразы "Оставайтесь на связи", "Даю согласие..." и т.д. занимают по одной строке
![221](https://user-images.githubusercontent.com/57535924/72738889-9b5d7700-3bb3-11ea-9b24-670459786633.jpg)

**Comment by ReactORcss** [comment]
![221](https://user-images.githubusercontent.com/57535924/72738833-7c5ee500-3bb3-11ea-8dfb-a32f3dfd5985.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
