### ISSUE TITLE
### Описание проблемы

### ISSUE THREAD

**Issue by johnny-Azimov** [netology-code/git-homeworks-neuro-issues#424]
@solarrust  

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по  воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты
![7](https://user-images.githubusercontent.com/59313698/72741988-c3fd6500-3be3-11ea-9a41-0ddb37d5d1c4.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
