### ISSUE TITLE
Легенда 2. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by johnny-Azimov** [netology-code/git-homeworks-neuro-issues#425]
@solarrust 

### Страница с формой обратной связи.

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Обратная связь"

**Ожидаемый результат**

Форма обратной связи удобна для заполнения.

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты

![8](https://user-images.githubusercontent.com/59313698/72744319-48ea7d80-3be8-11ea-8483-13a6121897dd.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
