### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by sheriff777** [netology-code/git-homeworks-neuro-issues#428]
Информация для @solarrust 

Главная страница. В блоке формы обратной связи неправильная верстка, она слишком узкая.

Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Safari
Пролистать страницу до блока обратной связи

Ожидаемый результат
Форма с белым фоном занимает всю ширину видимой области страницы

Фактический результат
Форма занимает только центр (см. скриншот)

Программное окружение
Устройство: Windows 10
Браузер: Chrome (Версия 79.0.3945.117 (Официальная сборка), (64 бит))

![111](https://user-images.githubusercontent.com/56364272/72822846-f919be00-3c9c-11ea-8285-5299c74eb1a9.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
