### ISSUE TITLE
Задача 2. Главная страница. Форма обратной связи сжата 

### ISSUE THREAD

**Issue by AnnaPo-hub** [netology-code/git-homeworks-neuro-issues#429]
@solarrust , привет! 

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в  браузере Safari.
Пролистать страницу до формы обратной связи. 

**Ожидаемый результат**
Форма имеет такую ширину, чтобы  каждое предложение помещалось по ширине в одну строку. 

**Фактический результат**
Форма узкая с переносами строк. 

**Программное окружение**

Устройство: MacBook Pro, macOS High Sierra (10.13.6)
Браузер:  Safari 13.0.4

![Снимок экрана 2020-01-22 в 22 17 02](https://user-images.githubusercontent.com/59263609/72926740-fafb8400-3d65-11ea-86e5-c2ae4969f7f0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
