### ISSUE TITLE
homework-3.2/2

### ISSUE THREAD

**Issue by sSlideR** [netology-code/git-homeworks-neuro-issues#431]
_Ещё чуть-чуть работы для @solarrust_ 

# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

### Ожидаемый результат
Форма обратной связи растянута на всю ширину экрана.

### Фактический результат
Форма обратной связи сужена, занимает ~50% ширины экрана (см. скриншоты).

### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![Screenshot2](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
