### ISSUE TITLE
Home-work-3-2-1

### ISSUE THREAD

**Issue by dsk4git** [netology-code/git-homeworks-neuro-issues#432]
Предложение для @solarrust 

# Описание проблемы
-------------------------------
### Шаги по воспроизведению ###
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат ###
Текст не наезжает на изображение

### Фактический результат ###
Текст наезжает на изображение (см. скриншот)
![scrshot_3_2](https://user-images.githubusercontent.com/59534086/73017718-b50ff000-3e39-11ea-9dfb-cfc670a71d3e.png)

### Программное окружение ###
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
