### ISSUE TITLE
Home-3-2-2

### ISSUE THREAD

**Issue by dsk4git** [netology-code/git-homeworks-neuro-issues#433]
Пожалуйста, ещё для @solarrust 

# Описание проблемы #
### Шаги по воспроизведению ###
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи
### Ожидаемый результат ###
Форма обратной связи растянута на всю ширину экрана.

### Фактический результат ###
Форма обратной связи сужена, занимает ~50% ширины экрана (см. скриншоты).

### Программное окружение ###
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты ###
![scrshot_3_2_3](https://user-images.githubusercontent.com/59534086/73018398-fce34700-3e3a-11ea-881a-bc18e8840356.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
