### ISSUE TITLE
Текст "Воспользуйтесь современными возможностями..." на главной странице наезжает на изображение 

### ISSUE THREAD

**Issue by IrinaStyazhkina** [netology-code/git-homeworks-neuro-issues#434]
### Описание проблемы
Текст "Воспользуйтесь современными возможностями..." на главной странице наезжает на изображение

### Шаги по воспроизведению

1. Перейти на главную страницу NeuroStartUp в мобильном браузере Chrome

1. Пролистать/проскроллить страницу до текста "Воспользуйтесь современными возможностями..." 

### Ожидаемый результат
Текст читается на контрастном фоне, не наезжает на изображение

### Фактический результат
Текст наезжает на изображение, сливается с фоном изображения, из-за чего практически не читаем (см. Скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![bug1](https://user-images.githubusercontent.com/47478651/72753400-e7b9ae80-3bd5-11ea-80b3-27a5def50303.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
