### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by IrinaStyazhkina** [netology-code/git-homeworks-neuro-issues#435]
### Описание проблемы
Форма обратной связи на главной странице слишком сжата

### Шаги по воспроизведению

1. Перейти на главную страницу NeuroStartUp в мобильном браузере Chrome

1. Пролистать/проскроллить страницу до формы обратной связи

### Ожидаемый результат
Форма обратной связи растянута на всю ширину устройства, текст читаем, в формах ввода достаточно пространства для текста

### Фактический результат
Форма слишком сжата, справа и слева есть ненужные значительные отступы.
Присутствуют ненужные переносы, из-за чего текст трудно читаем (см. Скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![bug2](https://user-images.githubusercontent.com/47478651/72754060-d83b6500-3bd7-11ea-8a67-ee550b12d488.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
