### ISSUE TITLE
Текст не наезжает на изображение

### ISSUE THREAD

**Issue by VeraKoptelova** [netology-code/git-homeworks-neuro-issues#438]
Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/57529376/73119903-de3f9600-3f89-11ea-8c77-9708fc48c24b.png)

**Comment by VeraKoptelova** [comment]
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
