### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by VeraKoptelova** [netology-code/git-homeworks-neuro-issues#439]
Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/57529376/73120011-f8c63f00-3f8a-11ea-826c-4094d680088a.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
