### ISSUE TITLE
Убрать текст с картинки

### ISSUE THREAD

**Issue by OftinaAleksandra** [netology-code/git-homeworks-neuro-issues#440]
@solarrust
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

** Скриншот**
![skrin1](https://user-images.githubusercontent.com/57321205/73120807-9289ee00-3f83-11ea-9419-8d36b08a6017.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
