### ISSUE TITLE
Масштабировать форму обратной связи под размер экрана

### ISSUE THREAD

**Issue by OftinaAleksandra** [netology-code/git-homeworks-neuro-issues#441]
@solarrust
**Форма обратной связи слишком сжата**

**Шаги по воспроизведению**
1. Открыть страницу обратной связи в мобильном браузере Chrome
2. Убедиться, что форма обратной связи сжата, имеется много свободного пространства вокруг формы.

**Ожидаемый результат**
Форма по размеру экрана

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

** Скриншот**
![skrin2](https://user-images.githubusercontent.com/57321205/73120884-894d5100-3f84-11ea-9119-527279722695.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
