### ISSUE TITLE
При просмотре лендинга в мобильном браузере текст наезжает на картинку

### ISSUE THREAD

**Issue by em0x5c** [netology-code/git-homeworks-neuro-issues#442]
@solarrust
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

###  Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное  окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/58791882/73139018-56858480-407a-11ea-9ac1-b8f889aab3cc.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
