### ISSUE TITLE
При просмотре лендинга в мобильном браузере форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by em0x5c** [netology-code/git-homeworks-neuro-issues#443]
@solarrust
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Форма обратной связи"

### Ожидаемый результат
Форма обратной связи не сжата и удобочитаема

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/58791882/73139136-ec6ddf00-407b-11ea-9a9d-922eaa36242c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
