### ISSUE TITLE
Текст наезжает на картинку.

### ISSUE THREAD

**Issue by Ksenia1311** [netology-code/git-homeworks-neuro-issues#444]
@solarrust

### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншоты
![1](https://user-images.githubusercontent.com/56920808/73201220-97989a00-4149-11ea-81b5-44a1d709e98b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
