### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Ksenia1311** [netology-code/git-homeworks-neuro-issues#445]
@solarrust

### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Обратная связь."
### Ожидаемый результат
Форма обратной связи не сжата

### Фактический результат
Форма обратной связи слишком сжата
 (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншоты
![2](https://user-images.githubusercontent.com/56920808/73201706-ab90cb80-414a-11ea-9d8c-4a6474b1aa4a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
