### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by PWMaestro** [netology-code/git-homeworks-neuro-issues#45]
# Описание проблемы
@solarrust 
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение
### Фактический результат
Текст наезжает на изображение (см. скриншот)
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![image](https://user-images.githubusercontent.com/48484710/54631572-58131300-4a8d-11e9-82a9-d78eb8e7d051.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
