### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Cancelkam** [netology-code/git-homeworks-neuro-issues#450]
@solarrust 
### **Описание проблемы**
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/49454495/73295489-d3e6fb80-4218-11ea-8450-1bd00ab76617.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
