### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Cancelkam** [netology-code/git-homeworks-neuro-issues#451]
@solarrust 
## **Описание проблемы**
# **Форма обратной связи слишком сжата**
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
**Ожидаемый результат**
Форма обратной связи полноразмерна

**Фактический результат**
 Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/49454495/73295974-c3835080-4219-11ea-8ecd-64c6715a5a5f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
