### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by ggamarin** [netology-code/git-homeworks-neuro-issues#454]
Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/60188645/73591506-5b29bd00-4500-11ea-9a3a-d131bc12bb2c.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
