### ISSUE TITLE
Форма обратной связи сжата по горизонтали

### ISSUE THREAD

**Issue by ggamarin** [netology-code/git-homeworks-neuro-issues#455]
Описание проблемы
Главная страница. Форма обратной связи "Оставайтесь на связи" слишком сжата.
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до формы обратной связи "Оставайтесь на связи".
Ожидаемый результат
Форма обратной связи растянута по горизонтали.

Фактический результат
Форма обратной связи вытянута и сжата (см. скриншот).

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60188645/73591519-8f9d7900-4500-11ea-80e9-331eab232ebb.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
