### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by marinagagarina** [netology-code/git-homeworks-neuro-issues#456]
**Шаги по воспроизведению.**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
3. Ожидаемый результат
4. Текст наезжает на изображение

**Фактический результат.**
Текст наезжает на изображение (см. скриншот)
@solarrust

**Программное окружение.**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
https://prnt.sc/qw3h8u

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
