### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by marinagagarina** [netology-code/git-homeworks-neuro-issues#457]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
Ширина формы обратной связи соответствует ширине экрана устройства и расположенному в форме тексту

**Фактический результат**
Ширина формы обратной связи слишком маленькая (см. скриншот)
@solarrust

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
https://prnt.sc/qw3kxd

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
