### ISSUE TITLE
Ошибки мобильной верстки 

### ISSUE THREAD

**Issue by uhdasha** [netology-code/git-homeworks-neuro-issues#458]
Ожидаемый результат
Текст не наезжает на изображение 

Фактический результат
Текст наезжает на изображение (см.скриншот)

Программное окружение
Устройство : IPhone (6/7/8)
Браузер : Chrome Версия 79.0.3945.130 (Официальная сборка), (64 бит)

Скриншоты
http://prntscr.com/qwtxd5

Главная страница ,форма обратной связи слишком сжата 
Шаги по воспроизведению
Открыть главную страницу веб сайта HeuroStartUp в мобильном браузере Chrome 
Пролистать страницу до веб-формы обратной связи "Воспользуйтесь современными возможностями ...

Ожидаемый результат 
Веб форма должна быть растянута по ширине экрана 

Фактический результат 
Веб форма имеет большие отступы по краям( правый и левый лендинг)

Программное окружение
Браузер : Chrome Версия 79.0.3945.130 (Официальная сборка), (64 бит)
скриншоты

![image_2020_02_03T11_49_10_918Z](https://user-images.githubusercontent.com/60215196/73652749-a2e34c80-4698-11ea-92aa-7e0417b36d52.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
