### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Dolidenok** [netology-code/git-homeworks-neuro-issues#459]
# Описание проблемы
### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншоты
![1](https://user-images.githubusercontent.com/60171644/73656955-4553fd80-46a2-11ea-8652-37f57a967d60.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
