### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by PWMaestro** [netology-code/git-homeworks-neuro-issues#46]
# Описание проблемы
@solarrust
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи.
### Ожидаемый результат
Текст заголовка по возможности не переносится на следующую строку;
При невозможности написания заголовка в одну строку он переносится по словам;
Боковые поля от краёв страницы до формы связи равны примерно 20px.
### Фактический результат
Текст заголовка переносится из-за нехватки места в строке;
Слова в заголовке переносятся по частям;
Боковые поля вокруг формы сравнимы с шириной формы.
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![image](https://user-images.githubusercontent.com/48484710/54632002-2a7a9980-4a8e-11e9-8221-5c4fd91263f1.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
