### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Dolidenok** [netology-code/git-homeworks-neuro-issues#460]
# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Перейти в раздел "Обратная связь"
### Ожидаемый результат
Форма обратной связи растягивается на весь экран

### Фактический результат
Форма обратной связи не растягивается на весь экран (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншоты
![2](https://user-images.githubusercontent.com/60171644/73657346-26a23680-46a3-11ea-9cec-0f3dae677247.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
