### ISSUE TITLE
Баг верстки. Текст наезжает на картинку

### ISSUE THREAD

**Issue by mkovarsky** [netology-code/git-homeworks-neuro-issues#461]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![112](https://user-images.githubusercontent.com/60435481/73665042-80116200-46b1-11ea-94b7-284f014182e3.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
