### ISSUE TITLE
Баг верстки. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by mkovarsky** [netology-code/git-homeworks-neuro-issues#462]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма обратной связи масштабируется под мобильный браузер

#### Фактический результат

Форма обратной связи сжата 

 (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![113](https://user-images.githubusercontent.com/60435481/73666063-388bd580-46b3-11ea-8ffd-50078d9c69ac.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
