### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by AntonZ-Frank** [netology-code/git-homeworks-neuro-issues#464]
# Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями" наезжает на изображение
## Шаги к воспроизведению
Открыть главную страницу сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями"

## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (прилог. скрин)

## Программное окружение
Устройство: DOOGE (Android 6.0)
Браузер: Chrome (70.0.3538.75)

## Cкриншот
![image](https://user-images.githubusercontent.com/60180659/73933148-a4617e80-48fd-11ea-980b-34fb3532a79a.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
