### ISSUE TITLE
Изображение наезжает на текст 

### ISSUE THREAD

**Issue by MrKarlino** [netology-code/git-homeworks-neuro-issues#466]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.** 

**Шаги по воспроизведению:**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**

![image](https://user-images.githubusercontent.com/60093547/73975329-28842800-4937-11ea-8805-ea49d0c10f00.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
