### ISSUE TITLE
Форма обратной связи слишком сжата 

### ISSUE THREAD

**Issue by MrKarlino** [netology-code/git-homeworks-neuro-issues#467]
**Главная страница. Блок формы заполнения для обратной связи слишком сжат.** 

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Тест полностью влезает в окно, у формы небольшие боковые отступы. 

**Фактический результат**
Форма сжата по краям (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![image](https://user-images.githubusercontent.com/60093547/73975504-8153c080-4937-11ea-8953-5a52656d8084.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
