### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Musppelheim** [netology-code/git-homeworks-neuro-issues#470]
# Описание проблемы
### Шаги по воспроизведению
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/58906082/74082228-8412fa80-4a8a-11ea-983c-1e5281af6665.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
