### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Musppelheim** [netology-code/git-homeworks-neuro-issues#471]
# Описание проблемы

### Шаги по воспроизведению
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до блока обратной связи

### Ожидаемый результат
Форма обратной связи отображается правильно

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/58906082/74083023-0a7f0a80-4a92-11ea-84f4-e96ed163a26d.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
