### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Maik808** [netology-code/git-homeworks-neuro-issues#475]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока обратной связи
### Ожидаемый результат
Форма обратной связи отображается правильно

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)
### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60012572/74088958-03b1c100-4aad-11ea-8874-2e6ea1a8a245.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
