### ISSUE TITLE
Текст наезжает на изображение.

### ISSUE THREAD

**Issue by Alexabelyatskaya** [netology-code/git-homeworks-neuro-issues#476]
**Описание проблемы**

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение.

**Фактический результат**

Текст наезжает на изображение (см. скриншот).

**Программное окружение**

-  Устройство: iPhone 8+ (iOS 12.1)
-  Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![изображение](https://user-images.githubusercontent.com/59415457/74090828-251ca800-4ac1-11ea-833e-7a6a4da12e79.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
