### ISSUE TITLE
Форма обратной связи заужена.

### ISSUE THREAD

**Issue by Alexabelyatskaya** [netology-code/git-homeworks-neuro-issues#477]
**Описание проблемы**

Форма обратной связи. Искажение верстки, форма обратной связи и поля ввода слишком узкие.

**Шаги по воспроизведению**

Открыть форму обратной связи.

**Ожидаемый результат**

Форма обратной связи достаточной ширины.

**Фактический результат**

Искажение верстки, форма обратной связи и поля ввода слишком узкие.

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![изображение](https://user-images.githubusercontent.com/59415457/74090918-81cc9280-4ac2-11ea-8b75-d3bd21f4b515.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
