### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by chirkovaekaterina** [netology-code/git-homeworks-neuro-issues#479]
### Описание

Главная страница. При просмотре с мобильного браузера форма обратной связи слишком сжата

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока обратной связи

**Ожидаемый результат**

Форма обратной связи отображается правильно

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60105549/74101976-3cef3d00-4b50-11ea-8b59-972bed8c2c4f.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
