### ISSUE TITLE
Ошибки в мобильной версии: Текст наезжает на картинку; Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Ruslan39** [netology-code/git-homeworks-neuro-issues#48]
@solarrust, обнаружены 2 ошибки при открытии лендинга через мобильное устройство.

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![ТекстНаезжает](https://camo.githubusercontent.com/e648681205a1dfdf6ed69784e1311b18ca924856/68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67)

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу вниз до блока "Обратный звонок"

#### Ожидаемый результат
Форма обратной связи нормальных размеров, удобна в использовании

#### Фактический результат
Форма обратной связи слишком сжата, занимает только половину экрана (см. скриншот)

#### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![УзкаяФорма](https://user-images.githubusercontent.com/43821963/54635459-e044e880-4a8c-11e9-8227-7e50b1895a20.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
