### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by OlgaNikulina** [netology-code/git-homeworks-neuro-issues#480]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты 

![Screenshot 3 1](https://user-images.githubusercontent.com/58890284/74104856-cf0c3b00-4b7a-11ea-80b3-3cc4b97f76c8.png)
@solarrust.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
