### ISSUE TITLE
Форма обратной связи неудобна для чтения

### ISSUE THREAD

**Issue by OlgaNikulina** [netology-code/git-homeworks-neuro-issues#481]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи..."

### Ожидаемый результат
Текстовый блок имеет более удобный для чтения вид.

### Фактический результат
Текстовый блок слишком сжат по ширине. (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

### Скриншоты

![Screenshot 3 1 -2](https://user-images.githubusercontent.com/58890284/74105033-34146080-4b7c-11ea-97e8-5fa4f81752ea.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
