### ISSUE TITLE
Некорректное отображение в мобильном браузере

### ISSUE THREAD

**Issue by AnnaDymova** [netology-code/git-homeworks-neuro-issues#482]
1. Главная_ страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**
  

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
-  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение
**Фактический результат**
Текст наезжает на изображение (см. скриншот)
**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![главная](https://user-images.githubusercontent.com/57713686/74132182-1afcc580-4bf7-11ea-9035-aaa5e05e6afc.jpg)

2. Форма обратной связи слишком сжата.

**Шаги по воспроизведению**
  
-  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
-   Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма отображается корректно
**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)
**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![ФС](https://user-images.githubusercontent.com/57713686/74133848-8300db00-4bfa-11ea-9461-ae8835661450.jpg)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
