### ISSUE TITLE
1. Текст наезжает на картинку;

### ISSUE THREAD

**Issue by Casa-Bonita** [netology-code/git-homeworks-neuro-issues#487]
### Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

_Скриншоты_

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/54758424/74296640-7644ca00-4d55-11ea-816f-c684e1fdc8d5.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
