### ISSUE TITLE
2. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Casa-Bonita** [netology-code/git-homeworks-neuro-issues#488]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма отображается корректно

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/54758424/74296840-0be05980-4d56-11ea-8dd8-a97392838cf6.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
