### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by l75800** [netology-code/git-homeworks-neuro-issues#489]
**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма отображается корректно

**Фактический результат**
Форма обратной связи отражается некорректно, слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

@solarrust 
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67-2](https://user-images.githubusercontent.com/59611972/74310986-de140880-4d87-11ea-966a-b07810dd05fa.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
