### ISSUE TITLE
Исправление ошибки в верстке главной странницы и формы

### ISSUE THREAD

**Issue by Adnormalize** [netology-code/git-homeworks-neuro-issues#49]
# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение
### Фактический результат
Текст наезжает на изображение (см. скриншот)
### Программное окружение

- Устройство iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/48749037/55058925-13483700-50a0-11e9-912d-80736652da87.png)
![ffasfsa](https://user-images.githubusercontent.com/48749037/55058983-47bbf300-50a0-11e9-99e7-c820611dc380.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
