### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by AntonZ-Frank** [netology-code/git-homeworks-neuro-issues#492]
# Описание проблемы
Главная страница. Форма обратной связи слишком сжата.
## Шаги по воспроизведению
Открыть главную страницу сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Форма обратной связи".

## Ожидаемый результат
Форма обратной связи отображается в соответствии с ТЗ, адаптируется под разрешение.

## Фактический результат
Форма обратной связи слишком сжата (см. скрин)

## Программное окружение
Устройство: DOOGE (Android 6.0)
Браузер: Chrome (70.0.3538.75)

## Cкриншот
![image](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
