### ISSUE TITLE
Главная страница. Текстовый блок наезжает на изображение.

### ISSUE THREAD

**Issue by sergsemenov** [netology-code/git-homeworks-neuro-issues#493]
@solarrust 

# Описание проблемы

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

### Шаги по воспроизведению
 
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат

Текст не наезжает на изображение

### Фактический результат

Текст наезжает на изображение (см. скриншот)

### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты

![изображение](https://user-images.githubusercontent.com/60171896/74419286-b8a3ff00-4e5a-11ea-9158-5663e6d0fcb3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
