### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by sergsemenov** [netology-code/git-homeworks-neuro-issues#494]
@solarrust 

# Описание проблемы

Главная страница. Форма обратной связи слишком сжата.

### Шаги по воспроизведению
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до блока "Воспользуйтесь современными возможностями..." (до формы обратной связи?)

### Ожидаемый результат

Форма обратной связи имеет ширину, указанную в документации по проекту.

### Фактический результат

Форма обратной связи чрезмерно узка (см. скриншот).

### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты
![изображение](https://user-images.githubusercontent.com/60171896/74419877-9bbbfb80-4e5b-11ea-8ba1-250db04dd639.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
