### ISSUE TITLE
В мобильной версии лендинга текстовый блок наезжает на изображение;

### ISSUE THREAD

**Issue by camenzindmp** [netology-code/git-homeworks-neuro-issues#495]
@solarrust

# Описание проблемы #
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

## Шаги по воспроизведению ##
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат ##
Текст не наезжает на изображение

## Фактический результат ##
Текст наезжает на изображение (см. скриншот)

## Программное окружение ##
1. Устройство: iPhone 8+ (iOS 12.1)
1. Браузер: Chrome (70.0.3538.75)

## Скриншоты ##
![nrst](https://user-images.githubusercontent.com/59551106/74503615-2c1e3d00-4f3d-11ea-97c0-469acc2f1a2e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
