### ISSUE TITLE
В мобильной версии лендинга форма обратной связи слишком сжата;

### ISSUE THREAD

**Issue by camenzindmp** [netology-code/git-homeworks-neuro-issues#496]
@solarrust

# Описание проблемы #
**Главная страница. Форма обратной связи слишком сжата.**

## Шаги по воспроизведению ##
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до формы обратной связи c заголовком **"Оставайтесь на связи"**

## Ожидаемый результат ##
Форма обратной связи имеет размеры, указанные в ТЗ по проекту

## Фактический результат ##
Размеры формы для обратной связи не соответсвуют ТЗ

## Программное окружение ##
1. Устройство: iPhone 8+ (iOS 12.1)
1. Браузер: Chrome (70.0.3538.75)

## Скриншоты ##
![nrst2](https://user-images.githubusercontent.com/59551106/74504202-2aee0f80-4f3f-11ea-846a-7f25d560c820.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
