### ISSUE TITLE
Текст наезжает на изображение 

### ISSUE THREAD

**Issue by MihailOkatev** [netology-code/git-homeworks-neuro-issues#497]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![screen](https://user-images.githubusercontent.com/57835783/74557702-c009fc00-4f71-11ea-8c35-14f4cf985c25.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
