### ISSUE TITLE
Форма обратной связи слишком сжата на мобильных устройствах 

### ISSUE THREAD

**Issue by MihailOkatev** [netology-code/git-homeworks-neuro-issues#498]
Главная страница. форма  "оставайтесь на связи" слишком сильно сжата

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
**Ожидаемый результат**

Нормальные размеры формы 
**Фактический результат**

форма сжата (см скриншот)
**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**Скриншоты**
![scr2](https://user-images.githubusercontent.com/57835783/74558214-ee3c0b80-4f72-11ea-959d-a747994b8975.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
