### ISSUE TITLE
Проблемы при просмотре лендинга на мобильном устройстве

### ISSUE THREAD

**Issue by plaguedoctor39** [netology-code/git-homeworks-neuro-issues#499]
## Проблемы
Указаны на скриншотах
1. Текст наезжает на картинку
1.  Форма обратной связи слишком сжата
## Программное окружение 
* Устройство: iPhone 6s (iOS 12.2)
* Браузер: Safari
## Скриншоты
![First](https://camo.githubusercontent.com/d90a6e5e9269c1926cc5e5ea6d624a3a06b53f9a/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)
![Second](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
