### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Adnormalize** [netology-code/git-homeworks-neuro-issues#50]
# Описание проблемы
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/48749037/55148958-d6ea0900-517b-11e9-8c4b-fadd24de9e4b.png)
### Нужно исправить ошибку. Сделать так, что-бы текст не наезжал на картинку
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
