### ISSUE TITLE
Текст на странице в мобильном браузере наезжает на картинку

### ISSUE THREAD

**Issue by VickyBooGit** [netology-code/git-homeworks-neuro-issues#500]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Safari
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение
#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8 (iOS 13.3.1)
* Браузер: Safari (13.3.1)

#### Текст наезжает на изображение
![image](https://user-images.githubusercontent.com/60144042/74663622-2af34700-51ad-11ea-8948-e0693ec8411c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
