### ISSUE TITLE
Форма обратной связи в мобильном браузере выглядит сжато

### ISSUE THREAD

**Issue by VickyBooGit** [netology-code/git-homeworks-neuro-issues#501]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть страницу Формы обратной связи в браузере Safari

#### Ожидаемый результат

Форма открывается на всю страницу

#### Фактический результат

Форма сжата 

#### Программное окружение

* Устройство: iPhone 8 (iOS 13.3.1)
* Браузер: Safari (13.3.1)

#### Форма на странице выглядит сжатой
![image](https://user-images.githubusercontent.com/60144042/74663158-51fd4900-51ac-11ea-8768-40a0f0039971.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
