### ISSUE TITLE
Главная страница сайта. Блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by alexreshetnikova** [netology-code/git-homeworks-neuro-issues#502]
Коллеги, добрый день!
@solarrust, обнаружен баг.

**Шаги по воспроизведению:**
1. Открыть главную страницу веб-сайта Neuro StartUp в браузере Firefox
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст белого цвета расположен на синем фоне, не наезжает на изображение
**Фактический результат**
Текст белого цвета наезжает на изображение белого цвета

**Программное окружение**
Устройство: Samsung Galaxy A50 (Android 9)
Браузер: Firefox (72.0.2)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/60314903/74668349-3f483b80-51cf-11ea-9db2-94a620488a64.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
