### ISSUE TITLE
Форма обратной связи в мобильной версии выглядит сжато

### ISSUE THREAD

**Issue by alexreshetnikova** [netology-code/git-homeworks-neuro-issues#503]
Коллеги, добрый день!
@solarrust, обнаружен баг.

**Шаги по воспроизведению:**
1. Открыть главную страницу веб-сайта Neuro StartUp в браузере Firefox
2. Открыть форму обратной связи

**Ожидаемый результат**
Текст равномерно распределен по ширине экрана
**Фактический результат**
Текст занимает 1/3 экрана

**Программное окружение**
Устройство: Samsung Galaxy A50 (Android 9)
Браузер: Firefox (72.0.2)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60314903/74669447-538d3800-51d1-11ea-963d-89327eeb599c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
