### ISSUE TITLE
Проблема с текстом и формой обратной связи

### ISSUE THREAD

**Issue by VieleSchritte** [netology-code/git-homeworks-neuro-issues#505]
@solarrust

### **Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome 
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями...

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Ожидаемый результат:**
Текст не наезжает на изображение

**Программное окружение**

- Устройство: iPhone X (iOS 12.1)
- Браузер: Google Chrome (70.0.3538.75)

**Скриншот**
<img width="654" alt="Screenshot 2020-02-18 at 12 39 44" src="https://user-images.githubusercontent.com/44835520/74724436-50d02880-524d-11ea-8dbd-d5f2fb16c441.png">

### **Форма обратной связи сжата слишком сильно**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome 
2. Пролистать страницу до формы обратной связи "Оставайтесь на связи"

**Фактический результат**
Форма сжата слишком сильно(см. скриншот)

**Ожидаемый результат:**
Форма занимает всю ширину блока

**Программное окружение**

- Устройство: iPhone X (iOS 12.1)
- Браузер: Google Chrome (70.0.3538.75)

**Скриншот**
<img width="401" alt="Screenshot 2020-02-18 at 12 49 39" src="https://user-images.githubusercontent.com/44835520/74724385-3b5afe80-524d-11ea-9034-d45092e75d88.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
