### ISSUE TITLE
Текст "Искусственный интеллект" наезжает на изображение

### ISSUE THREAD

**Issue by Nata-AMI** [netology-code/git-homeworks-neuro-issues#506]
Проблема. 
Текст "Искусственный интеллект для решения ваших задач" наезжает на изображение.

Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты

![Screenshot (1)](https://user-images.githubusercontent.com/58206222/74860141-f8427d80-5369-11ea-9a9f-ef070ec2a2c2.png)

![Screenshot (2)](https://user-images.githubusercontent.com/58206222/74860158-ff698b80-5369-11ea-8966-2c7f9f07b087.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
