### ISSUE TITLE
Проблема с формой обратной связи

### ISSUE THREAD

**Issue by VieleSchritte** [netology-code/git-homeworks-neuro-issues#507]
### **Форма обратной связи сжата слишком сильно**
Решила, что все-таки правильно создать отдельную issue для этой проблемы :)
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайте NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи "Оставайтесь на связи"

**Фактический результат:**
Форма сжата слишком сильно (см. скриншот)

**Ожидаемый результат:**
Форма занимает всю ширину блока

**Программное окружение**

- Устройство: iPhone X (iOS 12.1)
- Браузер: Google Chrome (70.0.3538.75)

**Скриншот**
<img width="401" alt="Screenshot 2020-02-18 at 12 49 39 1" src="https://user-images.githubusercontent.com/44835520/74927485-c02e4f80-53e8-11ea-8cd5-1f4d37c6397b.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
