### ISSUE TITLE
HW3.2 Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Polenova** [netology-code/git-homeworks-neuro-issues#509]
# Описание проблемы
### Форма обратной связи слишком сжата.

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2. Открыть станицу с блоком, где просят оставить контакты

**Ожидаемый результат**

Растянуть форму ближе к краям 

**Фактический результат**

Форма слишком сжата (см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/56669936/74939069-8a409980-53ef-11ea-8672-dd8545ae9694.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
