### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Adnormalize** [netology-code/git-homeworks-neuro-issues#51]
# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока c формой связи
### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)
### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/48749037/55149392-a8b8f900-517c-11e9-8cc7-b062aba02843.png)
## Решите проблему с оформлением формы обратной связи
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
