### ISSUE TITLE
Наезд текстового блока на изображение

### ISSUE THREAD

**Issue by Aleksei-Nikulshin** [netology-code/git-homeworks-neuro-issues#510]
### Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..."** **наезжает на изображение**

Предполагаемый исполнитель по устранению бага - @solarrust 
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![image](https://user-images.githubusercontent.com/60919700/75028895-ee805d80-54c2-11ea-9e3a-338fbf7f14f2.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
