### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Aleksei-Nikulshin** [netology-code/git-homeworks-neuro-issues#511]
### Описание проблемы
**Страница с обратной связью. Форма обратной связи занимает не всю ширину экрана (сжата)**

Предполагаемый исполнитель по устранению бага - @solarrust

#### Шаги по воспроизведению
Открыть страницу веб-сайта в Google Chrome 

#### Ожидаемый результат
Форма обратной связи занимает всю ширину экрана

#### Фактический результат
Форма обратной связи не занимает всю ширину экрана

#### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![image](https://user-images.githubusercontent.com/60919700/75029894-cd207100-54c4-11ea-92ab-85e311d508a9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
