### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by truff4ut** [netology-code/git-homeworks-neuro-issues#512]
### **Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust 

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/43514910/75057229-9a3ca400-54e9-11ea-882f-3f0531b755f4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
