### ISSUE TITLE
Форма обратной связи слишком сжата 

### ISSUE THREAD

**Issue by truff4ut** [netology-code/git-homeworks-neuro-issues#513]
### **Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Открыть форму, где просят ввести контакты 

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/43514910/75057587-7168de80-54ea-11ea-9a64-768ad9f110c2.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
