### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by kholodsergey14** [netology-code/git-homeworks-neuro-issues#515]
Форма обратной связи слишком сжата.
Шаги по просмотведению

NeuroStartUp в мобильном браузере Chrome
Открыть форму, где просят представить контакты
Ожидаемый результат

Не наезжает на изображение

Фактический результат

Текст наезжает на изображение (см. Скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншоты

68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
