### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by nastine** [netology-code/git-homeworks-neuro-issues#516]
# **Описание проблемы**

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/60929088/75090833-0fef5100-5578-11ea-8ec5-426ec21a95d7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
