### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by nastine** [netology-code/git-homeworks-neuro-issues#517]
# **Описание проблемы**

**Страница обратной связи. Текстовый блок "Оставайтесь на связи" слишком сжат.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Перейти на страницу обратной связи

**Ожидаемый результат**

Форма обратной связи по ширине окна.

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60929088/75090894-9c017880-5578-11ea-98ba-30de8e167563.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
