### ISSUE TITLE
Текст наезжает на изображение в мобильном браузере

### ISSUE THREAD

**Issue by Olesya1215** [netology-code/git-homeworks-neuro-issues#521]
# Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

## Шаги воспроизведения

1. Открыть главную страницу сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями...".

## Ожидаемый результат

Изображение расположено под текстом.

## Фактический результат

Текст наезжает на изображение (см. скриншот).

## Программное окружение

* Устройство: iPhone 8+ (iOS 12.1).
* Браузер: Chrome (70.0.3538.75).

## Скриншот

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/44785961/75146325-e8c98880-570b-11ea-85ef-5bc063d2f5c7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
