### ISSUE TITLE
Текст формы обратной связи отображается слишком узко в мобильном браузере

### ISSUE THREAD

**Issue by Olesya1215** [netology-code/git-homeworks-neuro-issues#522]
# Описание проблемы

**Форма обратной связи. Текстовый блок «Оставайтесь на связи» отображается узкой полосой текста**

## Шаги воспроизведения

1. Открыть форму обратной связи в мобильном браузере Chrome.

## Ожидаемый результат

Текст отображается по ширине страницы.

## Фактический результат

Границы текста слишком широкие, в строке помещается не больше двух слов (см. скриншот).

## Программное окружение

* Устройство: iPhone 8+ (iOS 12.1).
* Браузер: Chrome (70.0.3538.75).

## Скриншот

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/44785961/75146869-0e0ac680-570d-11ea-8c61-038df64491ea.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
