### ISSUE TITLE
Текст наезжает на картинку;

### ISSUE THREAD

**Issue by VyacheslavMiroshnik** [netology-code/git-homeworks-neuro-issues#524]
# Шаги по воспроизведению
 * Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
# Ожидаемый результат
* Текст не наезжает на изображение

# Фактический результат
* Текст наезжает на изображение (см. скриншот)

# Программное окружение
1. Устройство: iPhone 8+ (iOS 12.1)
1. Браузер: Chrome (70.0.3538.75)

# Скриншоты
![image](https://user-images.githubusercontent.com/36334648/75168966-cac64d00-5738-11ea-9cb4-0e9fddfd4d74.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
