### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by VyacheslavMiroshnik** [netology-code/git-homeworks-neuro-issues#525]
# Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Открыть форму обратной связи
# Ожидаемый результат
 * Форма не сжимается на мобильных устройствах 

# Фактический результат
* Форма сжимается 

# Программное окружение
1. Устройство: Asus Zenfone (Android 10)
1. Браузер: Chrome (70.0.3538.75)

# Скриншоты
![image](https://user-images.githubusercontent.com/36334648/75169700-0f9eb380-573a-11ea-9231-89221f055619.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
