### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by chillhead** [netology-code/git-homeworks-neuro-issues#526]
@solarrust 
# Описание проблемы
## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)

## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
## 
![screen text](https://user-images.githubusercontent.com/61307909/75245656-2fd47e00-57df-11ea-8fb1-7faba766c8f1.png)
Скриншоты

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
