### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by chillhead** [netology-code/git-homeworks-neuro-issues#527]
# Описание проблемы
# Страница обратной связи. Форма "Оставайтесь на связи" слишком сжата.
## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Перейти на страницу обратной связи
## Ожидаемый результат
Форма обратной связи по ширине окна.

## Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

## Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61307909/75246091-197af200-57e0-11ea-93dc-9bb169b4df31.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
