### ISSUE TITLE
Страница обратной связи. Форма "Оставайтесь на связи" слишком сжата.

### ISSUE THREAD

**Issue by pldenn** [netology-code/git-homeworks-neuro-issues#529]
@solarrust
**Страница обратной связи. Форма "Оставайтесь на связи" слишком сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Перейти на страницу обратной связи

**Ожидаемый результат**
Форма обратной связи по ширине окна.

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60191432/75254616-ab3f2b00-57f1-11ea-876e-05f7b3d612c0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
