### ISSUE TITLE
Адаптировать лендинг для мобильного браузера

### ISSUE THREAD

**Issue by OksiG** [netology-code/git-homeworks-neuro-issues#53]
@solarrust

# Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/49413119/56231076-415cdd80-6086-11e9-9647-f6554648e7b0.png)
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/49413119/56231077-415cdd80-6086-11e9-83f4-5fc237bd470b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
