### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by LosLena** [netology-code/git-homeworks-neuro-issues#530]
**Шаги по воспроизведению**

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

 **Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/61324790/75260963-362d1f00-580c-11ea-82bf-979b2c3ceab8.png)
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61324790/75261033-5230c080-580c-11ea-8d7e-66999285023d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
