### ISSUE TITLE
Мобильное отображение  - текст наезжает на картинку

### ISSUE THREAD

**Issue by Tester-qa4** [netology-code/git-homeworks-neuro-issues#531]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/60934762/75276176-1c490780-581f-11ea-95e5-260c62aadaa5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
