### ISSUE TITLE
Мобильное отображение - Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Tester-qa4** [netology-code/git-homeworks-neuro-issues#532]
**Форма обратной связи. После открытия, форма "Оставайтесь на связи"  сжимается, появляются корявые переносы**

**Шаги по воспроизведению**

Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

**Ожидаемый результат**
Форма сохранила пропорции, текст переносится корректно, все элементы выровнены по вертикальной сетке в соответствии с размерами

**Фактический результат**
Форма сжалась, появились не корректные переносы 

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/60934762/75276506-b5781e00-581f-11ea-8399-4c71dc8d31e4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
