### ISSUE TITLE
В мобильном браузере присутствуют две проблемы

### ISSUE THREAD

**Issue by SurfDRED** [netology-code/git-homeworks-neuro-issues#533]
# Описание проблемы

#### Главная страница. 
1. Текст наезжает на картинку;
2. Форма обратной связи слишком сжата;

#### Шаги по воспроизведению:

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
3. Пролистать страницу до блока "Оставайтесь на связи".

#### Ожидаемый результат:

1. Текст не наезжает на изображение.
2. Форма обратной связи не сжата.

#### Фактический результат:

1. Текст наезжает на картинку (см. скриншот №1);
2. Форма обратной связи слишком сжата  (см. скриншот №2);

#### Программное окружение:

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты:

Скриншот №1
![1](https://user-images.githubusercontent.com/56864991/75278712-a9359600-580a-11ea-9879-753f1f3e54e8.png)

Скриншот №2
![2](https://user-images.githubusercontent.com/56864991/75278716-aa66c300-580a-11ea-9a61-3e5a41ee7a79.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
