### ISSUE TITLE
Текстовый блок "Воспользуйтесь ......" наезжает на изображение

### ISSUE THREAD

**Issue by TyranR** [netology-code/git-homeworks-neuro-issues#535]
Привет! @solarrust

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/14344072/75288541-9da79680-582d-11ea-8e57-40dde3c9610c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
