### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by TyranR** [netology-code/git-homeworks-neuro-issues#536]
Привет, @solarrust!

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь..."

#### Ожидаемый результат

Форма выровнена под экран телефона

#### Фактический результат

Форма сильно сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 12+ (iOS 16.1)
* Браузер: Chrome (80.0.3538.75)

#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/14344072/75288822-2de5db80-582e-11ea-8b2c-b1d727e662d6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
