### ISSUE TITLE
Проблемы в мобильном браузере

### ISSUE THREAD

**Issue by MaxKocheshkov** [netology-code/git-homeworks-neuro-issues#537]
День добрый @solarrust !
# Проблемы при мобильном отображении
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение
### Фактический результат
Текст наезжает на изображение (см. скриншот 1)
### Шаги по воспроизведению
1. Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
### Ожидаемый результат
Текст отформатирован по размерам формы 
### Фактический результат
Текст не отформатирован по размерам формы (см. скриншот 2)
## Программное окружение
* Устройство: Huawei P Smart 2019 (Android 9.1)
* Браузер: Chrome (70.0.3538.75)
## Скриншоты
1. 
![Главная страница](https://camo.githubusercontent.com/d90a6e5e9269c1926cc5e5ea6d624a3a06b53f9a/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)
2. 
![Форма обратной связи](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
