### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by KpblckaKsu** [netology-code/git-homeworks-neuro-issues#539]
@solarrust 
# Описание проблемы
### Шаги по воспроизведению

Открыть страницу с формой обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

### Ожидаемый результат
Форма обратной связи во всю ширину экрана

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

## Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61318946/75384769-8fba4a00-58ef-11ea-9eb8-8e6018773508.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
