### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by ukishere** [netology-code/git-homeworks-neuro-issues#543]
# Описание проблемы

### Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат

Текст не наезжает на изображение

### Фактический результат

Текст наезжает на изображение (см. скриншот)

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/61353722/75471322-23008780-59a3-11ea-8fd6-2debd88129a5.png)

### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
