### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ukishere** [netology-code/git-homeworks-neuro-issues#544]
# Описание проблемы

### Шаги по воспроизведению

Открыть страницу с формой обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

### Ожидаемый результат

Текст не переносится посторочно.

### Фактический результат

Текст не вмещается на страницу. (см. скриншот)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61353722/75472445-92c34200-59a4-11ea-84fa-7c6c8a1e96c8.png)

### Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
