### ISSUE TITLE
текст наезжает на изображение

### ISSUE THREAD

**Issue by Slimkin** [netology-code/git-homeworks-neuro-issues#549]
# **Описание проблемы**

## **Шаги по воспроизведению**
1. открыть главную страницу в мобильном браузере Chrome
1. пролистать до блока "Воспользуйтесь современными..."

## **Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

## **Скриншот**

![sshot](https://user-images.githubusercontent.com/61383251/75550287-a7561780-5a42-11ea-955b-c77f71f9be75.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
