### ISSUE TITLE
Проблема в мобильном браузере #2

### ISSUE THREAD

**Issue by MaxKocheshkov** [netology-code/git-homeworks-neuro-issues#552]
День добрый @solarrust !
# Проблемы при мобильном отображении
### Шаги по воспроизведению
1. Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
### Ожидаемый результат
Текст отформатирован по размерам формы
### Фактический результат
Текст не отформатирован по размерам формы (см. скриншот)
##  Программное окружение
* Устройство: Huawei P Smart 2019 (Android 9.1)
* Браузер: Chrome (70.0.3538.75)
## Скриншот
![Форма](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
