### ISSUE TITLE
Ошибки в мобильной версии

### ISSUE THREAD

**Issue by bmaukenov** [netology-code/git-homeworks-neuro-issues#553]
Здравствуйте, @solarrust !
Заметил ошибку в мобильной версии. Далее я опишу возникшую проблему для Вас.

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты

<img width="381" alt="Снимок экрана 2020-02-29 в 06 19 03" src="https://user-images.githubusercontent.com/29486861/75596789-466b2580-5abc-11ea-8725-39e3a0cf7f25.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
