### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by bmaukenov** [netology-code/git-homeworks-neuro-issues#555]
Добрый день, @solarrust !

Заметил у Вас небольшую проблему с формой обратной связи - она слишком сжатая. Далее я опишу проблему

**Главная страница. Форма обратной связи слишком сжата, из-за этого не удобно читать, при этом есть место, чтобы расширить форму обратной связи**

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу доформы обратной связи..."

**Ожидаемый результат**

Форма обратной связи достаточно широка (почти на всю ширину экрана, чтобы удобно было читать и заполнять ее

**Фактический результат**

Форма обраной связи слишком сжата (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты
<img width="386" alt="Снимок экрана 2020-02-29 в 19 38 17" src="https://user-images.githubusercontent.com/29486861/75608658-b82e8800-5b2b-11ea-987e-82737399672e.png">
**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
