### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by EvgeniyaLion** [netology-code/git-homeworks-neuro-issues#557]
@solarrust 

# Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

# Ожидаемый результат

Текст не наезжает на изображение

# Фактический результат

Текст наезжает на изображение (см. скриншот)

# Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![img1](https://user-images.githubusercontent.com/61581208/75613590-7825d000-5b40-11ea-9312-968ce8db49a4.png)

![img2](https://user-images.githubusercontent.com/61581208/75613593-7cea8400-5b40-11ea-9163-e1487f7a17e2.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
