### ISSUE TITLE
Текст "Воспользуйтесь современными возможностями..." наезжает на картинку на главной странице

### ISSUE THREAD

**Issue by Iziumskii** [netology-code/git-homeworks-neuro-issues#558]
@solarrust 
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/48409708/75614454-f0dd5a00-5b49-11ea-8568-74549acf0544.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
