### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by Iziumskii** [netology-code/git-homeworks-neuro-issues#559]
@solarrust 
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

#### Ожидаемый результат

Форма обратной связи адаптирована под экран

#### Фактический результат

Форма обратной связи сжата горизонтально

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/48409708/75614514-998bb980-5b4a-11ea-89e4-d23b1a332abc.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
