### ISSUE TITLE
Сливание текста с фоном

### ISSUE THREAD

**Issue by Svift87** [netology-code/git-homeworks-neuro-issues#56]
@solarrust

### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/41532402/56305773-11d3d100-616b-11e9-928d-521779566022.png)

**Comment by Svift87** [comment]
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/41532402/56305833-34fe8080-616b-11e9-8665-0535b9f6b784.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
