### ISSUE TITLE
Проблемы мобильной версии

### ISSUE THREAD

**Issue by Utuska** [netology-code/git-homeworks-neuro-issues#562]
Добрый день, @solarrust

### Описание проблемы

> Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/61506687/75625448-1b252b00-5bcf-11ea-9f60-706d28aee90f.png)
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61506687/75625468-6a6b5b80-5bcf-11ea-803b-1dcec0e22005.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
