### ISSUE TITLE
Проблема с мобильной версией №1

### ISSUE THREAD

**Issue by PetrNikiforov14041995** [netology-code/git-homeworks-neuro-issues#563]
Привет, @solarrust
## Описание проблемы ##
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение** 
### **Шаги по воспроизведению** ###
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## **Фактический результат** ##
Текст **наезжает** на изображение (см. скриншот)

## **Ожидаемый результат** ##
Текст **не**  **наезжает** на изображение

## **Программное окружение** ##
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
 ## **Скриншот** ##
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/61342446/75628133-fabd9680-5bf7-11ea-84ce-60fb5c86dfb5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
