### ISSUE TITLE
Проблема с мобильной версией №2

### ISSUE THREAD

**Issue by PetrNikiforov14041995** [netology-code/git-homeworks-neuro-issues#564]
Привет, @solarrust
## **Описание проблемы** ##
Форма обратной связи сжата относительно ширины приложения
## **Шаги по воспроизведению** ##
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать до формы обратной связи

## **Фактический результат** ##
Страница обратной связи сжата. Текст выглядит не эстетично!

## **Ожидаемый результат** ##
Форма обратной связи читабельна, и выглядит эстетично.

## **Программное окружение** ##
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

## **Скриншот** ##
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61342446/75628276-386eef00-5bf9-11ea-877a-9bb5e8a5f977.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
