### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by FedorPeplinChamp** [netology-code/git-homeworks-neuro-issues#565]
@solarrust, просьба ознакомиться с первой проблемой по проекту. Скриншот прикладываю ниже:
![problem](https://camo.githubusercontent.com/d90a6e5e9269c1926cc5e5ea6d624a3a06b53f9a/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)

## Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

## Получение проблемы
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Технические характеристики устройства, на которых была получена проблема
1. Устройство: iPhone 8+ (iOS 12.1)
1. Браузер: Chrome (70.0.3538.75)

## Ожидание к исправлению

Отсутствие одинакового местоположения у текста и у изображения.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
