### ISSUE TITLE
Чрезмерное сжатие формы обратной связи

### ISSUE THREAD

**Issue by FedorPeplinChamp** [netology-code/git-homeworks-neuro-issues#567]
@solarrust, просьба ознакомиться со второй проблемой по проекту. Скриншот прикладываю ниже:
![problem](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

## Описание проблемы
**Страница обратной связи. Текстовый блок обратной связи визуально чрезмерно узок**

## Получение проблемы
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Перейти на форму обратной связи

## Технические характеристики устройства, на которых была получена проблема
1. Устройство: iPhone 8+ (iOS 12.1)
1. Браузер: Chrome (70.0.3538.75)

## Ожидание к исправлению
Расширение формы обратной связи, удобно визуализированной для пользователя.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
