### ISSUE TITLE
Проблема с мобильной версией(В)

### ISSUE THREAD

**Issue by mind-controled** [netology-code/git-homeworks-neuro-issues#568]
# Описание проблемы
**Форма обратной связи сжата относительно ширины приложения**
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать до формы обратной связи
### Ожидаемый результат
Форма обратной связи читабельна, и выглядит эстетично
### Фактический результат
Страница обратной связи сжата. Текст выглядит не эстетично(см. скриншот)
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншот
![Скриншот](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
