### ISSUE TITLE
Главная страница. Текст наезжает на изображение.

### ISSUE THREAD

**Issue by nosegay** [netology-code/git-homeworks-neuro-issues#569]
Здравствуйте, @solarrust!

**При открытии главной страницы через мобильный браузер текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.**

#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![problem_1](https://user-images.githubusercontent.com/61475090/75632103-ef736680-5c09-11ea-8464-13ab323a920b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
