### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by nosegay** [netology-code/git-homeworks-neuro-issues#570]
Здравствуйте, @solarrust!

**При открытии главной страницы через мобильный браузер форма обратной связи отображается некорректно.**

#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Форма обратной связи"

#### Ожидаемый результат
Ширина формы соответствует ширине экрана мобильного устройства

#### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![problem_2](https://user-images.githubusercontent.com/61475090/75632233-2d24bf00-5c0b-11ea-81cb-78051143029e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
