### ISSUE TITLE
"Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Veselov-im** [netology-code/git-homeworks-neuro-issues#571]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат

Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![Скриншот](https://user-images.githubusercontent.com/61295307/75634260-20a96200-5c1d-11ea-9eb8-78d51a973bcb.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
