### ISSUE TITLE
Mobile. Feedback form page. Form width is too compressed.

### ISSUE THREAD

**Issue by Grachya** [netology-code/git-homeworks-neuro-issues#573]
@solarrust 

#### Шаги по воспроизведению

1. Открыть страницу формы обратной связи NeuroStartUp в мобильном браузере Chrome
2. Форма слишком сжата

#### Ожидаемый результат

Форма в мобильной версии нормальной ширины

#### Фактический результат

Форма слишком сжата (см скриншот)

#### Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![screenshot](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
