### ISSUE TITLE
Проблема при работе с сайтом на мобильном браузере

### ISSUE THREAD

**Issue by Radniforg** [netology-code/git-homeworks-neuro-issues#574]
# Описание проблемы
**Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение на главной странице**
## Воспроизведение проблемы
1.   Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текстовый блок и изображение не наезжают друг на друга
### Фактический результат
Текстовый блок и изображение наезжают друг на друга
![Neuro1](https://user-images.githubusercontent.com/61646795/75711172-f6b47600-5cd6-11ea-8dc4-7de896f0e2d9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
