### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Radniforg** [netology-code/git-homeworks-neuro-issues#575]
# Описание проблемы
**Форма обратной связи слишком сжата, присутствует некорректный перенос слов**
## Воспроизведение проблемы
1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи
### Ожидаемый результат
Форма обратной связи удобна для заполнения и чтения
### Фактический результат
Форма обратной связи слишком сжата
![Neuro2](https://user-images.githubusercontent.com/61646795/75711441-78a49f00-5cd7-11ea-8962-f4a3ed67b7a4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
