### ISSUE TITLE
Проблема №1

### ISSUE THREAD

**Issue by kirillburnashov** [netology-code/git-homeworks-neuro-issues#576]
Привет, @solarrust 
# Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению:**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)

## Программное окружение
* Устройство: Iphone 8 Plus
* Браузер: Google (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/60434865/75743156-9d822c00-5d42-11ea-8c15-2edbe700f63a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
