### ISSUE TITLE
Проблема №2

### ISSUE THREAD

**Issue by kirillburnashov** [netology-code/git-homeworks-neuro-issues#577]
Привет, @solarrust 

# Описание проблемы
Форма обратной связи слишком сжата при просмотре с мобильного браузера. Некорректный перенос слов.

**Воспроизведение проблемы:**
1. Открыть в мобильном браузере Google главную страницу NeuroStartUp
1. Перейти в раздел "Обратная связь"

## Ожидаемый результат
Правильный перенос слов. Нормальное отображение формы обратной связи.

## Фактический результат
Перенос слов некорректен. Форма сжата. (см. скриншотх)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60434865/75744514-0a97c080-5d47-11ea-86b8-23d4a9fcdb14.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
