### ISSUE TITLE
Homework-3.2-Problem #1 - Text block on the main page passes over the picture

### ISSUE THREAD

**Issue by Sake-Seguro** [netology-code/git-homeworks-neuro-issues#578]
Mainly addressed to @solarrust - we have some technical issue to settle;  ref. NeuroStartUp project

# Problem description

**Main page. Text block "Exploring contemporary opportunities..." passes over the image**

## Actions to reproduce the bug

   1. Open the main page of our project in mobile browsers Google Chrome or Opera;
   1. Scroll down to the block "Exploring contemporary opportunities..." 

## Expected result

The text should NOT pass over the image.

## Factual result 

The text passes over the image. Please, look at the screenshot attached to this issue.

## Programming environment

* Technical means: Motorola MOTO Z2 Play (Android version - 7.4), Samsung S10 (Android version - 9.0)
* Browsers: Google Chrome (version 70.30) and Opera Mobile (66.00)

## Screenshots of the problem

![Problem-3 2-1](https://user-images.githubusercontent.com/61118704/75791062-06b17180-5d3a-11ea-802e-221307762194.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
