### ISSUE TITLE
Homework-3.2-Problem #2 - Feedback form is TOO condensed

### ISSUE THREAD

**Issue by Sake-Seguro** [netology-code/git-homeworks-neuro-issues#579]
Mainly addressed to @solarrust - we have some technical issue to settle;  ref. NeuroStartUp project

# Problem description

**Feedback form  appears TOO condensed and jammed while browsing with mobile means**

## Actions to reproduce the bug

   1. Open the main page of our project in mobile browsers Google Chrome or Opera;
   1. Scroll down to the feedback form 

## Expected result

The feedback form should be normally and proportionally distributed through the space designated.

## Factual result 

The feedback form is evidently TOO condensed and jammed.  Please, look at the screenshot attached to this note.

## Programming environment

* Technical means: Motorola MOTO Z2 Play (Android version - 7.4), Samsung S10 (Android version - 9.0)
* Browsers: Google Chrome (version 70.30) and Opera Mobile (66.00)

## Screenshots of the problem

![Problem-3 2-2](https://user-images.githubusercontent.com/61118704/75792887-93f5c580-5d3c-11ea-9bfd-df791ee25656.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
