### ISSUE TITLE
Некорректное отображение лендинга в мобильной версии

### ISSUE THREAD

**Issue by baskrasen** [netology-code/git-homeworks-neuro-issues#580]
#### Шаги воспроизведения: 
1. Открыть сайт NeuroStartUp на главной странице
2. Пролистать страницу до блока "Воспользуйтесь современными..."

**Ожидаемый результат**: Текст отображается корректно, на наезжает на картинку, 
**Фактический результат**:  Текст отображается некорректно, наезжает на картинку 
**Окружение:** 
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75) 
* Скриншот проблемы: 
![скрин](https://i.ibb.co/vDBS0rt/1iy2hs18.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
