### ISSUE TITLE
Некорректное отображение лендинга в мобильной версии 2

### ISSUE THREAD

**Issue by baskrasen** [netology-code/git-homeworks-neuro-issues#581]
#### Шаги воспроизведения: 
1. Открыть сайт NeuroStartUp на главной странице
2. Пролистать страницу до формы: "Оставайтесь на связи"

**Ожидаемый результат**: Текст отображается корректно, слова не переносятся частично
**Фактический результат**:  Текст отображается некорректно, слова переносятся некорректно
**Окружение:** 
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75) 
* Скриншот проблемы: 
![скрин](https://i.ibb.co/BgRvvcR/c0dcJs0i.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
