### ISSUE TITLE
проблема с формой обратной связи

### ISSUE THREAD

**Issue by Slimkin** [netology-code/git-homeworks-neuro-issues#582]
# **Описание проблемы**

## *Шаги по воспроизведению*
1. Открыть главную страницу в мобильном браузере
1. Пролистать до формы обратной связи

## **Ожидаемый результат**
Форма обратной связи адаптированна под экран

## **Фактический результат**
Форма сжата

## **Программное окружение**
* Устройство:  iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

## **Скриншот**
![ss2](https://user-images.githubusercontent.com/61383251/75897315-6e0a1700-5e49-11ea-84b2-b6aa766d1902.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
