### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by massarach** [netology-code/git-homeworks-neuro-issues#583]
@solarrust 

# Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/52579590/75977729-15408a00-5eee-11ea-8fc4-2ce73499503b.png)
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/52579590/75977731-15d92080-5eee-11ea-84a0-53aa45997485.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
