### ISSUE TITLE
Текстовый блок наезжает на изображение. Форма обратной связи сжата при просмотре на моб. устройстве.

### ISSUE THREAD

**Issue by GorbiAndrey** [netology-code/git-homeworks-neuro-issues#584]
# Описание проблемы
1. Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.
2. Главная страница. Форма обратной связи слишком сжата при воспроизведение на мобильном устройстве.

## Шаги по воспроизведению
 1.1 Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
 1.2 Пролистать страницу до блока "Воспользуйтесь современными возможностями...".

2.1 Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2.2 Пролистать страницу до блока "Форма обратной связи"

## Ожидаемый результат
1. Текст не наезжает на изображение.
2. Форма обратной связи располагается по всей ширине экрана мобильного устройства.

## Фактический результат
1. Текстовый блок наезжает на изображение (см. скриншот №1).
2. Форма обратной связи слишком сжата (см. скриншот №2).

## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (Версия 80.0.3987.122 (Официальная сборка))

## Скриншоты
* Скриншот №1
![текстовый блок](https://camo.githubusercontent.com/d90a6e5e9269c1926cc5e5ea6d624a3a06b53f9a/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)

* Скриншот №2
![Форма](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

[@solarrust](https://github.com/solarrust)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
