### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь..." наезжает на изображение 

### ISSUE THREAD

**Issue by Cazuist** [netology-code/git-homeworks-neuro-issues#587]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Уменьшить ширину экрана до 800px
3. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
**Устройство**: iPhone 8+ (iOS 12.1)
**Браузер**: Chrome (70.0.3538.75)

### Скриншот
<img src="https://user-images.githubusercontent.com/34417342/76195414-4aecb800-61f9-11ea-9d51-c1629cf0c0a6.png" width="450">

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
