### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Cazuist** [netology-code/git-homeworks-neuro-issues#588]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Выбрать в DevTools мобильное устройство / уменьшить размер браузера до 575px
3. Прокрутить страницу до блока формы обратной связи

### Ожидаемый результат
Форма отображается на весь экран

### Фактический результат
Форма занимает не весь экран по ширине (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75) 

### Скриншот
<img src="https://user-images.githubusercontent.com/34417342/76197519-56da7900-61fd-11ea-971d-e3e2c36c57cf.png" width = "400">

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
