### ISSUE TITLE
Баг отображения лендинга в мобильной версии 

### ISSUE THREAD

**Issue by Anastasia909** [netology-code/git-homeworks-neuro-issues#589]
### Описание проблемы:
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат

Текст не наезжает на изображение

### Фактический результат

Текст наезжает на изображение (см. скриншот)

### Программное окружение

 

- Устройство: iPhone 8+ (iOS 12.1)
-  Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/61245516/76225320-640f5c00-622d-11ea-82dd-7461f948cdf3.jpeg)
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61245516/76225332-6671b600-622d-11ea-8e87-42a29bb52558.jpeg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
