### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by susanna-susanna** [netology-code/git-homeworks-neuro-issues#59]
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Comment by solarrust** [comment]
Не полное описание проблемы. Не выполнены пункты задания: 
* Не забудьте приложить скриншот
* отметьте в тексте Issue пользователя @solarrust

Пожалуйста, ознакомьтесь с примером описания по ссылке: https://github.com/netology-code/git-homeworks/blob/master/remote/issue-example.md
