### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by DementevSlava** [netology-code/git-homeworks-neuro-issues#590]
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f3268635436](https://user-images.githubusercontent.com/61272107/76290426-42a98100-62bc-11ea-907b-2ddfe24785cb.png)
![68747470733a2f2f692e696d6775722e636f6d2f4863537059](https://user-images.githubusercontent.com/61272107/76290430-43daae00-62bc-11ea-928b-9cdb5f27f934.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
