### ISSUE TITLE
Отображение в мобильном браузере

### ISSUE THREAD

**Issue by AnnaNest** [netology-code/git-homeworks-neuro-issues#591]
@solarrust обрати внимание при открытие страницы в мобильтном браузере:
1. Текст "Воспользуйтесь современными возможностями..." наезжает на изображение;
2. Форма обратной связи слишком сжата.
Изображения прилагаю.
![erorr](https://user-images.githubusercontent.com/60582759/76305884-305f2100-6283-11ea-8007-b952cbd00778.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
