### ISSUE TITLE
Отображение лендинга в мобильном браузере.

### ISSUE THREAD

**Issue by OlegGunko** [netology-code/git-homeworks-neuro-issues#592]
@solarrust возникли проблемы с отображением лендинга в мобильном браузере. 

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

- Текст не наезжает на изображение
- Форма обратной связи не сжата

**Фактический результат**

- Текст наезжает на изображение (см. скриншот №1)
- Форма обратной связи сжата (см. скриншот №2)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот №1**
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/61455637/76317180-6b457100-62e4-11ea-86b1-3477347b96aa.png)

**Скриншот №2**
![12345](https://user-images.githubusercontent.com/61455637/76317631-2bcb5480-62e5-11ea-9660-29aa16a6c5e8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
