### ISSUE TITLE
Некорректное отображение лендинга в мобильной версии

### ISSUE THREAD

**Issue by VarsPtz** [netology-code/git-homeworks-neuro-issues#593]
@solarrust возникли проблемы с отображением лендинга в мобильном браузере.
# Описание проблемы
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
#### Ожидаемый результат
* Текст не наезжает на изображение
#### Фактический результат
* Текст наезжает на изображение (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
#### Скриншот

![error-1](https://user-images.githubusercontent.com/40685042/76389268-f02f9980-637b-11ea-9516-21de62043d1a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
