### ISSUE TITLE
Форма обратной связи на лендинге слишком сжата

### ISSUE THREAD

**Issue by VarsPtz** [netology-code/git-homeworks-neuro-issues#594]
@solarrust возникли проблемы с отображением лендинга в мобильном браузере.
# Описание проблемы
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму обратной связи
#### Ожидаемый результат
* Форма обратной связи не сжата
#### Фактический результат
* Форма обратной связи сжата  (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншот
![error-2](https://user-images.githubusercontent.com/40685042/76390860-3c300d80-637f-11ea-9493-41164d2f47ae.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
