### ISSUE TITLE
При просмотре лендинга в мобильном браузере присутствуют две проблемы

### ISSUE THREAD

**Issue by Butt5** [netology-code/git-homeworks-neuro-issues#595]
@solarrust

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
1. Текст не наезжает на изображение
2. Форма обратной связи не сжата

Фактический результат
1. Текст наезжает на изображение (см. скриншот)
2. Форма обратной связи слишком сжата (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![logo1](https://user-images.githubusercontent.com/61370419/76396670-ad28f280-638a-11ea-973e-db6fc7ee2e20.png)
![logo2](https://user-images.githubusercontent.com/61370419/76396674-b023e300-638a-11ea-90c7-b343a7fcad8d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
