### ISSUE TITLE
При просмотре лендинга в мобильном браузере присутствуют 2 проблемы.

### ISSUE THREAD

**Issue by Valeria-Kuzina** [netology-code/git-homeworks-neuro-issues#597]
@solarrust

# Описание проблем

##### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

##### Ожидаемый результат
Текст не наезжает на изображение

##### Фактический результат
Текст наезжает на изображение (см. скриншот)

##### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

##### Скриншот
![1](https://user-images.githubusercontent.com/58110393/76469102-a2a84080-63fe-11ea-876d-aa976b5aed03.png "Наезжает текст")

##### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу вниз до формы обратной связи 

##### Ожидаемый результат
Пропорциональное уменьшение текста и полей записи

##### Фактический результат
Тект не уменьшается, а сжимается (см. скриншот)

##### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

##### Скриншот
![2](https://user-images.githubusercontent.com/58110393/76469176-c53a5980-63fe-11ea-93db-ae46c45e4f63.png "Слишком сжато")

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
