### ISSUE TITLE
При просмотре лендинга в мобильном браузере возникают 2 проблемы.

### ISSUE THREAD

**Issue by GurinaElena** [netology-code/git-homeworks-neuro-issues#598]
@solarrust 

### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот
![image](https://user-images.githubusercontent.com/59961907/76499242-6a7d1e00-644f-11ea-88fe-c4e01bf3f7ca.png)

### Форма обратной связи слишком сжата.

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу вниз до формы обратной связи

**Ожидаемый результат**

Пропорциональное уменьшение текста и полей записи

**Фактический результат**

Текст не уменьшается, а сжимается (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот
![image](https://user-images.githubusercontent.com/59961907/76499422-bb8d1200-644f-11ea-8482-0826cb9c49cc.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
