### ISSUE TITLE
Более детальное описание #59

### ISSUE THREAD

**Issue by susanna-susanna** [netology-code/git-homeworks-neuro-issues#60]
@solarrust
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/44302089/56419134-eef80880-62a1-11e9-9223-d16128a10710.png)
![скрин issue](https://user-images.githubusercontent.com/44302089/56419159-fb7c6100-62a1-11e9-83b5-1f988e298164.png)

**Comment by solarrust** [comment]
Ок, можете не обращать внимание на комментарий к вашему предыдущему issue.
