### ISSUE TITLE
Не корректное отображение

### ISSUE THREAD

**Issue by mrAnderSun** [netology-code/git-homeworks-neuro-issues#603]
### Описание
 При отображении страницы в мобильном браузере происходит наезд текстового блока на изображение.

#### Воспроизведение

Для повторения заявленной картины требуется открыть главную страницу и прокрутить страницу вниз.

#### Программное Обеспечение

Android 8.1.0 Oreo
Google Chrome 80.0.3987.132

#### Ожидаемый результат 
Корректное отображение (без наездов блоков информации)

#### Фактический результат
Показан на скриншоте

####Скриншот
![Screen2](https://user-images.githubusercontent.com/61462960/76634907-6690ef00-6568-11ea-89dd-161c90ea8d6c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
