### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Lucien-L** [netology-code/git-homeworks-neuro-issues#604]
Шаги по воспроизведению

  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат

Текст не наезжает на изображение
Фактический результат

Текст наезжает на изображение (см. скриншот)
Программное окружение

1.    Устройство: iPhone 8+ (iOS 12.1)
2.    Браузер: Chrome (70.0.3538.75)
![11](https://user-images.githubusercontent.com/61544429/76634038-87a51000-6567-11ea-8fc3-80152cb2b153.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
