### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Tatiana0325** [netology-code/git-homeworks-neuro-issues#606]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
2. Просмотреть форму обратной связи

### Ожидаемый результат
Форма обратной связи более читаем на экране

### Фактический результат
Форма обратной связи слишком сжат (см. скриншот)

### Программное окружение

- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/58114214/76685015-7e787980-6621-11ea-955f-69c0853281e6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
