### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by OlegBirykov** [netology-code/git-homeworks-neuro-issues#608]
# Описание проблемы
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
#### Ожидаемый результат
Текст не наезжает на изображение
#### Фактический результат
Текст наезжает на изображение (см. скриншот)
#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
#### Скриншоты
![image](https://user-images.githubusercontent.com/59805563/76686318-935a0a80-662b-11ea-9675-f396b945ccd1.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
