### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by OlegBirykov** [netology-code/git-homeworks-neuro-issues#609]
# Описание проблемы
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"
#### Ожидаемый результат
1. Текст выглядит адекватно
1. Длина полей ввода достаточна для ввода контактных данных 
#### Фактический результат
1. Короткие надписи расположены в несколько строк, первое слово заголовка не умещается в строку (см. скриншот)
1. Длина полей ввода слишком мала, чтобы видеть вводимые данные без прокрутки
#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
#### Скриншоты
![image](https://user-images.githubusercontent.com/59805563/76686594-aa99f780-662d-11ea-8587-116b658379a0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
