### ISSUE TITLE
Некорректное отображение формы обратной связи на сайте

### ISSUE THREAD

**Issue by nicklada** [netology-code/git-homeworks-neuro-issues#610]
# Некорректное отображение формы обратной связи на сайте

Waiting for your response, @solarrust 

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

+ Устройство: iPhone 8+ (iOS 12.1)
+ Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![Снимок экрана 2020-03-14 в 19 43 21](https://user-images.githubusercontent.com/61970788/76686742-bb973880-662e-11ea-97a4-01dd6f27db3e.png)
![Снимок экрана 2020-03-14 в 19 43 36](https://user-images.githubusercontent.com/61970788/76686749-c356dd00-662e-11ea-983b-e11cd0f5de91.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
