### ISSUE TITLE
Некорректное отображение текста на главной странице при просмотре через мобильный браузер

### ISSUE THREAD

**Issue by Ann-Zol** [netology-code/git-homeworks-neuro-issues#611]
**Сценарий воспроизведения:**

1.  Открыть страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Листать до блока "Воспользуйтесь современными возможностями..."

**Фактический результат:** Текст отображается не корректно - заезжает на картинку (см. скрин)

**Ожидаемый результат:** Сначала идет блок текста "Воспользуйтесь современными возможностями...", затем отображается картинка.

**Программное окружение:**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Дополнительные материалы (скрин):** 
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/61914568/76691155-09289b00-6659-11ea-9a52-71a2d0a98e95.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
