### ISSUE TITLE
Некорректная верстка формы обратной связи для мобильного браузера

### ISSUE THREAD

**Issue by Ann-Zol** [netology-code/git-homeworks-neuro-issues#612]
**Сценарий воспроизведения:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму Обратной связи

Фактический результат: Форма обратной связи имеет некорректную верстку - поля узкие, тест сжат (см. скрин)

Ожидаемый результат: Верстка формы обратной связи должна быть адаптирована к мобильному браузеру, занимать всё пространство экрана, иметь удобные поля для ввода и адаптивный размер шрифта текста

**Программное окружение:**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Доп. материалы (скрин):**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61914568/76691279-58230000-665a-11ea-96be-1d3b2a171fd4.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
