### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by yana-prokudina** [netology-code/git-homeworks-neuro-issues#614]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Информация, содержащаяся в блоке, корректно отображается в браузере мобильного устройства. Верстка адаптирована.

**Фактический результат**

Информация, содержащаяся в блоке, слишком сжата. Верстка не адаптирована.

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/58114235/76700797-35c9ca80-66cc-11ea-933e-0fcc97056215.png)

@solarrust please fix this issue

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
