### ISSUE TITLE
Главная страница не соответствует макету дизайна мобильной версии, нужно поправить текст.

### ISSUE THREAD

**Issue by Daria-chizh** [netology-code/git-homeworks-neuro-issues#616]
# Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
## Ожидаемый результат
Текст не должен наезжать на изображение
## Фактический результат
Текст наезжает на изображение (см. скриншот)
## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
## Скриншоты
![image](https://user-images.githubusercontent.com/59864294/76704435-99bfb380-670b-11ea-9446-714f75a36058.png)
@solarrust.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
