### ISSUE TITLE
Форма обратной связи не соответствует адаптированной верстке.

### ISSUE THREAD

**Issue by Daria-chizh** [netology-code/git-homeworks-neuro-issues#617]
# Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"
## Ожидаемый результат
Весь блок должен соответствовать макету адаптированной вёрстки. 
## Фактический результат
Нет адаптированной вёрстки. Заголовок и абзацы блока переносится на новую строчку,  поля для заполнения данных маленькие, неудобные для пользователя (см. скриншот)
## Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
## Скриншоты
![image](https://user-images.githubusercontent.com/59864294/76704832-40a54f00-670e-11ea-96e3-71a2794807cb.png)

@solarrust.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
