### ISSUE TITLE
Нечитаемый текст поверх изображения

### ISSUE THREAD

**Issue by gavr1993** [netology-code/git-homeworks-neuro-issues#618]
#### Для воспроизведения:
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
* Пролистать страницу до текстового блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат:
Текст не наезжает на изображение

#### Фактический результат:
Текст наезжает на изображение (см. скриншот)

#### Программное окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

#### Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/56173584/76706025-8dc8f700-66f5-11ea-9b13-64ae3a47d454.png)

@solarrust

**Comment by gavr1993** [comment]
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
