### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by MozhaevIL** [netology-code/git-homeworks-neuro-issues#619]
# Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![Issue1 screenshot](https://user-images.githubusercontent.com/59886564/76708074-2fa41000-6705-11ea-96db-40d68b0b952f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
