### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by MozhaevIL** [netology-code/git-homeworks-neuro-issues#620]
# Описание проблемы

**Форма обратной связи слишком сжата в ширину**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Информация в блоке читаема с мобильного устройства

**Фактический результат**
При отображении на мобильном устройстве блок заужен

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![issue2 screenshot](https://user-images.githubusercontent.com/59886564/76708351-261ba780-6707-11ea-9204-7000f00e96a6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
