### ISSUE TITLE
Проблемы с текстом и формой обратной связи.

### ISSUE THREAD

**Issue by NataliaOleinik** [netology-code/git-homeworks-neuro-issues#622]
## В мобильном браузере присутствуют две проблемы:

- Текст наезжает на картинку;

- Форма обратной связи слишком сжата.
## Шаги по воспроизведению

1.  Открыть главную страницу в мобильном браузере и посмотреть на картинку
2. Открыть форму обратной связи
## Ожидаемый результат
 - Текст не наезжает на картинку
- Форма обратной связи удобной ширины
## Фактический результат
- Текст наезжает на картинку
- Форма обратной связи слишком сжата
## Скриншоты
![form1](https://user-images.githubusercontent.com/60175451/76743904-f53e7f80-67a5-11ea-8d5d-122329206b9d.png)
![page1](https://user-images.githubusercontent.com/60175451/76743908-f66fac80-67a5-11ea-8de3-cb3f4f1440f7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
