### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by NikolasDro** [netology-code/git-homeworks-neuro-issues#63]
@solarrust 

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**
![image](https://user-images.githubusercontent.com/46326741/56434424-ffce6b80-62ed-11e9-885b-eaf102e66fe0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
