### ISSUE TITLE
Текстовый блок наезжает на изображение; Форма обратной связи чрезмерно сжата

### ISSUE THREAD

**Issue by Posbon** [netology-code/git-homeworks-neuro-issues#630]
### В мобильном браузере присутствуют две проблемы:

- Текст наезжает на картинку;

- Форма обратной связи слишком сжата.

### Шаги по воспроизведению
1. Открыть главную страницу NeuroStartUp в мобильном браузере и посмотреть на картинку
"Воспользуйтесь современными возможностями..."

2. Открыть форму обратной связи

### Ожидаемый результат

- Текстовый блок "Воспользуйтесь современными возможностями..."
   не наезжает на картинку

- Форма обратной связи читабельна, слова целиком умещаются по ширине.

### Фактический результат

- Текстовый блок наезжает на картинку

- Форма обратной связи не читабельна слишком сжата

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншоты:

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/62098203/76863295-55015d00-6870-11ea-801a-833671f56d68.png)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/62098203/76863237-41ee8d00-6870-11ea-85e7-037d1462e53f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
