### ISSUE TITLE
Текст наезжает на картинку; Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by elenaslavutina** [netology-code/git-homeworks-neuro-issues#632]

**Comment by elenaslavutina** [comment]
# Описание проблемы

#### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HJ1VbMj.png)
![](https://user-images.githubusercontent.com/62098203/76863237-41ee8d00-6870-11ea-85e7-037d1462e53f.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
