### ISSUE TITLE
Текст наезжает на картинку; Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AnnVasilyeva** [netology-code/git-homeworks-neuro-issues#634]
**Шаги** по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншоты
![img-1](https://user-images.githubusercontent.com/59840841/76883809-c13e8980-688d-11ea-9d19-67bf927cbe2f.png)
![img-2](https://user-images.githubusercontent.com/59840841/76883921-e7642980-688d-11ea-9654-080b06697418.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
