### ISSUE TITLE
Проблемы с текстом на превью и формой обратной свзязи

### ISSUE THREAD

**Issue by DiRover** [netology-code/git-homeworks-neuro-issues#635]
@solarrust

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)

## Программное окружение
   *  Устройство: iPhone 8+ (iOS 12.1)
   *  Браузер: Chrome (70.0.3538.75)

## Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/55257129/76891792-a1619280-689a-11ea-8dab-2efd029c013d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
