### ISSUE TITLE
Проблемы с формой обратной связи

### ISSUE THREAD

**Issue by DiRover** [netology-code/git-homeworks-neuro-issues#636]
@solarrust

**Форма обратной связи. Форма обратной связи через чур сжата**
## Шаги по воспроизведению
1. Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока формы обратной связи

## Ожидаемый результат
1. Элементы формы обратной связи пропорционально занимают свои места
1. Высота текста пропорционально уменьшена согласно размерам экрана

## Фактический результат
Форма поиска сильно сжата (см. скриншот)

## Программное окружение
   *  Устройство: iPhone 8+ (iOS 12.1)
   *  Браузер: Chrome (70.0.3538.75)

## Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/55257129/76891758-94dd3a00-689a-11ea-9f42-20a280fef880.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
