### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Algol613** [netology-code/git-homeworks-neuro-issues#638]
Главная страница. Форма обратной связи слишком сжата.
Шаги по воспроизведению

    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до блока "Обратная связь"

Ожидаемый результат

Разметка текста в нормальном состоянии
Фактический результат

Текст несоизмеримо сжат, шрифт слишком большой (см. скриншот)
Программное окружение

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61864414/76898970-c3addd00-68a7-11ea-95df-54985ed47c7c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
