### ISSUE TITLE
 Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by GurinaElena** [netology-code/git-homeworks-neuro-issues#639]
@solarrust

### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншот
![image](https://user-images.githubusercontent.com/59961907/76938931-8c234d00-6908-11ea-9fbf-226e6bb4cc69.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
