### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by NikolasDro** [netology-code/git-homeworks-neuro-issues#64]
@solarrust 

**Главная страница. Форма обратной связи сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

**Ожидаемый результат**

Форма на всю ширину экрана

**Фактический результат**

Форма сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![image](https://user-images.githubusercontent.com/46326741/56435086-9c920880-62f0-11e9-81ad-8b7f33a3d5d3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
