### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by GurinaElena** [netology-code/git-homeworks-neuro-issues#640]
### Форма обратной связи слишком сжата.

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу вниз до формы обратной связи

**Ожидаемый результат**
Пропорциональное уменьшение текста и полей записи

**Фактический результат**
Текст не уменьшается, а сжимается (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот

![image](https://user-images.githubusercontent.com/59961907/76939174-fb993c80-6908-11ea-8864-3e5d4f5d85be.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
