### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by yignor** [netology-code/git-homeworks-neuro-issues#641]
@solarrust 

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/58684900/76948864-bed54180-6918-11ea-90f1-d5979bd50db5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
