### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by yignor** [netology-code/git-homeworks-neuro-issues#642]
@solarrust

**Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Обратная связь"

**Ожидаемый результат**

Форма будет вмещаться в окно браузера

**Фактический результат**

Форма сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

![image](https://user-images.githubusercontent.com/58684900/76949836-3d7eae80-691a-11ea-8aeb-eaf99321a1bb.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
