### ISSUE TITLE
Не корректная форма (сжатие) обратной связи

### ISSUE THREAD

**Issue by mrAnderSun** [netology-code/git-homeworks-neuro-issues#643]
## Описание
Отображение формы обратной связи на странице представлено в зауженном виде.

### Воспроизведение
Для повторения заявленной картины требуется открыть главную страницу и прокрутить страницу вниз.

### Программное Обеспечение
Android 8.1.0 Oreo.
Browser (встроенный в оболочку) V7.13.110.

### Ожидаемый результат
Корректное отображение (без сжатия формы).

### Фактический результат
Показан на скриншоте.

### Скриншот
![Screen3](https://user-images.githubusercontent.com/61462960/76964543-b692fb80-6944-11ea-9bcc-a2a500606c9f.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
