### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by tarapiygin** [netology-code/git-homeworks-neuro-issues#644]
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)
#### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/50370669/76976107-8fd4c500-6944-11ea-886d-e145c459c85f.png)
![2](https://user-images.githubusercontent.com/50370669/76976175-abd86680-6944-11ea-9b6c-b06d447efbfb.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
