### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by ZhukovaAnna** [netology-code/git-homeworks-neuro-issues#645]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**
### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/62005377/77043416-8e4fdf00-69ce-11ea-837a-f954876b7f80.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
