### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by ZhukovaAnna** [netology-code/git-homeworks-neuro-issues#646]
**Описание проблемы**
Главная страница. Форма обратной связи слишком сжата.
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2. Пролистать страницу до формы обратной связи.

### Ожидаемый результат
Форма обратной связи выровнена по ширине и высоте в соответствии с стандартами организации.
### Фактический результат
Форма обратной связи слишком сжата.(см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/62005377/77045397-27342980-69d2-11ea-8730-e4af9f66502a.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
