### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by nib287** [netology-code/git-homeworks-neuro-issues#648]
@solarrust

**Раздел контакты, Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**

1. Открыть страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма обратной связи не должна быть шириной меньше 270px
https://github.com/netology-code/git-homeworks-neuro-issues/blob/857e3d95477bfbd9c93fb04804a64d0007c1c075/index.html#L52

**Фактический результат**

Форма обратной связи  по ширине меньше 270px (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
