### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by AnastasiaChe8** [netology-code/git-homeworks-neuro-issues#65]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями ..."**
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/46500606/56815589-6c93b980-684a-11e9-9ebd-b639411ac96e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
