### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Anna-Filipova** [netology-code/git-homeworks-neuro-issues#650]
**_Описание проблемы_**
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
**_Шаги по воспроизведению_**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
**_Ожидаемый результат_**
Текст не наезжает на изображение
**_Фактический результат_**
Текст наезжает на изображение (см. скриншот)
**_Программное окружение_**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**_Скриншоты_**
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/62184331/77182352-ab270800-6add-11ea-86d5-b0177e4d374f.png)
@solarrust

**Comment by Anna-Filipova** [comment]
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
