### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Anna-Filipova** [netology-code/git-homeworks-neuro-issues#651]
**_Описание проблемы_**
Главная страница. Форма обратной связи слишком сжата.
**_Шаги по воспроизведению_**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до формы обратной связи
**_Ожидаемый результат_**
Форма обратной связи выровнена по ширине и высоте в соответствии с стандартами организации.
Форма обратной связи не должна быть шириной меньше 270px
**_Фактический результат_**
Форма обратной связи слишком сжата.(см. скриншот)
Форма обратной связи по ширине меньше 270px
**_Программное окружение_**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**_Скриншоты_**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/62184331/77184145-6e104500-6ae0-11ea-94c9-1677248f8d8c.png)
@solarrust

**Comment by Anna-Filipova** [comment]
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
