### ISSUE TITLE
Текст наезжает на картинку и форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Evgeniy-27** [netology-code/git-homeworks-neuro-issues#652]
@solarrust 
# Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/59884475/77221629-d06b5300-6b7d-11ea-8cfd-77bb76c8af99.png)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/59884475/77221627-cf3a2600-6b7d-11ea-8b2c-55d19a693d93.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
