### ISSUE TITLE
Текст наезжает на изображение 

### ISSUE THREAD

**Issue by georgeaslikyan** [netology-code/git-homeworks-neuro-issues#657]
# Описание проблемы
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/54264943/77230991-dc750600-6bb9-11ea-8ce2-1f8ee5a96f32.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
