### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by georgeaslikyan** [netology-code/git-homeworks-neuro-issues#658]
# Форма обратной связи сжата
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
####Ожидаемый результат
Форма обратной связи соответствует макету

#### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/54264943/77231329-016a7880-6bbc-11ea-86b1-df7076cd8299.png)
 @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
