### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AnastasiaChe8** [netology-code/git-homeworks-neuro-issues#66]
**Главная страница. Форма обратной связи сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до формы обратной связи.

**Ожидаемый результат**

Форма обратной связи не сжата

**Фактический результат**

Форма обратной связи сжата

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/46500606/56815972-402c6d00-684b-11e9-9eaa-309343175954.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
