### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by MKSInc** [netology-code/git-homeworks-neuro-issues#660]
### Форма обратной связи слишком сжата

@solarrust

### Программное окружение
 - Устройство: iPhone 8+ (iOS 12.1)
 - Браузер: Chrome (70.0.3538.75)

### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/40667150/77234508-bcdcde00-6bb7-11ea-9bf5-d0006d3b80b8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
