### ISSUE TITLE
текст наезжает на картинку

### ISSUE THREAD

**Issue by Valeriia-b** [netology-code/git-homeworks-neuro-issues#661]
# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
*Устройство: iPhone 8+ (iOS 12.1)
*Браузер: Chrome (70.0.3538.75)

### Скриншоты
![скриншот](https://user-images.githubusercontent.com/62112311/77247170-8d71b400-6c3f-11ea-8f12-af57c3b7bb0d.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
