### ISSUE TITLE
форма обратной связи сжата

### ISSUE THREAD

**Issue by Valeriia-b** [netology-code/git-homeworks-neuro-issues#662]
# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

### Ожидаемый результат
Форма отражается корректно

### Фактический результат
Форма сильно сжата (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншоты
![скриншот 2](https://user-images.githubusercontent.com/62112311/77247276-7a131880-6c40-11ea-8717-525ac805e23a.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
