### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by voevodina** [netology-code/git-homeworks-neuro-issues#663]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Тестовое окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![issue_index](https://user-images.githubusercontent.com/21043485/77253036-eefa4880-6c68-11ea-8f47-537baf301c5e.png)

@solarrust просьба передать в работу для устранения бага.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
