### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by voevodina** [netology-code/git-homeworks-neuro-issues#664]
**Форма обратной связи "Оставайтесь на связи" слишком сжата на мобильном устройстве**

**Шаги по воспроизведению**
Перейти на страницу с формой "Оставайтесь на связи" веб-сайта NeuroStartUp в мобильном браузере Chrome

**Ожидаемый результат**
Содержимое страницы с формой размещено по ширине экрана мобильного устройства

**Фактический результат**
 Форма слишком сжата (см. скриншот)

**Тестовое окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![issue_form](https://user-images.githubusercontent.com/21043485/77253356-9fb51780-6c6a-11ea-914e-cb8594dc5173.png)

@solarrust просьба передать для устранения на фронтенд.

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
