### ISSUE TITLE
Текст наезжает на картинку в мобильной версии.

### ISSUE THREAD

**Issue by xeniaplotnikova** [netology-code/git-homeworks-neuro-issues#665]
**Описание проблемы**

Главная страница. 
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

    Устройство: Samsung Galaxy F40 + (Android 10)
    Браузер: Chrome (80.0.3987.149)

**Скриншот** 

![Текст наезжает на картинку](https://user-images.githubusercontent.com/60033152/77317296-fdee0300-6d1b-11ea-8e1c-a5bbbdeee35e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
