### ISSUE TITLE
Форма обратной связи слишком сжата 

### ISSUE THREAD

**Issue by EmelinaTanya** [netology-code/git-homeworks-neuro-issues#666]
### Форма обратной связи сжата  
**Описание** **проблемы**:

**Шаги** **по** **воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
**Ожидаемый** **результат**
Форма обратной связи соответствует макету
**Фактический** **результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное** **окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**Скриншоты:**
![image](https://user-images.githubusercontent.com/62333591/77317584-e8310b80-6d24-11ea-9545-d022ac1a8f34.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
