### ISSUE TITLE
Форма обратной связи слишком сжата в мобильной версии.

### ISSUE THREAD

**Issue by xeniaplotnikova** [netology-code/git-homeworks-neuro-issues#667]
**Описание проблемы**

Главная страница. 
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

   1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
   1.  Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

  Устройство: Samsung Galaxy F40 + (Android 10)
  Браузер: Chrome (80.0.3987.149)

![Форма связи слишком сжата](https://user-images.githubusercontent.com/60033152/77317777-e2cfc300-6d1c-11ea-8d78-36cadf784dcf.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
