### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by EmelinaTanya** [netology-code/git-homeworks-neuro-issues#668]
### Описание проблемы
**Главная** **страница.** **Текстовый** **блок** **"Воспользуйтесь** **современными** **возможностями..."** **наезжает** **на** **изображение**
**Шаги** **по** **воспроизведению**

1. Открыть главную страницу веб-сайта **NeuroStartUp** в мобильном браузере **Chrome.**
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями...".

**Ожидаемый** **результат**
Текст отображается правильно, все хорошо видно.

**Фактический** **результат**
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![image](https://user-images.githubusercontent.com/62333591/77319053-9473f180-6d27-11ea-8dc4-092f10cf4b90.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
