### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by alexmaxevt** [netology-code/git-homeworks-neuro-issues#669]
**Главная страница. Блок с текстом под заголовком: "Воспользуйтесь современными возможностями искусственного интеллекта, оставив конкурентов позади!"**

**Как воспроизводится:**

1. Открыть главную страницу в браузере Edge
2. Нажать F12 и уменьшать разрешение (или нажать на кнопку смены девайса - с компьютера на смартфон)

**Ожидаемы результат:**
Текст будет выше изображения

**Фактический результат:**
Текст наезжает на картинку

**Программное обеспечение:**
- браузер Edge (версия 80.0.361.69)

**Скриншот с проблемой:**
![Аннотация 2020-03-24 111131](https://user-images.githubusercontent.com/54303988/77402817-4e1ea100-6dc0-11ea-8f87-549e29ad33c9.png)

@solarrust, исправьте, пожалуйста

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
