### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by alexmaxevt** [netology-code/git-homeworks-neuro-issues#670]
**Главная страница. Блок с формой обратной связи.**

**Как воспроизводится:**

1. Открыть главную страницу сайты в Edge
2. Нажать F12 и прокрутить вниз до формы.
3. Изменить девайс (с компьютера на смартфон) или уменьшать разрешение.

**Ожидаемый результат:**
Слова в тексте заголовка не будут переноситься на следующую строку

**Фактический результат:**
Происходит перенос в слове "Оставайтесь"

**Программное обеспечение:**

- Браузер Edge (версия 80.0.361.69)

**Скриншот проблемы**
![Аннотация 2020-03-24 111132](https://user-images.githubusercontent.com/54303988/77404922-7a87ec80-6dc3-11ea-8410-2a2fb2092a2c.png)

@solarrust, исправьте, пожалуйста

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
