### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by svetlana-konradi** [netology-code/git-homeworks-neuro-issues#673]
**Шаги по вопроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

**Ожидаемый результат**

Красиво должно быть @solarrust

**Фактический результат**

Форма сжата

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/53185747/77476184-8ad7b000-6e33-11ea-9e4e-166d8141cdf5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
