### ISSUE TITLE
Поправить мобильную верстку.

### ISSUE THREAD

**Issue by kvrdv** [netology-code/git-homeworks-neuro-issues#674]
# Недочеты в мобильной верстке
#### 3. Форма обратной связи слишком сжата.
***
#### Шаги по воспроизведению
1. Скачать репозиторий на рабочий стол.
2. Открыть файл index.html в браузере.
3. С помощью веб-инспектора, перейти в режиме адаптивного отображения на мобильный вид.
#### Ожидаемый результат
Корректная верстка без наслоений и переносов.
#### Фактический результат
Текст "прыгает", наслаивается на изображение, не читабелен. Формой обратной связи пользоваться не возможно.
#### Программное окружение
* Windows 10 Pro, v1909, 18363.657
* Mozilla Firefox 74.0 (64 bit)
#### Скриншоты
![issue screenshot 1](https://camo.githubusercontent.com/d90a6e5e9269c1926cc5e5ea6d624a3a06b53f9a/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)
![issue screenshot 2](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
