### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by chimerochka** [netology-code/git-homeworks-neuro-issues#676]
## Форма обратной связи слишком сжата

@solarrust 

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

### Ожидаемый результат

Равномерное отображение формы обратной связи

### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение

  * Устройство: iPhone 8+ (iOS 12.1)
  * Браузер: Chrome (70.0.3538.75) 

### Скриншот

![](https://i.imgur.com/HcSpYkT.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
