### ISSUE TITLE
Сжата форма обратной связи

### ISSUE THREAD

**Issue by sinoname** [netology-code/git-homeworks-neuro-issues#678]
# Форма обратной связи сжата
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

### Ожидаемый результат
Форма обратной связи соответствует макету

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты

![issue2](https://user-images.githubusercontent.com/59896293/77537442-c8c1ec00-6ea6-11ea-86f5-9120f614f584.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
