### ISSUE TITLE
текст наезжает на картинку

### ISSUE THREAD

**Issue by Molo4nayaPenka** [netology-code/git-homeworks-neuro-issues#681]
# Описание проблемы
#### **Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
#### **Ожидаемый результат**
Текст не наезжает на изображение
#### **Фактический результат**
Текст наезжает на изображение (см. скриншот)

#### **Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

#### **Скриншоты**
![git_hw3 2_pic1](https://user-images.githubusercontent.com/59918762/77628857-ad63e900-6f59-11ea-932b-805efed44cee.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
