### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Molo4nayaPenka** [netology-code/git-homeworks-neuro-issues#682]
@solarrust
# Описание проблемы
#### **Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи..."

#### **Ожидаемый результат**
Форма обратной связи будет выглядеть пропорционально размеру страницы

#### **Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

#### **Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

#### **Скриншоты**
![git_hw3 2_pic2](https://user-images.githubusercontent.com/59918762/77629602-d769db00-6f5a-11ea-931f-bfd2a165efd8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
