### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Helga-yalos** [netology-code/git-homeworks-neuro-issues#683]
@solarrust
# Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)

## Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншот
![Screenshot_8](https://user-images.githubusercontent.com/59892092/77656348-c635c400-6f84-11ea-898f-77afac65ab58.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
