### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Helga-yalos** [netology-code/git-homeworks-neuro-issues#684]
@solarrust
# Описание проблемы
Форма обратной связи слишком сжата
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

### Ожидаемый результат
Форма обратной связи по ширине равна ширине вьюпорта.

### Фактический результат
Форма обратной связи слишком сжата

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншот
![Screenshot_9](https://user-images.githubusercontent.com/59892092/77657041-c6828f00-6f85-11ea-8809-7876c9aab86a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
