### ISSUE TITLE
На главной странице NeuroStartUp текст наезжает на картинку.

### ISSUE THREAD

**Issue by juliaCodeGirl** [netology-code/git-homeworks-neuro-issues#685]
# На главной странице NeuroStartUp текст наезжает на картинку.

Назначено на **@solarrust**

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение, чётко видно картинку, текст виден и легко читаем.

**Фактический результат**
Текст наезжает на изображение, сложно прочитать текст (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![для нет](https://user-images.githubusercontent.com/31111799/77684164-9dc0c080-6faa-11ea-8731-fbbcc9e0d885.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
