### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by juliaCodeGirl** [netology-code/git-homeworks-neuro-issues#686]
# На главной странице NeuroStartUp форма для обратной связи слишком сжата.

Назначено на **@solarrust**

**Страница обратной связи на NeuroStartUp. Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**

1. Открыть главную страницу NeuroStartUp, перейти к форме "Обратная связь" в мобильном браузере Chrome
2. Просмотреть страницу, её удобство.

**Ожидаемый результат**
Форма удобна, легко читаема, текст равномерно переносится, все элементы выровнены, кнопки нормально расположены и кликабельны.

**Фактический результат**
Текст некорректно переносится, отображение не удобное, экран слишко узкий, элементы не выровнены (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![для нет2](https://user-images.githubusercontent.com/31111799/77688048-78cf4c00-6fb0-11ea-97e1-3fbaedf3ac3f.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
