### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by mprodan8** [netology-code/git-homeworks-neuro-issues#687]
@solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 13.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![Снимок экрана 2020-03-27 в 16 13 14](https://user-images.githubusercontent.com/62217328/77759560-f3967680-7045-11ea-965b-11e98a8f43f0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
