### ISSUE TITLE
Форма обратной связи "Оставайтесь на связи" слишком сжата

### ISSUE THREAD

**Issue by mprodan8** [netology-code/git-homeworks-neuro-issues#688]
@solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Форма по ширине растягивается на 80% экрана, текст "Оставайтесь на связи" не переносится или переносится по словам

**Фактический результат**

Форма по ширине занимает всего 50% экрана, текст "Оставайтесь на связи" переносится на середине слова

**Программное окружение**

Устройство: iPhone 8+ (iOS 13.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67 2](https://user-images.githubusercontent.com/62217328/77759881-8800d900-7046-11ea-83c2-5df9cc053e6e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
