### ISSUE TITLE
Проблема. Текст наезжает на картинку.

### ISSUE THREAD

**Issue by Antis85** [netology-code/git-homeworks-neuro-issues#689]
# Проблема. Текст наезжает на картинку.

@solarrust

## Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

## Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

## Ожидаемый результат
Текст не наезжает на изображение

## Фактический результат
Текст наезжает на изображение (см. скриншот)

## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

## Скриншоты
![image](https://user-images.githubusercontent.com/55399269/77820992-8d6a2c00-70f7-11ea-9808-24971ea5d37b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
