### ISSUE TITLE
Проблемы с версткой на главной странице (моб. версия)

### ISSUE THREAD

**Issue by damirkasen92** [netology-code/git-homeworks-neuro-issues#69]
# Описание проблем

1. На главной странице, блок содержащий текст "Воспользуйтесь современными возможностями..." наезжает на изображение (см. скриншот №1)
1. Форма обратной связи не адаптирована под ширину мобильных устройств, и в итоге слишком сжата (см. скриншот №2)

### Ошибки обнаружены посредством

- Устройство: Xiaomi Redmi Note 6 (Android 8.1.0)
- Браузер: Chrome (74.0.3729.136)

### Ожидаемый результат

1. Блок содержащий текст "Воспользуйтесь современными возможностями..." не должен наезжать на изображение 
1. Форма обратной связи должна быть адаптирована под мобильные устройства, и не должна быть слишком сжатой

@solarrust 

### Скриншоты 
**Скриншот №1**

![image](https://user-images.githubusercontent.com/50132660/57192385-a737d900-6f51-11e9-8af9-2303f964ff91.png)

**Скриншот №2**

![image](https://user-images.githubusercontent.com/50132660/57192392-b9b21280-6f51-11e9-9cf6-167024e12038.png)

**Comment by solarrust** [comment]
Нужно было создать два отдельных issue.
