### ISSUE TITLE
Проблема. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Antis85** [netology-code/git-homeworks-neuro-issues#690]
# Проблема. Форма обратной связи слишком сжата.

@solarrust

## Описание проблемы
Главная страница. Форма обратной связи "Оставайтесь на связи" слишком сжата.

## Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока с формой "Оставайтесь на связи"

## Ожидаемый результат
Содержимое страницы с формой размещено по ширине экрана мобильного устройства

## Фактический результат
Форма слишком сжата (см. скриншот)

## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

## Скриншоты
![image](https://user-images.githubusercontent.com/55399269/77821106-a58e7b00-70f8-11ea-8683-6509c2bfdf53.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
