### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Sklyr** [netology-code/git-homeworks-neuro-issues#691]
Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат

- Текст не наезжает на изображение

Фактический результат

- Текст наезжает на изображение (см. скриншот)

Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

@solarrust
![Пример](https://user-images.githubusercontent.com/60308598/77822211-5cf8b100-713c-11ea-82b5-d4640b6a9e69.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
