### ISSUE TITLE
Проблема. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Sklyr** [netology-code/git-homeworks-neuro-issues#692]
Описание проблемы

- Главная страница. Форма обратной связи "Оставайтесь на связи" слишком сжата.

Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока с формой "Оставайтесь на связи"

Ожидаемый результат

- Содержимое страницы с формой размещено по ширине экрана мобильного устройства

Фактический результат

- Форма слишком сжата (см. скриншот)

Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

@solarrust
![Пример 2](https://user-images.githubusercontent.com/60308598/77822280-08a20100-713d-11ea-9763-0f921695f5af.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
