### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by Odium-Mundi** [netology-code/git-homeworks-neuro-issues#696]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть страницу обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

#### Ожидаемый результат

Форма обратной связи имеет подходящий масштаб

#### Фактический результат

Форма слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![image](https://user-images.githubusercontent.com/61995344/77834535-7f97c380-7156-11ea-8bd8-e5d8f2109b8b.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
