### ISSUE TITLE
Текст лендинга в мобильном браузере наезжает на картинку

### ISSUE THREAD

**Issue by TatyanaGV** [netology-code/git-homeworks-neuro-issues#699]
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

@solarrust

#### Шаги по воспроизведению:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome;
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями...".

#### Ожидаемый результат:
Текст не наезжает на изображение

#### Фактический результат:
Текст наезжает на изображение (см. скриншот)

#### Программное окружение:
* Устройство: Samsung (Android 10)
* Браузер: Chrome (Версия 80.0.3987.132)

#### Скриншоты
![scrin lending](https://user-images.githubusercontent.com/52708640/77058584-b3e8e280-69e6-11ea-9245-aec8dc9360c7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
