### ISSUE TITLE
Текст наезжает на картинку via mobile browsing

### ISSUE THREAD

**Issue by Sheerazspb** [netology-code/git-homeworks-neuro-issues#7]
# Описание проблемы:

@ikrieg обратите внимание

<b> Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение
### Фактический результат
Текст наезжает на изображение (см. скриншот)
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/44028763/52609265-ba289900-2e8d-11e9-983a-8ccb707dbf66.png)

**Comment by solarrust** [comment]
Great! I'll fix it someday =)
