### ISSUE TITLE
Главная страницы. Текст-слоган наезжает на картинку.

### ISSUE THREAD

**Issue by Pager-290583** [netology-code/git-homeworks-neuro-issues#70]
На главной странице есть текст-слоган: "Воспользуйтесь современными возможностями...". Данный текст наезжает на картинку.

**Шаги для воспроизведения:**
1. Открыть главную страницу сайта
2. В режиме разработчика (Chrome) переключиться на мобильную версию сайта
3. Пролистать до блока с картинкой и текстом "Воспользуйтесь современными возможностями..."

**Фактический результат**: Текст "Воспользуйтесь современными возможностями..." наезжает на картинку.

**Ожидаемый результат**: Текст не должен наезжать на картинку

**Окружение**: 
* Mobile: iOS / Android
* Browser: Chrome Version 74.0.3729.108 (Official Build) (64-bit)

**Скриншот**

![image](https://user-images.githubusercontent.com/36411247/57194218-5edae400-6f6e-11e9-93ac-0800e3ce96bd.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
