### ISSUE TITLE
Форма обратной связи в мобильном браузере сжата

### ISSUE THREAD

**Issue by TatyanaGV** [netology-code/git-homeworks-neuro-issues#700]
### Форма обратной связи "оставайтесь на связи" не растянута пропорционально разрешению экрана (сжата по центру).

@solarrust

#### Шаги по воспроизведению:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome;
2. Пролистать страницу до блока "Оставайтесь на связи...".

#### Ожидаемый результат:
Форма обратной связи растянута пропорционально разрешению экрана

#### Фактический результат:
Форма обратной связи "оставайтесь на связи" не растянута пропорционально разрешению экрана (сжата по центру).

#### Программное окружение:
* Устройство: Samsung s10e (Android 10)
* Браузер: Chrome (Версия 80.0.3987.132)

#### Скриншоты
![scrin form feedback](https://user-images.githubusercontent.com/52708640/77063295-83a54200-69ee-11ea-8fa0-972431993adc.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
