### ISSUE TITLE
Текст подзаголовка наезжает на изображение

### ISSUE THREAD

**Issue by eugenekrabbs** [netology-code/git-homeworks-neuro-issues#701]
# Описание
На главной странице текст заголовка и подзаголовка не выровнены. Текст наезжает на изображение.
 
## Поиск ошибки 

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение
### Фактический результат
Текст наезжает на изображение

**Устройство:** Honor 8x (Android 10)
**Браузер:** Chrome (80.0.3987.149)

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/53967094/77900409-a9500800-7286-11ea-84ed-c18f8935856f.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
