### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by eugenekrabbs** [netology-code/git-homeworks-neuro-issues#702]
# Описание
Форма слишком узкая относительно ширины экрана.

## Поиск ошибки
На главной странице нажать кнопку "Связаться с нами"

### Ожидаемый результат
Форма обратной связи шире, так что текст занимает не более 3 строк
### Фактический результат
Форма слишком узкая, текст занимает более 3 строк, есть переносы внутри слов

**Устройство:** Honor 8x (Android 10)
**Браузер:** Chrome (80.0.3987.149)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/53967094/77901249-f54f7c80-7287-11ea-833f-34c0b14ab4d4.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
