### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by kristulkin** [netology-code/git-homeworks-neuro-issues#703]
>**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

> **Шаги по воспроизведению**
> 
> 1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
> 2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
> 
> **Ожидаемый результат**
> Текст не наезжает на изображение
> 
> **Фактический результат**
> Текст наезжает на изображение (см. скриншот)
> 
> **Программное окружение**
> 
> * Устройство: iPhone 8+ (iOS 12.1)
> * Браузер: Chrome (70.0.3538.75)
> 
> **Скриншоты**
> ![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/55235538/77928596-47f15e80-72b1-11ea-8d9d-1c06a6da7c57.png)

>**Форма обратной связи слишком сжата**

> **Шаги по воспроизведению**
> 
> *Открыть форму обратной связи
> 
> **Ожидаемый результат**
> Форма соответствует ширине окна
> 
> **Фактический результат**
> Форма обратной связи имеет слишком большие отступы (см. скриншот)
> 
> **Программное окружение**
> 
> * Устройство: iPhone 8+ (iOS 12.1)
> * Браузер: Chrome (70.0.3538.75)
> 
> **Скриншоты**
> 
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/55235538/77929749-b551bf00-72b2-11ea-83b2-6d6a53dfe37d.png)

**Comment by kristulkin** [comment]
>**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

> **Шаги по воспроизведению**
> 
> 1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
> 2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
> 
> **Ожидаемый результат**
> Текст не наезжает на изображение
> 
> **Фактический результат**
> Текст наезжает на изображение (см. скриншот)
> 
> **Программное окружение**
> 
> * Устройство: iPhone 8+ (iOS 12.1)
> * Браузер: Chrome (70.0.3538.75)
> 
> **Скриншоты**
> ![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/55235538/77928596-47f15e80-72b1-11ea-8d9d-1c06a6da7c57.png)


>**Форма обратной связи слишком сжата**

> **Шаги по воспроизведению**
> 
> *Открыть форму обратной связи
> 
> **Ожидаемый результат**
> Форма соответствует ширине окна
> 
> **Фактический результат**
> Форма обратной связи имеет слишком большие отступы (см. скриншот)
> 
> **Программное окружение**
> 
> * Устройство: iPhone 8+ (iOS 12.1)
> * Браузер: Chrome (70.0.3538.75)
> 
> **Скриншоты**
> 
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/55235538/77929749-b551bf00-72b2-11ea-83b2-6d6a53dfe37d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
