### ISSUE TITLE
Форма обратной связи сдавлена

### ISSUE THREAD

**Issue by abkirilenko** [netology-code/git-homeworks-neuro-issues#705]
@solarrust

# В чем проблема:
### Где:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока обратной связи

### Нужно:
Форма обратной связи растянулась на весь экран с внешними отступами в 2px

### Сейчас:
Внешние отступы 25% экрана

### Заметил на:
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот:
![Скриншот где все совсем плохо](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
