### ISSUE TITLE
Текст наезжает на блок изображения

### ISSUE THREAD

**Issue by skitalz** [netology-code/git-homeworks-neuro-issues#706]
### Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/58692849/78027845-b80dec00-7366-11ea-9571-f2e896ae2732.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
