### ISSUE TITLE
Index. Форма обратной связи - проблема с отображением

### ISSUE THREAD

**Issue by venom4ek** [netology-code/git-homeworks-neuro-issues#708]
Проблема с отображением формы обратной связи. @solarrust
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Форма обратной связи"
Ожидаемый результат
Форма обратной связи на ширину экрана с отступами от 1 до 2%

Фактический результат
Форма обратной связи сжата, занимает не более 50% от общей ширины

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![картинка](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
