### ISSUE TITLE
Исправить: текстовый блок "Воспользуйтесь ..." наезжает на изображение

### ISSUE THREAD

**Issue by BerezovTimur** [netology-code/git-homeworks-neuro-issues#709]
@solarrust

### Последовательность шагов
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Пролистать страницу до бл
![скрин](https://user-images.githubusercontent.com/62335721/78118243-67060280-740f-11ea-8a0a-19ab6dd1a6a6.png)
ока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение, текст легко читается

### Фактический результат
Изображение перекрывает текст (см. скриншот)

Программное окружение
Устройство: Xiaomi Redmi S2 (Android 9PQ1)
Браузер: Chrome (80.0.3987.149)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
