### ISSUE TITLE
Мобильная версия. Форма обратной связи сильно сжата.

### ISSUE THREAD

**Issue by Pager-290583** [netology-code/git-homeworks-neuro-issues#71]
**Форма обратной связи на сайте сильно сжата при отображении в мобильной версии.**

 **Шаги для воспроизведения:**
1. Открыть мобильную версию сайта
2. Пролистать до формы обратной связи

**Фактический результат:** Форма сильно сжата в отображении мобильной версии сайта

**Ожидаемый результат:** Форма обратной связи должна соответствовать макету дизайнера.

**Окружение**
* Mobile: iOS/Android
* Browser: Chrome Version 74.0.3729.108 (Official Build) (64-bit)
 
**Скриншот**

![image](https://user-images.githubusercontent.com/36411247/57194323-b88fde00-6f6f-11e9-8d14-c6594a7f8687.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
