### ISSUE TITLE
Исправить наезд текстового блока на изображение 

### ISSUE THREAD

**Issue by AlinaKaracheva** [netology-code/git-homeworks-neuro-issues#710]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями"
 наезжает на изображение.**

**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**

Текст не наезжает на изображение.

**Фактический результат:**

Текст наезжает на изображение (см. скриншот).

**Программное окружение:**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты:**

![Screenshot](https://user-images.githubusercontent.com/61938449/78277870-dbc76280-751d-11ea-9f2a-712c2dadc17b.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
