### ISSUE TITLE
Расширить форму обратной связи 

### ISSUE THREAD

**Issue by AlinaKaracheva** [netology-code/git-homeworks-neuro-issues#711]
**Главная страница. Форма обратной связи слишком сжата.**

**Шаги по воспроизведению:**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до окошка формы обратной связи.

**Ожидаемый результат:**

Форма обратной связи отображается корректно.

**Фактический результат:**

Форма обратной связи слишком сжата (см. скриншот).

**Программное окружение:**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот:**

![Screenshot1](https://user-images.githubusercontent.com/61938449/78281342-2f887a80-7523-11ea-95f8-fe2d55a3798a.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
