### ISSUE TITLE
Расширить форму обратной связи в мобильном браузере.

### ISSUE THREAD

**Issue by Palich63** [netology-code/git-homeworks-neuro-issues#712]
**Форма обратной связи "Оставаться на связе" не отображается пропорционально разрешению экрана, вытянута по центру.**
______________________________________________________________________________________________

_**Вниманию:**_ @solarrust

**Шаги по воспроизведению:**
   

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи...".

**Ожидаемый результат:**

- Форма обратной связи отображается пропорционально разрешению экран.

**Фактический результат:**

- Форма обратной связи сжата и вытянута по центру

**Программное окружение:**

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

**Скриншот**
![изображение](https://user-images.githubusercontent.com/62203001/78299003-32439980-753c-11ea-84b0-7fd0c22600d5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
