### ISSUE TITLE
Исправить наезд текстового блока "Воспользуйтесь современными возможностями..." на картинку 

### ISSUE THREAD

**Issue by Palich63** [netology-code/git-homeworks-neuro-issues#713]
**Текстовой блок "Воспользуйтесь современными возможностями..." на главной странице наезжает на изображение.**
______________________________________________________________________________________________

_**Вниманию:**_ @solarrust

**Шаги по воспроизведению:**
   

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. На главной странице текстовой блок "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**

- Текстовой блок не наезжает на картинку

**Фактический результат:**

- Текстовой блок наезжает на картинку

**Программное окружение:**

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

**Скриншот**
![изображение](https://user-images.githubusercontent.com/62203001/78300326-f8749200-753f-11ea-9f2d-22a3b8ac13c5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
