### ISSUE TITLE
Текст наезжает на картинку 

### ISSUE THREAD

**Issue by Suyunbaev** [netology-code/git-homeworks-neuro-issues#714]
@solarrust
Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![ишью](https://user-images.githubusercontent.com/59930712/78355379-a45cc280-75be-11ea-9db6-2b0e473a98f6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
