### ISSUE TITLE
Форма обратной связи не корректно отображается 

### ISSUE THREAD

**Issue by Suyunbaev** [netology-code/git-homeworks-neuro-issues#715]
Форма обратной связи не корректно отображается 

@solarrust

Шаги по воспроизведению:
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Перейти к блоку обратной связи.
Планируемый результат:
Форма обратной связи отображается корректно.

Фактический результат:
![ишью 2](https://user-images.githubusercontent.com/59930712/78355607-05849600-75bf-11ea-8335-d8884484307a.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
