### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Romio-wow** [netology-code/git-homeworks-neuro-issues#719]
### Описание проблемы ### 

**Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Перейти на форму обратной связи

**Ожидаемый результат**

Форма обратной связи растянута по экрану

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/60536678/78453265-33d6a400-7699-11ea-8e64-73478ff31849.png)

**Пользователь
@solarrust**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
