### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Pavel-Laukhin** [netology-code/git-homeworks-neuro-issues#720]
Уважаемая @solarrust !

Я заметил, что **текстовый блок наезжает на картинку.**

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в десктопном браузере Opera
1. Долистать страницу до фразы "Воспользуйтесь современными..."

#### Ожидаемый результат
Текст не наезжает на картинку

#### Фактический результат
Текст наезжает на картинку с изображением монитора

### Программное окружение
**Компьютер:** MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
**Версия OS:** macOS Catalina 10.15.3 64-bit (19D76)
**Браузер:** Opera (Версия: 67.0.3575.115)

## Скриншот
![image](https://user-images.githubusercontent.com/62621310/78456557-14e20d00-76ad-11ea-9ab3-6edb15528af2.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
