### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by likhovidIlya** [netology-code/git-homeworks-neuro-issues#721]
# Описание проблемы
### Главная страница. Форма обратной связи слишком сжата.

@solarrust 

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до блока "Обратная связь..."

**Ожидаемый результат**
Форма обратной связи расширена

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![forma obratki](https://user-images.githubusercontent.com/62901662/78456547-05fb5a80-76ad-11ea-8e74-65c7769d713b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
