### ISSUE TITLE
Форма обратной связи слишком сжата (узкая)

### ISSUE THREAD

**Issue by Pavel-Laukhin** [netology-code/git-homeworks-neuro-issues#723]
Уважаемая @solarrust !

Я заметил, что **форма обратной связи слишком сжата**.

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в десктопном браузере Opera на Mac
1. Долистать страницу до формы обратной связи

### Ожидаемый результат
Форма обратной связи имеет нормальные размеры

### Фактический результат
Форма настолько узкая, что даже слова не влезают целиком

### Программное окружение
**Компьютер:** MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
**Версия OS:** macOS Catalina 10.15.3 64-bit (19D76)
**Браузер:** Opera (Версия: 67.0.3575.115)

## Скриншот
![image](https://user-images.githubusercontent.com/62621310/78456672-a6ea1580-76ad-11ea-91ea-082d00f1a8e7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
