### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by IrinaSklyar** [netology-code/git-homeworks-neuro-issues#724]
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/62458956/78458877-64303980-76bd-11ea-9276-ff46705839c8.png)

Пользователь @solarrust

**Comment by IrinaSklyar** [comment]
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/62458956/78458860-377c2200-76bd-11ea-8610-70e913a615fd.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
