### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by IrinaSklyar** [netology-code/git-homeworks-neuro-issues#725]
Пользователь @solarrust 

Шаги по воспроизведению:
Открыть главную страницу веб-сайта NeuroStartUp в десктопном браузере Opera на Mac
Долистать страницу до формы обратной связи
Ожидаемый результат
Форма обратной связи имеет нормальные размеры

Фактический результат
Форма обратной связи слишком сжата (см. скриншот)
![78456672-a6ea1580-76ad-11ea-91ea-082d00f1a8e7](https://user-images.githubusercontent.com/62458956/78458932-e587cc00-76bd-11ea-8ad7-b236f95a264e.png)

Программное окружение
Компьютер: MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
Версия OS: macOS Catalina 10.15.3 64-bit (19D76)
Браузер: Opera (Версия: 67.0.3575.115)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
