### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by fjfoxru** [netology-code/git-homeworks-neuro-issues#729]
# Описание проблемы

**Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
Форма нормальных размеров

**Фактический результат**
Форма слишком узкая (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61179622/78470893-8f566f80-7735-11ea-9d3f-bb6c084f9820.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
