### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by martiboo** [netology-code/git-homeworks-neuro-issues#73]
# Описание проблемы

**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Нажать на кнопку обратной связи

**Ожидаемый результат**

Форма обратной связи не сжата

**Фактический результат**

Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/50113725/57327556-eca60300-7117-11e9-8786-bd4af4bf9a52.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
