### ISSUE TITLE
Текстовый блок наезжает на картинку

### ISSUE THREAD

**Issue by ViktorUdovin** [netology-code/git-homeworks-neuro-issues#730]
# Описание проблемы

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

#### Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

#### Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/62377731/78499129-f1c46580-775f-11ea-919f-3e9636f75ad1.png)

Пользователь
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
