### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ViktorUdovin** [netology-code/git-homeworks-neuro-issues#731]
## Описание проблемы

Форма обратной связи слишком сжата

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Перейти на форму обратной связи

#### Ожидаемый результат
Форма обратной связи растянута по экрану

#### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

Устройство: iPhone 8+ (iOS 12.1)

Браузер: Chrome (70.0.3538.75)
#### Скриншот

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/62377731/78499457-e4a87600-7761-11ea-98a0-50b718490a3d.png)

#### Пользователь
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
