### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by opodryadov** [netology-code/git-homeworks-neuro-issues#733]
@solarrust, возникла следующая проблема: 

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу вниз до формы обратной связи

#### Ожидаемый результат

Форма обратной связи нормальных размеров

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншот

![](https://i.imgur.com/HcSpYkT.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
