### ISSUE TITLE
Текст наезжает на картинку.

### ISSUE THREAD

**Issue by ekababiy** [netology-code/git-homeworks-neuro-issues#740]
@solarrust 
**Описание проблемы**
На главной странице текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**
1.Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2.Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/62432555/78596768-0171a600-7855-11ea-8701-2463808e4b13.png)
****

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
