### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by ekababiy** [netology-code/git-homeworks-neuro-issues#741]
@solarrust
**Описание проблемы:** 
Форма обратной связи слишком сжата

**Шаги по воспроизведению**
1. Открыть главную страницу с формой веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Перейти к блоку обратной связи.

**Ожидаемый результат**
Форма отображается корректно.

**Фактический результат**
Форма слишком сжата (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/62432555/78597304-f23f2800-7855-11ea-99af-f5482c31215c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
