### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Evgeny-crypt** [netology-code/git-homeworks-neuro-issues#747]
# Описание проблемы
@solarrust 

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![neuro](https://user-images.githubusercontent.com/63101273/78779446-54c42f80-79e0-11ea-932f-4182ed21dc46.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
