### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Evgeny-crypt** [netology-code/git-homeworks-neuro-issues#749]
# Описание проблемы
@solarrust 
#### Главная страница. 
**Форма обратной связи слишком сжата**

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

форма обратной связи не сжата

#### Фактический результат

форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![neuro2](https://user-images.githubusercontent.com/63101273/78779620-95bc4400-79e0-11ea-8366-72305bbf1993.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
