### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by malinindev** [netology-code/git-homeworks-neuro-issues#75]
# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншот: 
![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/44972568/57586394-f35cbd80-74fd-11e9-9db7-558dcc9e9490.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
