### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AlexP-1** [netology-code/git-homeworks-neuro-issues#751]
@solarrust 

# **ОПИСАНИЕ ПРОБЛЕМЫ**

### *Шаги по воспроизведению*

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Обратная связь"

### *Ожидаемый результат*

Форма обратной связи не сжата

### *Фактический результат*

Форма обратной связи слишком сжата (см. скриншот)
Программное окружение

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63120928/78795484-83390f00-79ce-11ea-9e56-d0b8e317d25c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
