### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Vadim2107** [netology-code/git-homeworks-neuro-issues#752]
# Описание проблемы
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![image](https://user-images.githubusercontent.com/58651870/78816226-1a579400-79da-11ea-92e6-4c5ccb5b91a5.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
