### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Vadim2107** [netology-code/git-homeworks-neuro-issues#753]
# Описание проблемы
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи..."3. 

### Ожидаемый результат
Ширина формы обратной связи 80 % от ширины экрана.

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![image](https://user-images.githubusercontent.com/58651870/78817124-5e976400-79db-11ea-965e-12e6c761371e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
