### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by alexander-drach** [netology-code/git-homeworks-neuro-issues#755]
**Страница с формой обратной связи. Форма сильно сжата.**

**Шаги по воспроизведению**

1. Открыть страницу с формой веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
наверно контент и поля формы растягиваются 100% ширины экрана

**Фактический результат**
по факту контент и поля сильно сжаты (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![скрин формы](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

для пользователя @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
