### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by SafaryanAlexandr** [netology-code/git-homeworks-neuro-issues#758]
### Фактический результат
Текст наезжает на изображение (см. скриншот)

*Программное окружение*
*Устройство: iPhone 8+ (iOS 12.1)*
*Браузер: Chrome (70.0.3538.75)*

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/51951459/78944296-39335480-7ac6-11ea-88e1-dfa0108e7ca0.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
