### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by SafaryanAlexandr** [netology-code/git-homeworks-neuro-issues#759]
*форма обратной связи сжата при просмотре на мобильном устройстве*

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/51951459/78944883-a1cf0100-7ac7-11ea-9cab-68e04574e39b.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
