### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by malinindev** [netology-code/git-homeworks-neuro-issues#76]
# Описание проблемы
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока с формой обратной связи

### Ожидаемый результат
Форма имеет корректную ширину

### Фактический результат
Форма слишком сжата (см скриншот)

### Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншот: 
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/44972568/57586461-f2785b80-74fe-11e9-8f8b-3cc6b2cf609e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
