### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by alexbaldr** [netology-code/git-homeworks-neuro-issues#768]
### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншоты
![image](https://user-images.githubusercontent.com/62666905/79010787-55d59800-7b6b-11ea-9630-fa4b9533aac6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
