### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by alexbaldr** [netology-code/git-homeworks-neuro-issues#769]
### Шаги по воспроизведению:
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Перейти к блоку обратной связи.
### Ожидаемый результат:
Форма обратной связи отображается корректно.

### Фактический результат:
![image](https://user-images.githubusercontent.com/62666905/79011149-19566c00-7b6c-11ea-9fb2-8ec944464bae.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
