### ISSUE TITLE
Описание проблемы

### ISSUE THREAD

**Issue by stepankrylov** [netology-code/git-homeworks-neuro-issues#77]
Здравствуйте, @solarrust 

При просмотре лендинга в мобильном браузере были обнаружены следующие проблемы:

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/50091565/57606714-e2a25b00-7582-11e9-8cb0-792c0211798d.png)

**Главная страница. Блок "Форма обратной связи" слишком сжата"**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Форма обратной связи"

**Ожидаемый результат**

Форма имеет нормальную ширину

**Фактический результат**

Форма слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/50091565/57606768-0f567280-7583-11e9-8e88-346468e05b32.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
