### ISSUE TITLE
Слишком узкая форма "Оставайтесь на связи"

### ISSUE THREAD

**Issue by pava-14** [netology-code/git-homeworks-neuro-issues#770]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма обратной связи занимает всю ширину видимой области страницы

#### Фактический результат

Форма обратной связи расположена по центру и занимает только часть видимой области страницы.  (см. скриншот)

#### Программное окружение

* Устройство: Honor 10 (Android 9.0)
* Браузер: Chrome (80.0.3987.162)

#### Скриншоты

![](https://i.imgur.com/1p3fOj8.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
