### ISSUE TITLE
Текстовый блок наезжает на картинку

### ISSUE THREAD

**Issue by pava-14** [netology-code/git-homeworks-neuro-issues#771]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: Honor 10 (Android 9.0)
* Браузер: Chrome (80.0.3987.162)

#### Скриншоты

![](https://i.imgur.com/hQRi8x6.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
