### ISSUE TITLE
Узкая форма "Оставайтесь на связи"

### ISSUE THREAD

**Issue by danilkarpukhin** [netology-code/git-homeworks-neuro-issues#773]
**Описание проблемы**
**Главная страница. Слишком узкая форма "Оставайтесь на связи".**
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма обратной связи занимает всю ширину видимой области страницы

**Фактический результат**
Форма обратной связи расположена по центру и занимает только часть видимой области страницы. (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![](https://i.imgur.com/HcSpYkT.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
