### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by KirillovProj** [netology-code/git-homeworks-neuro-issues#777]
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

#### Ожидаемый результат

Форма, растянутая по ширине экрана

#### Фактический результат

Слишком сжатая форма (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63199449/79040223-bb6b6800-7bef-11ea-8ec4-8a4d2d051be2.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
