### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by sgvsv** [netology-code/git-homeworks-neuro-issues#779]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Форма обратной связи отображается на всю ширину страницы

#### Фактический результат

Форма оратной связи сжата по горизонтали в мобильном браузере (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HcSpYkT.png)

@solarrust требуется внимание

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
