### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by TONY-COR72Z** [netology-code/git-homeworks-neuro-issues#78]
# Описание проблемы

### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)
 
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты
![1](https://user-images.githubusercontent.com/22939507/57631566-64f14600-75a8-11e9-9e89-5489d70f2d6e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
