### ISSUE TITLE
Форма обратной связи слишком вытянута

### ISSUE THREAD

**Issue by 547sereja** [netology-code/git-homeworks-neuro-issues#780]
# Описание проблемы
### Форма обратной связи слишком вытянута, на одной строчке всего 2-3 слова.
* Шаги по воспроизведению
     * Открыть форму обратной связи NeuroStartUp в мобильном браузере Chrome

* Ожидаемый результат от @solarrust
     * Текст по всей ширине экрана

* Фактический результат
     * Текст наезжает слишком узкий  
[см. скриншот](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

* Программное окружение:
    * Устройство: iPhone 8+ (iOS 12.1)
    * Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
