### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by 547sereja** [netology-code/git-homeworks-neuro-issues#781]
# Описание проблемы
### Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
* Шаги по воспроизведению
     * Открыть главную страницу и пролистать до формы обратной связи NeuroStartUp в мобильном браузере Chrome

* Ожидаемый результат от @solarrust
     * Текст не наезжает на картинку

* Фактический результат
     * Текст наезжает на картинку 
[см. скриншот](https://camo.githubusercontent.com/d90a6e5e9269c1926cc5e5ea6d624a3a06b53f9a/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)

* Программное окружение:
    * Устройство: iPhone 8+ (iOS 12.1)
    * Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
