### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Flayka** [netology-code/git-homeworks-neuro-issues#786]
**Главная страница.  Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока обратной связи "Оставайтесь на связи"

**Ожидаемый результат**

Блок обратной связи удобочитаемый, с заданной шириной 385 пикселей

**Фактический результат**

Блок обратной связи сжат до 195 пикселей (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63101226/79055233-1636ab00-7c54-11ea-8020-59787ff45682.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
