### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by TONY-COR72Z** [netology-code/git-homeworks-neuro-issues#79]
# Описание проблемы

### Шаги по воспроизведению
1. Открыть форму обратной связи

### Ожидаемый результат
Форма обратной связи не сжата

### Предполагаемые шаги по исправлению
1. Уменьшить внешние отступы слева и справа
1. Уменьшить шрифт

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)
 
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты
![2](https://user-images.githubusercontent.com/22939507/57631959-290ab080-75a9-11e9-92ea-e5124d5e5f87.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
