### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by MarinaMuratova** [netology-code/git-homeworks-neuro-issues#790]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот** 
![Снимок экрана 2020-04-12 в 20 27 43](https://user-images.githubusercontent.com/60069259/79075536-230ed980-7cfc-11ea-86b7-7421bde4303a.png)
@solarrust, исправь!

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
