### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by MarinaMuratova** [netology-code/git-homeworks-neuro-issues#791]
**Ожидаемый результат**

Текст в форме обратной связи хорошо читается, форма выглядит красиво

**Фактический результат**

Форма слишком сжата, читается плохо (см. скриншот)

**Скриншот**
![Снимок экрана 2020-04-12 в 20 33 14](https://user-images.githubusercontent.com/60069259/79075655-ded00900-7cfc-11ea-9d84-6bf66e3c54e6.png)

@solarrust, исправь!

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
