### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Nataliya772** [netology-code/git-homeworks-neuro-issues#793]
# **Главная страница. Текстовый блок "Форма обратной связи" слишком сжата.**
@solarrust
## Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока _"Форма обратной связи"_

### Ожидаемый результат
Предложения в тексте помещаются в строку

### Фактический результат
Предложения в тексте практически "спрессованы" в столбец (см. [скриншот)](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
