### ISSUE TITLE
The text runs over the image.

### ISSUE THREAD

**Issue by PTeslov** [netology-code/git-homeworks-neuro-issues#794]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат

Текст не наезжает на изображение
### Фактический результат

Текст наезжает на изображение (см. скриншот)
### Программное окружение

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

Скриншоты
![изображение](https://user-images.githubusercontent.com/63097391/79077373-d6ca9600-7d09-11ea-95e6-12f6fa96d728.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
