### ISSUE TITLE
The feedback form is too compressed.

### ISSUE THREAD

**Issue by PTeslov** [netology-code/git-homeworks-neuro-issues#795]
### Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    Пролистать страницу до блока "Форма обратной связи"
### Ожидаемый результат
Форма обратной связи по размеру страницы.

### Фактический результат

Текст слишком сжат (см. скриншот)

### Программное окружение

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)
### Скриншоты
![изображение](https://user-images.githubusercontent.com/63097391/79077773-68d39e00-7d0c-11ea-9af8-7e6f89ba7aa1.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
