### ISSUE TITLE
Страница feedback слишком сжата

### ISSUE THREAD

**Issue by temirkaev** [netology-code/git-homeworks-neuro-issues#797]
# Описание проблемы
**Страница feedback слишком сжата**

@solarrust

**Шаги по воспроизведению**
Открыть feedback на сайте NeuroStartUp в мобильном браузере Chrome

**Ожидаемый результат**
Страница feedback не сжата

**Фактический результат**
Страница слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![скриншот](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
