### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by paveldred** [netology-code/git-homeworks-neuro-issues#798]
@solarrust Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/44031300/79079277-d8e72180-7d16-11ea-9fb1-2fa9971e4e89.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
