### ISSUE TITLE
Форма обратной связи сжата

### ISSUE THREAD

**Issue by paveldred** [netology-code/git-homeworks-neuro-issues#799]
@solarrust 
**Форма обратной связи слишком сжата**

**Шаги по воспроизведению**
Открыть форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome

**Ожидаемый результат**
Поля формы имеют ширину 50px

**Фактический результат**
Поля формы имеют ширину 30px (см. скриншот). Этого недостаточно для отображения телефонного номера и большинства имен целиком.

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/44031300/79079414-9a9e3200-7d17-11ea-850e-f32fc11fc94b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
