### ISSUE TITLE
Форма обратной связи слишком сжата via mobile browsing

### ISSUE THREAD

**Issue by Sheerazspb** [netology-code/git-homeworks-neuro-issues#8]
# Описание проблемы
@ikrieg обратите внимание

<b>  Форма обратной связи слишком сжата.
### Шаги по воспроизведению
1. Открыть любую страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до конца, до блока "Оставайтесь на связи"

### Ожидаемый результат
Форма растянута на всю ширину страницы
### Фактический результат
Форма сильно сжата по ширине

 (см. скриншот)
### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/44028763/52609729-52734d80-2e8f-11e9-8b7e-842b00c12e7b.png)

**Comment by solarrust** [comment]
Great! I'll fix it someday =)
