### ISSUE TITLE
Текстовый блок наезжает на картинку_1

### ISSUE THREAD

**Issue by cousy14** [netology-code/git-homeworks-neuro-issues#800]
@solarrust 
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншот

![1D59C075-BAB4-4A42-964A-5E5589E70BA1](https://user-images.githubusercontent.com/63116134/79080805-c40f8b80-7d20-11ea-9f04-00cca906fc2e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
