### ISSUE TITLE
Форма обратной связи слишком сжата_2

### ISSUE THREAD

**Issue by cousy14** [netology-code/git-homeworks-neuro-issues#801]
@solarrust

Форма обратной связи слишком сжата

Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до формы обратной связи

Ожидаемый результат

Форма, растянутая по ширине экрана

Фактический результат

Слишком сжатая форма (см. скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот

![A1567FC7-1B3E-4680-BCD3-492D18781F77](https://user-images.githubusercontent.com/63116134/79081084-d25ea700-7d22-11ea-9081-e7c2596ed9db.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
