### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Lars175** [netology-code/git-homeworks-neuro-issues#804]
**Priority P0**
@solarrust
Steps:

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Прокрутить страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: Huawei mate 30 PRO (androin 10.1)
Браузер: Chrome (80.0.3987.162)
Скрин ошибки:
![git-homeworks_remote at master · netology-code_git](https://user-images.githubusercontent.com/63231704/79130261-578f9d80-7daf-11ea-8270-f7f76c790178.jpg)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
