### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Lars175** [netology-code/git-homeworks-neuro-issues#805]
Priority: P0
@solarrust

Steps:

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Прокрутить страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат:
Форма обратной связи адаптирована под страницу.

Фактический результат:
Форма обратной связи слишком сжата (см. скриншот)

Окружение:

Устройство: Huawei mate 30 PRO (androin 10.1)
Браузер: Chrome (80.0.3987.162)

Скрин ошибки:
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63231704/79130748-28c5f700-7db0-11ea-97ce-c484396bf446.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
