### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by MikhailUsachev-Piter** [netology-code/git-homeworks-neuro-issues#808]
# Steps:

### Форма обратной связи слишком сжата (см. скриншот)
![Форма обратной связи](https://user-images.githubusercontent.com/63136175/79136231-56636e00-7db9-11ea-9fac-1a875854de43.png)

Окружение:

1. Устройство: Huawei mate 30 PRO (androin 10.1)
1. Браузер: Chrome (80.0.3987.162)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
