### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by o91leg** [netology-code/git-homeworks-neuro-issues#811]
@solarrust 
# Описаниепроблемы
**Форма обратной связи слишком сжата**
    
**Шаги по воспроизведению**

Открыть форму обратной связи 

**Ожидаемый результат**

Форма обратной связи нормального размера

#Фактический результат**

Форма обратной связи слишком сжата

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63369945/79138260-ea830480-7dbc-11ea-8987-02a2f61c9b77.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
