### ISSUE TITLE
Главная страница. Форма для связи. "Оставайтесь на связи" Слова не должны переноситься

### ISSUE THREAD

**Issue by DimaLev-7** [netology-code/git-homeworks-neuro-issues#813]
@solarrust

### Шаги по воспроизведению ###
1. Oткрыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Перейти на форму обратной связи
### Ожидаемый результат ### 
* Слова не переносятся
### Фактический результат ### 
* Слово Оставайтесь перенеслось (см. скриншот) *
### Программное окружение ### 
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
![79041308-777c6100-7bf7-11ea-9a59-b0c657190388](https://user-images.githubusercontent.com/62996272/79139282-b3adee00-7dbe-11ea-8086-e6aa9476df23.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
