### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение 

### ISSUE THREAD

**Issue by DimaLev-7** [netology-code/git-homeworks-neuro-issues#814]
@solarrust

### Шаги по воспроизведению ### 
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат ### 
* Текст не наезжает на изображение
###  Фактический результат ### 
* Текст наезжает на изображение (см. скриншот) *
###  Программное окружение ### 
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

![79040986-f9b75600-7bf4-11ea-8e64-80bfdd9cc80b](https://user-images.githubusercontent.com/62996272/79139459-04bde200-7dbf-11ea-88a8-3aaec81b8f0b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
