### ISSUE TITLE
Главная страница. Текст наезжает на изображение

### ISSUE THREAD

**Issue by RTS-1989** [netology-code/git-homeworks-neuro-issues#815]
**Текстовый блок на главной странице наезжает на изображение**

@solarrust

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

![1](https://user-images.githubusercontent.com/63114573/79141357-18734380-7dd3-11ea-8a0d-7d111b9c593c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
