### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by RTS-1989** [netology-code/git-homeworks-neuro-issues#816]
**Форма обратной связи слишком сжата**

@solarrust

**Шаги по воспроизведению**
Открыть форму обратной связи на сайте NeuroStartUp в браузере Chrome

**Ожидаемый результат**
Форма обратной связи на не сжата

**Фактический результат**
Форма обратной связи сжата (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

![2](https://user-images.githubusercontent.com/63114573/79141976-3e4d1800-7dd4-11ea-8d5c-760a6d2c5330.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
