### ISSUE TITLE
Главная страница. Текст наезжает на на изображение

### ISSUE THREAD

**Issue by Gnucheva** [netology-code/git-homeworks-neuro-issues#817]
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
@solarrust 

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
 ![bug](https://user-images.githubusercontent.com/63240341/79149445-dac0eb80-7dcf-11ea-9c4a-4ac855752390.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
