### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by TimBokarev** [netology-code/git-homeworks-neuro-issues#818]
@solarrust

### Описание проблемы

Форма обратной связи слишком сжата

**Шаги по воспроизведению**

Открыть форму обратной связи

**Ожидаемый результат**

Форма обратной связи нормального размера

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63168291/79149910-2e2f3b80-7dc8-11ea-9ddc-1ceac511b4c6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
