### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Gnucheva** [netology-code/git-homeworks-neuro-issues#819]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
@solarrust 

#### Ожидаемый результат

Текст распределен равномерно по экрану . 

#### Фактический результат

Текст слишком сжат на экране . 

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
![Обратная связь](https://user-images.githubusercontent.com/63240341/79150037-be717e80-7dd0-11ea-8325-40756aeee0f5.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
