### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by natdok85** [netology-code/git-homeworks-neuro-issues#82]
# Описание проблемы

Добрый день, @solarrust.
При работе над проектом обнаружилась проблема:

**главная страница: текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![Text](https://user-images.githubusercontent.com/43211311/57719254-013e4a00-7688-11e9-8be4-7d836cc7f0df.png)
**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
