### ISSUE TITLE
Главная страница. Текст наезжает на изображение

### ISSUE THREAD

**Issue by TimBokarev** [netology-code/git-homeworks-neuro-issues#820]
@solarrust

**Описание проблемы** 

Текстовый блок на главной странице наезжает на изображение (см. скриншот)

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/63168291/79150759-95012480-7dc9-11ea-9e3f-627ef7b748d3.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
