### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by lionfishka** [netology-code/git-homeworks-neuro-issues#823]
**Главная страница. Форма обратной связи слишком сжата**
@solarrust

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма занимает примерно 1/3 ширины экрана, каждое предложение занимает одну строчку.

**Фактический результат**
Форма обратной связи слишком сжата, текст располагается в несколько строчек (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![форма для связи](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
