### ISSUE TITLE
Главная страница. Текст наезжает на картинку

### ISSUE THREAD

**Issue by UlyanaErmoshina** [netology-code/git-homeworks-neuro-issues#824]
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/63065209/79219913-c5919e80-7e5b-11ea-97c5-52e82b52a726.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
