### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by UlyanaErmoshina** [netology-code/git-homeworks-neuro-issues#825]
### Шаги по воспроизведению

 Открыть форму обратной связи в мобильном браузере Chrome

### Ожидаемый результат
Форма обратной связи стандартного размера, согласно дизайну.

### Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншот

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63065209/79220987-b6135500-7e5d-11ea-8860-6ddb04dbda28.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
