### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by asrodionov** [netology-code/git-homeworks-neuro-issues#827]
@solarrust , нужно починить баг

### Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат
Форма занимает по ширине весь экран

### Фактический результат
Форма слишком сжата

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63148102/79222277-ea881080-7e5f-11ea-968f-4fdf622bd460.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
