### ISSUE TITLE
Баг " Форма обратной связи слишком сжата"

### ISSUE THREAD

**Issue by Alenovaalla** [netology-code/git-homeworks-neuro-issues#829]
@solarrust

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма занимает  1/3 ширины экрана, каждое предложение занимает одну строчку.

#### Фактический результат

Форма обратной связи слишком сжата, текст располагается в несколько строчек (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![image](https://user-images.githubusercontent.com/63126356/79245879-65155800-7e81-11ea-9821-17daa50c92a0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
