### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by natdok85** [netology-code/git-homeworks-neuro-issues#83]
# Описание проблемы

Добрый день, @solarrust. 
При работе над проектом обнаружилась проблема:

**форма "Оставайтесь на связи" на главной странице Уже, чем нужно.**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы "Оставайтесь на связи"

**Ожидаемый результат**
Форма не соответствует размеру

**Фактический результат**
Форма Уже, чем заготовленный блок (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**

![Форма](https://user-images.githubusercontent.com/43211311/57719925-69416000-7689-11e9-9fe2-54d25064442d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
