### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by PolyakovAlexQA** [netology-code/git-homeworks-neuro-issues#833]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

@solarrust 6aa1c0b172e285ee42e9a1045f32548414d75ed4

![скрин1](https://user-images.githubusercontent.com/63161652/79262640-4e2f2f80-7e9a-11ea-86d9-d8c9c9d44454.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
