### ISSUE TITLE
Вкладка "Обратная связь". Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by PolyakovAlexQA** [netology-code/git-homeworks-neuro-issues#834]
**Шаги по воспроизведению**
1.Открыть главную страницу
2.Переходим по ссылке обратная связь

**Ожидаемый результат**

Форма обратной связи в стандартном размере, удобна для просмотра, не сжата.

**Фактический результат**

Форма обратной связи слишком сжата. (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
@solarrust 857e3d95477bfbd9c93fb04804a64d0007c1c075

![скрин 2](https://user-images.githubusercontent.com/63161652/79263762-16c18280-7e9c-11ea-8131-abccd9106f8b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
