### ISSUE TITLE
Вкладка "Обратная связь". Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by mirrora2010** [netology-code/git-homeworks-neuro-issues#836]
@solarrust 
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму обратной связи

#### Ожидаемый результат
Форма обратной связи не слишком сжата.

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63370321/79279880-4b8b0500-7eaf-11ea-9fc9-d9f8d2160f15.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
