### ISSUE TITLE
Сжатая форма обратной связи

### ISSUE THREAD

**Issue by EkaterinaErm** [netology-code/git-homeworks-neuro-issues#839]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть меню веб-сайта NeuroStartUp в браузере Opera
2. Кликнуть на кнопку "Обратная связь"

#### Ожидаемый результат

Всплывает форма обратной связи адекватной ширины, вмещающей заголовок.

#### Фактический результат

Всплывает узкое окно, не вмещающее первое слово заголовка (см. скриншот)

#### Программное окружение

* Устройство: Ноутбук SAMSUNG E352-JS01 (Windows 10)
* Браузер: Opera (67.0.3575.115)

#### Скриншоты

![скриншот проблемы](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
