### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by vltrofimov** [netology-code/git-homeworks-neuro-issues#84]
@solarrust 
### Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

1. Устройство: iPhone 8+ (iOS 12.1)
2. Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/50232791/57746850-b4845e80-76db-11e9-9a3c-f7e662d4759b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
