### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ghost** [netology-code/git-homeworks-neuro-issues#840]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Блок масштабируется исходя из разрешения окна. 

#### Фактический результат

Блок обратной связи сжат.

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](http://i.piccy.info/i9/b10a376b76249af8e8faf3e15b216bcc/1586941403/38511/1372967/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
