### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Tatianathomas** [netology-code/git-homeworks-neuro-issues#844]
# Описание проблемы
**Главная страница. Форма обратной связи слишком сжата
Шаги по воспроизведению**
@solarrust 
 1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
  2.Пролистать страницу до блока "Форма обратной связи"

**Ожидаемый результат**
Форма занимает весь экран

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
    *Устройство: iPhone 8+ (iOS 12.1)
    *Браузер: Chrome (70.0.3538.75)

Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/53948371/79337195-825c2c00-7f3e-11ea-83de-64d7179f6c5e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
