### ISSUE TITLE
Верстка формы обратной связи

### ISSUE THREAD

**Issue by Andrey-Yakovtsev** [netology-code/git-homeworks-neuro-issues#846]
**Главная страница.Форма обратной связи слишком сжата.**

**Шаги по воспроизведению**

- [ ] 1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- [ ] 2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Блок масштабируется исходя из разрешения окна.

**Фактический результат**
Блок обратной связи сжат.

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

[Скриншот](https://camo.githubusercontent.com/15705499b0738752c3286f3aa5e3154f23b80a39/687474703a2f2f692e70696363792e696e666f2f69392f62313061333736623736323439616638653866616633653135623231366263632f313538363934313430332f33383531312f313337323936372f36383734373437303733336132663266363932653639366436373735373232653633366636643266343836333533373035393662353432653730366536372e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
