### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Alexey-Android** [netology-code/git-homeworks-neuro-issues#849]
# Описание проблемы
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..."  наезжает на изображение
**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75) 

**Скриншоты**
![image](https://user-images.githubusercontent.com/63456973/79376990-aed66f00-7f63-11ea-8757-a2f8388ae861.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
