### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by vltrofimov** [netology-code/git-homeworks-neuro-issues#85]
@solarrust 

### Описание проблемы
**Главная страница. Размеры формы обратной связи не соответствуют размерам просматриваемой области на экране телефона**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome.
2. Пролистать страницу до формы обратной связи.

**Ожидаемый результат**

Размеры формы обратной связи соответствуют размерам просматриваемой области на экране телефона

**Фактический результат**

Размеры формы обратной связи не соответствуют размерам просматриваемой области на экране телефона (см. скриншот)

**Программное окружение**

1. Устройство: iPhone 8+ (iOS 12.1)
2. Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/50232791/57747668-33c76180-76df-11e9-991a-c68714d326c1.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
