### ISSUE TITLE
Форма обратной связи  - замечание

### ISSUE THREAD

**Issue by Alexey-Android** [netology-code/git-homeworks-neuro-issues#850]
# Описание проблемы
### Не главная страница. Текстовый блок "Оставайтесь на связи" слишком сжат
**Шаги по воспроизведению**

1. Открыть не главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

* Форма пропорциональна

**Фактический результат**

* Форма слишком узкая

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**
![image](https://user-images.githubusercontent.com/63456973/79379980-738a6f00-7f68-11ea-920c-0624caffb153.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
