### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by eduard-help** [netology-code/git-homeworks-neuro-issues#851]
# Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. *Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome*
1. *Пролистать страницу до блока "Воспользуйтесь современными возможностями..."*

**Ожидаемый результат**
*Текст не наезжает на изображение*

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Вложение**
![photo-problem](https://user-images.githubusercontent.com/62300922/77592066-639be400-6f02-11ea-9f5f-59e3441e7d06.png)

@solarrust 
**Решение**
1. Так как используется Bootstrap, предлагаю исправить блочную систему для элемента <div>, а именно внести изменения в index.html:

https://github.com/netology-code/git-homeworks-neuro-issues/blob/857e3d95477bfbd9c93fb04804a64d0007c1c075/index.html#L41

> **Например**

`<div class="col-md-5 col-sm-7 mx-auto text-center">`

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
