### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by eduard-help** [netology-code/git-homeworks-neuro-issues#852]
# Описание проблемы
**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

1. *Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome*
1. *Пролистать страницу до Формы обратной связи*

**Ожидаемый результат**
*Ширина блока формы обратной связи соответствует экрану устройства на котором она отображается*

**Фактический результат**
Форма обратной связи слишком сжата на мобильных устройствах (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)

**Вложение**
![photo-problem](https://user-images.githubusercontent.com/63632717/79394134-72187100-7f7f-11ea-818b-4f3335c24aa0.png)

@solarrust 
**Решение**
1. Так как используется Bootstrap, предлагаю исправить блочную систему для элемента <div>, а именно внести изменения в index.html:

https://github.com/netology-code/git-homeworks-neuro-issues/blob/857e3d95477bfbd9c93fb04804a64d0007c1c075/index.html#L52

> **Например**

`<div class="contacts-card col-md-6 mx-auto card pt-4 pb-4">`

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
