### ISSUE TITLE
Текст заезжает на картинку

### ISSUE THREAD

**Issue by DenisV20** [netology-code/git-homeworks-neuro-issues#853]
### Шаги: ###
* Открыть браузер;
* Найти и исправить ошибку.

### Ожидаемый результат. ###
Текст не наезжает на картинку.

### Фактический результат. ###
Текст наезжает на картинку (см. скриншот)
![NS](https://user-images.githubusercontent.com/63121967/79396385-75622b80-7f84-11ea-8805-6aa0c855139e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
