### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by DenisV20** [netology-code/git-homeworks-neuro-issues#854]
### Шаги: ###
_Увеличить ширину окон для заполнения данных;
Улучшить читаемость текста._

**Ожидаемый вариант:**
_Расширить границы._

**Фактический вариант:**
_Страница сжата (**см. скриншот**)_
![Cont](https://user-images.githubusercontent.com/63121967/79397290-6bd9c300-7f86-11ea-8a36-d77cdab61d87.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
