### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Yan-Gus** [netology-code/git-homeworks-neuro-issues#855]
# Описание проблемы 

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![image](https://user-images.githubusercontent.com/63108940/79446350-c0ad2600-7fe6-11ea-8034-6ee3f9f43747.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
