### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Yan-Gus** [netology-code/git-homeworks-neuro-issues#856]
# Описание проблемы

**Главная страница. Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

- Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Необходимо расширить границы формы, чтобы текст занимал не больше двух строк.

**Фактический результат**
Узкая форма, текст занимает 3-4 строчки.

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![image](https://user-images.githubusercontent.com/63108940/79447624-d15e9b80-7fe8-11ea-933f-5b6c55224bfb.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
