### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by kazakovdmitri** [netology-code/git-homeworks-neuro-issues#857]
#### Описание проблемы

Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
https://github.com/netology-code/git-homeworks-neuro-issues/blob/857e3d95477bfbd9c93fb04804a64d0007c1c075/index.html#L43

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение
* Устройство: Samsung Galaxy S10

#### Скриншоты
![](https://i.imgur.com/jySupYq.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
