### ISSUE TITLE
Форма обратной связи слишком сжата 

### ISSUE THREAD

**Issue by kazakovdmitri** [netology-code/git-homeworks-neuro-issues#858]
#### Описание проблемы

Главная страница. Форма обратной связи слишком сжата и вытянута. 
https://github.com/netology-code/git-homeworks-neuro-issues/blob/857e3d95477bfbd9c93fb04804a64d0007c1c075/index.html#L54-L55

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Осьавайтесь на связи..."

#### Ожидаемый результат

Блок равномерно распределен по ширене экрана.

#### Фактический результат

Блок сжат и не распределен по ширине экрана.

#### Программное окружение

* Устройство: Samsung Galaxy S10

#### Скриншоты
![](https://i.imgur.com/uwkta6A.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
