### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by kyaleee** [netology-code/git-homeworks-neuro-issues#859]
### Описание проблемы

**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Програмное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![Inked68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67_LI](https://user-images.githubusercontent.com/63292579/79475462-61640b80-8010-11ea-9a86-e0504fff48f1.jpg)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
