### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by Bogdan57** [netology-code/git-homeworks-neuro-issues#86]
@solarrust
### Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/47219115/57776286-c390fe00-7727-11e9-91b1-8e7d2f973ae0.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
