### ISSUE TITLE
Сжатый текст в "Обратной связи"

### ISSUE THREAD

**Issue by kyaleee** [netology-code/git-homeworks-neuro-issues#860]
### Описание проблемы

**Главная страница. Предложения сильно сжимаются, занимая много строк**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**

Размер текста составляет не более 2х строк

**Фактический результат**

Текст сжимается до 3-4 строк

**Програмное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63292579/79476261-6c6b6b80-8011-11ea-9b36-2a4950149393.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
