### ISSUE TITLE
Главная страница. Текст наезжает на картинку

### ISSUE THREAD

**Issue by sonnegavis** [netology-code/git-homeworks-neuro-issues#861]
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты 
![2020-04-16_20-25-02](https://user-images.githubusercontent.com/63167125/79487186-86f91100-8020-11ea-9a5e-e5f283ca313e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
