### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by sonnegavis** [netology-code/git-homeworks-neuro-issues#862]
###  Описание проблемы

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Обратная связь"

**Ожидаемый результат** 
Форма обратной связи соответствует ширине экрана

**Фактический результат** 
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![2020-04-16_20-25-15](https://user-images.githubusercontent.com/63167125/79487663-48178b00-8021-11ea-9def-7d7dd5227fdc.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
