### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Yoji-kms** [netology-code/git-homeworks-neuro-issues#863]
***Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение***

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: Huawei P30 (EMUI 10)
* Браузер: Chrome (80.0.3987.162)

**Скриншот**
![image](https://user-images.githubusercontent.com/63704200/79488711-82068280-805d-11ea-9343-da656bd8251e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
