### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Yoji-kms** [netology-code/git-homeworks-neuro-issues#864]
***Главная страница. Форма "Оставайтесь на связи..." слишком сжата***

**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Форма обратной связи равномерно распределена по ширине экрана

**Фактический результат**
Форма обратной связи сжата (см. скриншот)

**Программное окружение**

Устройство: Huawei P30 (EMUI 10)
Браузер: Chrome (80.0.3987.162)

**Скриншот**
![image](https://user-images.githubusercontent.com/63704200/79489335-75cef500-805e-11ea-86fb-07d6f3267279.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
