### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Arkadi22** [netology-code/git-homeworks-neuro-issues#865]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см.скриншот neurostartup text)
![neurostartup text](https://user-images.githubusercontent.com/23100888/79497039-1b22a280-8038-11ea-91a3-d9ef04f30826.png)

**Программное окружение**

- Устройство Huawei Mate 20 Lite

- Браузер: Chrome (80.0.3987.162)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
