### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Arkadi22** [netology-code/git-homeworks-neuro-issues#866]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат**
Форма обратной связи должна быть адаптирована  под страницу

**Фактический результат**
Форма обратной связи слишком сжата (см.скриншот форма обратной связи)
![форма обратной связи](https://user-images.githubusercontent.com/23100888/79498374-3bebf780-803a-11ea-8758-e1089f295dec.png)

**Программное окружение**

- Устройство Huawei Mate 20 Lite

- Браузер: Chrome (80.0.3987.162)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
