### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by shapovalova-maria** [netology-code/git-homeworks-neuro-issues#868]
# Описание проблемы
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока формы обратной связи

### Ожидаемый результат
Форма обратной связи выглядит корректно

### Фактический результат
Форма обратной связи выглядит слишком сжатой (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61393342/79503510-90d74000-8031-11ea-988f-bed1c9abd64e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
