### ISSUE TITLE
Проблемы мобильной версии. Текст наезжает на картинку

### ISSUE THREAD

**Issue by HolowSpacer** [netology-code/git-homeworks-neuro-issues#869]
@solarrust
****Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..."** наезжает на изображение**
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

1. Устройство: iPhone 8+ (iOS 12.1)
2. Браузер: Chrome (70.0.3538.75)

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/63729342/79558401-c2412180-80ac-11ea-9730-10d801da1b7d.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
