### ISSUE TITLE
Проблемы мобильной версии. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by HolowSpacer** [netology-code/git-homeworks-neuro-issues#870]
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63729342/79559320-2a443780-80ae-11ea-855a-a39a5d7f35b4.png)
@solarrust
**Главная страница. Форма обратной связи слишком сжата**
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Форма правильных размеров

**Фактический результат**
Форма слишком сжата

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
