### ISSUE TITLE
Проблемы мобильной версии. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Surgutov** [netology-code/git-homeworks-neuro-issues#871]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

или
   
1. Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome.
2. Перейти "Инструменты" -> "Веб-разработка" -> "Адаптивный дизайн"

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)
Программное окружение

* Устройство: iPhone XS Max (iOS 12)
* Устройство: Pixel 2 XL  (Android  8.0)
* Браузер: Chrome (74.0)

Скриншоты
![iPhoneXSMax](https://user-images.githubusercontent.com/63395866/79571462-e4926980-80c3-11ea-96a9-ddf70531fd37.png)
![Pixel-2XL](https://user-images.githubusercontent.com/63395866/79571464-e52b0000-80c3-11ea-863a-896b160baeb7.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
