### ISSUE TITLE
Проблемы мобильной версии. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Surgutov** [netology-code/git-homeworks-neuro-issues#872]
**Главная страница. Форма обратной связи слишком сжата**
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

или

1. Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome.
2.Перейти "Инструменты" -> "Веб-разработка" -> "Адаптивный дизайн"

**Ожидаемый результат**
Форма обратной связи выглядит корректно, в соответствии с размером и разрешением экрана.

**Фактический результат**
Форма обратной связи выглядит слишком сжатой (см. скриншот)

Программное окружение

    Устройство: iPhone XS Max (iOS 12)
    Устройство: Pixel 2 XL (Android 8.0)
    Браузер: Chrome (74.0)

Скриншоты
![iPhoneXSMax-2](https://user-images.githubusercontent.com/63395866/79573973-1f969c00-80c8-11ea-8915-16dd7f964817.png)
![Pixel-2XL-2](https://user-images.githubusercontent.com/63395866/79573975-202f3280-80c8-11ea-85b3-0f8882bc3c08.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
