### ISSUE TITLE
Проблема мобильной версии. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ashfrol** [netology-code/git-homeworks-neuro-issues#874]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Форма отображается нормально

#### Фактический результат

Форма обратной связи слишком сжата

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

@solarrust 

#### Скриншоты

![](https://i.imgur.com/ROnh6SM.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
