### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Mirex33** [netology-code/git-homeworks-neuro-issues#875]
@solarrust
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот:** 
![image](https://user-images.githubusercontent.com/61405005/79602398-d6643d80-8103-11ea-9c6f-29063309b188.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
