### ISSUE TITLE
Текст не "Оставайтесь на связи..." не отформатирован

### ISSUE THREAD

**Issue by Mirex33** [netology-code/git-homeworks-neuro-issues#876]
@solarrust 
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Текст не отформатирован

**Фактический результат**
Текст не отформатирован

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)**

**Скриншот:** 
![image](https://user-images.githubusercontent.com/61405005/79603276-77072d00-8105-11ea-8bec-9c45bcd0ad90.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
