### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by agasferon** [netology-code/git-homeworks-neuro-issues#877]
# Описание проблемы

#### Главная страница. 
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: Nexus7 (Android 6.0)
* Браузер: Chrome (80.0.3987.163)

#### Скриншот
![for_1_issue](https://user-images.githubusercontent.com/60872486/79615020-6907db00-810a-11ea-803d-81b5e9f6647c.PNG)

**@solarrust**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
