### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by agasferon** [netology-code/git-homeworks-neuro-issues#878]
# Описание проблемы

#### Главная страница. 
Блок обратной связи слишком сжат относительно ширины экрана

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Блок обратной связи соответствует ширине экрана

#### Фактический результат

Блок обратной связи значительно меньше ширины экрана

#### Программное окружение

*Устройство: Nexus7 (Android 6.0)
*Браузер: Chrome (80.0.3987.163)

#### Скриншоты
![for_2_issue](https://user-images.githubusercontent.com/60872486/79615421-6b1e6980-810b-11ea-8b11-28c450820cde.PNG)

**@solarrust**

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
