### ISSUE TITLE
Текст наезжает на картинку; Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by melnykof** [netology-code/git-homeworks-neuro-issues#880]
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone SE (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**Скриншоты**
![1](https://user-images.githubusercontent.com/61194734/79635423-7e681e00-8179-11ea-8013-49046d98a73c.png)
![2](https://user-images.githubusercontent.com/61194734/79635424-7f00b480-8179-11ea-8806-f8fc91a5be2f.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
