### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by evagud** [netology-code/git-homeworks-neuro-issues#882]
@solarrust
Гудильхина Евгения Анатольевна

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

#### Ожидаемый результат

Форма обратной связи отображается корректно

#### Фактический результат

Форма обратной связи сжата

#### Программное окружение

* Устройство: ASUS LAPTOP-JHKQCJHF, 
Windows 10 х64,  версии 1903
 и сборки 18362.720, 
* Браузер: Google Chrome 
Версия 80.0.3987.132 (64 бит

#### Скриншоты

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
