### ISSUE TITLE
Текст наезжает на картинку.

### ISSUE THREAD

**Issue by MIkhail19870105** [netology-code/git-homeworks-neuro-issues#885]
@solarrust

# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![Text on pic](https://user-images.githubusercontent.com/63183489/79682193-f17c9d80-8228-11ea-8fc6-3899218533f8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
