### ISSUE TITLE
Форма обратной связи на сайте сильно сжата при отображении в мобильной версии

### ISSUE THREAD

**Issue by MIkhail19870105** [netology-code/git-homeworks-neuro-issues#886]
@solarrust

# Описание проблемы

####Главная страница. Форма обратной связи на сайте сильно сжата при отображении в мобильной версии

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

#### Ожидаемый результат

Форма обратной связи должна соответствовать макету

#### Фактический результат

Форма сжата в отображении мобильной версии (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![Form](https://user-images.githubusercontent.com/63183489/79682264-5df79c80-8229-11ea-8a8f-97447ecf5d05.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
