### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by iashmlv** [netology-code/git-homeworks-neuro-issues#887]
@solarrust 
### Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### **Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### **Ожидаемый результат**
Текст не наезжает на изображение

### **Фактический результат**
Текст наезжает на изображение (см. скриншот)

### **Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### **Скриншот**
<img width="327" alt="Снимок экрана 2020-04-19 в 11 45 19" src="https://user-images.githubusercontent.com/63490977/79683645-188c9c80-8234-11ea-92a1-4a93a4351d68.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
