### ISSUE TITLE
Форма обратной связи сильно сжата

### ISSUE THREAD

**Issue by iashmlv** [netology-code/git-homeworks-neuro-issues#888]
@solarrust 
### **Описание проблемы**
Главная страница. Форма обратной связи сильно сжата

### **Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до формы обратной связи

### **Ожидаемый результат**
Форма соответствует ширине страницы

### **Фактический результат**
Форма сжата по бокам в мобильной версии (см.скриншот)

### **Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### **Скриншот**
<img width="355" alt="Снимок экрана 2020-04-19 в 11 46 08" src="https://user-images.githubusercontent.com/63490977/79683765-db74da00-8234-11ea-9a6b-c5f75a82b3de.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
