### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by AnnaKulikovskikh** [netology-code/git-homeworks-neuro-issues#889]
### Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Нажать F12

1. Задать ширину экрана 795 или меньше

1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение
### Фактический результат
Текст наезжает на изображение (см. скриншот)
### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)
### Скриншоты
![Screenshot](https://user-images.githubusercontent.com/59337789/79684455-d82c1f00-8231-11ea-904d-a4d5316d0103.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
