### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AnnaKulikovskikh** [netology-code/git-homeworks-neuro-issues#890]
### Описание проблемы
Главная страница. Форма "Обратная связь" слишком сжата

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Нажать F12

1. Поизменять ширину экрана формы для обратной связки

1. Выбрать iPhone 8

### Ожидаемый результат
Соответствие макету дизайнера

### Фактический результат
см. скриншот

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![Screenshot1](https://user-images.githubusercontent.com/59337789/79684798-6dc8ae00-8234-11ea-9176-7b4abbfd8102.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
