### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Alexsashka43** [netology-code/git-homeworks-neuro-issues#892]
@solarrust

**Описание проблемы**

Главная страница. Форма обратной связи сильно сжата

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи
 

**Ожидаемый результат**

Форма соответствует ширине страницы

**Фактический результат**

Форма сжата по бокам в мобильной версии (см.скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

Скриншот
<img width="355" alt="79683765-db74da00-8234-11ea-9a6b-c5f75a82b3de" src="https://user-images.githubusercontent.com/63096544/79689635-d462c180-825e-11ea-9f6c-d199cd9b0408.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
