### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Ksenia-Ling** [netology-code/git-homeworks-neuro-issues#894]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

#### Ожидаемый результат
Ширина формы соответствует макету и ширине экрана
#### Фактический результат

Ширина формы слишком мала, слова и фразы переносятся на несколько строк (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63148020/79690651-23f7bc00-8264-11ea-99bf-48fc0318172b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
