### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by AlikAskat** [netology-code/git-homeworks-neuro-issues#895]
@solarrust 

# **`Описание проблемы`**

### **Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### **Ожидаемый результат**

Текст не наезжает на изображение

### **Фактический результат**

Текст наезжает на изображение (см. скриншот)

### **Программное окружение**

- Устройство: Realme XT 1921+ (Android 10)
- Браузер: Chrome (81.0.4044.96)

### **Скриншот**

![Promo neuro-startup](https://user-images.githubusercontent.com/62005497/79693932-e3f60080-8286-11ea-84dc-28a227a31021.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
