### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AlikAskat** [netology-code/git-homeworks-neuro-issues#896]
@solarrust 

# **Описание проблемы**

### **Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

### **Ожидаемый результат**

Ширина формы соответствует макету и ширине экрана

### **Фактический результат**

Ширина формы слишком мала, слова и фразы переносятся на несколько строк (см. скриншот)

### **Программное окружение**

- Устройство: Realme XT 1921+ (Android 10)
- Браузер: Chrome (81.0.4044.96)

### **Скриншоты**
![form of compression](https://user-images.githubusercontent.com/62005497/79694398-71d2eb00-8289-11ea-94bc-d286e12f75fb.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
