### ISSUE TITLE
Главная страница. Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by Ekaterina-Kolosova** [netology-code/git-homeworks-neuro-issues#897]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![image](https://user-images.githubusercontent.com/61948555/79698357-1147ac00-8291-11ea-8f7b-daf3870eb3d5.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
