### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by Ekaterina-Kolosova** [netology-code/git-homeworks-neuro-issues#898]
Главная страница. Форма обратной связи слишком сжата.
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи"
Ожидаемый результат
Форма занимает ширину экрана

Фактический результат
Форма занимает 50 % ширины экрана (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![image](https://user-images.githubusercontent.com/61948555/79698545-4a345080-8292-11ea-8727-7ba543002c55.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
