### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by AntonChernyak** [netology-code/git-homeworks-neuro-issues#899]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (@solarrust см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншот
<img src="https://i.imgur.com/iH11iB3.png" width="300">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
