### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by AntonChernyak** [netology-code/git-homeworks-neuro-issues#900]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

#### Ожидаемый результат

Форма занимает всю страницу

#### Фактический результат

Форма обратной связи слишком сжата (@solarrust см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншот
<img src="https://i.imgur.com/dZ41CSd.png" width="300">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
