### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Toanio** [netology-code/git-homeworks-neuro-issues#902]
# Описание проблемы
**Форма обратной связи сильно сжата по ширине**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
Форма соответствует макету и имеет правильные размеры по ширине и высоте

**Фактический результат**
Форма узкая и весь текст сжат (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![logo](https://user-images.githubusercontent.com/63148020/79690651-23f7bc00-8264-11ea-99bf-48fc0318172b.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
