### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by atname** [netology-code/git-homeworks-neuro-issues#908]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

### Ожидаемый результат
Ширина формы соответствует макету и ширине экрана

### Фактический результат
Ширина формы слишком мала, слова переносятся на другу строку 

### Программное окружение

- Устройство: Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (81.0.4044.96)

![image](https://user-images.githubusercontent.com/35631875/79783006-a659ac00-8348-11ea-916c-03e916197896.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
