### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Balakireva-Maria** [netology-code/git-homeworks-neuro-issues#909]
### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/63147523/79784203-5a643280-835b-11ea-8dfb-3e1363ce53c6.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
