### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Balakireva-Maria** [netology-code/git-homeworks-neuro-issues#910]
## Шаги по воспроизведению
1. Открыть страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до формы обратной связи

## Ожидаемый результат
Форма обратной связи растянута на ширину экрана

## Фактический результат
Форма обратной связи слишком сжата (см. скриншот)

## Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншот
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63147523/79784785-32290380-835c-11ea-882e-baeb77c2c336.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
