### ISSUE TITLE
Форма обратной связи на главной странице слишком сжата

### ISSUE THREAD

**Issue by akhabdulina** [netology-code/git-homeworks-neuro-issues#912]
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

#### Ожидаемый результат

Форма обратной связи соответствует ширине страницы.

#### Фактический результат

Форма сильно сжата, текст переносится некорректно (см. скриншот).

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://i.imgur.com/HcSpYkT.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
