### ISSUE TITLE
Текст наезжает на картинку;

### ISSUE THREAD

**Issue by melnykof** [netology-code/git-homeworks-neuro-issues#913]
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone SE (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**Скриншоты**
![1](https://user-images.githubusercontent.com/61194734/79829754-9a9fd100-83ac-11ea-969a-89521abf858c.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
