### ISSUE TITLE
Главная страница. Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by melnykof** [netology-code/git-homeworks-neuro-issues#914]
**Шаги по воспроизведению**
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Оставайтесь на связи..."
**Ожидаемый результат**
Форма обратной связи соответствует ширине страницы.

**Фактический результат**
Форма сильно сжата, текст переносится некорректно (см. скриншот).

**Программное окружение**
Устройство: iPhone SE (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
**Скриншоты**
![2](https://user-images.githubusercontent.com/61194734/79830021-36314180-83ad-11ea-812f-6cae5ce8d31f.png)
 @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
