### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by GorkovenkoSvetlana** [netology-code/git-homeworks-neuro-issues#915]
# Описание проблемы

### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат

Текст не наезжает на изображение

### Фактический результат

Текст наезжает на изображение (см. скриншот)

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

### Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/61566410/79847960-1b6cc600-83c9-11ea-82ca-b1a85e99739e.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
