### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by GorkovenkoSvetlana** [netology-code/git-homeworks-neuro-issues#916]
# Описание проблемы

###  Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат

Форма обратной связи по ширине экрана

### Фактический результат

Форма обратной связи слишком сжата

### Программное окружение

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

### Скриншоты
![Об св](https://user-images.githubusercontent.com/61566410/79849150-c631b400-83ca-11ea-9e92-894e7f0ec296.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
