### ISSUE TITLE
Форма обратной связи слишком сжата 

### ISSUE THREAD

**Issue by VincentVegaW** [netology-code/git-homeworks-neuro-issues#917]
@solarrust
# Описание проблемы #

## Шаги по воспроизведению ##
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат ###
Текст не наезжает на изображение

### Фактический результат ###
Текст наезжает на изображение (см. скриншот)

Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты ###
  я загрузила сюда котика) 

![Снимок экрана 2020-04-21 в 17 36 24](https://user-images.githubusercontent.com/60435700/79857368-e166e880-83f7-11ea-92cc-17fa5717c819.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
