### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by VincentVegaW** [netology-code/git-homeworks-neuro-issues#918]
@solarrust
# Описание проблемы #

## Шаги по воспроизведению ##
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат ###
Текст не наезжает на изображение

### Фактический результат ###
Текст наезжает на изображение (см. скриншот)

Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

### Скриншоты ###
сюда я добавила собачку))) 

![Снимок экрана 2020-04-21 в 17 37 46](https://user-images.githubusercontent.com/60435700/79858262-54bd2a00-83f9-11ea-97c9-e42323923772.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
