### ISSUE TITLE
текст наезжает на картинку 

### ISSUE THREAD

**Issue by DariaShugalo** [netology-code/git-homeworks-neuro-issues#919]
### Шаги по воспроизведению

1.  Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)

Браузер: Chrome (70.0.3538.75)

### Скриншоты
![image](https://user-images.githubusercontent.com/63112552/79889915-f7c47280-83fe-11ea-9eae-0b21cbd6bb55.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
