### ISSUE TITLE
Форма обратной связи слишком сжата 

### ISSUE THREAD

**Issue by DariaShugalo** [netology-code/git-homeworks-neuro-issues#920]
# Описание проблемы
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
### Ожидаемый результат
Текст не наезжает на изображение
Программное окружение
- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)
![image](https://user-images.githubusercontent.com/63112552/79890865-65bd6980-8400-11ea-95e5-0804ae7f6117.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
