### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by OlgaSleptsova** [netology-code/git-homeworks-neuro-issues#922]
**Главная страница. Форма обратной связи слишком сжата**
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

**Ожидаемый результат**
Форма обратной связи имеет эстетический прямоугольный вид.

**Фактический результат**
Форма обратной связи слишком сжата и неудобна в использовании (см. скриншот)

**Программное окружение**

1. Устройство: iPhone 8+ (iOS 12.1)
2. Браузер: Chrome (70.0.3538.75)

Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63954114/79900606-277f7480-8417-11ea-93d3-712bd8e19a9b.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
