### ISSUE TITLE
В мобильном браузере форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by bambr01** [netology-code/git-homeworks-neuro-issues#924]
**Главная страница. Блок "Оставайтесь на связи" не удобен для восприятия**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**
Форма обратной связи имеет удобный для восприятия и чтения вид. 

**Фактический результат**
Текст переносится на новые строки. Слова не помещаются в одну строку. Формы для заполнения данных слишком маленикие (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншот**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/61264074/79969478-3e1adf80-849a-11ea-9907-7141c19d7f94.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
