### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by VityaJulin** [netology-code/git-homeworks-neuro-issues#928]
Форма обратной связи слишком сжата.
Шаги по воспроизведению
Открыть Форму обратной связи веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Форма обратной связи."
Ожидаемый результат
Форма обратной связи имеет достаточную ширину, для удобства чтения ее текста.

Фактический результат
Форма обратной связи слишком сжата. (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/40697114/79997954-c8773980-84c2-11ea-9a23-a827fbdbdaf4.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
