### ISSUE TITLE
В мобильном браузере текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by IvanVorobev** [netology-code/git-homeworks-neuro-issues#929]
### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат
Текст не наезжает на изображение

### Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

![Текст наезжает на картинку](https://user-images.githubusercontent.com/63260533/80026919-94fcd500-84eb-11ea-9e83-75f5b1ad196e.png)

### @solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
