### ISSUE TITLE
В мобильном браузере форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by IvanVorobev** [netology-code/git-homeworks-neuro-issues#930]
### Шаги по воспроизведению:

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

### Ожидаемый результат
Форма обратной связи имеет удобный для восприятия и заполнения вид

### Фактический результат
Блок сжат. Текст переносится в нескольких местах. Формы для заполнения также слишком сжаты  (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншот
![Блок слишком сжат](https://user-images.githubusercontent.com/63260533/80028322-9c24e280-84ed-11ea-8abd-27c740781841.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
