### ISSUE TITLE
 Текст "Воспользуйтесь современными возможностями..." наезжает на изображение.

### ISSUE THREAD

**Issue by Ander1977** [netology-code/git-homeworks-neuro-issues#933]
Главная страница. Текст "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в  браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Laptop, Windows 10
Браузер: Google Chrome Версия 81.0.4044.122 
![git-hom](https://user-images.githubusercontent.com/63086193/80172532-94ba2200-8630-11ea-8fae-f44f6031cb14.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
