### ISSUE TITLE
Слишком сжат блок формы обратной связи.

### ISSUE THREAD

**Issue by Ander1977** [netology-code/git-homeworks-neuro-issues#934]
Шаги по воспроизведению:

1. Открыть страницу веб-сайта NeuroStartUp  браузере Chrome
2. Пролистать страницу до формы обратной связи

Ожидаемый результат:
Форма обратной связи растянута на ширину экрана

Фактический результат:
Форма обратной связи слишком сжата (см. скриншот)

Программное окружение
Laptop, Windows 10
Браузер Google Chrome Версия 81.0.4044.122 
![git-hom2](https://user-images.githubusercontent.com/63086193/80173061-05157300-8632-11ea-8067-7d7118d994d1.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
