### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by NekrasovaMarina** [netology-code/git-homeworks-neuro-issues#935]
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![issue 1](https://user-images.githubusercontent.com/49407150/80251978-2d778e80-867f-11ea-9aa1-effc1c896d38.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
