### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by NekrasovaMarina** [netology-code/git-homeworks-neuro-issues#936]
**Шаги по воспроизведению**

1. Открыть форму обратной связи в мобильном браузере Chrome

**Ожидаемый результат**
Форма обратной связи не сжата

**Фактический результат**
Форма обратной связи слишком сжата (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![issue 2](https://user-images.githubusercontent.com/49407150/80252233-96f79d00-867f-11ea-89cd-25213f796f98.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
