### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by OlgaDanilovaV** [netology-code/git-homeworks-neuro-issues#937]
# Описание проблемы
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

Шаги по воспроизведению:

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

### Ожидаемый результат:
Текст не наезжает на изображение

### Фактический результат:
Текст наезжает на изображение (см. скриншот)

### Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншоты:
![скрин](https://user-images.githubusercontent.com/60325937/80280645-f8664d00-870d-11ea-886f-edd401e3c472.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
