### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by OlgaDanilovaV** [netology-code/git-homeworks-neuro-issues#938]
# Описание проблемы
### Шаги по воспроизведению:
* Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
* Перейти на форму обратной связи

### Ожидаемый результат:
Текст распределен по странице

### Фактический результат:
Текст слишком сжат (см. скриншот)

### Программное окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншот:
![скрин2](https://user-images.githubusercontent.com/60325937/80281262-99570700-8712-11ea-8ec1-07bcfb126342.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
