### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by Andy2710** [netology-code/git-homeworks-neuro-issues#939]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
* Шаги по воспроизведению:
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
* Ожидаемый результат:
Текст не наезжает на изображение

* Фактический результат:
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

@solarrust

- 

![скрин](https://user-images.githubusercontent.com/63413016/80282059-fef9c200-8717-11ea-9c98-422773b85cb1.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
