### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by ShIvan23** [netology-code/git-homeworks-neuro-issues#942]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат

Текст не наезжает на изображение

Фактический результат

Текст наезжает на изображение (см. скриншот)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншоты
<img width="381" alt="Снимок экрана 2020-04-25 в 19 07 20" src="https://user-images.githubusercontent.com/64086981/80284563-07f28f80-8728-11ea-83dc-a7494a26a659.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
