### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by NazarovAleksey** [netology-code/git-homeworks-neuro-issues#945]
@solarrust 
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/63412103/80285629-c79f0b80-873f-11ea-985c-51cdd6a3eda7.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
