### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by tatiana-polyakova** [netology-code/git-homeworks-neuro-issues#947]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть страницу с контактами веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма ввода контактов для обратной связи выровнена по ширине окна

#### Фактический результат

Буквы в словах перенесены на следующие сточки как попало из-за установленных сжатых границ переноса текста (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

@solarrust 

#### Скриншоты

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
