### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by TallMSG** [netology-code/git-homeworks-neuro-issues#95]
### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

Пользователю @solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/42735558/58020327-80140680-7b10-11e9-8394-066329463854.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
