### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by EkaterinaLitviniva** [netology-code/git-homeworks-neuro-issues#953]
**to @solarrust**

**Главная страница. Форма обратной связи сильно сжата**

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до формы обратной связи
Ожидаемый результат

Форма обратной связи достаточно широкая для комфортного взаимодействия

**Фактический результат**

Форма обратной связи очень узкая (см. скриншот)

**Программное окружение**

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Скриншот**

![image](https://user-images.githubusercontent.com/58698219/80311814-8e6fa580-87ea-11ea-8ee3-c39d7c62c736.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
