### ISSUE TITLE
Ошибка. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by KalininArtemVal** [netology-code/git-homeworks-neuro-issues#955]
### Адресовано:
@solarrust

### Шаги по воспроизведению:
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пройти в форму обратной связи

### Ожидаемый результат:
Текст в форме обратной связи сжат

### Фактический результат:
обратите внимание на текст на скриншоте (см. скриншот)

### Программное окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

### Скриншоты:
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/44933170/80313680-2a061380-87f5-11ea-916a-09a0a8f60eec.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
