### ISSUE TITLE
Ошибка. Текст наезжает на изображение

### ISSUE THREAD

**Issue by SideAndrey** [netology-code/git-homeworks-neuro-issues#958]
Адресовано
@solarrust
Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
Скриншоты

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/62262950/80376053-f208da00-88a1-11ea-8eb8-d92d983a3b18.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
