### ISSUE TITLE
Ошибка. Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by SideAndrey** [netology-code/git-homeworks-neuro-issues#959]
Адресовано:
@solarrust

Шаги по воспроизведению:
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пройти в форму обратной связи

Ожидаемый результат:
Текст в форме обратной связи сжат

Фактический результат:
обратите внимание на текст на скриншоте (см. скриншот)

Программное окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

Скриншот:
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/62262950/80377878-82481e80-88a4-11ea-819e-d1a0c948f4d1.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
