### ISSUE TITLE
Изменение формы обратной связи

### ISSUE THREAD

**Issue by TallMSG** [netology-code/git-homeworks-neuro-issues#96]
### Главная страница. Форма обратной связи слишком сжата

Пользователю @solarrust

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Форма обратной связи"

**Ожидаемый результат**

1. Форма обратной связи должна вписываться по ширине в мобильный браузер
2. Слова должны отображаться без переносов

**Фактический результат**
Форма обратной связи не вписывается по ширине в мобильный браузер (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/42735558/58020528-0deff180-7b11-11e9-84d0-0fa5e00a00e8.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
