### ISSUE TITLE
Поехавшая верстка мобильной версии лендинга NeuroStartUp

### ISSUE THREAD

**Issue by BerkutZ** [netology-code/git-homeworks-neuro-issues#961]
*Адресовано:*
@solarrust, 6aa1c0b

**Предусловие:**
Скачать на смартфон мобильный браузер Google Chrome.

**Шаги воспроизведения:**

1)Открыть главную страницу веб-сайта NeuroStartUp
2) Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение

**Фактический результат:**
Текст наезжает на изображение (см. скриншот)

**Окружение:**
Redmi Note 8T (Android 9 PKQ1.190616.001), Chrome (70.0.3538.75)

**Скриншот:**

![bag neurostartup](https://user-images.githubusercontent.com/47637446/80378549-3f8f4200-88b6-11ea-869f-1c4b27075fcf.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
