### ISSUE TITLE
Ошибка верстки формы обратной связи мобильной версии лендинга NeuroStartUp

### ISSUE THREAD

**Issue by BerkutZ** [netology-code/git-homeworks-neuro-issues#963]
*Адресовано:*
@solarrust, 6aa1c0b

**Предусловие:**
Скачать на смартфон мобильный браузер Google Chrome.

**Шаги воспроизведения:**

1) Открыть лендинг NeuroStartUp.
2) Пролистать страницу до блока "Оставайтесь на связи".

**Ожидаемый результат:**
Окно формы обратной связи корректно располагается на экране смартфона, равномерно заполняя доступное пространство.

**Фактический результат:**
Окно формы обратной связи сжато и вытянуто в длинное полотно (см. скриншот).

**Окружение:**
Redmi Note 8T (Android 9 PKQ1.190616.001), Chrome (70.0.3538.75)

**Скриншот:**

![bag neurostartup 2](https://user-images.githubusercontent.com/47637446/80379365-7023ab80-88b7-11ea-8e47-ca08b487ee5e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
