### ISSUE TITLE
Форма обратной связи слишком сжата на главной странице

### ISSUE THREAD

**Issue by kristinavenevtseva** [netology-code/git-homeworks-neuro-issues#967]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи "Оставайтесь на связи..."

#### Ожидаемый результат

Форма обратной связи достаточной ширины 

#### Фактический результат

Форма обратной связи слишком сжата (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![Screenshot](https://user-images.githubusercontent.com/63412659/80553042-24652500-89d1-11ea-9be4-2c3fb1763cb7.png)
@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
