### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by IgorEkimow** [netology-code/git-homeworks-neuro-issues#97]
**Описание проблемы**
При просмотре лендинга в мобильном браузере присутствуют **две** проблемы:
- Текст наезжает на картинку;
- Форма обратной связи слишком сжата.

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)[

![1](https://user-images.githubusercontent.com/36897481/58282786-6512f200-7daf-11e9-92a8-fe4193aca859.png)
![2](https://user-images.githubusercontent.com/36897481/58282787-6512f200-7daf-11e9-892a-287fd83e0c82.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
