### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Svetlana-Arkhipova** [netology-code/git-homeworks-neuro-issues#971]
@solarrust 
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи"

#### Ожидаемый результат

Форма обратной связи занимает всю ширину экрана

#### Фактический результат

Форма обратной связи слишком узкая

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67 (1)](https://user-images.githubusercontent.com/61383260/80605969-65465380-8a3c-11ea-8681-6177d63e79ac.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
