### ISSUE TITLE
Текстовый блок наезжает на изображение

### ISSUE THREAD

**Issue by vakabunga** [netology-code/git-homeworks-neuro-issues#974]
# Описание проблемы (@solarrust)

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: iPhone X (iOS 13.3.1)
* Браузер: Chrome (81.0.4044.124)

#### Скриншоты

![](https://i.imgur.com/HJ1VbMj.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
