### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by vakabunga** [netology-code/git-homeworks-neuro-issues#975]
# Описание проблемы (@solarrust)

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до формы обратной связи

#### Ожидаемый результат

Форма обратной связи растягивается до ширины браузера

#### Фактический результат

Форма обратной связи занимает 50% от ширины окна браузера и слишком сжата. (Проблема в стилизации класса .col-6)

#### Программное окружение

* Устройство: iPhone X (iOS 13.3.1)
* Браузер: Chrome (81.0.4044.124)

#### Скриншоты

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
