### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by GalinaBaeva** [netology-code/git-homeworks-neuro-issues#976]
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

Assignee: @solarrust

Шаги по воспроизведению:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат:

Текст не наезжает на изображение

Фактический результат:
Текст наезжает на изображение (см. скриншот)
![СКРИНШОТ](https://user-images.githubusercontent.com/63532172/80864494-b13b0780-8c8b-11ea-92ab-d27b1b2b8ad5.png)

Программное окружение:
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
