### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by GalinaBaeva** [netology-code/git-homeworks-neuro-issues#977]
Главная страница. Форма обратной связи занимает не весь экран браузера.

Assignee: @solarrust

Шаги по воспроизведению:
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome;
2. Пролистать страницу до формы обратной связи.

Ожидаемый результат:
Форма обратной связи занимает всю ширину окна браузера.

Фактический результат:
Форма обратной связи занимает слишком сжата. см. скриншот.
![СКРИНШОТ 2](https://user-images.githubusercontent.com/63532172/80864584-58b83a00-8c8c-11ea-82a9-f1955c9e198c.png)

Программное окружение:
Устройство: iPhone X (iOS 13.3.1)
Браузер: Chrome (81.0.4044.124)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
