### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by Ableyev** [netology-code/git-homeworks-neuro-issues#978]
@solarrust 
Не корректно на вебе отображается текст: он наезжает на картинку. Нужно текст сместить вверх, а картинку вниз.

Скрин: 
<img width="383" alt="Снимок экрана 2020-05-06 в 10 45 44" src="https://user-images.githubusercontent.com/64348919/81149656-4a696700-8f87-11ea-95cf-575acac3de00.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
