### ISSUE TITLE
Форма обратной связи не корректно отображается на мобе

### ISSUE THREAD

**Issue by Ableyev** [netology-code/git-homeworks-neuro-issues#979]
@solarrust 
Форма обратной связи слишком узкая по ширине, из-за чего выглядит не очень фукнционально и эстетично.

Скрин:
<img width="393" alt="Снимок экрана 2020-05-06 в 10 52 46" src="https://user-images.githubusercontent.com/64348919/81149878-ba77ed00-8f87-11ea-9079-8af0b09713d0.png">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
