### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by testsan** [netology-code/git-homeworks-neuro-issues#980]
#### Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
@solarrust
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Firefox
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
#### Ожидаемый результат
Текст не наезжает на изображение
#### Фактический результат
Текст наезжает на изображение (см. скриншот)
#### Программное окружение
* Устройство: HTC U PLAY 4/64 (Android 6.0)
* Браузер: Firefox (68.8.0)
#### Скриншоты
![Screenshot_20200505-141451](https://user-images.githubusercontent.com/63858538/81175505-54ea2780-8fac-11ea-92d1-63eca1eac9d0.png)
![Screenshot_20200506-141430](https://user-images.githubusercontent.com/63858538/81175548-63384380-8fac-11ea-847a-7c5f013e4a0c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
