### ISSUE TITLE
Форма обратной связи отображается некорректно

### ISSUE THREAD

**Issue by testsan** [netology-code/git-homeworks-neuro-issues#981]
#### Главная страница. Форма обратной связи слишком сжата
@solarrust
#### Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Firefox
1. Пролистать страницу до формы обратной связи "Оставайтесь на связи..."
#### Ожидаемый результат
Форма обратной связи растягивается до ширины браузера
#### Фактический результат
Форма обратной связи слишком сжата.
#### Программное окружение
* Устройство: HTC U PLAY 4/64 (Android 6.0)
* Браузер: Firefox (68.8.0)
#### Скриншоты
![Screenshot_20200506-141506](https://user-images.githubusercontent.com/63858538/81175983-199c2880-8fad-11ea-819e-475d05c95b7e.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
