### ISSUE TITLE
Заголовок "Искусственный интеллект..." и текстовый блок "Воспользуйтесь современными возможностями..." не адаптированы к мобильному браузеру

### ISSUE THREAD

**Issue by nastiamikh** [netology-code/git-homeworks-neuro-issues#982]
@solarrust 

**Шаги по воспроизведению:**
- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Safari
- Пролистать страницу до заголовка "Искусственный интеллект решающий..." и блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
- Заголовок "Искусственный интеллект решающий...", как и в десктопной версии браузера,  выровнен на центру страницы
- Текстовый блок "Воспользуйтесь современными возможностями..." не наезжает на изображение 

**Фактический результат:**
- Заголовок "Искусственный интеллект решающий..." смещен в правую часть страницы (см. скриншот)
- Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение (см. скриншот)

**Программное окружение:**
- Устройство: iPhone 7 (iOS 13.3.1)
- Браузер: Safari 

![IMG_4042](https://user-images.githubusercontent.com/63406296/81199224-f5fcd080-8ff4-11ea-84bc-64fa6241e544.PNG)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
