### ISSUE TITLE
Форма обратной связи сужена в мобильной версии браузера

### ISSUE THREAD

**Issue by nastiamikh** [netology-code/git-homeworks-neuro-issues#983]
@solarrust 

**Шаги по воспроизведению:**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Safari
- Пролистать страницу до блока "Оставайтесь на связи"

**Ожидаемый результат:**
Форма обратной связи занимает всю ширину экрана

**Фактический результат:**
Форма обратной связи слишком узкая

**Программное окружение:**

- Устройство: iPhone 7 (iOS 13.3.1)
- Браузер: Safari

![IMG_4041](https://user-images.githubusercontent.com/63406296/81202206-d8316a80-8ff8-11ea-9eb0-91ae6f4dba0f.PNG)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
