### ISSUE TITLE
Lending Page

### ISSUE THREAD

**Issue by Aleksandr-Suchugov** [netology-code/git-homeworks-neuro-issues#984]
Hi!
**There are some issues on the Lending Page that have to be fixed:**

- white margins from the left and right sides;
- the header content and the description are very narrow;
- some parts of the description are crossing the background image.

**Expected result:**

- the background image should occupy 100% of display;
- center content;
- the description must be readable.

**Device and app:**

iPhone 6s
Yandex ver. 20.4.0.1458

**Screenshots:**

![page-1](https://user-images.githubusercontent.com/58569395/81262053-c7f3ac80-9045-11ea-99e7-e4aacfd98c15.JPG)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
