### ISSUE TITLE
Subscription Form

### ISSUE THREAD

**Issue by Aleksandr-Suchugov** [netology-code/git-homeworks-neuro-issues#985]
Hi!
**There are some issues on the Subscription Form that have to be fixed:**

- white margins from the left and right sides;
- the form is centered by own margins, therefore, it looks very narrow;
- superfluous padding before the form;

**Expected result:**

- the form should occupy 95% of display the rest is for the grey color background;
- center content;

**Device and app:**

iPhone 6s
Yandex ver. 20.4.0.1458

**Screenshots:**
![page-2](https://user-images.githubusercontent.com/58569395/81262260-2c167080-9046-11ea-9462-56c903ab4155.JPG)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
