### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by Sviridova-Olga** [netology-code/git-homeworks-neuro-issues#987]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Перейти к блоку "Оставайтесь на связи"

#### Ожидаемый результат

Форма обратной связи нормального размера

#### Фактический результат

Форма обратной связи слишком сжата

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

@solarrust
![image](https://user-images.githubusercontent.com/63497505/81276261-70603b80-905b-11ea-88d0-8612d4da0f87.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
