### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by TomuraCreator** [netology-code/git-homeworks-neuro-issues#99]
## Описание проблемы
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..."** **наезжает на изображение**
**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

   * Устройство: iPhone 8+ (iOS 12.1)
   * Браузер: Chrome (70.0.3538.75)

Скриншоты
![изображение](https://user-images.githubusercontent.com/42077765/59365802-dbb56680-8d41-11e9-8427-e0c52342ba77.png)

![изображение](https://user-images.githubusercontent.com/42077765/59365785-d3f5c200-8d41-11e9-89cc-81bb1705a0e9.png)

@solarrust

**Comment by solarrust** [comment]
Нужно было создать два отдельных issue: по одному на каждую из проблем.
